import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let actionmoviesExtra: [QSpec] = [
        Q(1, "'Yippee-ki-yay' is the catchphrase of which action hero?", "John McClane", ["Martin Riggs", "John Rambo", "Dutch Schaefer"]),
        Q(1, "Who plays agent Ethan Hunt in the 'Mission: Impossible' films?", "Tom Cruise", ["Matt Damon", "Brad Pitt", "Keanu Reeves"]),
        Q(1, "Keanu Reeves plays which retired hitman?", "John Wick", ["Jason Bourne", "Frank Martin", "Bryan Mills"]),
        Q(1, "Arnold first said 'I'll be back' in which movie?", "The Terminator", ["Predator", "Total Recall", "Commando"]),
        Q(1, "In 'Taken,' Liam Neeson warns he has 'a very particular set of' what?", "Skills", ["Rules", "Tools", "Friends"]),
        Q(1, "Vin Diesel's Dom Toretto leads the crew in which movie series?", "Fast & Furious", ["The Transporter", "The Expendables", "Mission: Impossible"]),
        Q(1, "Indiana Jones is famously afraid of what?", "Snakes", ["Spiders", "Rats", "Heights"]),
        Q(1, "James Bond takes his martini how?", "Shaken, not stirred", ["Stirred, not shaken", "On the rocks", "Dry with a twist"]),
        Q(1, "What is Tom Cruise's call sign in 'Top Gun'?", "Maverick", ["Iceman", "Goose", "Viper"]),
        Q(1, "Mr. T played which character on 'The A-Team'?", "B.A. Baracus", ["Hannibal Smith", "H.M. Murdock", "Templeton Peck"]),
        Q(1, "Which pocket tool did MacGyver carry everywhere?", "A Swiss Army knife", ["A Leatherman", "A Zippo lighter", "A folding saw"]),
        Q(1, "Which 1980s show starred David Hasselhoff and a talking car?", "Knight Rider", ["Airwolf", "The Fall Guy", "Street Hawk"]),
        Q(1, "Chuck Norris played Cordell Walker in which series?", "Walker, Texas Ranger", ["Lone Star", "Longmire", "The Highwayman"]),
        Q(1, "In 'Beverly Hills Cop,' Axel Foley is a detective from which city?", "Detroit", ["Chicago", "Cleveland", "Philadelphia"]),
        Q(1, "'We're gonna need a bigger boat' is a line from which movie?", "Jaws", ["The Perfect Storm", "The Abyss", "Deep Blue Sea"]),
        Q(1, "Rocky Balboa runs up the art museum steps in which city?", "Philadelphia", ["Pittsburgh", "Boston", "Baltimore"]),
        Q(1, "Tony Soprano runs his crew in which state?", "New Jersey", ["New York", "Rhode Island", "Pennsylvania"]),
        Q(1, "'M*A*S*H' is set during which war?", "The Korean War", ["World War II", "The Vietnam War", "World War I"]),
        Q(1, "Tom Selleck plays NYPD commissioner Frank Reagan on which show?", "Blue Bloods", ["NCIS", "Law & Order", "Chicago P.D."]),
        Q(1, "Mark Harmon's Leroy Jethro Gibbs leads the team on which show?", "NCIS", ["JAG", "Criminal Minds", "CSI"]),
        Q(1, "John Wayne went by which nickname?", "The Duke", ["The King", "The Chairman", "The Kid"]),
        Q(1, "'Rush Hour' teams Chris Tucker with which star?", "Jackie Chan", ["Jet Li", "Chow Yun-fat", "Donnie Yen"]),
        Q(1, "In 'The Matrix,' which pill does Neo take?", "The red pill", ["The blue pill", "The green pill", "The white pill"]),
        Q(1, "Who played Bond in 'Dr. No' (1962), the first Bond film?", "Sean Connery", ["Roger Moore", "David Niven", "George Lazenby"]),
        Q(1, "'Deadliest Catch' crews brave the Bering Sea to catch what?", "Crab", ["Salmon", "Tuna", "Halibut"]),
        Q(1, "Each episode of '24' plays out in real time over how long?", "One hour", ["Two hours", "30 minutes", "One day"]),
        Q(1, "Finish the 'Godfather' line: 'Leave the gun, take the...'", "Cannoli", ["Cake", "Car", "Cash"]),
        Q(1, "In 'National Treasure,' Nicolas Cage steals which document?", "The Declaration of Independence", ["The Constitution", "The Bill of Rights", "The Emancipation Proclamation"]),

        Q(2, "'Hasta la vista, baby' comes from which movie?", "Terminator 2", ["The Terminator", "True Lies", "Total Recall"]),
        Q(2, "Who plays villain Hans Gruber in 'Die Hard'?", "Alan Rickman", ["Jeremy Irons", "Gary Oldman", "Christopher Walken"], "Jeremy Irons played Hans's brother Simon in 'Die Hard with a Vengeance.'"),
        Q(2, "'Die Hard with a Vengeance' pairs McClane with which actor?", "Samuel L. Jackson", ["Danny Glover", "Justin Long", "Reginald VelJohnson"]),
        Q(2, "In 'Road House' (1989), Patrick Swayze's Dalton works as a what?", "Bouncer", ["Bartender", "Sheriff", "Trucker"]),
        Q(2, "In 'The Fugitive,' Dr. Kimble hunts a killer missing what?", "An arm", ["An eye", "A finger", "An ear"], "Tommy Lee Jones won an Oscar as Deputy U.S. Marshal Sam Gerard."),
        Q(2, "James Garner played a laid-back private eye on which show?", "The Rockford Files", ["Magnum, P.I.", "Simon & Simon", "Mannix"]),
        Q(2, "Who plays Jack Ryan in the Prime Video series?", "John Krasinski", ["Chris Pine", "Ben Affleck", "Alec Baldwin"]),
        Q(2, "Timothy Olyphant plays U.S. Marshal Raylan Givens on which show?", "Justified", ["Longmire", "Deadwood", "Banshee"]),
        Q(2, "Billy Bob Thornton plays a West Texas oilman on which show?", "Landman", ["Tulsa King", "Mayor of Kingstown", "Lioness"]),
        Q(2, "Pierce Brosnan's first Bond film was which?", "GoldenEye", ["Tomorrow Never Dies", "The World Is Not Enough", "Licence to Kill"]),
        Q(2, "In 'Goldfinger,' the villain targets the gold at which U.S. site?", "Fort Knox", ["West Point", "The Denver Mint", "The Federal Reserve"]),
        Q(2, "Dom Toretto's beer of choice in 'Fast & Furious' is what?", "Corona", ["Modelo", "Budweiser", "Tecate"]),
        Q(2, "Who directed 'The Good, the Bad and the Ugly'?", "Sergio Leone", ["Sergio Corbucci", "John Ford", "Sam Peckinpah"]),
        Q(2, "Val Kilmer plays which gunslinger in 'Tombstone'?", "Doc Holliday", ["Wyatt Earp", "Johnny Ringo", "Curly Bill"]),
        Q(2, "'Book 'em, ___' was McGarrett's line on 'Hawaii Five-O.' Book 'em, who?", "Danno", ["Chin", "Kono", "Duke"]),
        Q(2, "Columbo's trademark line before one last question is what?", "Just one more thing", ["One last question", "Hold on a minute", "Oh, and another thing"]),
        Q(2, "Steve McQueen drives which car in the 'Bullitt' chase?", "Ford Mustang", ["Dodge Charger", "Chevrolet Camaro", "Pontiac GTO"], "The hitmen he chases through San Francisco drive a Dodge Charger."),
        Q(2, "Danny Ocean's crew hits the vault under which Las Vegas casino?", "The Bellagio", ["Caesars Palace", "The Venetian", "The Flamingo"]),
        Q(2, "Who plays ranch hand Rip Wheeler on 'Yellowstone'?", "Cole Hauser", ["Luke Grimes", "Wes Bentley", "Ryan Bingham"]),
        Q(2, "Which writer is behind 'Yellowstone,' '1883' and 'Tulsa King'?", "Taylor Sheridan", ["Vince Gilligan", "David Chase", "Nic Pizzolatto"]),
        Q(2, "Sylvester Stallone plays an exiled New York mobster on which show?", "Tulsa King", ["Mayor of Kingstown", "Boardwalk Empire", "Landman"]),
        Q(2, "Before drifting, Jack Reacher was a major in which part of the Army?", "Military Police", ["Special Forces", "The Rangers", "Military Intelligence"]),
        Q(2, "The Cartwright family's ranch on 'Bonanza' is called what?", "The Ponderosa", ["The High Chaparral", "The Big Valley", "The Shiloh"]),
        Q(2, "Kevin Costner plays which lawman in 'The Untouchables'?", "Eliot Ness", ["Melvin Purvis", "Wyatt Earp", "Frank Hamer"]),
        Q(2, "What is the name of Indy's young sidekick in 'Temple of Doom'?", "Short Round", ["Mutt", "Sallah", "Marcus"]),
        Q(2, "Who played Apollo Creed in the 'Rocky' films?", "Carl Weathers", ["Mr. T", "Dolph Lundgren", "Tony Burton"], "Weathers also played Dillon opposite Arnold in 'Predator.'"),
        Q(2, "'NCIS' was spun off from which Navy legal drama?", "JAG", ["The Unit", "Tour of Duty", "Navy Log"]),
        Q(2, "In 'Under Siege,' Steven Seagal's Casey Ryback is the ship's what?", "Cook", ["Chaplain", "Mechanic", "Medic"], "The film is set aboard the battleship USS Missouri."),

        Q(3, "'Die Hard's' Nakatomi Plaza was played by a tower named for which studio?", "20th Century Fox", ["Warner Bros.", "Paramount", "Universal"], "Fox Plaza in Los Angeles was still under construction during the shoot."),
        Q(3, "Nicolas Cage's character in 'Con Air' is named what?", "Cameron Poe", ["Castor Troy", "Stanley Goodspeed", "Memphis Raines"], "Poe is a paroled Army Ranger just trying to get home to his family."),
        Q(3, "Which director made both 'Predator' and 'Die Hard'?", "John McTiernan", ["James Cameron", "Richard Donner", "Tony Scott"], "The two films came out back to back, in 1987 and 1988."),
        Q(3, "Who directed the original 'Top Gun' (1986)?", "Tony Scott", ["Ridley Scott", "Michael Bay", "Joseph Kosinski"], "Joseph Kosinski directed the 2022 sequel, 'Top Gun: Maverick.'"),
        Q(3, "Who plays Major Reisman, leader of 'The Dirty Dozen'?", "Lee Marvin", ["Charles Bronson", "Telly Savalas", "Jim Brown"], "Bronson, Savalas and Brown all play members of the Dozen."),
        Q(3, "Bruce Lee died six days before which of his films premiered?", "Enter the Dragon", ["Fist of Fury", "The Big Boss", "The Way of the Dragon"], "It opened in Hong Kong on July 26, 1973, co-produced with Warner Bros."),
        Q(3, "Who turned down the Best Actor Oscar for playing 'Patton'?", "George C. Scott", ["Marlon Brando", "Gregory Peck", "Lee Marvin"], "He was the first actor ever to decline the award."),
        Q(3, "'The Hurt Locker' made who the first woman to win Best Director?", "Kathryn Bigelow", ["Sofia Coppola", "Jane Campion", "Greta Gerwig"], "Bigelow also directed 'Point Break.'"),
        Q(3, "KITT in the original 'Knight Rider' stands for Knight Industries what?", "Two Thousand", ["Tactical Transport", "Turbo Technology", "Tracking Terminal"], "David Hasselhoff starred as Michael Knight on NBC from 1982 to 1986."),
        Q(3, "What is MacGyver's rarely used first name?", "Angus", ["Mac", "Hamish", "Duncan"], "It wasn't revealed until the original series' seventh and final season."),
        Q(3, "Who narrated 'The Dukes of Hazzard' and sang its theme?", "Waylon Jennings", ["Willie Nelson", "Johnny Cash", "Kris Kristofferson"], "The show credited him as The Balladeer; the theme is 'Good Ol' Boys.'"),
        Q(3, "Who played Marshal Matt Dillon on 'Gunsmoke'?", "James Arness", ["Chuck Connors", "Clint Walker", "Robert Fuller"], "The show ran 20 seasons, from 1955 to 1975."),
        Q(3, "NCIS's Ducky, David McCallum, starred in which 1960s spy show?", "The Man from U.N.C.L.E.", ["I Spy", "The Avengers", "Get Smart"], "He played Russian agent Illya Kuryakin opposite Robert Vaughn."),
        Q(3, "'Chicago Fire' is set at which fictional firehouse?", "Firehouse 51", ["Firehouse 49", "Engine 33", "Station 19"], "It premiered on NBC in 2012 and launched the One Chicago franchise."),
        Q(3, "Who played Maj. Dick Winters in 'Band of Brothers'?", "Damian Lewis", ["David Schwimmer", "Ron Livingston", "Donnie Wahlberg"], "David Schwimmer played Herbert Sobel, Easy Company's first commander."),
        Q(3, "In 'Saving Private Ryan,' what was Capt. Miller before the war?", "A schoolteacher", ["A lawyer", "A mechanic", "A police officer"], "Tom Hanks's Miller keeps it secret until a standoff among his own men."),
        Q(3, "In 'Gone in 60 Seconds' (2000), the car called Eleanor is a what?", "1967 Shelby GT500", ["1969 Dodge Charger", "1970 Chevelle SS", "1970 Plymouth Barracuda"], "In the 1974 original, Eleanor was a yellow Ford Mustang."),
        Q(3, "R. Lee Ermey played Gunnery Sgt. Hartman in which film?", "Full Metal Jacket", ["Platoon", "Heartbreak Ridge", "An Officer and a Gentleman"], "Ermey really had been a Marine Corps drill instructor."),
        Q(3, "In 'Jaws,' Quint tells of surviving the sinking of which ship?", "USS Indianapolis", ["USS Arizona", "USS Maine", "USS Yorktown"], "Robert Shaw played Quint, the salty shark hunter."),
        Q(3, "The bank robbers in 'Point Break' wear masks of whom?", "Former U.S. presidents", ["Hockey goalies", "Famous surfers", "Classic movie monsters"], "The Ex-Presidents wore Reagan, Carter, Nixon and Johnson masks."),
        Q(3, "Who composed the 'Mission: Impossible' theme?", "Lalo Schifrin", ["John Williams", "Jerry Goldsmith", "Henry Mancini"], "It's written in 5/4 time, an unusual meter for a TV theme."),
        Q(3, "Who plays the marshal facing a noon showdown in 'High Noon' (1952)?", "Gary Cooper", ["John Wayne", "Jimmy Stewart", "Henry Fonda"], "The story unfolds almost in real time, with clocks shown throughout."),
        Q(3, "Which novelist created U.S. Marshal Raylan Givens of 'Justified'?", "Elmore Leonard", ["Cormac McCarthy", "Larry McMurtry", "James Lee Burke"], "Raylan first appeared in Leonard's 1993 novel 'Pronto.'"),
        Q(3, "The final scene of 'The Sopranos' is set in which restaurant?", "Holsten's", ["Satriale's", "Vesuvio", "Artie's Diner"], "It's a real ice cream and candy shop in Bloomfield, New Jersey."),
        Q(3, "What was the title of the 1983 'M*A*S*H' finale?", "Goodbye, Farewell and Amen", ["Farewell to the 4077th", "The Last Chopper Out", "So Long, Korea"], "About 106 million Americans watched it on February 28, 1983."),
        Q(3, "How many official Bond films did Roger Moore make?", "Seven", ["Five", "Six", "Eight"], "His run went from 'Live and Let Die' (1973) to 'A View to a Kill' (1985)."),
        Q(3, "What is Indiana Jones's real first name?", "Henry", ["Walter", "Harold", "Howard"], "In 'The Last Crusade,' we learn he took the name Indiana from the family dog."),
        Q(3, "In 'Smokey and the Bandit,' what are they hauling to Atlanta?", "Coors beer", ["Moonshine", "Budweiser", "Pabst Blue Ribbon"], "The run was 400 cases from Texarkana, with Bandit in a Pontiac Trans Am."),
    ]
}
