import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let ballsportsExtra: [QSpec] = [
        // Tier 1
        Q(1, "In the NBA, a basket from behind the arc is worth how many points?", "3", ["2", "4", "1"]),
        Q(1, "How many players per team are on a basketball court at once?", "5", ["6", "4", "7"]),
        Q(1, "In basketball, traveling means what?", "Moving your feet without dribbling", ["Dribbling with both hands at once", "Stepping on the out-of-bounds line", "Kicking the ball on purpose"]),
        Q(1, "Which NBA team plays its home games at Madison Square Garden?", "New York Knicks", ["Brooklyn Nets", "Boston Celtics", "Philadelphia 76ers"]),
        Q(1, "Michael Jordan won all six of his NBA titles with which team?", "Chicago Bulls", ["Washington Wizards", "Detroit Pistons", "New York Knicks"]),
        Q(1, "In baseball, how many strikes make a strikeout?", "3", ["2", "4", "5"]),
        Q(1, "In baseball, how many balls earn the batter a walk?", "4", ["3", "5", "6"]),
        Q(1, "A grand slam in baseball is what?", "A homer with the bases loaded", ["Four hits by one batter in a game", "A walk-off homer in the ninth", "Stealing second, third and home"]),
        Q(1, "Fenway Park is home to which team?", "Boston Red Sox", ["New York Yankees", "Chicago Cubs", "Baltimore Orioles"]),
        Q(1, "How many innings are in a standard MLB game?", "9", ["7", "8", "10"]),
        Q(1, "In baseball, what is the bullpen?", "Where relief pitchers warm up", ["Where the manager sits", "Where reporters watch", "Where the next batter waits"]),
        Q(1, "In hockey, a hat trick is what?", "Three goals by one player in a game", ["Three assists by one player in a game", "Three fights in a single period", "Three straight saves by the goalie"]),
        Q(1, "A minor penalty in the NHL sends a player to the box for how long?", "2 minutes", ["5 minutes", "1 minute", "10 minutes"]),
        Q(1, "A hockey puck is made of what?", "Rubber", ["Plastic", "Wood", "Cork"]),
        Q(1, "How many periods are in a regulation NHL game?", "3", ["4", "2", "5"]),
        Q(1, "A Zamboni is what?", "The ice-resurfacing machine", ["The goalie's catching glove", "A penalty shot in overtime", "The arena's goal horn"]),
        Q(1, "In soccer, which player may handle the ball inside their own box?", "The goalkeeper", ["The captain", "The sweeper", "The center back"]),
        Q(1, "How many players per team start on a soccer field?", "11", ["10", "12", "9"]),
        Q(1, "Lionel Messi is from which country?", "Argentina", ["Chile", "Brazil", "Uruguay"]),
        Q(1, "Cristiano Ronaldo is from which country?", "Portugal", ["Spain", "Brazil", "Italy"]),
        Q(1, "A standard soccer match lasts how long, before stoppage time?", "90 minutes", ["60 minutes", "80 minutes", "120 minutes"]),
        Q(1, "A golfer yells 'Fore!' to warn people about what?", "A ball heading their way", ["Lightning nearby", "The last hole", "A lost ball search"]),
        Q(1, "What does the winner of the Masters famously put on?", "A green jacket", ["A red jacket", "A gold blazer", "A plaid cap"]),
        Q(1, "In golf, a bogey is what?", "One stroke over par", ["One under par", "Two over par", "Exactly par"]),
        Q(1, "How many holes are in a standard round of golf?", "18", ["9", "12", "24"]),
        Q(1, "Which tennis major is played on grass?", "Wimbledon", ["The French Open", "The US Open", "The Australian Open"]),
        Q(1, "In tennis scoring, 'love' means what?", "Zero", ["A tie", "Game point", "Fifteen"]),
        Q(1, "In tennis, an ace is what?", "A serve the opponent never touches", ["Two serving faults in a row", "A return that clips the net cord", "A drop shot that bounces twice"]),

        // Tier 2
        Q(2, "Which Celtic won 11 NBA championships as a player?", "Bill Russell", ["Larry Bird", "John Havlicek", "Bob Cousy"], "He won the last two as the Celtics' player-coach, in 1968 and 1969."),
        Q(2, "In 1962, Wilt Chamberlain scored how many points in one NBA game?", "100", ["81", "92", "73"], "He did it against the Knicks in Hershey, Pennsylvania."),
        Q(2, "Larry Bird played his entire NBA career for which team?", "Boston Celtics", ["Indiana Pacers", "Los Angeles Lakers", "Detroit Pistons"]),
        Q(2, "Which NBA great was nicknamed 'The Mailman'?", "Karl Malone", ["John Stockton", "Charles Barkley", "Patrick Ewing"], "Because he always delivered."),
        Q(2, "In basketball, an 'and-one' is what?", "A made shot plus a foul shot", ["A one-handed dunk in traffic", "A single missed free throw", "A shot at the final buzzer"]),
        Q(2, "Hitting for the cycle means one game with what?", "A single, double, triple and homer", ["Four home runs in one game", "A hit in each of nine innings", "Four stolen bases in one game"]),
        Q(2, "How many career home runs did Babe Ruth hit?", "714", ["755", "660", "762"]),
        Q(2, "Which Yankee was nicknamed 'The Iron Horse'?", "Lou Gehrig", ["Joe DiMaggio", "Mickey Mantle", "Yogi Berra"]),
        Q(2, "In 1997, MLB retired which jersey number for every team?", "42", ["3", "44", "21"], "It was Jackie Robinson's number, retired 50 years after his debut."),
        Q(2, "In baseball slang, a 'can of corn' is what?", "An easy fly ball", ["A bunt single", "A wild pitch", "A slow curveball"]),
        Q(2, "Which team won the 2016 World Series to end a 108-year drought?", "Chicago Cubs", ["Cleveland Indians", "Boston Red Sox", "Chicago White Sox"], "They beat Cleveland in a Game 7 that went 10 innings."),
        Q(2, "A pitcher's ERA measures what?", "Earned runs allowed per nine innings", ["Strikeouts per nine innings", "Walks and hits per inning", "Pitches thrown per batter faced"]),
        Q(2, "Which hockey legend was nicknamed 'The Great One'?", "Wayne Gretzky", ["Mario Lemieux", "Gordie Howe", "Bobby Orr"]),
        Q(2, "In hockey, a power play is what?", "More skaters after a rival's penalty", ["A slap shot from the blue line", "A line change on the fly", "A fight between two enforcers"]),
        Q(2, "In hockey, the crease is what?", "The painted area in front of the net", ["The faceoff circle at center ice", "The penalty box by the boards", "The door to the team bench"]),
        Q(2, "Which NHL trophy goes to the regular-season MVP?", "The Hart Trophy", ["The Conn Smythe Trophy", "The Vezina Trophy", "The Lady Byng Trophy"]),
        Q(2, "Which club calls Old Trafford home?", "Manchester United", ["Manchester City", "Liverpool", "Arsenal"]),
        Q(2, "Which country won the 2022 World Cup in Qatar?", "Argentina", ["France", "Brazil", "Croatia"], "They beat France on penalties after a 3-3 draw."),
        Q(2, "Maradona's 'Hand of God' goal in 1986 came against which country?", "England", ["West Germany", "Italy", "Brazil"]),
        Q(2, "Pelé won how many World Cups with Brazil?", "3", ["2", "4", "1"], "He won in 1958, 1962 and 1970."),
        Q(2, "In Spanish soccer, 'El Clásico' is which matchup?", "Real Madrid vs. Barcelona", ["Atlético vs. Real Madrid", "Sevilla vs. Real Betis", "Barcelona vs. Valencia"]),
        Q(2, "Which country won the 1994 World Cup, hosted by the U.S.?", "Brazil", ["Italy", "Germany", "Argentina"], "The final against Italy was the first World Cup final decided on penalties."),
        Q(2, "Which golfer was nicknamed 'The Golden Bear'?", "Jack Nicklaus", ["Arnold Palmer", "Gary Player", "Tom Watson"]),
        Q(2, "In casual golf, a mulligan is what?", "An unofficial do-over shot", ["A shot out of a bunker", "A missed short putt", "A ball lost in water"]),
        Q(2, "Tiger Woods won his first Masters in which year?", "1997", ["1995", "1999", "2001"], "He won by 12 strokes at age 21."),
        Q(2, "In golf's Ryder Cup, the U.S. team plays against whom?", "Europe", ["Asia", "Australia", "South America"]),
        Q(2, "Rafael Nadal won which major 14 times?", "The French Open", ["Wimbledon", "The US Open", "The Australian Open"]),
        Q(2, "In tennis, a 'bagel' is a set won by what score?", "6-0", ["6-1", "7-6", "6-4"]),

        // Tier 3
        Q(3, "In 2006, Kobe Bryant scored 81 points against which team?", "Toronto Raptors", ["Phoenix Suns", "Sacramento Kings", "Dallas Mavericks"], "It came on January 22, 2006, at home in Los Angeles."),
        Q(3, "James Naismith's first basketball game in 1891 used what for hoops?", "Peach baskets", ["Barrel hoops", "Fishing nets", "Wooden crates"], "He invented the game at a YMCA school in Springfield, Massachusetts."),
        Q(3, "Which team drafted Kobe Bryant in 1996 before trading him to the Lakers?", "Charlotte Hornets", ["Philadelphia 76ers", "New Jersey Nets", "Boston Celtics"], "He went 13th overall and was traded for center Vlade Divac."),
        Q(3, "Before it became the NBA in 1949, the league was called what?", "The BAA", ["The ABA", "The ABL", "The AAU"], "The Basketball Association of America merged with the rival NBL."),
        Q(3, "In 1995, Reggie Miller scored 8 points in 9 seconds against which team?", "New York Knicks", ["Chicago Bulls", "Orlando Magic", "Atlanta Hawks"], "It happened in Game 1 at Madison Square Garden; the Pacers won 107-105."),
        Q(3, "Michael Jordan's 1989 series-winner known as 'The Shot' beat which team?", "Cleveland Cavaliers", ["New York Knicks", "Detroit Pistons", "Utah Jazz"], "He hung in the air over Craig Ehlo to win Game 5 at the buzzer."),
        Q(3, "Who hit baseball's 'Shot Heard 'Round the World' in 1951?", "Bobby Thomson", ["Ralph Branca", "Willie Mays", "Duke Snider"], "His homer won the pennant for the Giants over the Brooklyn Dodgers."),
        Q(3, "Cy Young won how many games in his career?", "511", ["373", "417", "455"], "Each league's top pitching award is named for him."),
        Q(3, "Which Yankee threw a perfect game in the 1956 World Series?", "Don Larsen", ["Whitey Ford", "Allie Reynolds", "Bob Turley"], "Yogi Berra famously leapt into his arms after the final out."),
        Q(3, "Cal Ripken Jr. played how many consecutive games?", "2,632", ["2,130", "2,495", "2,801"], "He passed Lou Gehrig's 2,130 in 1995 and sat down voluntarily in 1998."),
        Q(3, "Babe Ruth began his MLB career with which team?", "Boston Red Sox", ["New York Yankees", "Boston Braves", "Philadelphia Athletics"], "He broke in as a pitcher and was sold to the Yankees after the 1919 season."),
        Q(3, "Ted Williams batted .406 in which season?", "1941", ["1938", "1946", "1949"], "He went 6-for-8 in a doubleheader on the last day rather than sit out."),
        Q(3, "The Red Sox broke the 'Curse of the Bambino' in which year?", "2004", ["1986", "2007", "2013"], "It was their first World Series title since 1918."),
        Q(3, "How many goals did Wayne Gretzky score in the 1981-82 season?", "92", ["87", "76", "85"], "He scored his first 50 in just 39 games."),
        Q(3, "Which team traded Wayne Gretzky to the Los Angeles Kings in 1988?", "Edmonton Oilers", ["Calgary Flames", "Winnipeg Jets", "Quebec Nordiques"], "He had won four Stanley Cups in Edmonton."),
        Q(3, "Lord Stanley, who donated the Stanley Cup, held which job?", "Governor General of Canada", ["Prime Minister of Canada", "Mayor of Montreal", "British ambassador to the U.S."], "First awarded in 1893, the Cup is older than the NHL."),
        Q(3, "Bobby Orr's famous 1970 'flying goal' beat which team for the Cup?", "St. Louis Blues", ["New York Rangers", "Chicago Black Hawks", "Montreal Canadiens"], "He was tripped right after scoring in overtime and sailed through the air."),
        Q(3, "In 1959, Jacques Plante made what gear a regular part of hockey?", "The goalie mask", ["Leg pads", "The blocker", "The curved stick"], "He refused to return to the net without it after taking a shot to the face."),
        Q(3, "Which club went unbeaten through the 2003-04 Premier League season?", "Arsenal", ["Chelsea", "Manchester United", "Liverpool"], "They were nicknamed 'The Invincibles.'"),
        Q(3, "In the 2006 World Cup final, Zinedine Zidane headbutted which player?", "Marco Materazzi", ["Gianluigi Buffon", "Fabio Cannavaro", "Andrea Pirlo"], "He was sent off, and Italy beat France on penalties."),
        Q(3, "Leicester City won the 2015-16 Premier League at what preseason odds?", "5,000 to 1", ["500 to 1", "1,000 to 1", "2,500 to 1"], "They finished 10 points clear of Arsenal."),
        Q(3, "In 2005, Liverpool came back from 3-0 down to win a Champions League final against whom?", "AC Milan", ["Juventus", "Real Madrid", "Bayern Munich"], "Fans call it the Miracle of Istanbul."),
        Q(3, "In 1986, who won the Masters at age 46?", "Jack Nicklaus", ["Tom Watson", "Raymond Floyd", "Greg Norman"], "He shot 30 on the back nine on Sunday."),
        Q(3, "Who won golf's Grand Slam in 1930 and later co-founded Augusta National?", "Bobby Jones", ["Walter Hagen", "Ben Hogan", "Gene Sarazen"], "He did it as an amateur and retired from competition that year."),
        Q(3, "At the 1935 Masters, Gene Sarazen holed out with what rare shot?", "A double eagle", ["A hole-in-one", "A 90-foot putt", "A chip for eagle"], "His 4-wood on the par-5 15th helped force a playoff, which he won."),
        Q(3, "Wimbledon's 11-hour match in 2010 was John Isner against whom?", "Nicolas Mahut", ["Gilles Simon", "Richard Gasquet", "Gaël Monfils"], "The match spanned three days; Isner took the fifth set 70-68."),
        Q(3, "Who won five straight Wimbledon titles from 1976 to 1980?", "Björn Borg", ["John McEnroe", "Jimmy Connors", "Ivan Lendl"], "McEnroe ended the run in the 1981 final."),
        Q(3, "In 1973's 'Battle of the Sexes,' Billie Jean King beat whom?", "Bobby Riggs", ["Rod Laver", "Arthur Ashe", "Jack Kramer"], "The Houston Astrodome match drew a TV audience in the tens of millions."),
    ]
}
