import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let bookclubExtra: [QSpec] = [
        Q(1, "Who wrote 'Pride and Prejudice'?", "Jane Austen", ["Charlotte Brontë", "Louisa May Alcott", "George Eliot"]),
        Q(1, "Who wrote 'The Hunger Games'?", "Suzanne Collins", ["Veronica Roth", "Stephenie Meyer", "Lois Lowry"]),
        Q(1, "Who wrote the 'Harry Potter' books?", "J.K. Rowling", ["Rick Riordan", "Philip Pullman", "Cornelia Funke"]),
        Q(1, "On BookTok, what does TBR stand for?", "To be read", ["Too busy reading", "Top book reviews", "The book rack"]),
        Q(1, "When a reader marks a book 'DNF,' what does it mean?", "Did not finish", ["Do not forget", "Definitely new favorite", "Dark new fantasy"]),
        Q(1, "In romance-reader speak, what does HEA stand for?", "Happily ever after", ["Hero's emotional arc", "High-emotion angst", "Heartbreak ends all"]),
        Q(1, "Which romance trope has sworn rivals falling in love?", "Enemies to lovers", ["Friends to lovers", "Second chance", "Forced proximity"]),
        Q(1, "Which romance trope has a couple pretending to be together?", "Fake dating", ["Slow burn", "Love triangle", "Grumpy-sunshine"]),
        Q(1, "Which 'Today' show host runs the 'Read with Jenna' book club?", "Jenna Bush Hager", ["Jenna Fischer", "Jenna Dewan", "Jenna Lyons"]),
        Q(1, "Michelle Obama's 2018 memoir is called what?", "Becoming", ["Living History", "Spoken from the Heart", "The Audacity of Hope"]),
        Q(1, "Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", ["Ernest Hemingway", "John Steinbeck", "William Faulkner"]),
        Q(1, "In 'The Great Gatsby,' what color is the light at the end of Daisy's dock?", "Green", ["Red", "White", "Blue"]),
        Q(1, "Who wrote 'To Kill a Mockingbird'?", "Harper Lee", ["Truman Capote", "Flannery O'Connor", "Carson McCullers"]),
        Q(1, "Who wrote 'The Da Vinci Code'?", "Dan Brown", ["John Grisham", "James Patterson", "Michael Crichton"]),
        Q(1, "Who wrote 'The Girl on the Train'?", "Paula Hawkins", ["Gillian Flynn", "Ruth Ware", "Lisa Jewell"]),
        Q(1, "Agatha Christie's detective Hercule Poirot is from which country?", "Belgium", ["France", "Switzerland", "The Netherlands"]),
        Q(1, "Besides Poirot, which sleuth did Agatha Christie create?", "Miss Marple", ["Nancy Drew", "Jessica Fletcher", "Jane Rizzoli"]),
        Q(1, "In 'The Handmaid's Tale,' the handmaids dress in what color?", "Red", ["White", "Blue", "Green"]),
        Q(1, "In 'The Hunger Games,' Katniss volunteers to take whose place?", "Prim", ["Gale", "Madge", "Rue"]),
        Q(1, "Who wrote the 1970 novel 'Are You There God? It's Me, Margaret'?", "Judy Blume", ["Beverly Cleary", "Lois Lowry", "Paula Danziger"]),
        Q(1, "Which site, bought by Amazon in 2013, lets readers log and rate books?", "Goodreads", ["StoryGraph", "LibraryThing", "Wattpad"]),
        Q(1, "On BookTok, a book with 'sprayed edges' has what?", "Colored page edges", ["Worn corners", "A torn dust jacket", "Gold-foil lettering"]),
        Q(1, "Which March sister dies in 'Little Women'?", "Beth", ["Amy", "Meg", "Jo"]),
        Q(1, "Who played the heroine in the 2024 film 'It Ends with Us'?", "Blake Lively", ["Sydney Sweeney", "Margot Robbie", "Florence Pugh"]),
        Q(1, "Who wrote 'Gone with the Wind'?", "Margaret Mitchell", ["Harper Lee", "Pearl S. Buck", "Edna Ferber"]),
        Q(1, "Heathcliff is the brooding hero of which novel?", "Wuthering Heights", ["Jane Eyre", "Rebecca", "Great Expectations"]),
        Q(1, "Who wrote 'Me Before You'?", "Jojo Moyes", ["Sophie Kinsella", "Cecelia Ahern", "Marian Keyes"]),
        Q(1, "Which Stephen King novel features a clown called Pennywise?", "It", ["Carrie", "Misery", "The Shining"]),

        Q(2, "Who wrote 'The Joy Luck Club'?", "Amy Tan", ["Lisa See", "Celeste Ng", "Maxine Hong Kingston"], "The 1989 novel became a 1993 film."),
        Q(2, "Who wrote the 'Outlander' novels?", "Diana Gabaldon", ["Julia Quinn", "Philippa Gregory", "Deborah Harkness"]),
        Q(2, "What's the second book in the 'Twilight' saga?", "New Moon", ["Eclipse", "Breaking Dawn", "Midnight Sun"]),
        Q(2, "Which series did Sarah J. Maas publish before ACOTAR?", "Throne of Glass", ["Shadow and Bone", "The Cruel Prince", "Red Queen"]),
        Q(2, "What's the name of the heroine of 'A Court of Thorns and Roses'?", "Feyre", ["Nesta", "Elain", "Celaena"]),
        Q(2, "After 'Iron Flame,' what's the third book in the Empyrean series?", "Onyx Storm", ["Crown of Midnight", "Kingdom of Ash", "Ruthless Vows"]),
        Q(2, "Madeline Miller's 'Circe' retells a figure from which epic?", "The Odyssey", ["The Iliad", "The Aeneid", "Beowulf"]),
        Q(2, "Who narrates 'The Book Thief'?", "Death", ["Liesel Meminger", "Max Vandenburg", "Rudy Steiner"]),
        Q(2, "Kathryn Stockett's 'The Help' is set in which Mississippi city?", "Jackson", ["Oxford", "Biloxi", "Tupelo"]),
        Q(2, "Who wrote 'The Color Purple'?", "Alice Walker", ["Toni Morrison", "Maya Angelou", "Zora Neale Hurston"]),
        Q(2, "In 'Pride and Prejudice,' Lydia Bennet runs off with whom?", "Mr. Wickham", ["Mr. Collins", "Mr. Bingley", "Colonel Fitzwilliam"]),
        Q(2, "In 'Sense and Sensibility,' Elinor and Marianne share what surname?", "Dashwood", ["Bennet", "Bertram", "Woodhouse"]),
        Q(2, "In 'Jane Eyre,' Mr. Rochester's house is called what?", "Thornfield Hall", ["Thrushcross Grange", "Gateshead Hall", "Northanger Abbey"]),
        Q(2, "'Anne of Green Gables' is set on which Canadian island?", "Prince Edward Island", ["Vancouver Island", "Cape Breton Island", "Newfoundland"]),
        Q(2, "In 'Little Women,' Jo March's full first name is what?", "Josephine", ["Joanna", "Johanna", "Jocelyn"]),
        Q(2, "The musical 'Wicked' is based on a 1995 novel by whom?", "Gregory Maguire", ["L. Frank Baum", "Neil Gaiman", "Stephen Schwartz"]),
        Q(2, "Who wrote 'Practical Magic'?", "Alice Hoffman", ["Anne Rice", "Deborah Harkness", "Sarah Addison Allen"]),
        Q(2, "In 'It Ends with Us,' the heroine opens what kind of shop?", "A flower shop", ["A bakery", "A bookstore", "A coffee shop"]),
        Q(2, "Taylor Jenkins Reid's 'Carrie Soto Is Back' is about which sport?", "Tennis", ["Golf", "Figure skating", "Swimming"]),
        Q(2, "Kristin Hannah's 'The Women' follows an Army nurse in which war?", "The Vietnam War", ["The Korean War", "World War II", "The Gulf War"]),
        Q(2, "The sleuths of 'The Thursday Murder Club' live where?", "A retirement village", ["A seaside hotel", "A convent", "A college town"], "Author Richard Osman created and co-hosted the BBC quiz show 'Pointless.'"),
        Q(2, "Who wrote 'People We Meet on Vacation'?", "Emily Henry", ["Abby Jimenez", "Christina Lauren", "Tessa Bailey"]),
        Q(2, "Who wrote the thriller 'The Housemaid'?", "Freida McFadden", ["Lisa Jewell", "Riley Sager", "Ruth Ware"], "The 2025 film starred Sydney Sweeney and Amanda Seyfried."),
        Q(2, "Who played Amy Dunne in the 2014 film 'Gone Girl'?", "Rosamund Pike", ["Rooney Mara", "Emily Blunt", "Charlize Theron"]),
        Q(2, "Which Nickelodeon star wrote the memoir 'I'm Glad My Mom Died'?", "Jennette McCurdy", ["Miranda Cosgrove", "Amanda Bynes", "Victoria Justice"]),
        Q(2, "Paulo Coelho, author of 'The Alchemist,' is from which country?", "Brazil", ["Portugal", "Argentina", "Spain"]),
        Q(2, "Many of Stephen King's stories are set in which state?", "Maine", ["Vermont", "New Hampshire", "Massachusetts"]),
        Q(2, "The Newbery Medal honors what kind of books?", "Children's literature", ["Poetry", "Mystery novels", "Debut novels"], "It was first awarded in 1922."),

        Q(3, "Louisa May Alcott published thrillers under which pen name?", "A. M. Barnard", ["L. M. Barrett", "A. J. Harlow", "E. M. Whitcomb"], "Most of her thrillers ran anonymously or under that pseudonym."),
        Q(3, "The Nancy Drew books are credited to which pen name?", "Carolyn Keene", ["Franklin W. Dixon", "Laura Lee Hope", "Ann M. Martin"], "Franklin W. Dixon was the house name on the Hardy Boys."),
        Q(3, "Who was the first woman to win the Pulitzer Prize for Fiction?", "Edith Wharton", ["Willa Cather", "Pearl S. Buck", "Margaret Mitchell"], "She won in 1921 for 'The Age of Innocence.'"),
        Q(3, "In 1993, who became the first Black woman to win the Nobel Prize in Literature?", "Toni Morrison", ["Maya Angelou", "Alice Walker", "Gwendolyn Brooks"], "'Beloved' had won her the Pulitzer Prize in 1988."),
        Q(3, "Donna Tartt won the 2014 Pulitzer Prize for which novel?", "The Goldfinch", ["The Secret History", "The Little Friend", "A Little Life"], "The title comes from a 1654 painting by Carel Fabritius."),
        Q(3, "Donna Tartt's 'The Secret History' is set at a college in which state?", "Vermont", ["Connecticut", "Maine", "New York"], "The fictional Hampden College is modeled on Bennington, where Tartt studied."),
        Q(3, "In 'All the Light We Cannot See,' Marie-Laure takes refuge in which walled town?", "Saint-Malo", ["Carcassonne", "Avignon", "Dinan"], "Anthony Doerr's novel won the 2015 Pulitzer Prize for Fiction."),
        Q(3, "Barbara Kingsolver's 'Demon Copperhead' reimagines which Dickens novel?", "David Copperfield", ["Oliver Twist", "Great Expectations", "Bleak House"], "It shared the 2023 Pulitzer Prize for Fiction."),
        Q(3, "In 'Remarkably Bright Creatures,' the aquarium's octopus is named what?", "Marcellus", ["Octavian", "Inky", "Otto"], "It lives at an aquarium in the fictional town of Sowell Bay, Washington."),
        Q(3, "In 'Lessons in Chemistry,' Elizabeth Zott's dog is named what?", "Six-Thirty", ["Half-Past", "Midnight", "Bunsen"], "He's named for the time he first followed her home."),
        Q(3, "In Emily Henry's 'Book Lovers,' Nora Stephens works as what?", "A literary agent", ["A book editor", "A bookseller", "A ghostwriter"], "Her rival-turned-love interest, Charlie, is the book editor."),
        Q(3, "Ali Hazelwood's 'The Love Hypothesis' began as fan fiction for which franchise?", "Star Wars", ["Harry Potter", "Twilight", "Marvel"], "Hero Adam Carlsen is named after actor Adam Driver."),
        Q(3, "Amazon launched the first Kindle in which year?", "2007", ["2004", "2009", "2010"], "The first model sold out in about five and a half hours."),
        Q(3, "Which U.S. bookstore chain closed all its stores in 2011?", "Borders", ["B. Dalton", "Crown Books", "Books-A-Million"], "Crown Books had closed a decade earlier, in 2001."),
        Q(3, "In 2011, novelist Ann Patchett opened which Nashville bookstore?", "Parnassus Books", ["BookPeople", "Powell's Books", "The Strand"], "She co-founded it with Karen Hayes."),
        Q(3, "Paris bookshop Shakespeare and Company sits across the Seine from which cathedral?", "Notre-Dame", ["Sacré-Cœur", "Saint-Sulpice", "Sainte-Chapelle"], "The original shop, run by Sylvia Beach, published 'Ulysses' in 1922."),
        Q(3, "In Daphne du Maurier's 'Rebecca,' who is the housekeeper at Manderley?", "Mrs. Danvers", ["Mrs. Fairfax", "Mrs. Hughes", "Mrs. Hudson"], "Mrs. Fairfax is the housekeeper at Thornfield in 'Jane Eyre.'"),
        Q(3, "In 'Anne of Green Gables,' Anne breaks a slate over whose head?", "Gilbert Blythe", ["Diana Barry", "Matthew Cuthbert", "Josie Pye"], "He had called her 'Carrots.' She eventually marries him."),
        Q(3, "In 'Gone Girl,' Amy's parents wrote a children's book series called what?", "Amazing Amy", ["Adorable Amy", "Brave Little Amy", "Always Amy"], "Amy resents the fictional Amy, who always gets things right."),
        Q(3, "Tara Westover's memoir 'Educated' recounts a childhood in which state?", "Idaho", ["Montana", "Utah", "Wyoming"], "She had never set foot in a classroom until she went to college at 17."),
        Q(3, "The Brontë sisters grew up in which Yorkshire village?", "Haworth", ["Whitby", "Grasmere", "Hebden Bridge"], "The parsonage where they wrote is now the Brontë Parsonage Museum."),
        Q(3, "'Where the Crawdads Sing' takes place near which fictional North Carolina town?", "Barkley Cove", ["Pelican Point", "Pamlico Point", "Cape Harbor"], "The 2022 film was produced by Reese Witherspoon's company, Hello Sunshine."),
        Q(3, "What was the very first Reese's Book Club pick, in 2017?", "Eleanor Oliphant Is Completely Fine", ["Where the Crawdads Sing", "Little Fires Everywhere", "The Last Thing He Told Me"], "Gail Honeyman's debut is set in Glasgow."),
        Q(3, "In 'The Summer I Turned Pretty,' Belly spends summers at which beach?", "Cousins Beach", ["Seabrook Beach", "Tides Point", "Sandy Cove"], "Jenny Han also wrote 'To All the Boys I've Loved Before.'"),
        Q(3, "In 'Fourth Wing,' Violet trains at which war college?", "Basgiath", ["Aretia", "Navarre", "Poromiel"], "Navarre is the kingdom; Poromiel is its rival across the border."),
        Q(3, "Louisa May Alcott wrote 'Little Women' at Orchard House in which town?", "Concord", ["Salem", "Lexington", "Amherst"], "Neighbors in Concord included Emerson, Thoreau, and Hawthorne."),
        Q(3, "In 'Wild,' Cheryl Strayed hikes which long-distance trail?", "The Pacific Crest Trail", ["The Appalachian Trail", "The John Muir Trail", "The Continental Divide Trail"], "Reese Witherspoon played her in the 2014 film."),
        Q(3, "Sweet Valley High's twins Jessica and Elizabeth share what surname?", "Wakefield", ["Whitfield", "Wentworth", "Winslow"], "The series was created by Francine Pascal in 1983."),
    ]
}
