import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let carsExtra: [QSpec] = [
        Q(1, "A dashboard light shaped like an oil can warns about what?", "Low oil pressure", ["Low coolant", "Low fuel", "Low washer fluid"], "Pull over soon: an engine without oil pressure can wreck itself fast."),
        Q(1, "A red battery-shaped dashboard light points to a problem with what?", "Charging system", ["Headlight bulbs", "Sound system", "Power locks"]),
        Q(1, "A dash light showing a thermometer in wavy lines warns of what?", "Engine overheating", ["A cold cabin", "Overheated brakes", "Low tire pressure"]),
        Q(1, "The horseshoe-shaped light with an exclamation point warns about what?", "Low tire pressure", ["Low brake fluid", "A loose gas cap", "Worn wiper blades"]),
        Q(1, "Which brand's logo is four interlocking rings?", "Audi", ["Volkswagen", "Opel", "Subaru"], "The rings stand for four companies that merged into Auto Union in 1932."),
        Q(1, "Which brand's logo is a three-pointed star?", "Mercedes-Benz", ["Volkswagen", "Chrysler", "Cadillac"]),
        Q(1, "Which brand's logo is a charging bull?", "Lamborghini", ["Ferrari", "Maserati", "Alfa Romeo"]),
        Q(1, "Which company makes the Mustang?", "Ford", ["Chevrolet", "Dodge", "Pontiac"]),
        Q(1, "Which company makes the Prius?", "Toyota", ["Honda", "Nissan", "Hyundai"]),
        Q(1, "Which company makes the Civic and the Accord?", "Honda", ["Toyota", "Mazda", "Kia"]),
        Q(1, "Which company makes the Silverado pickup?", "Chevrolet", ["Ford", "Ram", "Toyota"]),
        Q(1, "Which company makes the Miata?", "Mazda", ["Nissan", "Mitsubishi", "Subaru"]),
        Q(1, "The name Volkswagen means what in English?", "People's car", ["Fast wagon", "Wolf's car", "Road machine"]),
        Q(1, "Hyundai and Kia come from which country?", "South Korea", ["Japan", "China", "Taiwan"]),
        Q(1, "What does MPG stand for?", "Miles per gallon", ["Motor power gauge", "Miles per gear", "Max pump gallons"]),
        Q(1, "What does SUV stand for?", "Sport utility vehicle", ["Standard utility vehicle", "Super urban vehicle", "Sport unit van"]),
        Q(1, "The Daytona 500 is a race in which series?", "NASCAR", ["IndyCar", "Formula 1", "NHRA"]),
        Q(1, "The Monaco Grand Prix is a race in which series?", "Formula 1", ["NASCAR", "IndyCar", "MotoGP"]),
        Q(1, "In 'Back to the Future,' Doc Brown builds his time machine from what car?", "A DeLorean", ["A Corvette", "A Mustang", "A Trans Am"], "The DMC-12 had gull-wing doors and a stainless steel body."),
        Q(1, "In Pixar's 'Cars,' Lightning McQueen races under what number?", "95", ["43", "3", "88"], "It nods to 1995, the year 'Toy Story' came out."),
        Q(1, "James Bond's classic DB5 was built by which company?", "Aston Martin", ["Jaguar", "Bentley", "Rolls-Royce"], "It first appeared in 'Goldfinger' in 1964."),
        Q(1, "What is engine coolant, or antifreeze, for?", "Controlling engine heat", ["Lubricating the pistons", "Cleaning the fuel injectors", "Sealing slow tire leaks"]),
        Q(1, "Calipers, pads, and rotors are part of which system?", "Brakes", ["Suspension", "Exhaust", "Steering"]),
        Q(1, "In a gas engine, spark plugs do what?", "Ignite the fuel and air", ["Charge the battery", "Cool the cylinders", "Pump fuel to the engine"]),
        Q(1, "A car's odometer measures what?", "Total distance driven", ["Engine speed", "Fuel level", "Outside air temperature"]),
        Q(1, "A tachometer shows what?", "Engine speed", ["Road speed", "Oil pressure", "Coolant temperature"]),
        Q(1, "Chevrolet launched the Camaro in 1966 to rival which car?", "Ford Mustang", ["Dodge Charger", "Pontiac GTO", "Plymouth Barracuda"]),
        Q(1, "Mr. Bean famously drives which car?", "A Mini", ["A Fiat 500", "A VW Beetle", "A Reliant Robin"], "His running nemesis is a three-wheeled Reliant he keeps tipping over."),

        Q(2, "A flashing dash light of a car with squiggly skid marks means what?", "Traction control is working", ["The road is wet", "Tire tread is low", "The car needs a wheel alignment"]),
        Q(2, "A diesel engine ignites its fuel with what?", "Heat from compressed air", ["A spark plug", "A pilot flame", "A spark from the alternator"], "Squeezing air hard enough makes it hot enough to light the fuel."),
        Q(2, "A four-stroke engine's strokes are intake, compression, power, and what?", "Exhaust", ["Ignition", "Injection", "Cooling"]),
        Q(2, "A timing belt keeps what in sync?", "Crankshaft and camshafts", ["Front and rear wheels", "Fuel pump and fuel injectors", "Alternator and battery"]),
        Q(2, "A car's differential lets the drive wheels do what?", "Turn at different speeds", ["Brake one at a time on ice", "Adjust their own tire pressure", "Steer with the rear axle too"]),
        Q(2, "Blue-gray smoke from the tailpipe usually means the engine is burning what?", "Oil", ["Coolant", "Brake fluid", "Transmission fluid"]),
        Q(2, "Mazda is famous for which unusual engine design?", "The rotary", ["The boxer", "The W16", "The radial"]),
        Q(2, "Subaru and Porsche are both known for which engine layout?", "Boxer", ["Rotary", "V-twin", "W12"], "The pistons lie flat and punch outward, like a boxer's fists."),
        Q(2, "AMG is the performance arm of which brand?", "Mercedes-Benz", ["BMW", "Audi", "Volkswagen"]),
        Q(2, "Lexus is the luxury brand of which carmaker?", "Toyota", ["Honda", "Nissan", "Mazda"]),
        Q(2, "Nissan's GT-R carries what monster nickname?", "Godzilla", ["King Kong", "Mothra", "The Kraken"], "Australia's Wheels magazine coined it for the R32 GT-R in 1989."),
        Q(2, "The GTI is the hot version of which Volkswagen?", "Golf", ["Jetta", "Passat", "Tiguan"]),
        Q(2, "The Ford Mustang debuted in which year?", "1964", ["1962", "1967", "1969"], "It was unveiled at the New York World's Fair."),
        Q(2, "The Ford Model T's famous nickname was what?", "Tin Lizzie", ["Iron Horse", "Old Faithful", "Black Bess"]),
        Q(2, "Which carmaker introduced the three-point seat belt in 1959?", "Volvo", ["Saab", "Mercedes-Benz", "Ford"], "Volvo opened the patent so every maker could use it for free."),
        Q(2, "The winner of the Indy 500 traditionally drinks what in Victory Lane?", "Milk", ["Champagne", "Lemonade", "Orange juice"], "Louis Meyer started it in 1936 with a bottle of buttermilk."),
        Q(2, "In NASCAR, the white flag means what?", "One lap to go", ["Caution on track", "Pit road closed", "Race is over"]),
        Q(2, "In Formula 1, a blue flag tells a driver what?", "Let a faster car pass", ["Pit at the end of this lap", "Track is slippery", "Race is stopped"]),
        Q(2, "Richard Petty, 'The King,' retired with how many NASCAR Cup wins?", "200", ["105", "150", "250"], "His last win came at the 1984 Firecracker 400 at Daytona."),
        Q(2, "Who coined the term 'horsepower'?", "James Watt", ["Henry Ford", "Karl Benz", "Thomas Edison"], "He used it to sell steam engines to people who ran mills with horses."),
        Q(2, "In 'Ford v Ferrari,' Christian Bale plays which driver?", "Ken Miles", ["Carroll Shelby", "Dan Gurney", "Bruce McLaren"]),
        Q(2, "KITT in 'Knight Rider' was a modified what?", "Pontiac Trans Am", ["Chevrolet Camaro", "Ford Mustang", "Dodge Charger"]),
        Q(2, "The General Lee in 'The Dukes of Hazzard' is what car?", "Dodge Charger", ["Plymouth Road Runner", "Pontiac GTO", "Chevy Chevelle"]),
        Q(2, "On 'Top Gear,' the anonymous helmeted test driver is called what?", "The Stig", ["The Ghost", "The Pilot", "The Wheelman"]),
        Q(2, "In 'The Fast and the Furious' (2001), Brian's orange car is what?", "Toyota Supra", ["Nissan Skyline", "Honda NSX", "Mazda RX-7"]),
        Q(2, "Lewis Hamilton won his first F1 title, in 2008, with which team?", "McLaren", ["Mercedes", "Ferrari", "Williams"]),
        Q(2, "The E in E85 fuel stands for what?", "Ethanol", ["Electric", "Economy", "Emissions"]),
        Q(2, "The Jeep was born as a vehicle for whom?", "The US Army in WWII", ["The US Postal Service", "National Park rangers", "Midwest farmers"]),

        Q(3, "On a diesel, a dash light shaped like a coiled wire means what?", "The glow plugs are warming up", ["The turbocharger is spooling up", "The fuel filter is clogged", "The exhaust is too hot"], "Wait for it to go out before cranking, especially on a cold morning."),
        Q(3, "Karl Benz's 1886 Patent-Motorwagen had how many wheels?", "Three", ["Two", "Four", "Six"], "The first one made about two-thirds of a horsepower."),
        Q(3, "In 1888, who took the first long-distance drive in a car, a Benz?", "Bertha Benz", ["Karl Benz", "Gottlieb Daimler", "Wilhelm Maybach"], "She drove 66 miles to Pforzheim, buying fuel at a pharmacy on the way."),
        Q(3, "The 'Mercedes' in Mercedes-Benz was originally whose name?", "A Daimler dealer's daughter", ["Karl Benz's wife", "Gottlieb Daimler's mother", "A famous Spanish racing driver"], "Emil Jellinek raced Daimlers under his daughter's name from 1899."),
        Q(3, "The name Audi comes from the Latin word for what?", "Listen", ["Drive", "Gold", "Speed"], "It translates founder August Horch's surname, German for 'hark.'"),
        Q(3, "Before cars, the Toyoda family business built what?", "Automatic looms", ["Sewing machines", "Bicycles", "Rice cookers"], "Sakichi Toyoda's son Kiichiro started the car department in 1933."),
        Q(3, "Who designed the original Volkswagen Beetle?", "Ferdinand Porsche", ["Karl Benz", "Gottlieb Daimler", "Wilhelm Maybach"]),
        Q(3, "Ferrari's prancing horse first flew on whose WWI fighter plane?", "Francesco Baracca", ["Manfred von Richthofen", "Eddie Rickenbacker", "Italo Balbo"], "Baracca's parents told Enzo Ferrari it would bring him luck."),
        Q(3, "Before building his own cars, Enzo Ferrari raced for which brand?", "Alfa Romeo", ["Maserati", "Lancia", "Bugatti"], "Scuderia Ferrari, founded in 1929, raced Alfa Romeos at first."),
        Q(3, "The horse on Porsche's crest comes from which city's coat of arms?", "Stuttgart", ["Munich", "Wolfsburg", "Ingolstadt"]),
        Q(3, "Maserati's Ghibli, Levante, and Bora are all named after what?", "Winds", ["Italian lakes", "Fighting bulls", "Mountain passes"]),
        Q(3, "Which engineer designed the original 1959 Mini?", "Alec Issigonis", ["John Cooper", "Colin Chapman", "William Lyons"], "Its sideways engine left 80% of the floor for people and luggage."),
        Q(3, "Which carmaker first sold an electric self-starter, in 1912?", "Cadillac", ["Ford", "Buick", "Packard"], "Charles Kettering designed it, retiring the dangerous hand crank."),
        Q(3, "Ralph Teetor, the inventor of cruise control, was what?", "Blind", ["Deaf", "Colorblind", "Left-handed"], "Chrysler first offered his invention in 1958, as 'Auto-Pilot.'"),
        Q(3, "'Flash of Genius' tells how Robert Kearns invented what?", "The intermittent wiper", ["The third brake light", "Cruise control", "The rearview camera"], "He won patent cases against both Ford and Chrysler."),
        Q(3, "Since which model year have all US cars carried an OBD-II port?", "1996", ["1986", "1991", "2001"], "It's why a cheap scanner can read the check engine codes on most cars."),
        Q(3, "The Chevrolet Corvette debuted in which year?", "1953", ["1949", "1956", "1961"], "All 300 first-year cars were Polo White with red interiors."),
        Q(3, "The A-Team's black van was made by which company?", "GMC", ["Ford", "Dodge", "Volkswagen"], "It was a 1983 GMC Vandura with a red stripe and a roof spoiler."),
        Q(3, "Who won five Formula 1 world titles in the 1950s?", "Juan Manuel Fangio", ["José Froilán González", "Stirling Moss", "Jack Brabham"], "He won them with Alfa Romeo, Mercedes, Ferrari, and Maserati."),
        Q(3, "The Bugatti Veyron was powered by what engine layout?", "W16", ["V12", "V16", "Flat-12"], "Its 8.0-liter engine had four turbochargers."),
        Q(3, "Who beat Niki Lauda to the 1976 F1 title by a single point?", "James Hunt", ["Mario Andretti", "Jody Scheckter", "Emerson Fittipaldi"], "Their rivalry is the story of the 2013 film 'Rush.'"),
        Q(3, "A classic quarter-mile drag strip is how many feet long?", "1,320", ["1,000", "1,500", "1,760"], "NHRA shortened Top Fuel and Funny Car races to 1,000 feet in 2008."),
        Q(3, "Motorsport's Triple Crown is usually the Monaco GP, the 24 Hours of Le Mans, and what?", "The Indianapolis 500", ["The Daytona 500", "The 24 Hours of Daytona", "The Bathurst 1000"], "Graham Hill completed it with his 1972 Le Mans win."),
        Q(3, "Who won the first Indianapolis 500, in 1911?", "Ray Harroun", ["Louis Meyer", "Barney Oldfield", "Ralph DePalma"], "His Marmon Wasp used a rearview mirror instead of a riding mechanic."),
        Q(3, "Carroll Shelby won the 1959 24 Hours of Le Mans driving for which brand?", "Aston Martin", ["Ferrari", "Jaguar", "Mercedes-Benz"], "He co-drove the DBR1 with Roy Salvadori."),
        Q(3, "In 1991, which brand became the first from Japan to win Le Mans?", "Mazda", ["Toyota", "Nissan", "Honda"], "The winning 787B used a four-rotor rotary engine."),
        Q(3, "Which NASCAR champion did rival Cale Yarborough nickname 'Jaws'?", "Darrell Waltrip", ["Bobby Allison", "Rusty Wallace", "Benny Parsons"], "Waltrip went on to win Cup titles in 1981, 1982, and 1985."),
        Q(3, "Top Fuel dragsters run mostly on what fuel?", "Nitromethane", ["Methanol", "Ethanol", "Racing gasoline"], "Nitro carries its own oxygen, so an engine can burn far more of it."),
    ]
}
