import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let divasExtra: [QSpec] = [
        Q(1, "The Beyhive is the fan base of which singer?", "Beyoncé", ["Rihanna", "Ciara", "Lizzo"]),
        Q(1, "Lady Gaga calls her fans what?", "Little Monsters", ["Arianators", "Lovatics", "Smilers"]),
        Q(1, "'Rolling in the Deep' is on which Adele album?", "21", ["19", "25", "30"]),
        Q(1, "'Toxic' and '...Baby One More Time' are hits by whom?", "Britney Spears", ["Christina Aguilera", "Jessica Simpson", "Mandy Moore"]),
        Q(1, "Gwen Stefani fronted which band before going solo?", "No Doubt", ["Garbage", "Hole", "The Cranberries"]),
        Q(1, "Rihanna's 2007 smash with Jay-Z was what?", "Umbrella", ["Diamonds", "Work", "Rude Boy"]),
        Q(1, "Whitney Houston starred opposite Kevin Costner in which 1992 film?", "The Bodyguard", ["Waiting to Exhale", "The Preacher's Wife", "Sparkle"]),
        Q(1, "'Roar' and 'Firework' are hits by whom?", "Katy Perry", ["Kesha", "Demi Lovato", "Kelly Clarkson"]),
        Q(1, "Kelly Clarkson won the very first season of which show?", "American Idol", ["The Voice", "The X Factor", "Star Search"]),
        Q(1, "Who sang 'Man! I Feel Like a Woman!'?", "Shania Twain", ["Faith Hill", "LeAnn Rimes", "Martina McBride"]),
        Q(1, "Céline Dion's 'My Heart Will Go On' is from which movie?", "Titanic", ["Armageddon", "Pearl Harbor", "The Bodyguard"]),
        Q(1, "Beyoncé first found fame in which girl group?", "Destiny's Child", ["TLC", "En Vogue", "SWV"]),
        Q(1, "Miley Cyrus's dad had a 1992 hit with what?", "Achy Breaky Heart", ["Friends in Low Places", "Boot Scootin' Boogie", "Chattahoochee"]),
        Q(1, "Taylor Swift named her 2014 album after what?", "Her birth year", ["Her lucky number", "Her first apartment", "Her mom's birth year"], "She was born in December 1989."),
        Q(1, "Adele's 2015 comeback single was what?", "Hello", ["Someone Like You", "Easy on Me", "Skyfall"]),
        Q(1, "Madonna's 1990 hit named after a dance from Harlem's ballroom scene is what?", "Vogue", ["Express Yourself", "Holiday", "Music"]),
        Q(1, "Dolly Parton's 1980 hit about office life is what?", "9 to 5", ["Jolene", "Islands in the Stream", "Here You Come Again"]),
        Q(1, "Cher's 1998 comeback smash was what?", "Believe", ["Strong Enough", "If I Could Turn Back Time", "Dark Lady"]),
        Q(1, "What was the Spice Girls' 1996 debut single?", "Wannabe", ["Spice Up Your Life", "Say You'll Be There", "2 Become 1"]),
        Q(1, "Billie Eilish sang the theme for which James Bond film?", "No Time to Die", ["Skyfall", "Spectre", "Quantum of Solace"]),
        Q(1, "Billie Eilish's 'What Was I Made For?' is from which 2023 film?", "Barbie", ["Wonka", "Wicked", "Oppenheimer"]),
        Q(1, "Lizzo famously plays which instrument on stage?", "Flute", ["Saxophone", "Violin", "Clarinet"]),
        Q(1, "Olivia Rodrigo's 2021 breakout single was what?", "drivers license", ["traitor", "happier", "brutal"]),
        Q(1, "Taylor Swift's 'Love Story' retells which Shakespeare play?", "Romeo and Juliet", ["Hamlet", "Much Ado About Nothing", "Macbeth"]),
        Q(1, "'Espresso' and 'Please Please Please' are by whom?", "Sabrina Carpenter", ["Chappell Roan", "Tate McRae", "Olivia Rodrigo"]),
        Q(1, "Who sang the disco anthem 'I Will Survive'?", "Gloria Gaynor", ["Donna Summer", "Diana Ross", "Chaka Khan"]),
        Q(1, "Who had a 1984 No. 1 with 'What's Love Got to Do with It'?", "Tina Turner", ["Cyndi Lauper", "Pat Benatar", "Diana Ross"]),
        Q(1, "Beyoncé grew up in which Texas city?", "Houston", ["Dallas", "Austin", "San Antonio"]),
        Q(2, "Lady Gaga's birth name is Stefani what?", "Germanotta", ["Gagliardi", "Genovese", "Giordano"]),
        Q(2, "At which 2010 awards show did Lady Gaga wear a dress made of raw meat?", "MTV VMAs", ["Grammys", "American Music Awards", "Met Gala"]),
        Q(2, "Ariana Grande played Cat Valentine on which Nickelodeon show?", "Victorious", ["Drake & Josh", "Zoey 101", "True Jackson, VP"]),
        Q(2, "Britney Spears's 2013-2017 Las Vegas residency was called what?", "Piece of Me", ["Circus", "Glory", "Oops!"]),
        Q(2, "Rihanna headlined the Super Bowl halftime show in which year?", "2023", ["2021", "2022", "2024"]),
        Q(2, "Mariah Carey first released 'All I Want for Christmas Is You' in which year?", "1994", ["1990", "1998", "2001"], "It didn't reach No. 1 on the Hot 100 until December 2019."),
        Q(2, "Taylor Swift's cat Olivia Benson is named for a character on which show?", "Law & Order: SVU", ["Grey's Anatomy", "Criminal Minds", "Scandal"]),
        Q(2, "Beyoncé's 2008 onstage alter ego was named what?", "Sasha Fierce", ["Roxie Blaze", "Coco Fierce", "Nia Storm"]),
        Q(2, "Adele won an Oscar for which James Bond theme?", "Skyfall", ["Writing's on the Wall", "GoldenEye", "Casino Royale"]),
        Q(2, "Dua Lipa was born in which city?", "London", ["Pristina", "Tirana", "Manchester"]),
        Q(2, "In the 2024 film 'Wicked,' Ariana Grande plays whom?", "Glinda", ["Elphaba", "Nessarose", "Madame Morrible"]),
        Q(2, "Kylie Minogue first found fame as Charlene on which soap?", "Neighbours", ["Home and Away", "EastEnders", "Coronation Street"]),
        Q(2, "Whose first No. 1, in 1999, was 'Genie in a Bottle'?", "Christina Aguilera", ["Britney Spears", "Jessica Simpson", "Mandy Moore"]),
        Q(2, "Janet Jackson's 1986 breakthrough album was called what?", "Control", ["janet.", "The Velvet Rope", "Damita Jo"]),
        Q(2, "Madonna played Eva Perón in which 1996 film?", "Evita", ["Dick Tracy", "Desperately Seeking Susan", "A League of Their Own"]),
        Q(2, "Whitney Houston and Mariah Carey dueted on a song from which film?", "The Prince of Egypt", ["The Bodyguard", "Waiting to Exhale", "Glitter"], "'When You Believe' won the Oscar for Best Original Song."),
        Q(2, "Beyoncé's 2013 self-titled album dropped with what twist?", "No announcement at all", ["Vinyl only", "Free with a phone", "Sold only at Target"]),
        Q(2, "Miley Cyrus's 'Flowers' won which big Grammy in 2024?", "Record of the Year", ["Song of the Year", "Album of the Year", "Best New Artist"]),
        Q(2, "Time named Taylor Swift its Person of the Year in which year?", "2023", ["2015", "2020", "2024"]),
        Q(2, "Barbra Streisand won Best Actress for which film?", "Funny Girl", ["Hello, Dolly!", "The Way We Were", "A Star Is Born"], "She tied with Katharine Hepburn that year."),
        Q(2, "Lorde, of 'Royals' fame, is from which country?", "New Zealand", ["Australia", "Ireland", "Canada"]),
        Q(2, "Which singer is known as the Queen of Disco?", "Donna Summer", ["Chaka Khan", "Diana Ross", "Grace Jones"]),
        Q(2, "Which Spice Girl wore the Union Jack dress at the 1997 BRITs?", "Geri Halliwell", ["Mel B", "Emma Bunton", "Mel C"]),
        Q(2, "At the 2009 VMAs, Kanye West interrupted Taylor Swift accepting which award?", "Best Female Video", ["Video of the Year", "Best New Artist", "Best Pop Video"]),
        Q(2, "Which country star is Miley Cyrus's godmother?", "Dolly Parton", ["Reba McEntire", "Shania Twain", "Loretta Lynn"]),
        Q(2, "Christina Aguilera's first single came from which Disney film?", "Mulan", ["Pocahontas", "Hercules", "Tarzan"], "The song was 'Reflection,' released in 1998."),
        Q(2, "Who won Best New Artist at the 2025 Grammys?", "Chappell Roan", ["Sabrina Carpenter", "Doechii", "Benson Boone"]),
        Q(2, "Bette Midler's 'Wind Beneath My Wings' is from which film?", "Beaches", ["Hocus Pocus", "The Rose", "Steel Magnolias"]),
        Q(3, "What was Whitney Houston's first No. 1 on the Hot 100?", "Saving All My Love for You", ["Greatest Love of All", "How Will I Know", "I Wanna Dance with Somebody"], "It topped the chart in October 1985."),
        Q(3, "By 1988 Whitney Houston had set a record with how many straight No. 1s?", "Seven", ["Five", "Six", "Eight"], "The streak broke a record shared by the Beatles and the Bee Gees."),
        Q(3, "How many straight Hot 100 No. 1s did Mariah Carey open her career with?", "Five", ["Three", "Four", "Six"], "'Emotions' in 1991 made it five, beating the Jackson 5's four."),
        Q(3, "Aretha Franklin's 'Respect' was written and first recorded by whom?", "Otis Redding", ["Sam Cooke", "Ray Charles", "Marvin Gaye"], "Redding released it in 1965; Aretha's version followed in 1967."),
        Q(3, "Sinéad O'Connor's 1990 smash was written by Prince. What was it?", "Nothing Compares 2 U", ["Mandinka", "The Emperor's New Clothes", "Troy"], "He first gave it to his side project, The Family, in 1985."),
        Q(3, "Which Swedish songwriter wrote '...Baby One More Time'?", "Max Martin", ["Shellback", "RedOne", "Timbaland"], "Martin also co-wrote hits for Taylor Swift, Katy Perry and Ariana Grande."),
        Q(3, "Sia co-wrote which 2012 Rihanna No. 1?", "Diamonds", ["We Found Love", "Only Girl (In the World)", "Stay"], "Sia said she wrote it in about 14 minutes."),
        Q(3, "Which member of The National co-produced Taylor Swift's 'folklore'?", "Aaron Dessner", ["Matt Berninger", "Bryan Devendorf", "Scott Devendorf"], "Jack Antonoff also produced several of its tracks."),
        Q(3, "As 'Nils Sjöberg,' Taylor Swift co-wrote a 2016 hit for whom?", "Calvin Harris", ["Zedd", "The Chainsmokers", "Kygo"], "The song was 'This Is What You Came For,' sung by Rihanna."),
        Q(3, "Taylor Swift wrote 'Better Man' (2016) for which country group?", "Little Big Town", ["Lady A", "The Band Perry", "Sugarland"], "It won Song of the Year at the 2017 CMA Awards, with Swift credited."),
        Q(3, "OneRepublic's Ryan Tedder co-wrote which Beyoncé ballad?", "Halo", ["Irreplaceable", "If I Were a Boy", "Listen"], "'Halo' won Best Female Pop Vocal Performance in 2010."),
        Q(3, "Madonna's 'Material Girl' video recreates a number from which film?", "Gentlemen Prefer Blondes", ["Some Like It Hot", "How to Marry a Millionaire", "The Seven Year Itch"], "It restages Marilyn Monroe's 'Diamonds Are a Girl's Best Friend.'"),
        Q(3, "In 2023, Beyoncé broke the all-time Grammy record held by whom?", "Georg Solti", ["Quincy Jones", "Alison Krauss", "Stevie Wonder"], "Her 32nd win passed the conductor's 31."),
        Q(3, "In 2024, Taylor Swift became the first artist to win Album of the Year how many times?", "Four", ["Two", "Three", "Five"], "Fearless, 1989, folklore and Midnights."),
        Q(3, "Diane Warren wrote which Toni Braxton hit?", "Un-Break My Heart", ["Breathe Again", "You're Makin' Me High", "Another Sad Love Song"], "It spent 11 weeks at No. 1 on the Hot 100 in 1996-97."),
        Q(3, "Cher's 'Believe' made which vocal effect famous?", "Auto-Tune", ["Talk box", "Echo chamber", "Vocal doubling"], "It became known in the studio world as the Cher effect."),
        Q(3, "Tina Turner played Aunty Entity in which film?", "Mad Max Beyond Thunderdome", ["The Road Warrior", "Tank Girl", "Escape from New York"], "She also sang its theme, 'We Don't Need Another Hero.'"),
        Q(3, "Janet Jackson played Penny on which 1970s sitcom?", "Good Times", ["The Jeffersons", "What's Happening!!", "Sanford and Son"], "She joined the show in 1977, at age 11."),
        Q(3, "Céline Dion is the youngest of how many children?", "Fourteen", ["Eight", "Ten", "Twelve"], "She grew up in Charlemagne, Quebec."),
        Q(3, "Céline Dion sang Disney's 1991 'Beauty and the Beast' theme with whom?", "Peabo Bryson", ["Michael Bolton", "Luther Vandross", "Babyface"], "The duet won a Grammy and the song won the Oscar."),
        Q(3, "Kylie Minogue's first Grammy came for which song?", "Come Into My World", ["Can't Get You Out of My Head", "Padam Padam", "Slow"], "She won Best Dance Recording in 2004."),
        Q(3, "Which Taylor Swift album did she write entirely by herself?", "Speak Now", ["Fearless", "Red", "Lover"], "She wrote all 14 tracks of the 2010 album solo."),
        Q(3, "The Eras Tour played its final show in December 2024 in which city?", "Vancouver", ["Toronto", "Los Angeles", "Nashville"], "It ended at BC Place after 149 shows on five continents."),
        Q(3, "Which song made Beyoncé the first Black woman to top Billboard's Hot Country Songs?", "Texas Hold 'Em", ["16 Carriages", "Jolene", "II Most Wanted"], "It topped that chart in February 2024, about a week after its release."),
        Q(3, "Ariana Grande made her Broadway debut in which musical?", "13", ["Annie", "Hairspray", "Wicked"], "The 2008 show was a Jason Robert Brown musical with an all-teen cast."),
        Q(3, "At the first MTV VMAs in 1984, Madonna performed atop a giant what?", "Wedding cake", ["Disco ball", "Grand piano", "Staircase"], "She sang 'Like a Virgin' in a wedding dress."),
        Q(3, "The spoken bridge of 'Oops!... I Did It Again' references which film?", "Titanic", ["Armageddon", "Men in Black", "Jurassic Park"], "The bit is about the necklace the old lady dropped into the ocean."),
        Q(3, "The 'Roan' in Chappell Roan comes from what?", "Her grandpa's favorite song", ["Her first horse", "Her hometown", "A Missouri river"], "Chappell was his surname; the song was 'The Strawberry Roan.'"),
    ]
}
