import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let fashionExtra: [QSpec] = [
        Q(1, "Which sportswear brand is known for its three stripes?", "Adidas", ["Puma", "Nike", "Reebok"]),
        Q(1, "Christian Louboutin heels are famous for soles of what color?", "Red", ["Black", "Gold", "Blue"]),
        Q(1, "The quilted 2.55 bag with a chain strap comes from which house?", "Chanel", ["Dior", "Gucci", "Prada"], "It's named for its debut date: February 1955."),
        Q(1, "Who made the little black dress a staple in the 1920s?", "Coco Chanel", ["Elsa Schiaparelli", "Christian Dior", "Jeanne Lanvin"], "In 1926 Vogue compared her simple black dress to Ford's Model T."),
        Q(1, "Linen is woven from which plant?", "Flax", ["Cotton", "Hemp", "Bamboo"]),
        Q(1, "What is a stiletto?", "A tall, thin high heel", ["A flat ballet shoe", "A chunky block heel", "A cork wedge"]),
        Q(1, "What is a romper?", "A one-piece top and shorts", ["A loose knit cardigan", "A cropped puffer jacket", "A pleated tennis skirt"]),
        Q(1, "Which diamond pattern is a classic on socks and sweaters?", "Argyle", ["Plaid", "Paisley", "Houndstooth"]),
        Q(1, "Which Italian house uses the head of Medusa as its logo?", "Versace", ["Fendi", "Moschino", "Valentino"]),
        Q(1, "What does 'fast fashion' mean?", "Cheap, quickly made trendy clothes", ["Clothing sold only through apps", "Performance gear for runners", "Wrinkle-free clothing for travel"]),
        Q(1, "Tiffany & Co.'s signature box is what color?", "Robin's egg blue", ["Mint green", "Blush pink", "Lavender"]),
        Q(1, "A pashmina is a type of what?", "Shawl", ["Handbag", "Sandal", "Hat"]),
        Q(1, "Espadrilles traditionally have soles made of what?", "Braided jute rope", ["Carved cork", "Molded rubber", "Stacked wood"]),
        Q(1, "A sweetheart neckline is shaped like what?", "The top of a heart", ["A deep V", "A straight line", "A square"]),
        Q(1, "Which brand makes Wayfarer sunglasses?", "Ray-Ban", ["Oakley", "Persol", "Maui Jim"]),
        Q(1, "What is a clutch?", "A small handbag with no handle", ["A wide belt", "A low-heeled shoe", "A long evening glove"]),
        Q(1, "Which brand made sheepskin boots a 2000s craze?", "UGG", ["Sorel", "Hunter", "Timberland"]),
        Q(1, "A polo player on horseback is whose logo?", "Ralph Lauren", ["Tommy Hilfiger", "Lacoste", "Brooks Brothers"]),
        Q(1, "Which animal is on Lacoste's logo?", "A crocodile", ["A lizard", "A snake", "A shark"], "Tennis star René Lacoste was nicknamed 'the Crocodile.'"),
        Q(1, "How long is a maxi skirt?", "Ankle or floor length", ["Mid-thigh", "Just above the knee", "Mid-calf"]),
        Q(1, "Which British house is famous for its camel, black, red, and white check?", "Burberry", ["Barbour", "Mulberry", "Aquascutum"]),
        Q(1, "What is athleisure?", "Workout clothes worn every day", ["Formal wear for golf clubs", "Waterproof hiking gear", "Clothes made from recycled plastic"]),
        Q(1, "When a tailor hems your pants, what changes?", "The length", ["The waist", "The color", "The pockets"]),
        Q(1, "Blue jeans are traditionally dyed with what?", "Indigo", ["Henna", "Saffron", "Beet juice"]),
        Q(1, "Velour tracksuits were a 2000s craze thanks to which brand?", "Juicy Couture", ["Abercrombie & Fitch", "Ed Hardy", "Baby Phat"]),
        Q(1, "Converse's classic canvas high-top is named after whom?", "Chuck Taylor", ["Stan Smith", "Michael Jordan", "Rod Laver"], "Taylor was a basketball player turned Converse salesman."),
        Q(1, "The plaid on a Scottish kilt is called what?", "Tartan", ["Paisley", "Gingham", "Chevron"]),
        Q(1, "What is a mule?", "A backless shoe", ["A lace-up boot", "A strappy sandal", "A rain boot"]),

        Q(2, "What is the pattern of small, jagged, broken checks called?", "Houndstooth", ["Herringbone", "Gingham", "Argyle"]),
        Q(2, "In 1873, Levi Strauss and Jacob Davis patented what for work pants?", "Copper rivets", ["The zipper", "Belt loops", "Back pockets"]),
        Q(2, "Stan Smith sneakers are made by which brand?", "Adidas", ["Nike", "Reebok", "New Balance"]),
        Q(2, "The paisley pattern is named after a town in which country?", "Scotland", ["India", "Ireland", "England"]),
        Q(2, "On 'Project Runway,' who told designers to 'make it work'?", "Tim Gunn", ["Michael Kors", "Isaac Mizrahi", "Zac Posen"]),
        Q(2, "Amancio Ortega founded which fashion chain?", "Zara", ["Mango", "H&M", "Uniqlo"]),
        Q(2, "The 'H' in H&M stands for Hennes, Swedish for what?", "Hers", ["His", "Home", "Hands"], "It opened in 1947 as a women's clothing store in Västerås."),
        Q(2, "Uniqlo comes from which country?", "Japan", ["South Korea", "China", "Taiwan"]),
        Q(2, "Which designer dressed the Sex Pistols and helped invent punk style?", "Vivienne Westwood", ["Mary Quant", "Zandra Rhodes", "Katharine Hamnett"]),
        Q(2, "Which supermodel was nicknamed 'The Body'?", "Elle Macpherson", ["Cindy Crawford", "Claudia Schiffer", "Naomi Campbell"]),
        Q(2, "In the 2008 'Sex and the City' film, Big proposes with a shoe by whom?", "Manolo Blahnik", ["Jimmy Choo", "Christian Louboutin", "Stuart Weitzman"]),
        Q(2, "The Baguette, a small bag tucked under the arm, is from which house?", "Fendi", ["Dior", "Celine", "Balenciaga"]),
        Q(2, "The Lady Dior bag was renamed in honor of whom?", "Princess Diana", ["Grace Kelly", "Queen Elizabeth II", "Princess Margaret"]),
        Q(2, "The 'DK' in DKNY stands for which designer?", "Donna Karan", ["Anne Klein", "Norma Kamali", "Liz Claiborne"]),
        Q(2, "Who designed Michelle Obama's 2009 inaugural ball gown?", "Jason Wu", ["Prabal Gurung", "Narciso Rodriguez", "Oscar de la Renta"]),
        Q(2, "Mohair comes from which animal?", "The Angora goat", ["The Angora rabbit", "The alpaca", "The cashmere goat"]),
        Q(2, "What is a Peter Pan collar?", "A flat collar with rounded ends", ["A tall stand-up collar", "A pointed button-down collar", "A wide sailor collar"]),
        Q(2, "What is a Mary Jane?", "A shoe with a strap over the instep", ["A slip-on loafer with a tassel", "A lace-up ankle boot", "A backless slide sandal"]),
        Q(2, "Which designer revived Gucci as creative director in the 1990s?", "Tom Ford", ["Alessandro Michele", "Marc Jacobs", "John Galliano"]),
        Q(2, "Elsa Schiaparelli made which color her signature?", "Shocking pink", ["Tiffany blue", "Klein blue", "Emerald green"]),
        Q(2, "Hermès packs its purchases in boxes of what color?", "Orange", ["Navy", "Black", "Red"]),
        Q(2, "The bikini, launched in 1946, was named after what?", "A Pacific atoll", ["A French beach", "Its designer", "A Brazilian dance"], "Louis Réard named it for Bikini Atoll, then in the news for bomb tests."),
        Q(2, "The Birkin bag is named after which actress and singer?", "Jane Birkin", ["Jane Fonda", "Brigitte Bardot", "Catherine Deneuve"]),
        Q(2, "Which Italian designer has a shade of red named after him?", "Valentino", ["Versace", "Armani", "Gucci"]),
        Q(2, "London's Savile Row is famous for what?", "Bespoke men's tailoring", ["Shoemakers", "Hat shops", "Department stores"]),
        Q(2, "Who designed Audrey Hepburn's black dress in 'Breakfast at Tiffany's'?", "Hubert de Givenchy", ["Coco Chanel", "Christian Dior", "Cristóbal Balenciaga"]),
        Q(2, "Birkenstock sandals come from which country?", "Germany", ["Switzerland", "Denmark", "Austria"]),
        Q(2, "Which house introduced the horsebit loafer in 1953?", "Gucci", ["Ferragamo", "Tod's", "Prada"]),

        Q(3, "What was Pantone's first Color of the Year, for 2000?", "Cerulean", ["Tangerine Tango", "Marsala", "Mimosa"], "Pantone pitched the calm blue as a hue for the new millennium."),
        Q(3, "Who designed Marilyn Monroe's white dress in 'The Seven Year Itch'?", "William Travilla", ["Edith Head", "Oleg Cassini", "Hubert de Givenchy"], "Travilla called his most famous creation 'that silly little dress.'"),
        Q(3, "Who designed Princess Diana's 1994 'revenge dress'?", "Christina Stambolian", ["Catherine Walker", "Bruce Oldfield", "Elizabeth Emanuel"], "Diana had owned it for three years, fearing it was too daring."),
        Q(3, "Marc Jacobs joined which house in 1997 to launch its ready-to-wear?", "Louis Vuitton", ["Christian Dior", "Celine", "Givenchy"], "Before him, the house was known for luggage and leather goods."),
        Q(3, "The interlocking YSL logo was designed by which artist?", "Cassandre", ["Andy Warhol", "Jean Cocteau", "Salvador Dalí"], "The poster artist pitched just one design, and the house took it."),
        Q(3, "Coco Chanel first made her name selling what?", "Hats", ["Perfume", "Handbags", "Jersey dresses"], "In 1910 she opened a millinery shop on Paris's Rue Cambon."),
        Q(3, "Who created Louis Vuitton's Monogram canvas in 1896?", "Georges Vuitton", ["Louis Vuitton", "Gaston-Louis Vuitton", "Marc Jacobs"], "The founder's son designed it partly to stop counterfeiters."),
        Q(3, "Who made Jackie Kennedy's pillbox hat for the 1961 inauguration?", "Halston", ["Oleg Cassini", "Mr. John", "Lilly Daché"], "He was then head milliner at Bergdorf Goodman."),
        Q(3, "Christian Louboutin got his red-sole idea from what?", "An assistant's nail polish", ["A red carpet at Cannes", "A Moulin Rouge poster", "A cardinal's robes"], "He painted a prototype's dull black sole with her red polish and kept it."),
        Q(3, "Levi Strauss opened his dry goods business in which city in 1853?", "San Francisco", ["Denver", "New York", "Sacramento"], "He came west to supply the California Gold Rush boom."),
        Q(3, "Cristóbal Balenciaga opened his first house in which country?", "Spain", ["France", "Italy", "Portugal"], "He started in San Sebastián before moving to Paris in 1937."),
        Q(3, "The designers known as the 'Antwerp Six' came from which country?", "Belgium", ["Netherlands", "Denmark", "Switzerland"], "They included Dries Van Noten and Ann Demeulemeester."),
        Q(3, "Rei Kawakubo founded which fashion label?", "Comme des Garçons", ["Issey Miyake", "Yohji Yamamoto", "Kenzo"], "The Met's 2017 show on her was only its second on a living designer."),
        Q(3, "The 2018 Met Gala theme, 'Heavenly Bodies,' paired fashion with what?", "The Catholic imagination", ["Astronomy", "Greek mythology", "Space travel"], "The Vatican lent papal vestments for the exhibition."),
        Q(3, "Which editor wrote the 'Why Don't You...?' column for Harper's Bazaar?", "Diana Vreeland", ["Carmel Snow", "Grace Mirabella", "Anna Wintour"], "One tip: rinse a blond child's hair in dead champagne, as they do in France."),
        Q(3, "Nylon stockings went on sale across the US in which year?", "1940", ["1935", "1946", "1952"], "Shoppers lined up for them on 'N-Day,' May 15."),
        Q(3, "Shoe designer Jimmy Choo was born in which country?", "Malaysia", ["Singapore", "Hong Kong", "Thailand"], "Born in Penang, he made his first pair of shoes at age 11."),
        Q(3, "Who succeeded Karl Lagerfeld as Chanel's creative head in 2019?", "Virginie Viard", ["Phoebe Philo", "Clare Waight Keller", "Maria Grazia Chiuri"], "She had worked alongside Lagerfeld for three decades."),
        Q(3, "Who became Dior's first female artistic director in 2016?", "Maria Grazia Chiuri", ["Phoebe Philo", "Sarah Burton", "Stella McCartney"], "Her debut featured a T-shirt reading 'We Should All Be Feminists.'"),
        Q(3, "The trench coat takes its name from which war?", "World War I", ["The Boer War", "The Crimean War", "World War II"], "Officers wore them in the trenches of the Western Front."),
        Q(3, "Linda Evangelista said supermodels don't wake up for less than what?", "$10,000 a day", ["$5,000 a day", "$1,000 an hour", "$50,000 a show"], "She said it to Vogue in 1990."),
        Q(3, "The 1960s model Twiggy was born with what name?", "Lesley Hornby", ["Susan Pemberton", "Patricia Hurst", "Gillian Hart"], "At 16 she was named 'The Face of 1966' by the Daily Express."),
        Q(3, "Tiffany's signature blue first appeared on the cover of what, in 1845?", "Its jewelry catalog", ["A shopping bag", "Its first ring box", "A store awning"], "Charles Lewis Tiffany chose it for the cover of his Blue Book catalog."),
        Q(3, "In which decade did Burberry introduce its check as a coat lining?", "1920s", ["1890s", "1950s", "1970s"], "It first appeared in 1924, inside the trench coat."),
        Q(3, "Salvatore Ferragamo patented which heel in 1937?", "The cork wedge", ["The stiletto", "The kitten heel", "The Cuban heel"], "Sanctions on Italy made steel for shoe arches scarce, so he tried cork."),
        Q(3, "The Hermès Birkin bag was first sketched on what?", "An airplane sick bag", ["A cocktail napkin", "A hotel menu", "A boarding pass"], "Jane Birkin met Hermès chief Jean-Louis Dumas on a Paris-London flight."),
        Q(3, "Coco Chanel's given first name was what?", "Gabrielle", ["Colette", "Marguerite", "Adrienne"], "The nickname is usually traced to songs she sang in cafés in Moulins."),
        Q(3, "Nike paid Carolyn Davidson how much to design the swoosh in 1971?", "$35", ["$350", "$3,500", "$100"], "She was a Portland State student; Nike later gave her stock."),
    ]
}
