import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let fightnightExtra: [QSpec] = [
        Q(1, "Muhammad Ali said he'd float like a butterfly and sting like what?", "A bee", ["A wasp", "A scorpion", "A jellyfish"]),
        Q(1, "Which boxing promoter was famous for his sky-high, straight-up hair?", "Don King", ["Bob Arum", "Eddie Hearn", "Lou DiBella"]),
        Q(1, "UFC stands for Ultimate Fighting what?", "Championship", ["Challenge", "Combat", "Circuit"]),
        Q(1, "Which comedian and podcaster is famous as a UFC commentator?", "Joe Rogan", ["Bill Burr", "Theo Von", "Andrew Schulz"]),
        Q(1, "Muay Thai comes from which country?", "Thailand", ["Japan", "China", "Vietnam"]),
        Q(1, "In 2017, Floyd Mayweather boxed which UFC star?", "Conor McGregor", ["Nate Diaz", "Anderson Silva", "Khabib Nurmagomedov"]),
        Q(1, "Hulk Hogan's ring gear was famously which colors?", "Red and yellow", ["Black and white", "Green and gold", "Blue and silver"]),
        Q(1, "Which wrestler told America to 'Snap into a Slim Jim'?", "Randy Savage", ["Hulk Hogan", "Ric Flair", "The Ultimate Warrior"]),
        Q(1, "Which wrestler is known as 'The Nature Boy'?", "Ric Flair", ["Shawn Michaels", "Dusty Rhodes", "Randy Savage"]),
        Q(1, "In the Royal Rumble, how is a wrestler eliminated?", "Over the top rope to the floor", ["By pinfall", "By submission", "By count-out"]),
        Q(1, "Which WWE event is billed as 'The Showcase of the Immortals'?", "WrestleMania", ["SummerSlam", "Royal Rumble", "Survivor Series"]),
        Q(1, "In pro wrestling, a 'heel' is what?", "A villain", ["A hero", "A referee", "A manager"]),
        Q(1, "Which wrestler's signature move was 'The People's Elbow'?", "The Rock", ["John Cena", "Triple H", "Batista"]),
        Q(1, "Who said 'Everybody has a plan until they get punched in the mouth'?", "Mike Tyson", ["Muhammad Ali", "George Foreman", "Floyd Mayweather"]),
        Q(1, "A referee counts to what number for a knockout?", "10", ["5", "8", "12"]),
        Q(1, "Despite the name, a boxing ring is what shape?", "Square", ["Circular", "Octagonal", "Hexagonal"]),
        Q(1, "In boxing and MMA, the two corners are traditionally which colors?", "Red and blue", ["Black and white", "Red and green", "Blue and gold"]),
        Q(1, "A corner signals it's giving up by throwing in what?", "The towel", ["A glove", "A flag", "The mouthguard"]),
        Q(1, "A wild, looping power punch is nicknamed what?", "A haymaker", ["A jab", "A cross", "An uppercut"]),
        Q(1, "Floyd Mayweather goes by which nickname?", "Money", ["Hitman", "Sugar", "The Truth"]),
        Q(1, "A 'pound-for-pound' list ranks boxers how?", "Regardless of weight class", ["By career earnings", "By knockout rate", "Heaviest to lightest"]),
        Q(1, "In boxing, a punch below the belt is called what?", "A low blow", ["A rabbit punch", "A kidney punch", "A body blow"]),
        Q(1, "In MMA, 'tapping out' signals what?", "The fighter gives up", ["A foul was committed", "A timeout request", "The round is over"]),
        Q(1, "A rear-naked choke is applied from where?", "Behind the opponent", ["In front of the opponent", "Beside the opponent", "Against the cage"]),
        Q(1, "What is the quick, straight punch thrown with the lead hand?", "The jab", ["The hook", "The uppercut", "The overhand"]),
        Q(1, "What is the UFC's eight-sided cage called?", "The Octagon", ["The Hexagon", "The Pentagon", "The Pit"]),
        Q(1, "Which sport is nicknamed 'the sweet science'?", "Boxing", ["Fencing", "Wrestling", "Judo"]),
        Q(1, "In a boxer's corner, what does the 'cut man' do?", "Treats cuts and swelling", ["Keeps the time", "Scores the rounds", "Carries the round cards"]),

        Q(2, "Heavyweight Rocky Marciano retired undefeated at what record?", "49-0", ["50-0", "45-0", "47-0"]),
        Q(2, "Which heavyweight was nicknamed 'Smokin' Joe'?", "Joe Frazier", ["Joe Louis", "Jersey Joe Walcott", "Joe Calzaghe"]),
        Q(2, "Muhammad Ali lit the Olympic cauldron at which Games?", "Atlanta 1996", ["Los Angeles 1984", "Seoul 1988", "Barcelona 1992"]),
        Q(2, "Why was Muhammad Ali stripped of his title in 1967?", "He refused the military draft", ["He failed a drug test", "He lost a rematch", "He skipped a weigh-in"]),
        Q(2, "Ali's trick of leaning on the ropes to tire out a slugger was called what?", "Rope-a-dope", ["Stick and move", "Peek-a-boo", "Shoulder roll"]),
        Q(2, "Golden Boy Promotions was founded by which boxer?", "Oscar De La Hoya", ["Floyd Mayweather", "Julio César Chávez", "Sugar Ray Leonard"]),
        Q(2, "'Canelo,' Álvarez's nickname for his red hair, is Spanish for what?", "Cinnamon", ["Copper", "Carrot", "Fire"]),
        Q(2, "Outside the ring, Manny Pacquiao served in what?", "The Philippine Senate", ["The Supreme Court", "The Cabinet", "The Central Bank"]),
        Q(2, "Which heavyweight champion became the mayor of Kyiv?", "Vitali Klitschko", ["Wladimir Klitschko", "Oleksandr Usyk", "Ruslan Chagaev"]),
        Q(2, "Who upset Anthony Joshua in 2019 to take his heavyweight belts?", "Andy Ruiz Jr.", ["Joseph Parker", "Dillian Whyte", "Deontay Wilder"]),
        Q(2, "Mayweather beat Pacquiao in their 2015 megafight by what?", "Unanimous decision", ["Split decision", "Knockout", "Disqualification"]),
        Q(2, "Pro boxing rounds are scored under what system?", "The 10-point must", ["The 5-point must", "One point per punch", "The 20-point scale"]),
        Q(2, "Whose catchphrase is 'Let's get ready to rumble!'?", "Michael Buffer", ["Bruce Buffer", "Jimmy Lennon Jr.", "Howard Cosell"], "His half-brother Bruce became the UFC's longtime announcer."),
        Q(2, "Who was the first woman to hold two UFC titles at once?", "Amanda Nunes", ["Valentina Shevchenko", "Cris Cyborg", "Ronda Rousey"], "She added featherweight gold to her bantamweight belt at UFC 232 in 2018."),
        Q(2, "Which UFC great was nicknamed 'The Spider'?", "Anderson Silva", ["Chuck Liddell", "Lyoto Machida", "Vitor Belfort"]),
        Q(2, "Demetrious 'Mighty Mouse' Johnson ruled which UFC division?", "Flyweight", ["Bantamweight", "Featherweight", "Lightweight"]),
        Q(2, "Ronda Rousey won most of her early fights with which submission?", "The armbar", ["The guillotine", "The triangle choke", "The kimura"]),
        Q(2, "Khabib Nurmagomedov hails from which Russian republic?", "Dagestan", ["Chechnya", "Tatarstan", "Ingushetia"]),
        Q(2, "In 2023, the UFC and WWE merged to form what company?", "TKO Group", ["Endeavor Fight Co.", "Zuffa Global", "Titan Sports"]),
        Q(2, "The Pride Fighting Championships were based in which country?", "Japan", ["Brazil", "South Korea", "The Netherlands"]),
        Q(2, "In 1990s wrestling, what did 'nWo' stand for?", "New World Order", ["New Wrestling Order", "National Wrestling Organization", "New Warrior Outlaws"]),
        Q(2, "WCW's weekly show in the 'Monday Night Wars' was called what?", "Nitro", ["Raw", "Dynamite", "SmackDown"]),
        Q(2, "Which wrestler is known as 'The Heartbreak Kid'?", "Shawn Michaels", ["Bret Hart", "Jeff Hardy", "Edge"]),
        Q(2, "Winning the Money in the Bank briefcase earns what?", "A guaranteed title match", ["A cash prize", "A Hall of Fame spot", "A WrestleMania main event"], "The holder can cash it in at any moment within a year."),
        Q(2, "Andre the Giant was born in which country?", "France", ["Belgium", "Switzerland", "Canada"]),
        Q(2, "Which WWE star calls himself 'The Tribal Chief'?", "Roman Reigns", ["The Rock", "Jey Uso", "Drew McIntyre"]),
        Q(2, "Which wrestler is known as 'The American Nightmare'?", "Cody Rhodes", ["Seth Rollins", "Dean Ambrose", "Randy Orton"]),
        Q(2, "Rey Mysterio's masked, high-flying style comes from which tradition?", "Lucha libre", ["Puroresu", "Catch wrestling", "Strong style"]),

        Q(3, "In 2001, the Fertitta brothers and Dana White bought the UFC for about how much?", "$2 million", ["$20 million", "$200,000", "$50 million"], "They created a company called Zuffa to run it."),
        Q(3, "In 2016, the UFC was sold to a group led by which company?", "WME-IMG", ["Disney", "Live Nation", "Comcast"], "The deal valued the promotion at over $4 billion."),
        Q(3, "Who fought Ronda Rousey in the first women's bout in UFC history?", "Liz Carmouche", ["Miesha Tate", "Cat Zingano", "Sara McMann"], "They headlined UFC 157 in Anaheim in February 2013."),
        Q(3, "Anthony Pettis's 'Showtime Kick' off the cage happened in which promotion?", "WEC", ["Strikeforce", "Pride", "Bellator"], "He landed it on Benson Henderson at WEC 53 in December 2010."),
        Q(3, "In 2019, Jorge Masvidal knocked out Ben Askren in how many seconds?", "5", ["15", "30", "45"], "A flying knee at UFC 239, the fastest knockout in UFC history."),
        Q(3, "UFC champ Henry Cejudo won 2008 Olympic gold in what sport?", "Freestyle wrestling", ["Judo", "Boxing", "Taekwondo"], "He won at 55 kg in Beijing at age 21."),
        Q(3, "In 2015, Conor McGregor knocked out José Aldo in how many seconds?", "13", ["31", "8", "45"], "It happened at UFC 194 and won him the featherweight title."),
        Q(3, "Holly Holm's head-kick upset of Ronda Rousey took place in which country?", "Australia", ["Brazil", "Canada", "Mexico"], "UFC 193 drew a huge crowd to Melbourne's Docklands Stadium in 2015."),
        Q(3, "Mike Tyson won his first heavyweight title in 1986 by beating whom?", "Trevor Berbick", ["Pinklon Thomas", "Tony Tucker", "Michael Spinks"], "At 20, he became the youngest heavyweight champion ever."),
        Q(3, "Joe Louis beat which German in their famous 1938 rematch?", "Max Schmeling", ["Primo Carnera", "Ingemar Johansson", "Gene Tunney"], "The rematch at Yankee Stadium ended in the first round."),
        Q(3, "Sugar Ray Robinson was born with what name?", "Walker Smith Jr.", ["Raymond Robinson", "Ray Charles Leonard", "Walter Sims"], "He boxed as an amateur using the ID card of a youth named Ray Robinson."),
        Q(3, "Which boxer legally made 'Marvelous' part of his name?", "Marvin Hagler", ["Sugar Ray Leonard", "Thomas Hearns", "Aaron Pryor"], "He changed it in 1982, fed up with announcers leaving the word out."),
        Q(3, "Buster Douglas upset Mike Tyson in 1990 in which city?", "Tokyo", ["Las Vegas", "London", "Atlantic City"], "Douglas was a 42-to-1 underdog at the Tokyo Dome."),
        Q(3, "At 45, George Foreman regained the heavyweight title in 1994 by beating whom?", "Michael Moorer", ["Evander Holyfield", "Tommy Morrison", "Riddick Bowe"], "He won by a 10th-round knockout, 20 years after losing to Ali."),
        Q(3, "Ali's 1965 'phantom punch' KO of Sonny Liston happened in which state?", "Maine", ["Nevada", "Florida", "New Jersey"], "The rematch was held in a small hockey arena in Lewiston."),
        Q(3, "Lennox Lewis won 1988 Olympic gold boxing for which country?", "Canada", ["Great Britain", "Jamaica", "The United States"], "He beat Riddick Bowe in the super heavyweight final in Seoul."),
        Q(3, "In 1992, which champion dumped the WBC heavyweight belt in a trash can?", "Riddick Bowe", ["Lennox Lewis", "Evander Holyfield", "Michael Moorer"], "He did it rather than face Lennox Lewis, the WBC's mandatory challenger."),
        Q(3, "Which trainer shaped a teenage Mike Tyson?", "Cus D'Amato", ["Angelo Dundee", "Emanuel Steward", "Eddie Futch"], "He taught Tyson the 'peek-a-boo' style, hands high by the cheeks."),
        Q(3, "Hulk Hogan famously body-slammed Andre the Giant at which WrestleMania?", "WrestleMania III", ["WrestleMania I", "WrestleMania V", "WrestleMania VI"], "It happened in 1987 at the Pontiac Silverdome in Michigan."),
        Q(3, "Who teamed with Hulk Hogan in the first WrestleMania's main event?", "Mr. T", ["Cyndi Lauper", "Muhammad Ali", "Liberace"], "Ali was a guest referee that night, and Liberace was guest timekeeper."),
        Q(3, "Stone Cold's 'Austin 3:16' speech came after he won which 1996 event?", "King of the Ring", ["Royal Rumble", "SummerSlam", "Survivor Series"], "He beat Jake 'The Snake' Roberts in the tournament final."),
        Q(3, "Hulk Hogan turned villain and formed the nWo at which 1996 event?", "Bash at the Beach", ["Starrcade", "SuperBrawl", "Halloween Havoc"], "He was revealed as the third man alongside Scott Hall and Kevin Nash."),
        Q(3, "Who was The Undertaker's urn-carrying manager?", "Paul Bearer", ["Jimmy Hart", "Bobby Heenan", "Paul Heyman"], "The urn was said to give the Deadman his supernatural power."),
        Q(3, "Mick Foley's three personas were Mankind, Dude Love and who?", "Cactus Jack", ["Kid Chaos", "Rattlesnake Rick", "Captain Carnage"], "All three entered the 1998 Royal Rumble."),
        Q(3, "The Rock debuted in the WWF in 1996 under what name?", "Rocky Maivia", ["Flex Kavana", "Dwayne Johnson", "The Great One"], "The name joined those of his father, Rocky Johnson, and grandfather, Peter Maivia."),
        Q(3, "What was the name of Jake 'The Snake' Roberts's ring python?", "Damien", ["Slither", "Sampson", "Goliath"], "Roberts has admitted he was afraid of snakes his whole life."),
        Q(3, "The Undertaker made his WWF debut at which 1990 event?", "Survivor Series", ["Royal Rumble", "SummerSlam", "WrestleMania VI"], "He was Ted DiBiase's mystery partner on the Million Dollar Team."),
        Q(3, "Who won the first women's main event of WrestleMania, in 2019?", "Becky Lynch", ["Charlotte Flair", "Ronda Rousey", "Bayley"], "She beat Rousey and Flair to take both women's titles at WrestleMania 35."),
    ]
}
