import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let footballExtra: [QSpec] = [
        Q(1, "How many points is a touchdown worth?", "6", ["7", "3", "5"]),
        Q(1, "How many points is a field goal worth?", "3", ["2", "1", "4"]),
        Q(1, "In the NFL, how many players does each team have on the field at once?", "11", ["9", "10", "12"]),
        Q(1, "In the NFL, how many downs does an offense get to earn a first down?", "4", ["3", "5", "6"]),
        Q(1, "How long is an NFL field from goal line to goal line?", "100 yards", ["90 yards", "110 yards", "120 yards"]),
        Q(1, "How deep is each NFL end zone?", "10 yards", ["5 yards", "15 yards", "20 yards"]),
        Q(1, "How long is an NFL quarter?", "15 minutes", ["10 minutes", "12 minutes", "20 minutes"]),
        Q(1, "When a team punts on fourth down, what does it do?", "Kicks it away to the other team", ["Tries a field goal", "Runs a trick play", "Calls a timeout"]),
        Q(1, "In football, what does PAT stand for?", "Point after touchdown", ["Pass attempt total", "Penalty against team", "Play action throw"]),
        Q(1, "What color flag do referees throw for a penalty?", "Yellow", ["Red", "White", "Orange"]),
        Q(1, "A false start is a penalty on which side?", "The offense", ["The defense", "The coaches", "The receiving team"]),
        Q(1, "What is an onside kick?", "A short kickoff the kickers try to grab", ["A kickoff that goes out of bounds", "A field goal from midfield", "A punt on third down"]),
        Q(1, "What is a blitz?", "Extra defenders rushing the quarterback", ["A long pass down the sideline", "A drive with no huddles", "A kick that bounces sideways"]),
        Q(1, "In the NFL, the two-minute warning is what?", "A built-in stop at 2:00 left in a half", ["A penalty for stalling", "A signal to swap quarterbacks", "A two-minute halftime break"]),
        Q(1, "A punt returner waves a hand over his head. What's he calling for?", "A fair catch", ["A timeout", "A penalty", "A substitution"]),
        Q(1, "Pass interference is what?", "Illegal contact before a pass arrives", ["Throwing two passes on one play", "Throwing from past the line", "Dropping an easy catch"]),
        Q(1, "Why does a quarterback 'take a knee' at the end of a game?", "To run out the clock", ["To stop the clock", "To draw a penalty", "To rest his legs"]),
        Q(1, "After a big win, players often dump a cooler of Gatorade on whom?", "The head coach", ["The team owner", "The quarterback", "The referee"]),
        Q(1, "When a team 'goes for it' on fourth down, what is it doing?", "Running a play instead of kicking", ["Trying a long field goal", "Punting from its end zone", "Calling its last timeout"]),
        Q(1, "Which two NFL teams traditionally host a game every Thanksgiving?", "Lions and Cowboys", ["Bears and Packers", "Giants and Eagles", "Chiefs and Raiders"]),
        Q(1, "Fans of which team wave the 'Terrible Towel'?", "Pittsburgh Steelers", ["Cleveland Browns", "Baltimore Ravens", "Cincinnati Bengals"], "Broadcaster Myron Cope dreamed it up for a 1975 playoff game."),
        Q(1, "The Pro Football Hall of Fame is in which city?", "Canton, Ohio", ["Green Bay, Wisconsin", "Dallas, Texas", "Chicago, Illinois"]),
        Q(1, "Arrowhead Stadium opened in 1972 as the home of which team?", "Kansas City Chiefs", ["Denver Broncos", "Oakland Raiders", "Atlanta Falcons"]),
        Q(1, "Fans in foam 'Cheesehead' hats are rooting for which team?", "Green Bay Packers", ["Minnesota Vikings", "Chicago Bears", "Detroit Lions"]),
        Q(1, "A punt downed in the receiving team's end zone is called what?", "A touchback", ["A safety", "A fair catch", "A turnover"]),
        Q(1, "Which position usually takes the handoff and runs with the ball?", "Running back", ["Tight end", "Wide receiver", "Linebacker"]),
        Q(1, "An NFL game tied after four quarters goes to what?", "Overtime", ["A shootout", "A coin flip", "A replay"]),
        Q(1, "The NFL is split into which two conferences?", "AFC and NFC", ["ACC and SEC", "AFL and NFL", "East and West"]),

        Q(2, "Which bowl game is nicknamed 'The Granddaddy of Them All'?", "Rose Bowl", ["Orange Bowl", "Sugar Bowl", "Cotton Bowl"], "It's played in Pasadena, California."),
        Q(2, "The Heisman Trophy goes to whom each year?", "College football's top player", ["The NFL's top rookie", "The best college coach", "The Super Bowl MVP"]),
        Q(2, "The 'Dawg Pound' end-zone section belongs to which NFL team?", "Cleveland Browns", ["Cincinnati Bengals", "Pittsburgh Steelers", "Baltimore Ravens"]),
        Q(2, "Which team won Super Bowl I?", "Green Bay Packers", ["Kansas City Chiefs", "Dallas Cowboys", "Baltimore Colts"]),
        Q(2, "Which quarterback guaranteed a win before Super Bowl III?", "Joe Namath", ["Johnny Unitas", "Len Dawson", "Bart Starr"], "His Jets upset the Baltimore Colts 16-7."),
        Q(2, "Which team went 17-0 in 1972, capped by a Super Bowl win?", "Miami Dolphins", ["Pittsburgh Steelers", "Dallas Cowboys", "Oakland Raiders"]),
        Q(2, "Which NFL team has a horseshoe on its helmet?", "Indianapolis Colts", ["Denver Broncos", "Dallas Cowboys", "Arizona Cardinals"]),
        Q(2, "Which team recorded 'The Super Bowl Shuffle' in 1985?", "Chicago Bears", ["Miami Dolphins", "New York Giants", "San Francisco 49ers"], "About seven weeks later, the Bears won Super Bowl XX."),
        Q(2, "When a quarterback calls an audible, what is he doing?", "Changing the play at the line", ["Asking for a timeout", "Faking an injury", "Calling for a fair catch"]),
        Q(2, "In the shotgun formation, where does the quarterback line up?", "Several yards behind the center", ["Directly under center", "Out wide by the sideline", "Behind the fullback"]),
        Q(2, "A play-action pass starts with what?", "A fake handoff", ["A lateral", "A quarterback spike", "A pitch to a receiver"]),
        Q(2, "What is a screen pass?", "A short pass behind a wall of blockers", ["A deep throw down the sideline", "A pass tipped at the line", "A throw after a fake field goal"]),
        Q(2, "In the NFL Draft, who is 'Mr. Irrelevant'?", "The very last pick", ["The first pick", "The oldest rookie", "The first player traded"], "The title dates to 1976 and comes with a week of parties in Newport Beach."),
        Q(2, "The Raiders moved from Oakland to which city in 2020?", "Las Vegas", ["Los Angeles", "San Antonio", "San Diego"]),
        Q(2, "The 1972 'Immaculate Reception' was caught by which Steeler?", "Franco Harris", ["Lynn Swann", "Rocky Bleier", "John Stallworth"]),
        Q(2, "In a 3-4 defense, what do the numbers mean?", "3 linemen and 4 linebackers", ["3 corners and 4 safeties", "4 linemen and 3 linebackers", "3 blitzers and 4 in coverage"]),
        Q(2, "Who went No. 1 overall in the 1998 NFL Draft?", "Peyton Manning", ["Ryan Leaf", "Randy Moss", "Charles Woodson"], "Ryan Leaf went second, to the San Diego Chargers."),
        Q(2, "In Super Bowl LII, who caught the 'Philly Special' touchdown?", "Nick Foles", ["Zach Ertz", "Trey Burton", "Alshon Jeffery"], "Foles was the quarterback; tight end Trey Burton threw it."),
        Q(2, "The 'Purple People Eaters' defense played for which team?", "Minnesota Vikings", ["Baltimore Ravens", "Los Angeles Rams", "Kansas City Chiefs"]),
        Q(2, "College football's Iron Bowl is Alabama vs. which rival?", "Auburn", ["LSU", "Tennessee", "Georgia"]),
        Q(2, "In 2002, Emmitt Smith broke whose career rushing record?", "Walter Payton", ["Barry Sanders", "Jim Brown", "Eric Dickerson"]),
        Q(2, "Which QB led the 'Greatest Show on Turf' Rams to win Super Bowl XXXIV?", "Kurt Warner", ["Marc Bulger", "Trent Green", "Jim Everett"], "A few years earlier he was stocking shelves at an Iowa grocery store."),
        Q(2, "Which Cowboys coach was famous for wearing a fedora on the sideline?", "Tom Landry", ["Jimmy Johnson", "Bill Parcells", "Barry Switzer"]),
        Q(2, "The Baltimore Ravens are named after a poem by whom?", "Edgar Allan Poe", ["Walt Whitman", "Robert Frost", "Emily Dickinson"], "Poe is buried in Baltimore."),
        Q(2, "Who owns the Green Bay Packers?", "Its fan shareholders", ["The city of Green Bay", "The Lambeau family", "The State of Wisconsin"]),
        Q(2, "In Super Bowl LI, the Patriots came back from 28-3 to beat whom?", "Atlanta Falcons", ["Seattle Seahawks", "Carolina Panthers", "Philadelphia Eagles"], "It was the first Super Bowl to go to overtime."),
        Q(2, "John Madden made which layered Thanksgiving dish famous on air?", "Turducken", ["Turkey Wellington", "Deep-fried turkey", "Turkey pot pie"], "It's a chicken inside a duck inside a turkey."),
        Q(2, "A 'hook and ladder' play pairs a catch with what?", "A lateral to a teammate", ["A second forward pass", "A quarterback sneak", "A fake field goal"]),

        Q(3, "Doug Flutie's famous 1984 Hail Mary for Boston College beat which team?", "Miami", ["Notre Dame", "Penn State", "Florida State"], "Gerard Phelan caught it, and Flutie won the Heisman Trophy that season."),
        Q(3, "Who made the 'Helmet Catch' in Super Bowl XLII?", "David Tyree", ["Plaxico Burress", "Amani Toomer", "Steve Smith"], "Four plays later, Plaxico Burress caught the winning touchdown."),
        Q(3, "Who scored on the 'Music City Miracle' kickoff return in January 2000?", "Kevin Dyson", ["Frank Wycheck", "Derrick Mason", "Eddie George"], "Frank Wycheck's cross-field lateral beat the Buffalo Bills 22-16."),
        Q(3, "Whose 47-yard kick went 'wide right' at the end of Super Bowl XXV?", "Scott Norwood", ["Steve Christie", "Gary Anderson", "Matt Bahr"], "The Giants held on to win 20-19."),
        Q(3, "In the January 1988 AFC title game, which Browns back fumbled near the goal line?", "Earnest Byner", ["Kevin Mack", "Greg Pruitt", "Leroy Hoard"], "Denver's Jeremiah Castille stripped him, and the Broncos won 38-33."),
        Q(3, "The January 2002 'Tuck Rule' game in the snow was the Patriots vs. whom?", "Oakland Raiders", ["Pittsburgh Steelers", "Tennessee Titans", "Miami Dolphins"], "The NFL abolished the tuck rule in 2013."),
        Q(3, "Who was the first player ever picked in an NFL draft, in 1936?", "Jay Berwanger", ["Sammy Baugh", "Red Grange", "Bronko Nagurski"], "The first Heisman winner, he never played a down in the NFL."),
        Q(3, "Who won the Heisman Trophy in both 1974 and 1975?", "Archie Griffin", ["Tony Dorsett", "Earl Campbell", "Billy Sims"], "He was a running back at Ohio State."),
        Q(3, "The Bills lost four straight Super Bowls. Who beat them in the last two?", "Dallas Cowboys", ["New York Giants", "Washington", "San Francisco 49ers"], "The Giants and Washington won the first two."),
        Q(3, "What was Super Bowl I officially called?", "AFL-NFL World Championship Game", ["National Football Championship", "AFL-NFL Title Bowl", "World Professional Football Bowl"], "It was played in Los Angeles in January 1967, and it didn't sell out."),
        Q(3, "Which Super Bowl dropped the Roman numerals for one year?", "Super Bowl 50", ["Super Bowl 40", "Super Bowl 25", "Super Bowl 30"], "Designers decided a lone 'L' didn't work as a logo."),
        Q(3, "Who scored the first touchdown in Super Bowl history?", "Max McGee", ["Jim Taylor", "Boyd Dowler", "Elijah Pitts"], "He only got in after Boyd Dowler reinjured his shoulder early in the game."),
        Q(3, "In 1952, which rookie intercepted a record 14 passes in 12 games?", "Dick 'Night Train' Lane", ["Emlen Tunnell", "Jack Christiansen", "Yale Lary"], "He did it for the Los Angeles Rams."),
        Q(3, "The first Monday Night Football game, in 1970, was the Jets at which team?", "Cleveland Browns", ["Baltimore Colts", "Miami Dolphins", "New York Giants"], "Howard Cosell, Keith Jackson and Don Meredith called the Browns' 31-21 win."),
        Q(3, "The 2018 'Minneapolis Miracle' was Case Keenum's walk-off TD pass to whom?", "Stefon Diggs", ["Adam Thielen", "Kyle Rudolph", "Jarius Wright"], "It was the first NFL playoff game to end on a touchdown as time expired."),
        Q(3, "In 1970, which Saints kicker booted a record 63-yard field goal?", "Tom Dempsey", ["Jan Stenerud", "George Blanda", "Garo Yepremian"], "The record stood for 43 years, until Matt Prater's 64-yarder in 2013."),
        Q(3, "A 34-minute power outage halted Super Bowl XLVII in which city?", "New Orleans", ["Miami", "Indianapolis", "Houston"], "The Ravens led 28-6 when the Superdome lights went out, and held on to win."),
        Q(3, "Who was NFL commissioner when the AFL-NFL merger was announced in 1966?", "Pete Rozelle", ["Bert Bell", "Paul Tagliabue", "Lamar Hunt"], "The Super Bowl MVP trophy was renamed in his honor in 1990."),
        Q(3, "In what year did the NFL adopt the two-point conversion?", "1994", ["1978", "1987", "2001"], "College football had used it since 1958."),
        Q(3, "Before moving to Detroit in 1934, the Lions were which Ohio team?", "Portsmouth Spartans", ["Canton Bulldogs", "Columbus Panhandles", "Dayton Triangles"], "Radio man George A. Richards bought the team for $8,000."),
        Q(3, "In 1984, the Colts slipped out of Baltimore overnight in what?", "Mayflower moving vans", ["A chartered train", "Army cargo planes", "Rented school buses"], "The trucks rolled out in a snowstorm in the early hours of March 29."),
        Q(3, "Who intercepted Russell Wilson at the goal line to win Super Bowl XLIX?", "Malcolm Butler", ["Darrelle Revis", "Devin McCourty", "Brandon Browner"], "He was an undrafted rookie out of West Alabama."),
        Q(3, "The first televised NFL game, in 1939, was played at which ballpark?", "Ebbets Field", ["Polo Grounds", "Yankee Stadium", "Wrigley Field"], "NBC's broadcast reached about 1,000 TV sets in New York."),
        Q(3, "In what year did college football first allow the forward pass?", "1906", ["1869", "1920", "1933"], "Reforms followed pressure from Theodore Roosevelt after a deadly 1905 season."),
        Q(3, "Which school won the first Rose Bowl game, in 1902?", "Michigan", ["Stanford", "Harvard", "USC"], "It won 49-0, and the Rose Bowl switched to chariot races until 1916."),
        Q(3, "The Green Bay Packers took their name from a sponsor in what business?", "Meatpacking", ["Paper mills", "Shipping", "Cheesemaking"], "The Indian Packing Company paid $500 for the first uniforms in 1919."),
        Q(3, "How did the Saints open the second half of Super Bowl XLIV?", "An onside kick", ["A fake punt", "A flea flicker", "A halfback pass"], "Sean Payton called it 'Ambush,' and New Orleans beat the Colts 31-17."),
        Q(3, "Who was the first Black quarterback to start and win a Super Bowl?", "Doug Williams", ["Warren Moon", "Randall Cunningham", "James Harris"], "He was MVP of Super Bowl XXII for Washington."),
    ]
}
