import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let gearExtra: [QSpec] = [
        Q(1, "A Phillips screwdriver has what tip shape?", "A cross", ["A flat blade", "A square", "A six-point star"]),
        Q(1, "The bubble in a level tells you what?", "If a surface is level or plumb", ["How long a board is", "How deep a drilled hole is", "How tight a bolt is"]),
        Q(1, "A stud finder locates what behind drywall?", "Framing studs", ["Hidden mold", "Termite damage", "Drafts"]),
        Q(1, "The claw on a claw hammer is mostly for what?", "Pulling nails", ["Splitting wood", "Stripping wire", "Scraping paint"]),
        Q(1, "Which sandpaper grit is the finest?", "220", ["40", "60", "100"], "The higher the number, the smaller the grit and the smoother the finish."),
        Q(1, "Duct tape was first made for the military during which war?", "World War II", ["World War I", "The Korean War", "The Vietnam War"], "It sealed ammo boxes so soldiers could rip them open fast."),
        Q(1, "On a tent, the 'rainfly' is what?", "A waterproof cover over the top", ["The floor mat", "The mesh bug netting", "A tent stake"]),
        Q(1, "'Glamping' is short for what?", "Glamorous camping", ["Glacier camping", "Group lamp camping", "Global camping"]),
        Q(1, "S'mores are graham crackers, chocolate, and what?", "Toasted marshmallow", ["Peanut butter", "Salted caramel sauce", "Sliced banana"]),
        Q(1, "A trailhead is what?", "Where a trail begins", ["A trail's highest point", "A campsite", "A ranger station"]),
        Q(1, "Old Faithful geyser is in which national park?", "Yellowstone", ["Yosemite", "Grand Teton", "Glacier"]),
        Q(1, "A fishing bobber does what?", "Floats and dips when a fish bites", ["Sinks the bait", "Reels in line", "Scares off the small fish"]),
        Q(1, "Plumber's tape gets wrapped around what?", "Pipe threads", ["Leaky hoses", "Electrical wire", "Tool handles"]),
        Q(1, "When a circuit breaker 'trips,' what does it do?", "Cuts power to that circuit", ["Boosts the voltage", "Switches the house to battery", "Resets the clocks"]),
        Q(1, "A carabiner is what?", "A metal clip with a spring gate", ["A climbing shoe", "A knot for joining ropes", "A tent pole"]),
        Q(1, "Vise-Grip is a famous brand of what tool?", "Locking pliers", ["Bench vises", "Pipe wrenches", "Wire strippers"]),
        Q(1, "An Allen wrench is also called what?", "A hex key", ["A Torx key", "A spanner", "A nut driver"]),
        Q(1, "In Britain, a wrench is usually called what?", "A spanner", ["A ratchet", "A mallet", "A driver"]),
        Q(1, "On a hiking trail, a switchback is what?", "A zigzag up a steep slope", ["A river crossing", "A dead end", "A loop back to the start"]),
        Q(1, "On a boat, PFD stands for what?", "Personal flotation device", ["Portable fuel drum", "Primary float deck", "Propeller fault detector"], "It's the Coast Guard's term for life jackets and throwable cushions."),
        Q(1, "Poison ivy leaves grow in groups of how many?", "Three", ["Two", "Five", "Seven"], "Hence the old rhyme: leaves of three, let it be."),
        Q(1, "In fire building, kindling is what?", "Small sticks that catch easily", ["The biggest logs", "Wet wood", "Leftover ash from the last fire"]),
        Q(1, "A hacksaw is made to cut what?", "Metal", ["Drywall", "Tree limbs", "Tile"]),
        Q(1, "Half Dome and El Capitan are in which national park?", "Yosemite", ["Yellowstone", "Zion", "Glacier"]),
        Q(1, "Which fish swims from the ocean up rivers to spawn?", "Salmon", ["Tuna", "Walleye", "Catfish"]),
        Q(1, "Which boat is usually paddled with a double-bladed paddle?", "A kayak", ["A canoe", "A rowboat", "A gondola"]),
        Q(1, "To check a 90-degree corner, a carpenter uses a what?", "Square", ["Level", "Plumb bob", "Chalk line"]),
        Q(1, "Which wrench can fit many sizes of nut?", "An adjustable wrench", ["A box-end wrench", "A socket", "A combination wrench"]),

        Q(2, "Why does the hook on a tape measure slide a little?", "To offset its own thickness", ["It's a sign of wear", "To lock the blade in place", "To score the wood"], "It slides out when you hook an edge and in when you push against one."),
        Q(2, "The square knot is also called what?", "The reef knot", ["The bowline", "The sheet bend", "The granny knot"]),
        Q(2, "Which company makes the Swiss Army Knife?", "Victorinox", ["Leatherman", "Gerber", "Buck"]),
        Q(2, "In building, 'plumb' means what?", "Perfectly vertical", ["Perfectly level", "Angled at 45 degrees", "Perfectly round"]),
        Q(2, "In woodworking, a dovetail is a type of what?", "Joint", ["Saw", "Finish", "Clamp"]),
        Q(2, "A 2x4 actually measures about how many inches?", "1.5 by 3.5", ["2 by 4", "1.75 by 3.75", "1.25 by 3.25"], "Boards are named before they're dried and planed down."),
        Q(2, "A standard sheet of plywood is how big?", "4 by 8 feet", ["4 by 10 feet", "3 by 6 feet", "5 by 10 feet"]),
        Q(2, "Rebar is steel bar used to reinforce what?", "Concrete", ["Drywall", "Roof shingles", "Timber beams"]),
        Q(2, "Torx screws have what tip shape?", "A six-point star", ["A square", "A triangle", "A cross with a center dot"]),
        Q(2, "To a hiker, a 'thru-hike' means what?", "Walking a long trail end to end", ["Hiking through a cave", "Hiking only at night", "Hiking off-trail with no map or gear"]),
        Q(2, "The Pacific Crest Trail runs from Mexico to where?", "Canada", ["Alaska", "Montana", "Idaho"]),
        Q(2, "Carhartt is best known for what?", "Workwear", ["Power tools", "Coolers", "Camp stoves"]),
        Q(2, "Which power tool brand is famous for yellow and black?", "DeWalt", ["Makita", "Milwaukee", "Ryobi"]),
        Q(2, "Craftsman hand tools were long sold with what promise?", "A lifetime warranty", ["Free sharpening", "A 30-day trial", "Free engraving with your name"]),
        Q(2, "On a three-prong plug, the round prong is for what?", "Ground", ["Hot", "Neutral", "Extra power"]),
        Q(2, "A standard US wall outlet supplies about how many volts?", "120", ["240", "100", "220"]),
        Q(2, "In paint, 'eggshell' describes what?", "A low-luster sheen", ["A kind of wood stain", "A kind of primer", "A textured brush stroke"]),
        Q(2, "A shim is what?", "A thin wedge to level or fill a gap", ["A small finishing nail", "A wood glue", "A guide for straight saw cuts"]),
        Q(2, "A Dremel is what kind of tool?", "A rotary tool", ["A nail gun", "A belt sander", "A band saw"]),
        Q(2, "On a trail, a cairn is what?", "A stack of rocks marking the way", ["A trail shelter", "A low pass between two peaks", "A water source"]),
        Q(2, "What color are the Appalachian Trail's main blazes?", "White", ["Blue", "Orange", "Yellow"], "Blue blazes mark side trails to water, views, and shelters."),
        Q(2, "Why can hunters wear blaze orange around deer?", "Deer can't pick out orange well", ["Orange masks human scent", "Deer are drawn to orange", "Deer only see in black and white"]),
        Q(2, "A clove hitch is used to do what?", "Tie a rope around a post", ["Join two ropes", "Make a fixed loop", "Shorten a rope without cutting it"]),
        Q(2, "In archery, fletching is what?", "The vanes on an arrow", ["The bowstring", "The arrowhead", "The notch for the string"]),
        Q(2, "On a boat, 'port' is which side?", "Left, facing the bow", ["Right, facing the bow", "The back", "The front"]),
        Q(2, "A topographic map shows elevation with what?", "Contour lines", ["Colored dots", "Arrows", "Shaded grid squares"]),
        Q(2, "The survival 'rule of threes' says you last about three days without what?", "Water", ["Food", "Shelter", "Sleep"]),
        Q(2, "Whitewater rapids are rated from Class I up to Class what?", "VI", ["IV", "V", "X"]),

        Q(3, "The Phillips screw got its big break on which carmaker's 1930s line?", "General Motors", ["Ford", "Chrysler", "Packard"], "GM used it to build Cadillacs; by 1940, 85% of US screw makers licensed it."),
        Q(3, "The '40' in WD-40 refers to what?", "Its 40th formula attempt", ["Its 40 ingredients", "Its 1940 launch", "Its 40-degree freezing point"], "WD stands for Water Displacement, straight from the chemist's lab book."),
        Q(3, "Milwaukee's Sawzall, launched in 1951, is what kind of saw?", "Reciprocating", ["Circular", "Band", "Compound miter"], "It was meant to cut all materials, hence the name."),
        Q(3, "REI was founded as a climbers' co-op in 1938 in which city?", "Seattle", ["Denver", "Portland", "Boulder"], "It started when Lloyd Anderson couldn't find a decent ice axe at a fair price."),
        Q(3, "L.L.Bean's very first product, in 1912, was what?", "A hunting boot", ["A canvas tote", "A wool shirt", "A carved duck decoy"], "Of the first 100 pairs, 90 came back, so he fixed the stitching."),
        Q(3, "In what year did Alex Honnold free solo El Capitan?", "2017", ["2014", "2019", "2012"], "He climbed the Freerider route with no rope in under four hours."),
        Q(3, "Which climber founded Patagonia?", "Yvon Chouinard", ["Royal Robbins", "Tommy Caldwell", "Conrad Anker"], "He got his start forging steel climbing pitons by hand."),
        Q(3, "Which president signed the 1916 law creating the National Park Service?", "Woodrow Wilson", ["Teddy Roosevelt", "William Taft", "Calvin Coolidge"]),
        Q(3, "Which adjustable knot is the classic for tightening tent guylines?", "Taut-line hitch", ["Clove hitch", "Sheet bend", "Double fisherman's"], "It slides to tension the line, then grips under load."),
        Q(3, "Stanley bottle inventor William Stanley Jr. also pioneered what?", "The AC transformer", ["The light bulb", "The telephone", "The radio"], "His 1913 steel vacuum bottle grew out of welding work on transformers."),
        Q(3, "The KA-BAR knife became famous with which branch in WWII?", "US Marine Corps", ["US Army", "US Coast Guard", "US Army Air Forces"], "The Marines adopted it in 1942 as a fighting and utility knife."),
        Q(3, "Mount Whitney, the lower 48's tallest peak, is in which state?", "California", ["Colorado", "Washington", "Nevada"], "The John Muir Trail from Yosemite ends on its summit."),
        Q(3, "Climbers use a figure-eight follow-through to do what?", "Tie into a harness", ["Tie a hammock to a tree", "Hang a bear bag", "Tie a boat to a dock"]),
        Q(3, "Despite its name, a jointer does what?", "Flattens a board's face or edge", ["Glues boards together", "Cuts dovetails", "Drills angled pocket screw holes"]),
        Q(3, "Japanese saws like the ryoba cut on the pull, which lets the blade be what?", "Thinner", ["Thicker", "Heavier", "Stiffer"], "Pulling keeps the blade in tension, so it won't buckle."),
        Q(3, "Who was the Sierra Club's first president, in 1892?", "John Muir", ["Ansel Adams", "Aldo Leopold", "Gifford Pinchot"], "He held the job for 22 years, until his death."),
        Q(3, "Hiking's Triple Crown is the AT, the PCT, and which trail?", "Continental Divide Trail", ["John Muir Trail", "Pacific Northwest Trail", "Long Trail"]),
        Q(3, "America's oldest long-distance hiking trail, the Long Trail, is in which state?", "Vermont", ["Maine", "New Hampshire", "New York"], "Built from 1910 to 1930, it helped inspire the Appalachian Trail."),
        Q(3, "George Perry's record 22-lb largemouth bass came from which state?", "Georgia", ["Florida", "Texas", "Alabama"], "Caught in 1932, it was tied in 2009 by a bass from Japan."),
        Q(3, "The compound bow, patented in 1969, eases the draw with what?", "Cams on the limbs", ["A second string", "A spring-loaded stock", "A trigger lock"], "Holless Wilbur Allen first tried pulleys before settling on cams."),
        Q(3, "The small black diamonds on a tape measure repeat every how many inches?", "19.2", ["16", "24", "12.5"], "Five of them split 8 feet evenly, for laying out joists and trusses."),
        Q(3, "Estwing hammers are famous for being made how?", "Forged from one piece of steel", ["With hickory handles", "From titanium", "With leather-wrapped fiberglass"], "Ernest Estwing started the company in 1923 in Rockford, Illinois."),
        Q(3, "Klein Tools, founded in 1857, is a favorite of which trade?", "Electricians", ["Plumbers", "Carpenters", "Welders"], "Its first tool was a pair of pliers for a telegraph lineman."),
        Q(3, "Snap-on is known for selling its tools how?", "From vans that visit shops", ["Only in hardware stores", "Only by mail order", "At home parties"], "Dealers drive routes and see the same mechanics every week."),
        Q(3, "In 2001, Smokey Bear's slogan swapped 'forest fires' for what?", "Wildfires", ["Campfires", "Brush fires", "Grass fires"], "Smokey first appeared on a Forest Service poster in 1944."),
        Q(3, "Nalgene water bottles started out as what?", "Lab equipment", ["Military canteens", "Baby bottles", "Bike bottles"], "By the 1970s, scientists were carrying the tough lab bottles on hikes."),
        Q(3, "Velcro's Swiss inventor got the idea from what?", "Burrs stuck to his dog", ["Gecko feet", "Woven bird nests", "Pine cones"], "George de Mestral came home from a 1941 hunting trip covered in them."),
        Q(3, "Coleman got its start in 1900 renting out what?", "Gasoline lamps", ["Canvas tents", "Camp stoves", "Wooden ice chests"], "W.C. Coleman lit up Oklahoma Territory with pressure lamps."),
    ]
}
