import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let gossipExtra: [QSpec] = [
        Q(1, "In July 2026, Taylor Swift and Travis Kelce married at which New York venue?", "Madison Square Garden", ["Radio City Music Hall", "Barclays Center", "Yankee Stadium"], "Adam Sandler officiated the ceremony."),
        Q(1, "Brad Pitt and Angelina Jolie met filming which 2005 action movie?", "Mr. & Mrs. Smith", ["Ocean's Twelve", "Troy", "Salt"]),
        Q(1, "Justin Bieber married which model in 2018?", "Hailey Baldwin", ["Kendall Jenner", "Gigi Hadid", "Bella Hadid"]),
        Q(1, "At the 2001 AMAs, Britney Spears and Justin Timberlake wore matching outfits made of what?", "Denim", ["Leather", "Velvet", "Sequins"]),
        Q(1, "Ryan Reynolds and Blake Lively met filming which 2011 superhero movie?", "Green Lantern", ["Deadpool", "Thor", "X-Men: First Class"]),
        Q(1, "In 2005, Tom Cruise jumped on whose talk-show couch over Katie Holmes?", "Oprah Winfrey", ["Ellen DeGeneres", "Jay Leno", "David Letterman"]),
        Q(1, "Garth Brooks married which country singer in 2005?", "Trisha Yearwood", ["Reba McEntire", "Martina McBride", "Wynonna Judd"]),
        Q(1, "In 2022, Jennifer Lopez and Ben Affleck got married in which city?", "Las Vegas", ["Los Angeles", "Miami", "New York"], "They threw a bigger celebration in Georgia a month later."),
        Q(1, "Miley Cyrus married which 'Hunger Games' actor in 2018?", "Liam Hemsworth", ["Josh Hutcherson", "Chris Hemsworth", "Sam Claflin"], "They met filming 'The Last Song' in 2009."),
        Q(1, "Prince William and Kate Middleton married in 2011 at which London church?", "Westminster Abbey", ["St Paul's Cathedral", "Southwark Cathedral", "St Martin-in-the-Fields"]),
        Q(1, "Ellen DeGeneres married which actress in 2008?", "Portia de Rossi", ["Jodie Foster", "Jane Lynch", "Cynthia Nixon"]),
        Q(1, "In 1954, Marilyn Monroe married which baseball legend?", "Joe DiMaggio", ["Mickey Mantle", "Ted Williams", "Babe Ruth"]),
        Q(1, "Justin Timberlake married which actress in 2012?", "Jessica Biel", ["Cameron Diaz", "Mila Kunis", "Jessica Alba"]),
        Q(1, "Tim McGraw married which country singer in 1996?", "Faith Hill", ["Shania Twain", "Martina McBride", "Reba McEntire"]),
        Q(1, "John Krasinski married which actress in 2010?", "Emily Blunt", ["Jenna Fischer", "Anne Hathaway", "Rashida Jones"]),
        Q(1, "In 2015, Ashton Kutcher married which 'That '70s Show' costar?", "Mila Kunis", ["Laura Prepon", "Lisa Robin Kelly", "Debra Jo Rupp"]),
        Q(1, "Nicole Kidman married which country singer in 2006?", "Keith Urban", ["Kenny Chesney", "Brad Paisley", "Blake Shelton"]),
        Q(1, "Demi Moore was married to which action star from 1987 to 2000?", "Bruce Willis", ["Sylvester Stallone", "Mel Gibson", "Harrison Ford"]),
        Q(1, "Prince Harry and Meghan's son, born in 2019, is named what?", "Archie", ["Arthur", "Albert", "Alfie"]),
        Q(1, "Cher's first husband and singing partner was who?", "Sonny Bono", ["Tony Orlando", "Glen Campbell", "Bobby Darin"]),
        Q(1, "Kylie Jenner and Travis Scott's daughter, born in 2018, is named what?", "Stormi", ["True", "Dream", "Chicago"]),
        Q(1, "Joe Jonas married which 'Game of Thrones' star in 2019?", "Sophie Turner", ["Maisie Williams", "Emilia Clarke", "Natalie Dormer"]),
        Q(1, "Lucille Ball and husband Desi Arnaz starred together in which sitcom?", "I Love Lucy", ["The Honeymooners", "Father Knows Best", "Bewitched"]),
        Q(1, "Kristen Stewart and Robert Pattinson dated after starring together in which film series?", "Twilight", ["The Hunger Games", "Divergent", "The Maze Runner"]),
        Q(1, "Zendaya and Tom Holland first costarred in which 2017 film?", "Spider-Man: Homecoming", ["The Greatest Showman", "Avengers: Infinity War", "Dune"]),
        Q(1, "Scarlett Johansson married which 'SNL' Weekend Update anchor in 2020?", "Colin Jost", ["Michael Che", "Seth Meyers", "Pete Davidson"]),
        Q(1, "In 1968, Johnny Cash married which singer?", "June Carter", ["Patsy Cline", "Loretta Lynn", "Emmylou Harris"]),
        Q(1, "Tom Hanks married which actress in 1988?", "Rita Wilson", ["Meg Ryan", "Sally Field", "Daryl Hannah"]),

        Q(2, "Chris Hemsworth married which Spanish actress in 2010?", "Elsa Pataky", ["Penélope Cruz", "Paz Vega", "Úrsula Corberó"]),
        Q(2, "Carrie Underwood married which NHL player in 2010?", "Mike Fisher", ["Sidney Crosby", "Ryan Kesler", "Henrik Lundqvist"]),
        Q(2, "Harry and Meghan's daughter Lilibet is named for whose family nickname?", "Queen Elizabeth II", ["Princess Diana", "Princess Margaret", "The Queen Mother"]),
        Q(2, "Prince William and Kate Middleton met at which university?", "St Andrews", ["Edinburgh", "Oxford", "Durham"]),
        Q(2, "Kim Kardashian and Kanye West married in 2014 in which Italian city?", "Florence", ["Rome", "Venice", "Milan"]),
        Q(2, "Beyoncé and Jay-Z married in which year?", "2008", ["2004", "2006", "2010"]),
        Q(2, "Jennifer Aniston and Brad Pitt married in which year?", "2000", ["1998", "2002", "2004"], "They wed in Malibu and divorced in 2005."),
        Q(2, "David and Victoria Beckham's 1999 wedding was held in which country?", "Ireland", ["Scotland", "England", "France"], "They married at Luttrellstown Castle, outside Dublin."),
        Q(2, "Ben Affleck and Jennifer Garner costarred in which 2003 superhero film?", "Daredevil", ["The Punisher", "Hulk", "X2"]),
        Q(2, "Channing Tatum and Jenna Dewan met filming which dance movie?", "Step Up", ["Stomp the Yard", "Save the Last Dance", "Magic Mike"]),
        Q(2, "Courteney Cox met future husband David Arquette making which movie?", "Scream", ["Halloween H20", "The Faculty", "Urban Legend"]),
        Q(2, "In 2010, Nicole Richie married the frontman of which band?", "Good Charlotte", ["Simple Plan", "Fall Out Boy", "Sum 41"]),
        Q(2, "Before Blake Shelton, Gwen Stefani was married to the singer of which band?", "Bush", ["Live", "Creed", "Silverchair"]),
        Q(2, "How many times was Elizabeth Taylor married?", "Eight", ["Five", "Six", "Seven"], "She wed seven different men."),
        Q(2, "Madonna married which actor in 1985?", "Sean Penn", ["Warren Beatty", "Matt Dillon", "Tim Robbins"], "They met on the set of her 'Material Girl' video."),
        Q(2, "Katy Perry married which British comedian in 2010?", "Russell Brand", ["Jimmy Carr", "Ricky Gervais", "James Corden"], "They wed in India."),
        Q(2, "Ben Affleck and Jennifer Lopez first costarred in which 2003 film?", "Gigli", ["Paycheck", "Maid in Manhattan", "Out of Sight"]),
        Q(2, "Zoë Kravitz is the daughter of Lenny Kravitz and which actress?", "Lisa Bonet", ["Nia Long", "Halle Berry", "Jada Pinkett Smith"]),
        Q(2, "Fans nicknamed Taylor Swift and Harry Styles's 2012 romance what?", "Haylor", ["Tarry", "Swyles", "Harlor"]),
        Q(2, "Elvis met Priscilla Beaulieu while serving in the Army in which country?", "West Germany", ["Japan", "South Korea", "England"]),
        Q(2, "Beyoncé's twins, born in 2017, are Rumi and who?", "Sir", ["King", "Legend", "Prince"]),
        Q(2, "Christie Brinkley played the title role in which Billy Joel music video?", "Uptown Girl", ["Piano Man", "Just the Way You Are", "She's Always a Woman"], "They married in 1985."),
        Q(2, "Andre Agassi married which fellow tennis champion in 2001?", "Steffi Graf", ["Martina Hingis", "Monica Seles", "Gabriela Sabatini"]),
        Q(2, "David and Victoria Beckham's first son, born in 1999, is named what?", "Brooklyn", ["Romeo", "Cruz", "Hudson"]),
        Q(2, "Shakira met Gerard Piqué on the video shoot for which song?", "Waka Waka", ["Hips Don't Lie", "Whenever, Wherever", "She Wolf"], "It was the official song of the 2010 World Cup."),
        Q(2, "Before Gwen Stefani, Blake Shelton was married to which country star?", "Miranda Lambert", ["Carrie Underwood", "Kelsea Ballerini", "Kacey Musgraves"]),
        Q(2, "Travis Kelce said he tried to give Taylor Swift a friendship bracelet with his what?", "Phone number", ["Jersey number", "Initials", "Podcast name"], "He told the story on his 'New Heights' podcast in 2023."),
        Q(2, "In 2019, Chris Pratt married the daughter of which actor?", "Arnold Schwarzenegger", ["Sylvester Stallone", "Bruce Willis", "Kurt Russell"]),

        Q(3, "Brad Pitt and Angelina Jolie married in 2014 at which French estate?", "Château Miraval", ["Château Margaux", "Château Lafite", "Château d'Yquem"], "The Provence estate is best known for its rosé."),
        Q(3, "Angelina Jolie met her first husband, Jonny Lee Miller, filming which 1995 movie?", "Hackers", ["Gia", "Foxfire", "Playing God"], "They married in 1996."),
        Q(3, "Madonna married Guy Ritchie in 2000 at which Scottish castle?", "Skibo Castle", ["Balmoral Castle", "Eilean Donan", "Dunrobin Castle"], "Their son Rocco was christened nearby the day before."),
        Q(3, "Jennifer Lopez's twins with Marc Anthony are Max and who?", "Emme", ["Ella", "Esme", "Eva"], "The twins were born in February 2008."),
        Q(3, "In 2013, Kanye West proposed to Kim Kardashian at which ballpark?", "AT&T Park", ["Dodger Stadium", "Yankee Stadium", "Wrigley Field"], "He rented the Giants' park for her 33rd birthday; it's now Oracle Park."),
        Q(3, "Chrissy Teigen met John Legend on the set of which of his music videos?", "Stereo", ["Ordinary People", "Green Light", "Used to Love U"], "Their 2013 wedding in Italy appears in his 'All of Me' video."),
        Q(3, "Justin and Hailey Bieber held their 2019 wedding ceremony in which state?", "South Carolina", ["Georgia", "Tennessee", "North Carolina"], "They had married legally a year earlier."),
        Q(3, "Rihanna and A$AP Rocky's first son, born in 2022, is named after which rapper?", "RZA", ["GZA", "Method Man", "Ghostface Killah"], "RZA is the Wu-Tang Clan's founder and producer."),
        Q(3, "Ben Affleck's 2002 engagement ring for Jennifer Lopez held what color diamond?", "Pink", ["Green", "Yellow", "Blue"], "The 6.1-carat Harry Winston stone was reported at $1.2 million."),
        Q(3, "Justin Timberlake and Jessica Biel married in 2012 in which country?", "Italy", ["France", "Mexico", "Greece"], "The ceremony was in Puglia, the heel of Italy's boot."),
        Q(3, "Mariah Carey and Nick Cannon's twins, born in 2011, are Monroe and who?", "Moroccan", ["Maverick", "Montana", "Mercer"], "Cannon proposed in her apartment's Moroccan-style room."),
        Q(3, "Taylor Swift's 2025 engagement post said your gym teacher was marrying your what?", "English teacher", ["Music teacher", "Drama teacher", "Math teacher"], "It became one of Instagram's most-liked posts ever."),
        Q(3, "Dolly Parton met her future husband Carl Dean outside what kind of business?", "A laundromat", ["A diner", "A record store", "A gas station"], "It was her first day in Nashville, in 1964; they married in 1966."),
        Q(3, "In 1968, Johnny Cash proposed to June Carter onstage in which city?", "London, Ontario", ["Nashville", "Memphis", "Toronto"], "They married on March 1, 1968, just days later."),
        Q(3, "Katharine Hepburn and Spencer Tracy made how many films together?", "Nine", ["Five", "Seven", "Twelve"], "Their first was 'Woman of the Year' in 1942."),
        Q(3, "'Star Wars' star Carrie Fisher was married to which singer-songwriter?", "Paul Simon", ["Art Garfunkel", "James Taylor", "Billy Joel"], "They married in 1983."),
        Q(3, "Pattie Boyd was married to George Harrison and which other guitar legend?", "Eric Clapton", ["Jimmy Page", "Keith Richards", "Jeff Beck"]),
        Q(3, "Elton John's husband, David Furnish, was born in which country?", "Canada", ["Australia", "United States", "Ireland"], "They formed a civil partnership on the first day it was legal in England."),
        Q(3, "Michael Douglas and Catherine Zeta-Jones share which birthday?", "September 25", ["September 15", "October 25", "August 25"], "He was born in 1944, she in 1969."),
        Q(3, "Goldie Hawn and Kurt Russell became a couple while making which film?", "Swing Shift", ["Overboard", "Private Benjamin", "Foul Play"], "They had first met as young actors on a 1968 Disney musical."),
        Q(3, "When Jennifer Lawrence married Cooke Maroney in 2019, what was his job?", "Art gallery director", ["Architect", "Film producer", "Sommelier"], "They married in Newport, Rhode Island."),
        Q(3, "Emma Stone met husband Dave McCary when she hosted which show?", "Saturday Night Live", ["The Tonight Show", "Jimmy Kimmel Live!", "The Ellen Show"], "He was a segment director there."),
        Q(3, "Ryan Reynolds and Blake Lively's first daughter, born in 2014, is named what?", "James", ["Olive", "Harper", "Violet"], "Taylor Swift's song 'Betty' uses the names James, Inez, and Betty."),
        Q(3, "Pink proposed to Carey Hart with a sign held up during what?", "His motocross race", ["His NASCAR race", "Her concert", "A hockey game"], "The sign also read 'I'm serious!' and he pulled off the track to say yes."),
        Q(3, "Céline Dion married her manager René Angélil in 1994 in which city?", "Montreal", ["Quebec City", "Las Vegas", "Paris"], "The Notre-Dame Basilica ceremony aired live on Canadian TV."),
        Q(3, "Prince Harry said he proposed to Meghan while they were doing what?", "Roasting a chicken", ["Walking the dogs", "Watching a movie", "Stargazing"], "He proposed at their cottage at Kensington Palace in 2017."),
        Q(3, "Marilyn Monroe's third husband was which playwright?", "Arthur Miller", ["Tennessee Williams", "Neil Simon", "Eugene O'Neill"], "They married in 1956 and divorced in 1961."),
        Q(3, "In 2010, Prince William proposed to Kate Middleton in which country?", "Kenya", ["Tanzania", "South Africa", "Botswana"], "He carried the ring in his backpack for about three weeks."),
    ]
}
