import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let grillExtra: [QSpec] = [
        Q(1, "Which company made the round charcoal kettle grill a backyard classic?", "Weber", ["Traeger", "Char-Broil", "Coleman"]),
        Q(1, "Which cut is the star of classic Texas barbecue?", "Brisket", ["Pork belly", "Lamb shoulder", "Chicken thighs"]),
        Q(1, "Pulled pork is usually made from which cut?", "Pork shoulder", ["Pork tenderloin", "Pork belly", "Ham hock"]),
        Q(1, "On a beer menu, IPA stands for what?", "India Pale Ale", ["Imperial Pale Ale", "Irish Pale Ale", "International Pale Ale"]),
        Q(1, "By law, bourbon must be at least 51% which grain?", "Corn", ["Rye", "Wheat", "Barley"]),
        Q(1, "Buffalo Trace, Jim Beam and Maker's Mark are distilled in which state?", "Kentucky", ["Tennessee", "Virginia", "Indiana"]),
        Q(1, "A beer 'flight' is what?", "A set of small tasting pours", ["A pitcher shared by the table", "A tall glass boot", "A seasonal release"]),
        Q(1, "The original Oktoberfest takes place in which city?", "Munich", ["Berlin", "Hamburg", "Cologne"]),
        Q(1, "A growler is what?", "A jug for carrying draft beer", ["An extra-bitter imperial ale", "A bar-top bottle opener", "A beer brewed with honey"]),
        Q(1, "A chimney starter is used for what?", "Lighting charcoal", ["Holding wood chips", "Venting a smoker", "Scraping grill grates"]),
        Q(1, "Which beer calls itself 'The King of Beers'?", "Budweiser", ["Coors", "Miller High Life", "Pabst Blue Ribbon"]),
        Q(1, "An Old Fashioned is whiskey, sugar, water and what?", "Bitters", ["Sweet vermouth", "Lemon juice", "Soda water"]),
        Q(1, "The mint julep is the traditional drink of which event?", "The Kentucky Derby", ["The Masters", "The Indy 500", "The Belmont Stakes"]),
        Q(1, "A classic British shandy is beer mixed with what?", "Lemonade", ["Tomato juice", "Cola", "Iced tea"], "Germans call their version a Radler."),
        Q(1, "Grilling with indirect heat means what?", "Food sits beside the fire", ["Food is wrapped in foil", "The lid stays open the whole time", "Food is flipped constantly"]),
        Q(1, "Traeger is best known for which kind of grill?", "Pellet grill", ["Gas grill", "Kamado", "Offset smoker"]),
        Q(1, "On smoked meat, the 'bark' is what?", "The dark outer crust", ["The exposed bone", "The fat cap", "The pink smoke ring"]),
        Q(1, "Yeast turns sugar into alcohol and which gas?", "Carbon dioxide", ["Nitrogen", "Oxygen", "Carbon monoxide"]),
        Q(1, "Crown Royal whisky famously comes in a bag of which color?", "Purple", ["Red", "Gold", "Emerald"], "It was created in 1939 for the royal visit of King George VI to Canada."),
        Q(1, "Which whiskey has 'Old No. 7' on its black label?", "Jack Daniel's", ["Jim Beam", "Evan Williams", "Wild Turkey"]),
        Q(1, "The classic 'low and slow' smoker temperature is about what?", "225°F", ["350°F", "425°F", "150°F"]),
        Q(1, "Filet mignon is cut from which part of the cow?", "The tenderloin", ["The chuck", "The rib", "The round"]),
        Q(1, "Which boxer put his name on a hit countertop grill?", "George Foreman", ["Muhammad Ali", "Joe Frazier", "Mike Tyson"]),
        Q(1, "Plank-grilled salmon traditionally sits on which wood?", "Cedar", ["Pine", "Birch", "Maple"]),
        Q(1, "The USDA's safe internal temperature for chicken is what?", "165°F", ["145°F", "135°F", "190°F"]),
        Q(1, "Whiskey's 'angel's share' is what?", "Whiskey lost to evaporation", ["The first pour off the still", "The distiller's sample", "A tip for the bartender"]),
        Q(1, "Maker's Mark bottles are known for what?", "Dripping red wax", ["A horse-and-jockey stopper", "A leather label", "A square green bottle"], "Margie Samuels, the founder's wife, came up with the look."),
        Q(1, "In the US, a 90 proof whiskey is what percent alcohol?", "45%", ["90%", "30%", "60%"]),

        Q(2, "Kansas City burnt ends come from which part of the brisket?", "The point", ["The flat", "The shank", "The chuck"]),
        Q(2, "The Jack Daniel's distillery is in which Tennessee town?", "Lynchburg", ["Nashville", "Tullahoma", "Shelbyville"]),
        Q(2, "The Big Green Egg is which style of cooker?", "Kamado", ["Offset smoker", "Pellet grill", "Hibachi"]),
        Q(2, "Classic beef fajitas are made with which cut?", "Skirt steak", ["Brisket", "Ribeye", "Flat iron steak"]),
        Q(2, "Brazilian steakhouse favorite picanha is what cut?", "Top sirloin cap", ["Beef short rib", "Chuck eye", "Flank steak"]),
        Q(2, "In Argentina, a backyard barbecue gathering is called what?", "An asado", ["A churrasco", "A braai", "A barbacoa"]),
        Q(2, "At Korean barbecue, galbi is what?", "Marinated short ribs", ["Grilled pork belly", "Sliced chicken thighs", "Spicy grilled squid"]),
        Q(2, "Aaron Franklin's famous barbecue joint is in which city?", "Austin", ["Houston", "Dallas", "San Antonio"], "In 2015 he won the James Beard award for Best Chef: Southwest."),
        Q(2, "South Carolina's golden barbecue sauce is built on what?", "Mustard", ["Mayonnaise", "Honey", "Butter"]),
        Q(2, "Samuel Adams beer is made by which company?", "Boston Beer Company", ["New England Brewing", "Yankee Brewing Co.", "Liberty Ale Works"], "Jim Koch and Rhonda Kallman founded it in 1984."),
        Q(2, "In old Miller Lite ads, 'Tastes great!' was answered with what?", "Less filling!", ["More flavor!", "Goes down easy!", "Ice cold!"]),
        Q(2, "A beer's IBU number measures what?", "Bitterness", ["Color", "Alcohol", "Carbonation"]),
        Q(2, "The first Oktoberfest, in 1810, celebrated what?", "A royal wedding", ["A war victory", "A record harvest", "A coronation"], "Crown Prince Ludwig of Bavaria married Princess Therese."),
        Q(2, "Märzen, the classic Oktoberfest lager, is named for which month?", "March", ["May", "September", "October"], "It was brewed in March and stored in cool cellars through summer."),
        Q(2, "What makes beer taste 'skunked'?", "Light hitting the hops", ["Heat warping the yeast", "Air getting into the can", "Sitting too long in a keg"]),
        Q(2, "A 'session' beer is one that is what?", "Low in alcohol", ["Aged a full year", "Extra hoppy", "Only sold on tap"]),
        Q(2, "The widget in a can of Guinness releases which gas?", "Nitrogen", ["Argon", "Oxygen", "Helium"]),
        Q(2, "Laphroaig, Lagavulin and Ardbeg are made on which island?", "Islay", ["Skye", "Orkney", "Arran"]),
        Q(2, "Smoky Scotch gets its smoke from drying barley over what?", "Peat fires", ["Hickory logs", "Coal fires", "Oak chips"]),
        Q(2, "By law, Scotch must age in oak for at least how long?", "3 years", ["1 year", "2 years", "5 years"]),
        Q(2, "Prohibition ended in 1933 with which amendment?", "The 21st", ["The 18th", "The 19th", "The 25th"]),
        Q(2, "Irish whiskey is traditionally distilled how many times?", "Three", ["Two", "Four", "Five"]),
        Q(2, "A Rob Roy is a Manhattan made with which whisky?", "Scotch", ["Irish whiskey", "Rye", "Canadian whisky"]),
        Q(2, "A craftsman who makes barrels is called what?", "A cooper", ["A chandler", "A wainwright", "A fletcher"]),
        Q(2, "Which country spells it 'whiskey,' with an e?", "Ireland", ["Scotland", "Japan", "Canada"]),
        Q(2, "To spatchcock a chicken, you cut out what?", "The backbone", ["The wishbone", "The wing tips", "The thigh bones"]),
        Q(2, "What is the highest USDA quality grade for beef?", "Prime", ["Choice", "Select", "Premium"]),
        Q(2, "Which chef hosted Food Network's 'Boy Meets Grill'?", "Bobby Flay", ["Guy Fieri", "Emeril Lagasse", "Tyler Florence"]),

        Q(3, "George Stephen built the first Weber kettle grill from what?", "Parts of a metal buoy", ["An old oil drum", "A washtub", "A water heater tank"], "He worked at Weber Brothers Metal Works in Chicago, which made buoys."),
        Q(3, "Kingsford charcoal began as a sideline of which carmaker?", "Ford", ["General Motors", "Chrysler", "Studebaker"], "Ford turned scrap wood from its Michigan sawmill into briquettes."),
        Q(3, "Classic Central Texas barbecue is smoked over which wood?", "Post oak", ["Hickory", "Applewood", "Cherry"]),
        Q(3, "Traditional Jamaican jerk is smoked over which wood?", "Pimento", ["Mesquite", "Mango", "Sugarcane"], "Pimento is the Jamaican name for allspice, and the wood comes from the same tree."),
        Q(3, "Which town did Texas lawmakers name the Barbecue Capital of Texas in 1999?", "Lockhart", ["Luling", "Taylor", "Llano"], "Kreuz Market, Black's and Smitty's are all in Lockhart."),
        Q(3, "Eastern North Carolina barbecue traditionally cooks what?", "The whole hog", ["Just the shoulder", "Beef brisket", "Pork spare ribs"], "Its sauce is vinegar and pepper, with no tomato at all."),
        Q(3, "Owensboro, Kentucky is famous for barbecuing which meat?", "Mutton", ["Goat", "Venison", "Turkey"], "Its festival also crowns the best burgoo, a thick meat and vegetable stew."),
        Q(3, "Genuine Kobe beef must come from cattle raised in which prefecture?", "Hyōgo", ["Miyazaki", "Kagoshima", "Hokkaido"], "The cattle must be Tajima-strain Japanese Black."),
        Q(3, "The word 'barbecue' traces back to which Caribbean people?", "The Taíno", ["The Aztec", "The Maya", "The Inca"], "Their barbacoa was a raised wooden frame, used to cook meat over a fire."),
        Q(3, "KCBS contests judge chicken, pork ribs, pork shoulder and what?", "Brisket", ["Sausage", "Turkey", "Lamb"]),
        Q(3, "In 1759, Arthur Guinness leased his Dublin brewery for how long?", "9,000 years", ["99 years", "999 years", "90,000 years"], "The rent was £45 a year."),
        Q(3, "Yuengling was founded in 1829 in which Pennsylvania town?", "Pottsville", ["Latrobe", "Scranton", "Allentown"], "Founder David Jüngling anglicized his name to Yuengling."),
        Q(3, "Rauchbier, a smoked beer, is a specialty of which German city?", "Bamberg", ["Munich", "Leipzig", "Dortmund"]),
        Q(3, "Under EU rules, Kölsch can only be brewed in and around which city?", "Cologne", ["Düsseldorf", "Munich", "Dortmund"], "The 1986 Kölsch Konvention set the rules; the EU protected the name in 1997."),
        Q(3, "Gose, a sour wheat beer, is brewed with coriander and what?", "Salt", ["Honey", "Black pepper", "Juniper"]),
        Q(3, "Belgian lambic beer is fermented with what?", "Wild airborne yeast", ["Lager yeast", "Champagne yeast", "Bread yeast from bakeries"]),
        Q(3, "In 1883, which brewery's lab first brewed with a pure lager yeast?", "Carlsberg", ["Heineken", "Guinness", "Pilsner Urquell"], "Emil Christian Hansen isolated it; Carlsberg gave it to other brewers free."),
        Q(3, "Which president signed the 1978 bill that legalized homebrewing?", "Jimmy Carter", ["Gerald Ford", "Ronald Reagan", "Richard Nixon"]),
        Q(3, "Imperial stout was first brewed strong to ship to which royal court?", "Russia's", ["Sweden's", "Prussia's", "Denmark's"], "London brewers shipped it to Catherine the Great's court."),
        Q(3, "A standard American whiskey barrel holds about how many gallons?", "53", ["30", "42", "75"]),
        Q(3, "Bourbon can go into the barrel at no more than what proof?", "125 proof", ["100 proof", "140 proof", "160 proof"], "It can come off the still at up to 160 proof."),
        Q(3, "The Whiskey Rebellion of 1794 was a revolt against what?", "A federal tax on whiskey", ["A state ban on distilling", "British tariffs", "A grain shortage"], "Washington rode out with the militia sent to put it down."),
        Q(3, "By 1799, George Washington's distillery made about how much whiskey a year?", "11,000 gallons", ["500 gallons", "2,000 gallons", "50,000 gallons"], "When it opened in 1797, it was the largest distillery in America."),
        Q(3, "Nikka founder Masataka Taketsuru learned whisky making in which country?", "Scotland", ["Ireland", "The United States", "Canada"], "He studied chemistry at the University of Glasgow from 1918."),
        Q(3, "Blanton's, launched in 1984, was marketed as the first what?", "Single barrel bourbon", ["Wheated bourbon", "Cask strength bourbon", "Bottled-in-bond bourbon"], "Its eight horse-and-jockey stoppers spell B-L-A-N-T-O-N-S."),
        Q(3, "'Whisky' comes from the Gaelic uisge beatha, meaning what?", "Water of life", ["Fire water", "Golden spirit", "Gift of barley"]),
        Q(3, "A Rusty Nail is Scotch mixed with what?", "Drambuie", ["Amaretto", "Kahlúa", "Sweet vermouth"]),
        Q(3, "The Sazerac is the official cocktail of which city?", "New Orleans", ["Louisville", "Nashville", "Charleston"], "Louisiana lawmakers made it official in 2008."),
    ]
}
