import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let nerdExtra: [QSpec] = [
        Q(1, "What green rock from his home planet weakens Superman?", "Kryptonite", ["Adamantium", "Vibranium", "Carbonite"], "It first appeared on the Superman radio show in 1943, not in the comics."),
        Q(1, "In Pac-Man, what do you eat to turn the ghosts blue?", "A power pellet", ["A cherry", "A key", "A bell"]),
        Q(1, "Which game has you rotate falling blocks to clear lines?", "Tetris", ["Pac-Man", "Breakout", "Frogger"]),
        Q(1, "Sonic the Hedgehog was the mascot of which game company?", "Sega", ["Nintendo", "Atari", "Sony"]),
        Q(1, "Mario's taller brother in green is named what?", "Luigi", ["Wario", "Toad", "Waluigi"]),
        Q(1, "Which yellow, electric Pokémon is the series mascot?", "Pikachu", ["Jigglypuff", "Raichu", "Psyduck"]),
        Q(1, "The Hulk's everyday alter ego is which scientist?", "Bruce Banner", ["Tony Stark", "Reed Richards", "Hank Pym"]),
        Q(1, "Wonder Woman's golden lasso forces people to do what?", "Tell the truth", ["Fall asleep", "Forget everything", "Freeze in place"]),
        Q(1, "Who is Batman's loyal butler?", "Alfred", ["Jarvis", "Lucius", "Jeeves"]),
        Q(1, "Which company makes the Xbox?", "Microsoft", ["Sony", "Nintendo", "Sega"], "The first Xbox launched in 2001."),
        Q(1, "Mario is forever rescuing which princess?", "Princess Peach", ["Princess Zelda", "Princess Leia", "Princess Fiona"]),
        Q(1, "Superman's bald billionaire archenemy is named what?", "Lex Luthor", ["Brainiac", "General Zod", "Darkseid"]),
        Q(1, "Finish Spider-Man's motto: 'With great power comes great...'", "Responsibility", ["Danger", "Sacrifice", "Glory"]),
        Q(1, "Which skinny soldier became Captain America in World War II?", "Steve Rogers", ["Bucky Barnes", "Nick Fury", "Sam Wilson"]),
        Q(1, "Which Nintendo console works on the TV and as a handheld?", "Nintendo Switch", ["Wii", "GameCube", "Nintendo 64"], "It launched in March 2017."),
        Q(1, "The Flash's superpower is what?", "Super speed", ["Flight", "Invisibility", "Super strength"]),
        Q(1, "Aquaman is king of which underwater kingdom?", "Atlantis", ["Wakanda", "Asgard", "Latveria"]),
        Q(1, "Which spiky-shelled king kidnaps the princess in Mario games?", "Bowser", ["Wario", "Ganon", "King Dedede"]),
        Q(1, "Call of Duty is what kind of game?", "First-person shooter", ["Racing game", "Puzzle game", "Sports game"]),
        Q(1, "Which game heroine raids tombs with twin pistols?", "Lara Croft", ["Samus Aran", "Jill Valentine", "Chun-Li"]),
        Q(1, "In gaming, what does NPC stand for?", "Non-player character", ["New player class", "Network play code", "Next power-up coin"]),
        Q(1, "Nintendo's hit 1989 handheld was called what?", "Game Boy", ["Game Gear", "Atari Lynx", "PSP"], "In North America it came bundled with Tetris."),
        Q(1, "Who played Wolverine in the X-Men movies?", "Hugh Jackman", ["Russell Crowe", "Liev Schreiber", "Ryan Reynolds"]),
        Q(1, "Who played Superman in the 1978 movie?", "Christopher Reeve", ["George Reeves", "Dean Cain", "Henry Cavill"]),
        Q(1, "In 'Endgame,' Captain America finally shouts 'Avengers...' what?", "Assemble", ["Unite", "Attack", "Charge"]),
        Q(1, "In Among Us, the hidden saboteur is called what?", "The Impostor", ["The Traitor", "The Spy", "The Mole"]),
        Q(1, "Who played Nick Fury in the Marvel movies?", "Samuel L. Jackson", ["Laurence Fishburne", "Don Cheadle", "Idris Elba"]),
        Q(1, "Which green dinosaur lets Mario ride on his back?", "Yoshi", ["Rex", "Birdo", "Dino"]),

        Q(2, "Thor's enchanted hammer is named what?", "Mjolnir", ["Stormbreaker", "Gungnir", "Excalibur"], "Stormbreaker is the axe he forges in 'Infinity War.'"),
        Q(2, "Wonder Woman grew up on which hidden island?", "Themyscira", ["Genosha", "Madripoor", "Krakoa"]),
        Q(2, "Which tech giant bought Minecraft in 2014?", "Microsoft", ["Google", "Sony", "Electronic Arts"], "The price was $2.5 billion."),
        Q(2, "Which comics legend made cameos across the Marvel movies?", "Stan Lee", ["Jack Kirby", "Steve Ditko", "Todd McFarlane"], "His first came in 1989's TV movie 'The Trial of the Incredible Hulk.'"),
        Q(2, "Which film kicked off the Marvel Cinematic Universe in 2008?", "Iron Man", ["The Incredible Hulk", "Thor", "Captain America"]),
        Q(2, "Who played T'Challa in 2018's 'Black Panther'?", "Chadwick Boseman", ["Michael B. Jordan", "Daniel Kaluuya", "Winston Duke"]),
        Q(2, "Heath Ledger won a posthumous Oscar as the Joker in which film?", "The Dark Knight", ["Batman Begins", "The Dark Knight Rises", "Suicide Squad"]),
        Q(2, "The Legend of Zelda's recurring villain is named what?", "Ganondorf", ["Bowser", "Ridley", "Dr. Wily"]),
        Q(2, "The X-Men's founder, Professor X, is named what?", "Charles Xavier", ["Erik Lehnsherr", "Hank McCoy", "Scott Summers"]),
        Q(2, "The characters in The Sims speak which made-up language?", "Simlish", ["Plumbobian", "Simspeak", "Sim-ese"]),
        Q(2, "Which company makes Fortnite?", "Epic Games", ["Activision", "Riot Games", "Valve"]),
        Q(2, "Kratos is the hero of which game series?", "God of War", ["Devil May Cry", "Dark Souls", "Assassin's Creed"]),
        Q(2, "In Mortal Kombat, who yells 'Get over here!'?", "Scorpion", ["Sub-Zero", "Raiden", "Liu Kang"]),
        Q(2, "Who is the outlaw hero of 'Red Dead Redemption 2'?", "Arthur Morgan", ["Dutch van der Linde", "Micah Bell", "Javier Escuella"]),
        Q(2, "In 'The Last of Us,' Joel escorts which teenager?", "Ellie", ["Clementine", "Aloy", "Elizabeth"]),
        Q(2, "S.H.I.E.L.D.'s flying aircraft carrier is called what?", "The Helicarrier", ["The Quinjet", "The Milano", "The Skybase"]),
        Q(2, "Hidden graffiti in 'Portal' warns that 'the cake is a...' what?", "Lie", ["Trap", "Gift", "Dream"]),
        Q(2, "The 'Leeroy Jenkins' battle-cry meme came from which game?", "World of Warcraft", ["EverQuest", "Halo 2", "Counter-Strike"], "His solo charge gets his whole group wiped out in a 2005 video."),
        Q(2, "Superman's birth name on Krypton is what?", "Kal-El", ["Jor-El", "Zor-El", "Kon-El"], "Jor-El is his father."),
        Q(2, "Wolverine's skeleton and claws are laced with which metal?", "Adamantium", ["Vibranium", "Uru", "Titanium"]),
        Q(2, "GoldenEye 007 was a 1997 hit on which console?", "Nintendo 64", ["PlayStation", "Sega Saturn", "Super Nintendo"]),
        Q(2, "In Duck Hunt, who laughs at you when you miss?", "The hunting dog", ["The ducks", "A crow", "The game warden"]),
        Q(2, "The Witcher games were made in which country?", "Poland", ["Russia", "Sweden", "Czech Republic"], "The books behind them are by Polish author Andrzej Sapkowski."),
        Q(2, "Peter Parker sells photos to which newspaper?", "The Daily Bugle", ["The Daily Planet", "The Gotham Gazette", "The Daily Star"]),
        Q(2, "Which monster killed Superman in the 1992 comics?", "Doomsday", ["Darkseid", "Brainiac", "Bizarro"], "'The Death of Superman' made headlines; he came back in 1993."),
        Q(2, "Which hero's battle cry is 'It's clobberin' time!'?", "The Thing", ["The Hulk", "Colossus", "Juggernaut"]),
        Q(2, "What is the silver-haired villain of 'Final Fantasy VII' called?", "Sephiroth", ["Kefka", "Ardyn", "Seymour"]),
        Q(2, "Disney bought Marvel Entertainment in which year?", "2009", ["2006", "2012", "2015"], "The price was about $4 billion."),

        Q(3, "Batman debuted in 1939 in which comic?", "Detective Comics #27", ["Action Comics #1", "Batman #1", "Detective Comics #1"], "Bob Kane and Bill Finger created him."),
        Q(3, "Jerry Siegel created Superman with which artist?", "Joe Shuster", ["Bob Kane", "Jack Kirby", "Joe Simon"], "Superman debuted in Action Comics #1 in 1938."),
        Q(3, "Which artist co-created Spider-Man with Stan Lee?", "Steve Ditko", ["John Romita Sr.", "Gil Kane", "John Buscema"], "Ditko also co-created Doctor Strange in 1963."),
        Q(3, "In 1981's 'Donkey Kong,' Mario was known by what name?", "Jumpman", ["Hammerman", "Climber", "Mr. Barrel"], "He was renamed for Mario Segale, landlord of Nintendo of America's office."),
        Q(3, "Which of Pac-Man's ghosts is the red one?", "Blinky", ["Pinky", "Inky", "Clyde"], "Pinky is pink, Inky is cyan and Clyde is orange."),
        Q(3, "Who created Tetris in 1984?", "Alexey Pajitnov", ["Shigeru Miyamoto", "Toru Iwatani", "Hideo Kojima"], "He built it on a Soviet computer at a Moscow research center."),
        Q(3, "Which designer created both Mario and Zelda?", "Shigeru Miyamoto", ["Satoru Iwata", "Hideo Kojima", "Gunpei Yokoi"], "His first big hit was 'Donkey Kong' in 1981."),
        Q(3, "The NES first went on sale in North America in which year?", "1985", ["1983", "1987", "1981"], "It opened in a New York test market; Japan got the Famicom in 1983."),
        Q(3, "Atari's famous 1983 landfill burial is best known for which film tie-in?", "E.T. the Extra-Terrestrial", ["Jaws", "Tron", "Ghostbusters"], "Diggers unearthed them in Alamogordo, New Mexico, in 2014."),
        Q(3, "Stan Lee was born with what name?", "Stanley Lieber", ["Stanley Levine", "Stanley Leibowitz", "Stanley Lehman"], "He first signed 'Stan Lee' as a pen name in 1941."),
        Q(3, "The X-Men first appeared in which year?", "1963", ["1961", "1968", "1975"], "Stan Lee and Jack Kirby created them; Wolverine joined in 1975."),
        Q(3, "Black Panther debuted in 1966 in which team's comic?", "The Fantastic Four", ["The Avengers", "The X-Men", "The Defenders"], "Stan Lee and Jack Kirby introduced him in issue #52."),
        Q(3, "Which artist co-created Thanos, first seen in 1973?", "Jim Starlin", ["John Byrne", "Frank Miller", "Jack Kirby"], "Thanos debuted in Iron Man #55."),
        Q(3, "Wonder Woman's creator also helped develop what?", "An early lie detector", ["The IQ test", "The Rorschach test", "The mood ring"], "William Moulton Marston's blood pressure test fed into the polygraph."),
        Q(3, "Princess Zelda was named after the wife of which author?", "F. Scott Fitzgerald", ["Ernest Hemingway", "John Steinbeck", "William Faulkner"], "A PR planner suggested it, and Miyamoto just liked the name."),
        Q(3, "In Sonic, what is Tails's full name?", "Miles Prower", ["Miles Fox", "Tyler Prowl", "Max Tailor"], "It's a pun on 'miles per hour.'"),
        Q(3, "Pokémon creator Satoshi Tajiri grew up collecting what?", "Insects", ["Stamps", "Coins", "Seashells"], "Other kids called him Dr. Bug."),
        Q(3, "Which Pokémon is number 151 in the original Pokédex?", "Mew", ["Mewtwo", "Dragonite", "Ditto"], "A programmer slipped it in at the last minute as a secret."),
        Q(3, "Minecraft creator Markus Persson is known online as what?", "Notch", ["Jeb", "Dinnerbone", "Herobrine"]),
        Q(3, "Which studio made 1993's 'Doom'?", "id Software", ["Valve", "Epic MegaGames", "3D Realms"], "John Carmack and John Romero led the tiny team."),
        Q(3, "What was the first home video game console, from 1972?", "Magnavox Odyssey", ["Atari 2600", "Fairchild Channel F", "Intellivision"], "Its inventor, Ralph Baer, is called the father of video games."),
        Q(3, "Which was the first superhero film nominated for Best Picture?", "Black Panther", ["The Dark Knight", "Joker", "Logan"], "It won three Oscars: costumes, production design and score."),
        Q(3, "Marvel Comics started out in 1939 under which name?", "Timely Comics", ["National Comics", "Fawcett Comics", "Quality Comics"], "It went by Atlas in the 1950s before becoming Marvel."),
        Q(3, "The 'S' in Shazam stands for which wise figure?", "Solomon", ["Samson", "Socrates", "Spartacus"], "The rest: Hercules, Atlas, Zeus, Achilles and Mercury."),
        Q(3, "GTA's original studio, DMA Design, was founded in which Scottish city?", "Dundee", ["Glasgow", "Edinburgh", "Aberdeen"], "The studio later moved to Edinburgh and became Rockstar North."),
        Q(3, "Nintendo's Wii was code-named what before launch?", "Revolution", ["Dolphin", "Project Reality", "NX"], "Dolphin was the GameCube; NX became the Switch."),
        Q(3, "Dungeons & Dragons was first published in which year?", "1974", ["1968", "1981", "1986"], "Gary Gygax and Dave Arneson created it."),
        Q(3, "Frank Miller's 1986 story of an aging Batman is called what?", "The Dark Knight Returns", ["Batman: Year One", "The Long Halloween", "Hush"], "In it, a 55-year-old Bruce Wayne comes out of retirement."),
    ]
}
