import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let realityExtra: [QSpec] = [
        Q(1, "On 'Survivor,' castaways are split into teams called what?", "Tribes", ["Clans", "Crews", "Packs"]),
        Q(1, "Who hosted the very first season of 'Survivor' in 2000?", "Jeff Probst", ["Phil Keoghan", "Chris Harrison", "Ryan Seacrest"]),
        Q(1, "How much does the winner of a regular 'Survivor' season take home?", "$1 million", ["$100,000", "$500,000", "$5 million"]),
        Q(1, "On 'The Bachelor,' the week the lead meets contestants' families is called what?", "Hometowns", ["Meet the Parents", "Family Week", "Homecoming"]),
        Q(1, "On 'Big Brother,' the houseguest who wins each week's power is the what?", "Head of Household", ["House Captain", "Top Dog", "Big Boss"]),
        Q(1, "On 'Love Island,' the second villa that tests the couples is called what?", "Casa Amor", ["Casa Bella", "Villa Rosa", "The Hideaway"]),
        Q(1, "'Love Island' began in which country?", "The United Kingdom", ["Australia", "The United States", "Sweden"], "ITV relaunched it in 2015, and the U.S. version followed in 2019."),
        Q(1, "On 'RuPaul's Drag Race,' the bottom two queens must do what to stay?", "Lip sync for their lives", ["Sew a new gown", "Win a trivia round", "Walk the runway again"]),
        Q(1, "Which country star won 'American Idol' season four in 2005?", "Carrie Underwood", ["Kellie Pickler", "Miranda Lambert", "Kelsea Ballerini"]),
        Q(1, "Which famously blunt British judge sat on the original 'American Idol' panel?", "Simon Cowell", ["Piers Morgan", "Gordon Ramsay", "Louis Walsh"]),
        Q(1, "On 'The Voice,' coaches judge singers with their backs turned in which round?", "The blind auditions", ["The battles", "The knockouts", "The live playoffs"]),
        Q(1, "On 'Bake Off,' Paul Hollywood's rare top compliment is a what?", "Handshake", ["High five", "Gold star", "Hug"]),
        Q(1, "Which 'Shark Tank' investor goes by 'Mr. Wonderful'?", "Kevin O'Leary", ["Mark Cuban", "Robert Herjavec", "Daymond John"]),
        Q(1, "Which Kardashian co-founded the shapewear brand SKIMS?", "Kim Kardashian", ["Khloé Kardashian", "Kourtney Kardashian", "Kendall Jenner"]),
        Q(1, "On 'Duck Dynasty,' the Robertson family business is known for making what?", "Duck calls", ["Fishing lures", "Hunting boots", "Decoy boats"]),
        Q(1, "Who is famous for saying 'You're doing amazing, sweetie'?", "Kris Jenner", ["Kim Kardashian", "Khloé Kardashian", "Caitlyn Jenner"]),
        Q(1, "On 'Jersey Shore,' GTL stands for gym, tan, and what?", "Laundry", ["Lunch", "Lotion", "Lifting"]),
        Q(1, "The Real Housewives franchise began in 2006 in which place?", "Orange County", ["New York City", "Atlanta", "Beverly Hills"]),
        Q(1, "The five experts on 'Queer Eye' are known as the Fab what?", "Five", ["Four", "Six", "Squad"]),
        Q(1, "On 'Hell's Kitchen,' the chefs split into which two team colors?", "Red and blue", ["Black and white", "Red and green", "Blue and gold"]),
        Q(1, "The 'Dancing with the Stars' champions lift which trophy?", "The Mirrorball Trophy", ["The Golden Shoe", "The Crystal Slipper", "The Silver Star"]),
        Q(1, "Tyra Banks coined which word for smiling with your eyes?", "Smize", ["Squinch", "Twinkle", "Glint"]),
        Q(1, "Who hosted the first season of 'The Amazing Race' in 2001?", "Phil Keoghan", ["Jeff Probst", "Tom Bergeron", "Carson Daly"]),
        Q(1, "'Fixer Upper' put which Texas city on the map?", "Waco", ["Austin", "Tyler", "Amarillo"], "Chip and Joanna Gaines run their Magnolia brand there."),
        Q(1, "On 'Chopped,' chefs must cook with surprise ingredients from a mystery what?", "Basket", ["Fridge", "Pantry", "Bag"]),
        Q(1, "On '90 Day Fiancé,' couples have 90 days to do what?", "Get married", ["Move out", "Break up", "Buy a house"], "It's the window a U.S. K-1 fiancé visa allows."),
        Q(1, "'Selling Sunset' follows agents at which brokerage?", "The Oppenheim Group", ["Compass", "The Agency", "Douglas Elliman"]),
        Q(1, "'Pawn Stars' is set at a pawn shop in which city?", "Las Vegas", ["Reno", "Atlantic City", "Phoenix"]),
        Q(2, "When a 'Survivor' castaway is voted out, what does the host snuff?", "Their torch", ["Their candle", "The campfire", "Their lantern"]),
        Q(2, "The first U.S. season of 'Survivor' was subtitled what?", "Borneo", ["Fiji", "The Australian Outback", "Palau"], "It was shot on Pulau Tiga, a small island off Borneo's coast."),
        Q(2, "What is the 'Survivor' motto?", "Outwit, Outplay, Outlast", ["Adapt, Survive, Win", "Trust, Betray, Win", "Outthink, Outlast, Outwin"]),
        Q(2, "'Cake Boss' Buddy Valastro's Carlo's Bakery is in which New Jersey city?", "Hoboken", ["Newark", "Jersey City", "Paterson"], "The bakery sits across the street from Hoboken City Hall."),
        Q(2, "On 'The Bachelor,' the rose handed out on night one is called the what?", "First impression rose", ["Welcome rose", "Opening rose", "Golden rose"]),
        Q(2, "Summer seasons of 'Love Island UK' are filmed on which Spanish island?", "Mallorca", ["Ibiza", "Tenerife", "Menorca"]),
        Q(2, "On 'Love Island,' working hard to win someone over is called what?", "Grafting", ["Crafting", "Mugging off", "Pieing"]),
        Q(2, "Drag Race's celebrity impersonation challenge is called what?", "Snatch Game", ["Match Game", "Celebrity Face-Off", "Star Search"], "It's a spoof of the 1970s game show 'Match Game.'"),
        Q(2, "Which 'American Idol' finalist later won an Oscar for 'Dreamgirls'?", "Jennifer Hudson", ["Fantasia Barrino", "Jordin Sparks", "LaToya London"], "She finished seventh on season three."),
        Q(2, "Which boy band was formed on 'The X Factor' UK in 2010?", "One Direction", ["The Wanted", "JLS", "Union J"], "They finished third that series."),
        Q(2, "NeNe Leakes was an original cast member of which 'Real Housewives' city?", "Atlanta", ["New York", "New Jersey", "Potomac"], "The show premiered on Bravo in October 2008."),
        Q(2, "Susan Boyle stunned 'Britain's Got Talent' in 2009 singing what?", "I Dreamed a Dream", ["Memory", "On My Own", "Don't Cry for Me Argentina"]),
        Q(2, "Who replaced Mary Berry as a 'Bake Off' judge in 2017?", "Prue Leith", ["Nigella Lawson", "Delia Smith", "Mary Portas"], "The show moved from the BBC to Channel 4 that year."),
        Q(2, "Which 2015 'Bake Off' winner baked the Queen's 90th birthday cake?", "Nadiya Hussain", ["Candice Brown", "Nancy Birtwhistle", "Jo Wheatley"], "She made an orange drizzle cake."),
        Q(2, "'Shark Tank' star Daymond John co-founded which clothing brand?", "FUBU", ["Sean John", "Rocawear", "Phat Farm"]),
        Q(2, "Which 'Shark Tank' investor is known as the 'Queen of QVC'?", "Lori Greiner", ["Barbara Corcoran", "Emma Grede", "Kendra Scott"]),
        Q(2, "Kim Kardashian lost a diamond earring in the ocean off which island?", "Bora Bora", ["Maui", "Mykonos", "St. Barts"], "It happened on a family trip in season six, which aired in 2011."),
        Q(2, "Which 'Jersey Shore' star calls himself 'The Situation'?", "Mike Sorrentino", ["Pauly DelVecchio", "Vinny Guadagnino", "Ronnie Ortiz-Magro"]),
        Q(2, "'Real Housewives of New York' star Bethenny Frankel built which cocktail brand?", "Skinnygirl", ["SlimSip", "Svelte", "Bare Naked"]),
        Q(2, "Which 'Real Housewives' star released the single 'Money Can't Buy You Class'?", "Luann de Lesseps", ["Ramona Singer", "Kyle Richards", "Teresa Giudice"], "Her title came from her marriage to French count Alexandre de Lesseps."),
        Q(2, "Lisa Vanderpump's beloved Pomeranian was named what?", "Giggy", ["Gizmo", "Biscuit", "Coco"]),
        Q(2, "On 'Top Chef,' the short challenge that opens most episodes is the what?", "Quickfire", ["Speed Round", "Flash Fry", "Mise en Place"]),
        Q(2, "Which NFL legend won 'Dancing with the Stars' season three?", "Emmitt Smith", ["Jerry Rice", "Hines Ward", "Donald Driver"], "Hines Ward and Donald Driver won later seasons."),
        Q(2, "On 'The Traitors,' the loyal players are called what?", "Faithfuls", ["Loyalists", "Innocents", "Believers"]),
        Q(2, "On 'Extreme Makeover: Home Edition,' crowds shouted what at the reveal?", "Move that bus!", ["Open the doors!", "Welcome home!", "Here it is!"]),
        Q(2, "'Here Comes Honey Boo Boo' spun off from which TLC show?", "Toddlers & Tiaras", ["Little People, Big World", "Say Yes to the Dress", "Cake Boss"]),
        Q(2, "Which 'Queer Eye' host made the 'French tuck' famous?", "Tan France", ["Antoni Porowski", "Bobby Berk", "Karamo Brown"]),
        Q(2, "On 'Newlyweds,' Jessica Simpson asked if which tuna brand was chicken?", "Chicken of the Sea", ["StarKist", "Bumble Bee", "Wild Planet"]),
        Q(3, "Who won the very first season of 'Survivor' in 2000?", "Richard Hatch", ["Kelly Wiglesworth", "Rudy Boesch", "Tina Wesson"], "He beat river guide Kelly Wiglesworth by a 4-3 jury vote."),
        Q(3, "Who won 'Survivor: Winners at War' and its $2 million prize?", "Tony Vlachos", ["Natalie Anderson", "Michele Fitzgerald", "Sarah Lacina"], "It was his second win, after 'Survivor: Cagayan.'"),
        Q(3, "The hidden immunity idol debuted on which 'Survivor' season?", "Guatemala", ["Palau", "Pearl Islands", "Vanuatu"], "Gary Hogeboom was the first to find one and play it at Tribal Council."),
        Q(3, "Who won 'Survivor: All-Stars' in 2004, the night she got engaged?", "Amber Brkich", ["Jenna Lewis", "Jenna Morasca", "Kathy O'Brien"], "Runner-up Rob Mariano proposed at the finale, before the votes were read."),
        Q(3, "Who won the first U.S. season of 'Big Brother' in 2000?", "Eddie McGee", ["Josh Souza", "Curtis Kin", "Dan Gheesling"], "That season, viewers phoned in to evict houseguests and to pick the winner."),
        Q(3, "Which Bachelor dumped his pick for runner-up Molly on 'After the Final Rose'?", "Jason Mesnick", ["Brad Womack", "Jake Pavelka", "Arie Luyendyk Jr."], "He and Molly Malaney married in 2010."),
        Q(3, "In 2017, who became the Bachelor franchise's first Black lead?", "Rachel Lindsay", ["Tayshia Adams", "Michelle Young", "Charity Lawson"], "She was a practicing attorney before the show."),
        Q(3, "Which former Bachelorette won 'Dancing with the Stars' season 28?", "Hannah Brown", ["Kaitlyn Bristowe", "JoJo Fletcher", "Becca Kufrin"], "Kaitlyn Bristowe won the very next season."),
        Q(3, "Which comedian narrated the 2015 reboot of 'Love Island UK'?", "Iain Stirling", ["Rob Beckett", "Joel Dommett", "Romesh Ranganathan"]),
        Q(3, "Who hosted season six of 'Love Island USA' in 2024?", "Ariana Madix", ["Sarah Hyland", "Arielle Vandenberg", "Maya Jama"], "She took over from Sarah Hyland, who hosted seasons four and five."),
        Q(3, "'Love Island UK' 2018 winner Dani Dyer is which actor's daughter?", "Danny Dyer", ["Ray Winstone", "Ross Kemp", "Phil Daniels"], "She and Jack Fincham won with 79.66 percent of the final vote."),
        Q(3, "Which queen won season six of 'RuPaul's Drag Race'?", "Bianca Del Rio", ["Adore Delano", "Courtney Act", "Sharon Needles"], "Adore Delano and Courtney Act were the runners-up."),
        Q(3, "Who won the first series of 'RuPaul's Drag Race UK' in 2019?", "The Vivienne", ["Divina de Campo", "Baga Chipz", "Cheryl Hole"], "Divina de Campo was the runner-up."),
        Q(3, "'American Idol' was adapted from which British show?", "Pop Idol", ["The X Factor", "Popstars", "Fame Academy"], "Simon Fuller created both shows."),
        Q(3, "Who beat Adam Lambert to win 'American Idol' season eight?", "Kris Allen", ["David Cook", "Danny Gokey", "Taylor Hicks"], "Lambert later toured as the frontman for Queen."),
        Q(3, "Which rocker was the shock fourth-place exit on 'American Idol' season five?", "Chris Daughtry", ["Bo Bice", "Constantine Maroulis", "Blake Lewis"], "Taylor Hicks went on to win that season."),
        Q(3, "'The Voice' began in 2010 as 'The Voice of' which country?", "Holland", ["Belgium", "Sweden", "Germany"], "It premiered on the Dutch channel RTL 4 in September 2010."),
        Q(3, "Who won the first 'Great British Bake Off' in 2010?", "Edd Kimber", ["John Whaite", "Jo Wheatley", "Frances Quinn"], "That first series moved to a new town every week."),
        Q(3, "Whose trademark makes 'Bake Off' air as the 'Baking Show' in the U.S.?", "Pillsbury", ["Betty Crocker", "Duncan Hines", "King Arthur"], "Pillsbury trademarked the name for its long-running recipe contest."),
        Q(3, "'Shark Tank' is adapted from a format first made in which country?", "Japan", ["The United Kingdom", "Canada", "Australia"], "The 2001 original is called 'The Tigers of Money.'"),
        Q(3, "Which Shark made a deal for Scrub Daddy in 2012?", "Lori Greiner", ["Mark Cuban", "Barbara Corcoran", "Kevin O'Leary"], "She put in $200,000 for 20 percent of the company."),
        Q(3, "Which 'Top Chef' winner took over as host from Padma Lakshmi?", "Kristen Kish", ["Stephanie Izard", "Brooke Williamson", "Melissa King"], "Kish won season 10, set in Seattle."),
        Q(3, "Who won the first season of 'Dancing with the Stars' in 2005?", "Kelly Monaco", ["John O'Hurley", "Joey McIntyre", "Rachel Hunter"], "Runner-up John O'Hurley won a charity rematch dance-off that September."),
        Q(3, "Who won the first cycle of 'America's Next Top Model' in 2003?", "Adrianne Curry", ["Shannon Stewart", "Yoanna House", "Eva Pigford"], "Yoanna House and Eva Pigford won the next two cycles."),
        Q(3, "Who won the first U.S. season of 'The Traitors' in 2023?", "Cirie Fields", ["Quentin Jiles", "Andie Vanacore", "Arie Luyendyk Jr."], "She was a Traitor and kept the whole $250,000 pot."),
        Q(3, "Who won 'Squid Game: The Challenge' in 2023?", "Mai Whelan", ["Phill Cain", "Sam Lantz", "Trey Plutnicki"], "As Player 287, she took home $4.56 million."),
        Q(3, "Kim Zolciak's 2009 single was 'Tardy for the' what?", "Party", ["Show", "Club", "Weekend"], "Her spin-off was 'Don't Be Tardy for the Wedding.'"),
        Q(3, "Who was the fashion expert on the original 'Queer Eye' in 2003?", "Carson Kressley", ["Ted Allen", "Thom Filicia", "Kyan Douglas"], "Food expert Ted Allen went on to host 'Chopped.'"),
    ]
}
