import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let romcomsExtra: [QSpec] = [
        Q(1, "In 'Pretty Woman,' Julia Roberts's character is named what?", "Vivian", ["Holly", "Kathleen", "Andie"]),
        Q(1, "Who plays Harry in 'When Harry Met Sally...'?", "Billy Crystal", ["Tom Hanks", "Chevy Chase", "Steve Martin"]),
        Q(1, "In 'Titanic,' how does Jack win his ticket?", "In a poker game", ["In a raffle", "As a tip from a passenger", "By working as a stoker"]),
        Q(1, "'Nobody puts Baby in a corner' is a line from which film?", "Dirty Dancing", ["Footloose", "Flashdance", "Grease"]),
        Q(1, "'10 Things I Hate About You' updates which Shakespeare play?", "The Taming of the Shrew", ["Much Ado About Nothing", "Twelfth Night", "As You Like It"]),
        Q(1, "In 'Pride and Prejudice,' how many Bennet sisters are there?", "Five", ["Three", "Four", "Six"]),
        Q(1, "Who played Bridget in 'Bridget Jones's Diary'?", "Renée Zellweger", ["Gwyneth Paltrow", "Rachel Weisz", "Helen Hunt"]),
        Q(1, "The famous romantic scene in 'Ghost' happens at a what?", "Pottery wheel", ["Piano", "Easel", "Sewing machine"]),
        Q(1, "In 'The Princess Diaries,' Mia learns she's heir to which kingdom?", "Genovia", ["Aldovia", "Monaco", "Ruritania"]),
        Q(1, "Finish the 'Jerry Maguire' line: 'You had me at...'", "Hello", ["Hi", "Goodbye", "First sight"]),
        Q(1, "In '50 First Dates,' Drew Barrymore's Lucy lives with what?", "Short-term memory loss", ["Narcolepsy", "Sleepwalking", "Face blindness"]),
        Q(1, "In 'La La Land,' Sebastian dreams of opening a what?", "Jazz club", ["Piano bar", "Record store", "Recording studio"]),
        Q(1, "In the film 'Grease,' Sandy has moved from which country?", "Australia", ["England", "Canada", "Ireland"]),
        Q(1, "'West Side Story' reworks which Shakespeare play?", "Romeo and Juliet", ["Othello", "Hamlet", "Twelfth Night"]),
        Q(1, "In 'The Proposal,' Andrew's family lives in which state?", "Alaska", ["Maine", "Montana", "Vermont"], "The town is Sitka, though the film was mostly shot in Massachusetts."),
        Q(1, "'Crazy Rich Asians' is mostly set in which country?", "Singapore", ["Hong Kong", "Malaysia", "Thailand"]),
        Q(1, "In 'To All the Boys I've Loved Before,' what happens to Lara Jean's secret letters?", "They get mailed", ["They get burned", "They go viral", "They're read aloud in class"]),
        Q(1, "Who plays Noah in 'The Notebook' (2004)?", "Ryan Gosling", ["Channing Tatum", "Bradley Cooper", "Chris Pine"]),
        Q(1, "Who stars in 'Sweet Home Alabama'?", "Reese Witherspoon", ["Kate Hudson", "Jennifer Garner", "Amanda Bynes"]),
        Q(1, "In 'Sex and the City,' Carrie's on-again, off-again love is known as what?", "Mr. Big", ["Mr. Right", "Mr. Wonderful", "Mr. Perfect"]),
        Q(1, "In 'P.S. I Love You,' Holly's late husband leaves her a series of what?", "Letters", ["Voicemails", "Videotapes", "Paintings"]),
        Q(1, "Finish the 'Casablanca' line: 'Here's looking at you,' what?", "Kid", ["Sweetheart", "Darling", "Doll"]),
        Q(1, "In 'Hitch,' Will Smith plays a what?", "Dating coach", ["Wedding planner", "Divorce lawyer", "Radio host"]),
        Q(1, "In 'Sleepless in Seattle,' Sam's son Jonah phones in to a what?", "Radio call-in show", ["TV talk show", "Newspaper advice column", "Dating hotline"]),
        Q(1, "The songs in 'Mamma Mia!' come from which band?", "ABBA", ["The Bee Gees", "Fleetwood Mac", "Queen"]),
        Q(1, "On 'Friends,' Ross insists he and Rachel were on a what?", "A break", ["A timeout", "A trial run", "A cooling-off period"]),
        Q(1, "On 'The Office,' Jim pines for which receptionist?", "Pam", ["Angela", "Kelly", "Meredith"]),
        Q(1, "Which 'Grey's Anatomy' doctor is nicknamed McDreamy?", "Derek Shepherd", ["Mark Sloan", "Alex Karev", "Preston Burke"]),

        Q(2, "Which song plays during the pottery scene in 'Ghost'?", "Unchained Melody", ["Stand by Me", "Only You", "Can't Help Falling in Love"], "The Righteous Brothers' 1965 recording returned to the charts after the film."),
        Q(2, "In 'Titanic,' the blue diamond necklace is called what?", "Heart of the Ocean", ["Star of the Sea", "Eye of the Storm", "Blue Empress"]),
        Q(2, "Audrey Hepburn plays who in 'Breakfast at Tiffany's'?", "Holly Golightly", ["Sabrina Fairchild", "Eliza Doolittle", "Princess Ann"]),
        Q(2, "In 'Enchanted,' Giselle comes from which animated kingdom?", "Andalasia", ["Genovia", "Arendelle", "Far Far Away"]),
        Q(2, "Who directed 'Pretty Woman,' 'Runaway Bride' and 'The Princess Diaries'?", "Garry Marshall", ["Rob Reiner", "Nancy Meyers", "Ron Howard"]),
        Q(2, "Who plays Jennifer Lopez's love interest in 'The Wedding Planner'?", "Matthew McConaughey", ["Gerard Butler", "Patrick Dempsey", "Paul Rudd"]),
        Q(2, "Who played Mr. Darcy in the 1995 BBC 'Pride and Prejudice'?", "Colin Firth", ["Hugh Grant", "Jeremy Northam", "Rupert Penry-Jones"], "He later played Mark Darcy in 'Bridget Jones's Diary.'"),
        Q(2, "'Twilight' is set in which small Washington town?", "Forks", ["Port Angeles", "Aberdeen", "Leavenworth"]),
        Q(2, "In '13 Going on 30,' what makes Jenna's wish come true?", "Wishing dust", ["A fortune-teller machine", "A shooting star", "A birthday candle"]),
        Q(2, "In 'Maid in Manhattan,' J.Lo falls for a Senate candidate played by whom?", "Ralph Fiennes", ["Hugh Grant", "Colin Firth", "Jude Law"]),
        Q(2, "Who wrote the screenplay for 'When Harry Met Sally...'?", "Nora Ephron", ["Nancy Meyers", "Amy Heckerling", "Diablo Cody"]),
        Q(2, "Nick and Charlie are the couple at the heart of which Netflix series?", "Heartstopper", ["Sex Education", "Young Royals", "Never Have I Ever"]),
        Q(2, "In 'Emily in Paris,' Emily's handsome downstairs neighbor Gabriel is a what?", "Chef", ["Photographer", "Architect", "Sommelier"]),
        Q(2, "'Love & Basketball' (2000) stars Sanaa Lathan and whom?", "Omar Epps", ["Taye Diggs", "Morris Chestnut", "Larenz Tate"]),
        Q(2, "Cher won her Best Actress Oscar for which rom-com?", "Moonstruck", ["Mermaids", "Mask", "Tea with Mussolini"]),
        Q(2, "In 'Legally Blonde,' Elle's chihuahua is named what?", "Bruiser", ["Tinkerbell", "Princess", "Peanut"]),
        Q(2, "Who wrote 'Four Weddings,' 'Notting Hill' and 'Love Actually'?", "Richard Curtis", ["Nick Hornby", "Mike Newell", "Stephen Fry"]),
        Q(2, "'Sleepless in Seattle' pays loving tribute to which 1957 film?", "An Affair to Remember", ["Roman Holiday", "Sabrina", "Brief Encounter"]),
        Q(2, "In 'Little Women,' Laurie ends up marrying which March sister?", "Amy", ["Jo", "Meg", "Beth"]),
        Q(2, "Who voices the gossip writer Lady Whistledown in 'Bridgerton'?", "Julie Andrews", ["Judi Dench", "Maggie Smith", "Emma Thompson"]),
        Q(2, "Which rom-com beat 'Saving Private Ryan' for Best Picture?", "Shakespeare in Love", ["As Good as It Gets", "Notting Hill", "Life Is Beautiful"]),
        Q(2, "'Anyone But You' (2023) is loosely based on which Shakespeare play?", "Much Ado About Nothing", ["Twelfth Night", "As You Like It", "The Tempest"]),
        Q(2, "In 'Notting Hill,' who plays William's scruffy flatmate Spike?", "Rhys Ifans", ["Hugh Bonneville", "Tim McInnerny", "James Purefoy"]),
        Q(2, "In 'Say Anything,' which song blasts from Lloyd's boombox?", "In Your Eyes", ["Don't You (Forget About Me)", "Every Breath You Take", "Take My Breath Away"]),
        Q(2, "In 'Bridget Jones's Diary,' Hugh Grant plays which cad?", "Daniel Cleaver", ["Mark Darcy", "George Wickham", "John Willoughby"]),
        Q(2, "In 'You've Got Mail,' Kathleen's online screen name is what?", "Shopgirl", ["Bookworm", "NY152", "Mailgirl"], "Joe Fox signs on as NY152."),
        Q(2, "In 'Letters to Juliet,' Sophie finds a decades-old love letter in which city?", "Verona", ["Venice", "Florence", "Siena"]),
        Q(2, "'Love means never having to say you're sorry' comes from which 1970 film?", "Love Story", ["The Way We Were", "Summer of '42", "Romeo and Juliet"]),

        Q(3, "In 'Serendipity,' Sara writes her number inside which novel?", "Love in the Time of Cholera", ["The English Patient", "Wuthering Heights", "Doctor Zhivago"], "Jonathan writes his on a five-dollar bill, and both go out into the world."),
        Q(3, "In 'Kate & Leopold,' Leopold tumbles into the present from which year?", "1876", ["1888", "1901", "1865"], "He falls through a time portal by the Brooklyn Bridge, then still being built."),
        Q(3, "'Somewhere in Time' (1980) was filmed at the Grand Hotel on which island?", "Mackinac Island", ["Nantucket", "Martha's Vineyard", "Catalina Island"], "Christopher Reeve's playwright wills himself back to the hotel in 1912."),
        Q(3, "In Gaskell's 'North and South,' Margaret Hale falls for which mill owner?", "John Thornton", ["Henry Lennox", "Robert Moore", "Nicholas Higgins"], "Richard Armitage played Thornton in the 2004 BBC adaptation."),
        Q(3, "In 'Jane Eyre,' Mr. Rochester's secret wife is named what?", "Bertha Mason", ["Blanche Ingram", "Adèle Varens", "Grace Poole"], "Jean Rhys told her story in the 1966 prequel 'Wide Sargasso Sea.'"),
        Q(3, "In 'Bringing Up Baby,' what kind of animal is Baby?", "A leopard", ["A tiger", "A lion cub", "A cheetah"], "Cary Grant plays a paleontologist chasing a missing dinosaur bone."),
        Q(3, "'The Philadelphia Story' was remade as which 1956 musical?", "High Society", ["Kiss Me Kate", "Gigi", "Funny Face"], "It was Grace Kelly's final film, released three months after her royal wedding."),
        Q(3, "In 'Pillow Talk' (1959), Doris Day and Rock Hudson share a what?", "Party line", ["Hotel suite", "Taxi", "Mailbox"], "It won the Oscar for its original story and screenplay."),
        Q(3, "In 'Sense and Sensibility,' Marianne Dashwood marries whom?", "Colonel Brandon", ["John Willoughby", "Edward Ferrars", "Mr. Palmer"], "Alan Rickman played Brandon in the 1995 film."),
        Q(3, "Stephenie Meyer says 'Twilight' began with what?", "A dream", ["A diary entry", "A painting", "A song lyric"], "She dreamed of a girl and a vampire in a meadow on June 2, 2003."),
        Q(3, "'Before Midnight' (2013) finds Jesse and Céline on holiday in which country?", "Greece", ["Italy", "Spain", "Croatia"], "It's the third film in Richard Linklater's 'Before' trilogy."),
        Q(3, "In 'You've Got Mail,' Joe Fox's dog is named what?", "Brinkley", ["Baxter", "Barkley", "Bingley"], "Joe calls for Brinkley in the final scene in Riverside Park."),
        Q(3, "'Mamma Mia!' (2008) was filmed mainly on which Greek island?", "Skopelos", ["Santorini", "Mykonos", "Corfu"], "In the film, the island is the fictional Kalokairi."),
        Q(3, "In 'The Notebook,' how many letters does Noah write Allie?", "365", ["52", "100", "1,000"], "One a day for a year; Allie's mother hid every one."),
        Q(3, "In 'Casablanca,' Ilsa's husband is named what?", "Victor Laszlo", ["Louis Renault", "Heinrich Strasser", "Signor Ferrari"], "Paul Henreid played the Czech resistance leader."),
        Q(3, "In 'Brief Encounter' (1945), where do Laura and Alec first meet?", "A railway station", ["A hospital", "A cinema", "A hotel lobby"], "He removes a bit of grit from her eye in the station refreshment room."),
        Q(3, "Who plays the older Allie in 'The Notebook'?", "Gena Rowlands", ["Joanne Woodward", "Ellen Burstyn", "Shirley MacLaine"], "The film's director, Nick Cassavetes, is her son."),
        Q(3, "'The Big Sick' was co-written by Kumail Nanjiani and whom?", "Emily V. Gordon", ["Zoe Kazan", "Mindy Kaling", "Greta Gerwig"], "Their script, based on how they met, was nominated for an Oscar."),
        Q(3, "Which 1997 rom-com won both lead acting Oscars?", "As Good as It Gets", ["Jerry Maguire", "My Best Friend's Wedding", "Good Will Hunting"], "Jack Nicholson and Helen Hunt both took home Oscars."),
        Q(3, "Bridget Jones first appeared in a column in which newspaper?", "The Independent", ["The Guardian", "The Times", "The Daily Telegraph"], "Helen Fielding's column began in February 1995 and became a novel in 1996."),
        Q(3, "Who took Bogart's role as Linus in the 1995 remake of 'Sabrina'?", "Harrison Ford", ["Kevin Costner", "Richard Gere", "Tom Hanks"], "Greg Kinnear played David, William Holden's part in the 1954 original."),
        Q(3, "In 'Cyrano de Bergerac,' Cyrano writes Roxane's love letters for whom?", "Christian", ["De Guiche", "Ragueneau", "Le Bret"], "Steve Martin updated Rostand's 1897 play as 'Roxanne' in 1987."),
        Q(3, "In David Nicholls's 'One Day,' Em and Dex are revisited on which date each year?", "July 15", ["July 4", "June 21", "August 1"], "It's St. Swithin's Day, the day they meet at graduation in 1988."),
        Q(3, "Harry and Sally first meet sharing a ride from which school?", "University of Chicago", ["Northwestern University", "Columbia University", "Yale University"], "They make the drive to New York in 1977."),
        Q(3, "In 'Pretty Woman,' Edward flies Vivian to San Francisco to see which opera?", "La Traviata", ["Carmen", "Madama Butterfly", "La Bohème"], "Verdi's opera is also about a courtesan who falls in love."),
        Q(3, "In 'Past Lives' (2023), Nora's childhood sweetheart is named what?", "Hae Sung", ["Arthur", "Min-ho", "Jun-seo"], "Celine Song's debut feature was nominated for Best Picture."),
        Q(3, "Which film ends with the line 'Well, nobody's perfect'?", "Some Like It Hot", ["The Apartment", "Sabrina", "The Seven Year Itch"], "Joe E. Brown says it to Jack Lemmon's Daphne."),
        Q(3, "Which 1960 Billy Wilder romantic comedy won Best Picture?", "The Apartment", ["Sabrina", "Pillow Talk", "Irma la Douce"], "Jack Lemmon and Shirley MacLaine star as a lonely clerk and an elevator operator."),
    ]
}
