import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let skincareExtra: [QSpec] = [
        Q(1, "What does SPF stand for?", "Sun protection factor", ["Skin protection formula", "Solar filter percentage", "Sun-proof finish"]),
        Q(1, "Which UV rays are the main cause of sunburn?", "UVB", ["UVA", "UVC", "Infrared"], "Easy way to remember: UVB for burning, UVA for aging."),
        Q(1, "In a morning skincare routine, where does sunscreen go?", "Last, after moisturizer", ["First, before cleanser", "Right after toner", "Under your serum"]),
        Q(1, "The usual rule for layering skincare is what?", "Thinnest to thickest", ["Thickest to thinnest", "Oils first, then water", "Creams before serums"]),
        Q(1, "'Broad spectrum' on a sunscreen means it does what?", "Guards against UVA and UVB", ["Stays on in water", "Suits all skin types", "Lasts all day"]),
        Q(1, "What does 'cruelty-free' on a beauty label mean?", "Not tested on animals", ["No animal ingredients", "No harsh chemicals", "Fair-trade sourced"]),
        Q(1, "A classic French manicure has what look?", "White tips on a pink base", ["Red nails, gold tips", "One glitter accent nail", "Two-tone split nails"]),
        Q(1, "In beauty talk, what is a 'dupe'?", "A cheaper lookalike", ["A limited edition", "A travel-size sample", "A refill pod"]),
        Q(1, "Micellar water is mainly used to do what?", "Remove makeup and cleanse", ["Set makeup", "Self-tan", "Soothe sunburn"]),
        Q(1, "Classic nail polish remover is mostly which solvent?", "Acetone", ["Ammonia", "Glycerin", "Peroxide"]),
        Q(1, "Rare Beauty was founded by which singer?", "Selena Gomez", ["Ariana Grande", "Lady Gaga", "Halsey"], "Ariana founded r.e.m. beauty, Gaga Haus Labs, and Halsey about-face."),
        Q(1, "Hailey Bieber founded which skincare brand?", "Rhode", ["Glow Recipe", "Summer Fridays", "Tower 28"]),
        Q(1, "Dry shampoo works by soaking up what?", "Oil at the roots", ["Leftover water", "Old hairspray", "Hair dye"]),
        Q(1, "Which coffee ingredient turns up in eye creams to fight puffiness?", "Caffeine", ["Tannin", "Sugar", "Theanine"]),
        Q(1, "Aloe vera gel is a classic go-to for what?", "Sunburn", ["Split ends", "Chipped nails", "Dark circles"]),
        Q(1, "At a salon, what is a 'blowout'?", "A wash and blow-dry style", ["A bold haircut", "A bleach job", "A scalp treatment"]),
        Q(1, "Classic ombré hair fades in which direction?", "Dark roots to lighter ends", ["Light roots to darker ends", "Left side to right side", "Front to back"]),
        Q(1, "What is a sheet mask?", "A serum-soaked fabric mask", ["A peel-off clay mask", "A sleep mask for eyes", "A tinted face film"]),
        Q(1, "Sephora was founded in which country?", "France", ["Italy", "United States", "Belgium"]),
        Q(1, "'Perm' is short for what?", "Permanent wave", ["Permanent curl", "Permanent set", "Perma-style"]),
        Q(1, "Top Mary Kay sellers famously earn what?", "A pink Cadillac", ["A red Corvette", "A pink Mustang", "A white Mercedes"]),
        Q(1, "Which drugstore skincare brand is named for its ceramides?", "CeraVe", ["Cetaphil", "Aveeno", "Neutrogena"]),
        Q(1, "Nivea Creme comes in a tin of what color?", "Blue", ["Red", "Green", "White"]),
        Q(1, "Purple shampoo is meant to do what?", "Tone down brassy yellow", ["Dye hair lavender", "Add volume", "Fight dandruff"]),
        Q(1, "Microblading is a semi-permanent tattoo for what?", "Eyebrows", ["Lips", "Eyeliner", "Freckles"]),
        Q(1, "Threading removes hair using what?", "Twisted cotton thread", ["Hot wax", "Tweezers", "A laser"]),
        Q(1, "Gua sha, the stone face-scraping ritual, comes from which country?", "China", ["Japan", "India", "Thailand"]),
        Q(1, "Urban Decay is famous for which line of eyeshadow palettes?", "Naked", ["Nude", "Bare", "Buff"]),
        Q(2, "Mineral sunscreens use zinc oxide and what other filter?", "Titanium dioxide", ["Aluminum oxide", "Silicon dioxide", "Magnesium oxide"]),
        Q(2, "Which color corrector cancels out redness?", "Green", ["Purple", "Peach", "Orange"]),
        Q(2, "Glossier grew out of which beauty blog?", "Into the Gloss", ["Byrdie", "Temptalia", "Beautypedia"], "Emily Weiss started the blog in 2010 and launched Glossier in 2014."),
        Q(2, "Sensibio H2O, a cult micellar water, is from which French brand?", "Bioderma", ["La Roche-Posay", "Avène", "Vichy"]),
        Q(2, "'Ding dong, ___ calling!' was whose famous slogan?", "Avon", ["Mary Kay", "Revlon", "Maybelline"]),
        Q(2, "Who founded The Body Shop in 1976?", "Anita Roddick", ["Mary Quant", "Bobbi Brown", "Laura Mercier"], "She opened the first shop in Brighton, England."),
        Q(2, "Maybelline is named after whom?", "The founder's sister Mabel", ["The founder's wife May", "A silent-film star", "The founder's daughter"], "Tom Lyle Williams was 19 when he started the company in 1915."),
        Q(2, "Retin-A is a brand name for which retinoid?", "Tretinoin", ["Adapalene", "Tazarotene", "Retinaldehyde"]),
        Q(2, "Ceramides in skincare are what kind of molecule?", "Lipids", ["Proteins", "Sugars", "Minerals"], "They make up about half the fats in the skin's outer layer."),
        Q(2, "COSRX's cult essence is 96 percent what?", "Snail mucin", ["Rice water", "Green tea", "Aloe vera"]),
        Q(2, "'Cica' creams are built on which plant?", "Centella asiatica", ["Chamomile", "Calendula", "Witch hazel"]),
        Q(2, "Bakuchiol is popular as a plant-based alternative to what?", "Retinol", ["Vitamin C", "Hyaluronic acid", "Niacinamide"]),
        Q(2, "In makeup, what is 'baking'?", "Letting powder sit, then dusting it off", ["Warming foundation first", "Layering three bronzers", "Heat-setting your lashes"], "Drag performers made it famous long before YouTube tutorials did."),
        Q(2, "Tarte's cult concealer is called what?", "Shape Tape", ["Soft Matte", "Born This Way", "Fit Me"]),
        Q(2, "Which Korean brand makes the cult Lip Sleeping Mask?", "Laneige", ["Innisfree", "Sulwhasoo", "Missha"]),
        Q(2, "Clinique's famous yellow moisturizer is called what?", "Dramatically Different", ["Soft Cream", "Ultra Facial", "Skin Food"]),
        Q(2, "Which of these has the most fragrance oil?", "Eau de parfum", ["Eau de toilette", "Eau de cologne", "Body mist"]),
        Q(2, "In perfume, the scents you smell first are called what?", "Top notes", ["Base notes", "Heart notes", "Dry-down notes"]),
        Q(2, "Madam C.J. Walker built her fortune selling what?", "Hair care products", ["Lipstick", "Face powder", "Perfume"], "She's often cited as America's first self-made female millionaire."),
        Q(2, "Coffin-shaped nails are also called what?", "Ballerina", ["Stiletto", "Squoval", "Almond"]),
        Q(2, "Botox comes from a toxin made by which bacterium?", "Clostridium botulinum", ["Staphylococcus aureus", "E. coli", "Streptococcus"]),
        Q(2, "Most sunless tanners darken skin with which ingredient?", "Dihydroxyacetone (DHA)", ["Beta-carotene", "Melanin", "Caffeine"]),
        Q(2, "Dermatologists say the body needs about how much sunscreen?", "A shot glass full", ["A teaspoon", "A nickel-size dab", "Half a cup"], "That's roughly one ounce, per the American Academy of Dermatology."),
        Q(2, "Parabens are added to cosmetics as what?", "Preservatives", ["Fragrances", "Thickeners", "Colorants"]),
        Q(2, "Ruby Woo is a cult red lipstick from which brand?", "MAC", ["NARS", "Dior", "Revlon"]),
        Q(2, "What does the makeup brand name e.l.f. stand for?", "Eyes Lips Face", ["Eyes Lashes Face", "Easy Luxe Finish", "Every Little Flaw"]),
        Q(2, "What is 'tightlining'?", "Lining the upper waterline", ["Lining the lower lashes", "Drawing a sharp wing", "Outlining the lips"]),
        Q(2, "The short 'wedge' haircut was a 1976 craze thanks to which Olympian?", "Dorothy Hamill", ["Peggy Fleming", "Nadia Comăneci", "Olga Korbut"]),
        Q(3, "Clinique was born from a 1967 Vogue article with what title?", "Can Great Skin Be Created?", ["Is Beauty Only Skin Deep?", "The Science of Soft Skin", "Can Skin Be Taught?"], "Evelyn Lauder brought it to Estée; Clinique launched at Saks in 1968."),
        Q(3, "Kiehl's opened in New York in 1851 as what?", "An apothecary", ["A barbershop", "A perfumery", "A soap factory"], "It began as a pharmacy in the East Village; L'Oréal bought it in 2000."),
        Q(3, "Vaseline's inventor got the idea from residue on what?", "Oil wells", ["Whaling ships", "Candle molds", "Coal carts"], "Robert Chesebrough saw oil workers use the 'rod wax' on cuts in 1859."),
        Q(3, "Estée Lauder's first face creams came from which relative's recipes?", "Her uncle", ["Her mother", "Her husband", "Her grandmother"], "John Schotz was a Hungarian chemist who mixed creams behind the family home."),
        Q(3, "Revlon launched in 1932 selling just one product. What?", "Nail enamel", ["Red lipstick", "Face powder", "Cold cream"], "The L in Revlon comes from co-founder Charles Lachman."),
        Q(3, "Shiseido opened in Tokyo's Ginza in 1872 as what?", "A pharmacy", ["A kimono shop", "A tea house", "A soap works"], "It was Japan's first private Western-style pharmacy."),
        Q(3, "MAC Cosmetics was founded in 1984 in which city?", "Toronto", ["New York", "Montreal", "London"], "MAC stands for Make-Up Art Cosmetics."),
        Q(3, "Bobbi Brown launched her brand in 1991 with ten of what?", "Lipsticks", ["Foundations", "Eyeshadows", "Brushes"], "They debuted at Bergdorf Goodman and sold 100 on the first day."),
        Q(3, "In 2021, who became the first makeup artist made a Dame?", "Pat McGrath", ["Charlotte Tilbury", "Mary Greenwell", "Val Garland"], "She was honored for services to fashion, beauty, and diversity."),
        Q(3, "Huda Beauty launched in 2013 with which product?", "False lashes", ["Liquid lipstick", "A contour kit", "Setting powder"], "Sephora Dubai picked them up, and they quickly sold out."),
        Q(3, "Benefit Cosmetics was started in 1976 by whom?", "Twin sisters", ["A mother and daughter", "Two roommates", "A husband and wife"], "Jean and Jane Ford opened The Face Place in San Francisco."),
        Q(3, "NYX Cosmetics is named after a Greek goddess of what?", "Night", ["Beauty", "Dawn", "The moon"], "Toni Ko founded it in 1999, at age 25."),
        Q(3, "Dove launched its 'Campaign for Real Beauty' in which year?", "2004", ["1998", "2001", "2009"], "It began with research finding only 2% of women called themselves beautiful."),
        Q(3, "Oil of Olay was created in 1952 in which country?", "South Africa", ["Australia", "England", "Canada"], "Its name is a play on lanolin, a key ingredient."),
        Q(3, "The skin's outermost layer of dead cells is called what?", "Stratum corneum", ["Stratum basale", "Stratum lucidum", "Stratum spinosum"], "It's the barrier that moisturizers and ceramides work to protect."),
        Q(3, "Elizabethan-era 'ceruse' whitened faces using what?", "White lead", ["Chalk", "Rice flour", "Egg white"], "It was toxic, and damaged the very skin it was meant to perfect."),
        Q(3, "The white base makeup worn by geisha is called what?", "Oshiroi", ["Thanaka", "Beni", "Kumadori"], "The name comes from shiroi, Japanese for white."),
        Q(3, "Lush co-founder Mo Constantine invented what in 1989?", "The bath bomb", ["The sheet mask", "The clay mask", "The lip scrub"], "She was inspired by fizzing Alka-Seltzer tablets."),
        Q(3, "Vidal Sassoon's famous geometric 1960s bob is called what?", "The five-point cut", ["The pixie crop", "The Eton crop", "The shag"], "He created it on model Grace Coddington, later of Vogue."),
        Q(3, "Who created the 1-to-4 hair typing chart behind labels like '3A'?", "Andre Walker", ["Vidal Sassoon", "Chris McMillan", "Paul Mitchell"], "He was Oprah Winfrey's longtime hairstylist."),
        Q(3, "In the 1870s, Marcel Grateau's famous waves were made with what?", "Heated tongs", ["Pin curls", "Rollers", "A perm machine"], "The Paris hairdresser's Marcel wave stayed in style for decades."),
        Q(3, "Which company invented the cushion compact in 2008?", "Amorepacific", ["Shiseido", "L'Oréal", "Kao"], "It debuted as the IOPE Air Cushion."),
        Q(3, "BB cream was first created in the 1960s in which country?", "Germany", ["South Korea", "Japan", "France"], "A dermatologist made it to soothe skin after peels; Korea made it a hit."),
        Q(3, "Oud, prized in perfumery, comes from which wood?", "Agarwood", ["Sandalwood", "Cedarwood", "Rosewood"], "The fragrant resin forms when the tree reacts to a mold infection."),
        Q(3, "The Fitzpatrick scale sorts skin into six types by what?", "How it reacts to sun", ["How oily it is", "How thick it is", "Its pore size"], "Harvard dermatologist Thomas Fitzpatrick created it in 1975."),
        Q(3, "The Dyson Airwrap curls hair using which airflow principle?", "The Coandă effect", ["The Venturi effect", "The Magnus effect", "The Doppler effect"], "Air moving along a curved surface clings to it and pulls hair around the barrel."),
        Q(3, "U.S. 'water resistant' sunscreens must say 40 minutes or how many?", "80", ["60", "90", "120"], "Those are the only two times the FDA allows on the label."),
        Q(3, "Glycolic acid, the smallest AHA, is classically derived from which plant?", "Sugarcane", ["Apples", "Willow bark", "Oranges"], "Apples give malic acid, citrus gives citric, and willow bark salicylic."),
    ]
}
