import Foundation

extension HisWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let techExtra: [QSpec] = [
        Q(1, "What does USB stand for?", "Universal Serial Bus", ["Unified System Board", "Universal Signal Bridge", "United Serial Band"]),
        Q(1, "VPN stands for what?", "Virtual private network", ["Verified public node", "Virtual protected net", "Visual processing network"]),
        Q(1, "In a computer, CPU stands for what?", "Central processing unit", ["Core power unit", "Computer program utility", "Central port uplink"]),
        Q(1, "In a web address, 'www' stands for what?", "World Wide Web", ["Wide Web Window", "World Web Wire", "Wireless Web Works"]),
        Q(1, "Galaxy phones are made by which company?", "Samsung", ["LG", "Motorola", "Google"]),
        Q(1, "Microsoft's own line of laptops and tablets is called what?", "Surface", ["ThinkPad", "Spectre", "Chromebook"]),
        Q(1, "Apple's voice assistant is called what?", "Siri", ["Alexa", "Cortana", "Bixby"]),
        Q(1, "Saving files 'to the cloud' means storing them where?", "On servers over the internet", ["On your phone's own chip", "On a USB stick", "On a home backup drive"]),
        Q(1, "On a Windows PC, Ctrl+Z does what?", "Undo", ["Redo", "Copy", "Paste"]),
        Q(1, "In 2023, the iPhone 15 switched to which charging port?", "USB-C", ["Lightning", "Micro-USB", "MagSafe"], "Apple made the change after an EU rule requiring a common charger."),
        Q(1, "ChatGPT was made by which company?", "OpenAI", ["Google", "Microsoft", "Meta"], "It launched to the public on November 30, 2022."),
        Q(1, "GoPro is best known for making what?", "Action cameras", ["Headphones", "Smartwatches", "Phone cases"]),
        Q(1, "Ransomware does what to your computer?", "Locks your files until you pay", ["Floods it with pop-up ads", "Records what you type", "Mines crypto in secret"]),
        Q(1, "The 'Blue Screen of Death' is what?", "A Windows crash screen", ["A Mac startup screen", "A TV with no signal", "A phone's dead display"]),
        Q(1, "A gigabyte is roughly how many megabytes?", "1,000", ["10", "100", "1,000,000"]),
        Q(1, "Amazon started out selling only what?", "Books", ["CDs", "Electronics", "Toys"], "Jeff Bezos launched it in 1995 as 'Earth's Biggest Bookstore.'"),
        Q(1, "How many bits make one byte?", "8", ["4", "10", "16"]),
        Q(1, "What is a CAPTCHA for?", "Telling humans from bots", ["Blocking pop-up ads", "Speeding up page loads", "Saving your password"]),
        Q(1, "Tweets were first limited to how many characters?", "140", ["100", "160", "280"], "Twitter doubled the limit to 280 in 2017."),
        Q(1, "On old Nokia phones, which game had you steer a growing line?", "Snake", ["Tetris", "Pong", "Space Impact"]),
        Q(1, "In 2011, IBM's Watson computer won which TV game show?", "Jeopardy!", ["Wheel of Fortune", "Family Feud", "Who Wants to Be a Millionaire"], "It beat champions Ken Jennings and Brad Rutter."),
        Q(1, "Which company made the Walkman?", "Sony", ["Panasonic", "Toshiba", "JVC"], "The first Walkman, the TPS-L2, went on sale in 1979."),
        Q(1, "The 'Save' icon in many apps is a picture of what?", "A floppy disk", ["A CD", "A hard drive", "A USB stick"]),
        Q(1, "In the 1980s tape wars, VHS beat which rival format?", "Betamax", ["LaserDisc", "8-track", "MiniDisc"], "Sony's Betamax came out in 1975, a year before JVC's VHS."),
        Q(1, "AOL's famous voice greeting was 'You've got' what?", "Mail", ["Messages", "Letters", "Email"], "Elwood Edwards recorded it in his living room in 1989 and was paid $200."),
        Q(1, "Netflix, founded in 1997, started out as what kind of business?", "DVD rentals by mail", ["A video store chain", "A cable channel", "A movie ticket app"], "It didn't start streaming until 2007."),
        Q(1, "On an internet speed test, 'ping' measures what?", "Response delay", ["Download speed", "Upload speed", "Signal strength"]),
        Q(1, "A surge protector guards your gadgets against what?", "Voltage spikes", ["Power outages", "Hackers", "Overheating"]),
        Q(2, "The '.com' in web addresses originally stood for what?", "Commercial", ["Company", "Computer", "Communication"]),
        Q(2, "The 'S' in 'https' means the connection is what?", "Secure (encrypted)", ["Streaming", "Shared", "Server-based"]),
        Q(2, "The word 'emoji' comes from which language?", "Japanese", ["Chinese", "Korean", "English"], "It means 'picture character' and has nothing to do with 'emotion.'"),
        Q(2, "Who invented the World Wide Web?", "Tim Berners-Lee", ["Vint Cerf", "Marc Andreessen", "Bill Gates"], "He proposed it in 1989 while working at CERN."),
        Q(2, "Google's name plays on 'googol,' a 1 followed by how many zeros?", "100", ["10", "1,000", "1 million"]),
        Q(2, "Apple's famous '1984' ad for the Macintosh aired during what?", "The Super Bowl", ["The Oscars", "The World Series", "The Olympics"], "Ridley Scott, fresh off 'Blade Runner,' directed it."),
        Q(2, "Which box links your home to your internet provider's line?", "The modem", ["The router", "The switch", "The range extender"]),
        Q(2, "Next to 2.4 GHz, 5 GHz Wi-Fi is faster but has what drawback?", "Shorter range", ["More interference", "Weaker security", "Needs a special cable"]),
        Q(2, "Private or incognito browsing hides your history from whom?", "Others using the same device", ["Your internet provider", "The sites you visit", "Your office network"]),
        Q(2, "Alan Turing helped crack which German code in World War II?", "Enigma", ["Purple", "Navajo", "Playfair"], "He worked at Bletchley Park, Britain's wartime codebreaking center."),
        Q(2, "Bill Gates co-founded Microsoft in 1975 with whom?", "Paul Allen", ["Steve Ballmer", "Steve Wozniak", "Gary Kildall"], "They started it in Albuquerque, New Mexico."),
        Q(2, "Google bought which site in 2006 for $1.65 billion?", "YouTube", ["Android", "Waze", "MySpace"]),
        Q(2, "In 2012, Facebook bought Instagram for how much?", "$1 billion", ["$100 million", "$5 billion", "$19 billion"], "Instagram had just 13 employees at the time."),
        Q(2, "Apple's first iPod (2001) promised how many songs in your pocket?", "1,000", ["100", "500", "10,000"]),
        Q(2, "BlackBerry phones came from which Canadian company?", "Research In Motion", ["Nortel", "Mitel", "Sierra Wireless"], "It renamed itself BlackBerry in 2013."),
        Q(2, "Which Windows version introduced the Start button?", "Windows 95", ["Windows 3.1", "Windows 98", "Windows XP"], "Its launch ads used the Rolling Stones' 'Start Me Up.'"),
        Q(2, "Most ultrawide monitors are sold in which aspect ratio?", "21:9", ["16:9", "4:3", "16:10"]),
        Q(2, "Android versions used to be nicknamed after what?", "Desserts", ["Robots", "Planets", "Dog breeds"], "Cupcake through Pie ran in alphabetical order until Android 10 dropped it."),
        Q(2, "In 2020, Apple began swapping Intel chips in Macs for its own. What was the first called?", "M1", ["A14", "G5", "X1"]),
        Q(2, "Tap-to-pay uses NFC. What does NFC stand for?", "Near-field communication", ["Network frequency code", "New fast charge", "Nearby file connection"]),
        Q(2, "The Y2K bug happened because computers stored years how?", "With only two digits", ["In binary", "As Roman numerals", "Counting from 1970"]),
        Q(2, "In 1997, IBM's Deep Blue beat which world chess champion?", "Garry Kasparov", ["Bobby Fischer", "Magnus Carlsen", "Anatoly Karpov"], "Kasparov had beaten an earlier version of the machine in 1996."),
        Q(2, "A standard 3.5-inch floppy disk held about how much?", "1.44 MB", ["144 KB", "14.4 MB", "700 MB"]),
        Q(2, "Active noise-canceling headphones work by doing what?", "Playing opposite sound waves", ["Sealing the ear canal", "Turning down the music", "Filtering out high pitches"]),
        Q(2, "The first text message ever sent, in 1992, said what?", "Merry Christmas", ["Hello world", "Happy New Year", "Can you read this?"], "Engineer Neil Papworth sent it from a computer to a Vodafone colleague's phone."),
        Q(2, "Microsoft's Cortana assistant is named after a character from which game?", "Halo", ["Mass Effect", "Portal", "StarCraft"]),
        Q(2, "In Excel, a cell full of '#####' usually means what?", "The column is too narrow", ["The formula has an error", "The data is hidden", "The cell is locked"]),
        Q(2, "What is thermal paste for in a PC?", "Moving heat from chip to cooler", ["Gluing the chip in place", "Insulating the wiring", "Blocking static shocks"]),
        Q(3, "Who sent the first network email and picked '@' for the address?", "Ray Tomlinson", ["Vint Cerf", "Tim Berners-Lee", "Marc Andreessen"], "He did it on ARPANET in 1971, choosing @ because it wasn't used in usernames."),
        Q(3, "Which 1993 web browser from the University of Illinois set off the web boom?", "Mosaic", ["Netscape Navigator", "Internet Explorer", "Opera"], "Co-author Marc Andreessen went on to co-found Netscape."),
        Q(3, "Before it was Google, Page and Brin's search engine was called what?", "BackRub", ["PageRank", "WebCrawler", "Stanford Search"], "It was named for how it analyzed the web's 'back links.'"),
        Q(3, "In 1976, the Apple I went on sale for what price?", "$666.66", ["$499.99", "$999.99", "$1,298"], "Wozniak said he simply liked repeating digits."),
        Q(3, "Microsoft bought which company in 2016 for about $26 billion?", "LinkedIn", ["Skype", "GitHub", "Nokia's phone unit"], "It was Microsoft's biggest deal until Activision Blizzard in 2023."),
        Q(3, "Twitter's bird logo was nicknamed Larry after which Larry?", "Larry Bird", ["Larry Page", "Larry Ellison", "Larry King"], "The name honored the Boston Celtics legend."),
        Q(3, "Who invented the computer mouse?", "Douglas Engelbart", ["Alan Kay", "Steve Jobs", "Ivan Sutherland"], "The first prototype, built with engineer Bill English, had a wooden shell."),
        Q(3, "The Mac's point-and-click look drew on work at which research lab?", "Xerox PARC", ["Bell Labs", "IBM Research", "MIT Media Lab"], "Steve Jobs toured PARC in 1979 and saw its graphical interface."),
        Q(3, "YouTube's first video, 'Me at the zoo,' shows its maker in front of what?", "Elephants", ["Giraffes", "Penguins", "Lions"], "Co-founder Jawed Karim posted it from the San Diego Zoo on April 23, 2005."),
        Q(3, "Microsoft Office's paperclip helper, Clippy, was officially named what?", "Clippit", ["Paperclip Pete", "Clipster", "Mr. Clip"], "It first popped up in Office 97."),
        Q(3, "The Java programming language was originally called what?", "Oak", ["Pine", "Elm", "Cedar"], "It was named for an oak tree outside creator James Gosling's office."),
        Q(3, "ENIAC, finished in 1945, was built to calculate what?", "Artillery firing tables", ["Census results", "German code keys", "Moon rocket paths"], "It weighed about 30 tons and filled a large room."),
        Q(3, "What does GPT in ChatGPT stand for?", "Generative Pre-trained Transformer", ["General Purpose Text", "Generative Program Tool", "Guided Prediction Technology"]),
        Q(3, "The MP3 format was largely developed at which German institute?", "Fraunhofer", ["Max Planck", "Helmholtz", "Leibniz"], "Engineers fine-tuned it on Suzanne Vega's a cappella song 'Tom's Diner.'"),
        Q(3, "Napster was co-founded in 1999 by Shawn Fanning and whom?", "Sean Parker", ["Mark Zuckerberg", "Jack Dorsey", "Kevin Systrom"], "Parker later became Facebook's first president."),
        Q(3, "In '1080p,' what does the 'p' stand for?", "Progressive", ["Pixels", "Picture", "Panel"], "Progressive scan draws every line of each frame; the 'i' in 1080i means interlaced."),
        Q(3, "In 1975, Kodak engineer Steven Sasson built the first what?", "Digital camera", ["Instant camera", "Camera phone", "Disposable camera"], "It weighed 8 pounds and took 23 seconds to record each image."),
        Q(3, "What was the first product ever scanned by a UPC barcode, in 1974?", "A pack of Juicy Fruit gum", ["A box of Tide", "A can of Campbell's soup", "A Hershey bar"], "It happened at a Marsh supermarket in Troy, Ohio."),
        Q(3, "What was the first .com domain ever registered?", "symbolics.com", ["ibm.com", "apple.com", "xerox.com"], "Computer maker Symbolics registered it on March 15, 1985."),
        Q(3, "Cambridge's Trojan Room webcam famously watched what?", "A coffee pot", ["A fish tank", "A parking lot", "A campus clock"], "Set up in 1991 to spare trips to an empty pot, it reached the web in 1993."),
        Q(3, "For 'Fantasia,' Walt Disney Studios bought eight of which early HP gadget?", "An audio oscillator", ["A film projector", "A microphone", "A loudspeaker"], "Hewlett and Packard started the company in a Palo Alto garage in 1939."),
        Q(3, "Apple's 1997 purchase of which company brought Steve Jobs back?", "NeXT", ["Pixar", "Be Inc.", "Palm"], "Apple paid more than $400 million for it."),
        Q(3, "A KVM switch lets you do what?", "Run several PCs from one keyboard", ["Split one monitor into three", "Boost Wi-Fi to a far room", "Charge several laptops at once"], "KVM stands for keyboard, video, mouse."),
        Q(3, "Amazon's Alexa was named partly as a nod to what?", "The Library of Alexandria", ["A Greek goddess", "A Roman empress", "A famous ship"], "Developers also liked that the hard 'x' is easy for a speaker to pick out."),
        Q(3, "Which Hollywood star co-patented a frequency-hopping radio system in 1942?", "Hedy Lamarr", ["Greta Garbo", "Marlene Dietrich", "Ingrid Bergman"], "She and composer George Antheil designed it to keep torpedo guidance from being jammed."),
        Q(3, "Nvidia's founders planned the company in 1992 at which restaurant chain?", "Denny's", ["IHOP", "Waffle House", "Bob's Big Boy"], "They met at a Denny's on Berryessa Road in San Jose."),
        Q(3, "VisiCalc, the 1979 'killer app' for the Apple II, was what kind of program?", "Spreadsheet", ["Word processor", "Database", "Video game"], "Dan Bricklin and Bob Frankston created it."),
        Q(3, "In 2010, a man paid how many bitcoins for two pizzas?", "10,000", ["100", "1,000", "100,000"], "Laszlo Hanyecz's May 22 purchase is celebrated as Bitcoin Pizza Day."),
    ]
}
