import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let weddingsExtra: [QSpec] = [
        Q(1, "A mimosa is sparkling wine and what?", "Orange juice", ["Peach purée", "Cranberry juice", "Grapefruit juice"]),
        Q(1, "What is the base spirit in a Bloody Mary?", "Vodka", ["Gin", "Tequila", "Rum"]),
        Q(1, "Eggs Benedict is topped with which sauce?", "Hollandaise", ["Béarnaise", "Béchamel", "Mornay"]),
        Q(1, "An Aperol Spritz is Aperol, Prosecco, and what?", "Soda water", ["Tonic water", "Ginger ale", "Lemonade"]),
        Q(1, "Which zodiac sign is the lion?", "Leo", ["Aries", "Sagittarius", "Taurus"]),
        Q(1, "Which zodiac sign is the bull?", "Taurus", ["Aries", "Capricorn", "Leo"]),
        Q(1, "A Christmas Day baby has which sun sign?", "Capricorn", ["Sagittarius", "Aquarius", "Pisces"]),
        Q(1, "Born on Halloween? Your sun sign is what?", "Scorpio", ["Libra", "Sagittarius", "Virgo"]),
        Q(1, "Your sun sign is set by your what?", "Birthday", ["Birth order", "Birthplace", "Blood type"]),
        Q(1, "What does the bride toss over her shoulder at the reception?", "Her bouquet", ["Her garter", "Her veil", "Her shoes"]),
        Q(1, "The ring bearer traditionally carries the rings on what?", "A small pillow", ["A silver tray", "A velvet box", "A basket"]),
        Q(1, "A 'save the date' is sent when?", "Before the formal invitation", ["With the thank-you notes", "After the ceremony", "The week of the wedding"]),
        Q(1, "An invitation with a 'plus-one' means what?", "You may bring a guest", ["Kids are welcome", "There are two meals", "A gift is expected"]),
        Q(1, "Stomping on a wrapped glass ends which kind of wedding?", "Jewish", ["Greek Orthodox", "Hindu", "Catholic"]),
        Q(1, "The person who leads the wedding ceremony is the what?", "Officiant", ["Usher", "Emcee", "Planner"]),
        Q(1, "Which color are wedding guests traditionally told not to wear?", "White", ["Navy", "Pink", "Green"]),
        Q(1, "A golden anniversary marks how many years?", "50", ["25", "40", "60"]),
        Q(1, "RSVP comes from which language?", "French", ["Italian", "Latin", "Spanish"]),
        Q(1, "Complete De Beers' 1947 slogan: 'A Diamond Is...'", "Forever", ["Priceless", "Timeless", "Everything"]),
        Q(1, "Diamonds are graded on cut, color, clarity, and what?", "Carat", ["Cost", "Crystal", "Class"]),
        Q(1, "In 1956, Grace Kelly married the prince of which country?", "Monaco", ["Liechtenstein", "Luxembourg", "Sweden"]),
        Q(1, "Harry and Meghan married in 2018 at which castle?", "Windsor Castle", ["Balmoral Castle", "Edinburgh Castle", "Leeds Castle"]),
        Q(1, "In 2025, Taylor Swift got engaged to which athlete?", "Travis Kelce", ["Patrick Mahomes", "Joe Burrow", "Jason Kelce"]),
        Q(1, "Beyoncé's 'Single Ladies' is subtitled 'Put a What on It'?", "Ring", ["Bow", "Lock", "Price"]),
        Q(1, "Whose 1960 recording of 'At Last' is a first-dance classic?", "Etta James", ["Aretha Franklin", "Ella Fitzgerald", "Nina Simone"]),
        Q(1, "Who played the dad in 1991's 'Father of the Bride'?", "Steve Martin", ["Chevy Chase", "Tom Hanks", "Billy Crystal"]),
        Q(1, "In 'My Big Fat Greek Wedding,' Dad cures everything with what?", "Windex", ["Olive oil", "Ouzo", "Lemon juice"]),
        Q(1, "In 'Friends,' Ross says whose name at the altar with Emily?", "Rachel", ["Monica", "Phoebe", "Julie"]),

        Q(2, "Kim Kardashian's 2011 marriage to which NBA player lasted 72 days?", "Kris Humphries", ["Lamar Odom", "Tristan Thompson", "Blake Griffin"]),
        Q(2, "In 2025, Jeff Bezos married Lauren Sánchez in which city?", "Venice", ["Rome", "Paris", "Monaco"]),
        Q(2, "Elizabeth Taylor married which actor twice?", "Richard Burton", ["Eddie Fisher", "Michael Wilding", "John Warner"]),
        Q(2, "Whose 1840 wedding popularized the white bridal gown?", "Queen Victoria", ["Queen Anne", "Marie Antoinette", "Empress Joséphine"]),
        Q(2, "Kate Middleton's engagement ring centers on what stone?", "A sapphire", ["A ruby", "An emerald", "A pink diamond"], "It was Princess Diana's ring first."),
        Q(2, "Princess Elizabeth married Philip in 1947 at which church?", "Westminster Abbey", ["St Paul's Cathedral", "St George's Chapel", "Canterbury Cathedral"]),
        Q(2, "Mendelssohn's 'Wedding March' was written for which play?", "A Midsummer Night's Dream", ["Much Ado About Nothing", "Romeo and Juliet", "Twelfth Night"]),
        Q(2, "The reception floor-filler 'Shout' (1959) is by whom?", "The Isley Brothers", ["The Temptations", "The Four Tops", "The Drifters"]),
        Q(2, "Which falls were billed the 'Honeymoon Capital of the World'?", "Niagara Falls", ["Victoria Falls", "Iguazu Falls", "Yosemite Falls"]),
        Q(2, "In '27 Dresses,' Katherine Heigl plays a perpetual what?", "Bridesmaid", ["Wedding planner", "Bride", "Florist"]),
        Q(2, "The original 'Say Yes to the Dress' is filmed at which shop?", "Kleinfeld", ["David's Bridal", "Vera Wang", "Bridals by Lori"]),
        Q(2, "A matron of honor is different from a maid of honor how?", "She's married", ["She's the bride's mother", "She's the groom's sister", "She's under 18"]),
        Q(2, "Which sign kicks off the zodiac year?", "Aries", ["Capricorn", "Aquarius", "Pisces"]),
        Q(2, "In astrology, which planet rules both Taurus and Libra?", "Venus", ["Mars", "Mercury", "Jupiter"]),
        Q(2, "Your rising sign is also called your what?", "Ascendant", ["Descendant", "Midheaven", "North Node"]),
        Q(2, "Which animal comes first in the Chinese zodiac?", "The rat", ["The ox", "The dragon", "The tiger"]),
        Q(2, "The traditional first-anniversary gift is what?", "Paper", ["Cotton", "Wood", "Tin"]),
        Q(2, "In a Jewish wedding, the canopy over the couple is called what?", "Chuppah", ["Ketubah", "Tallit", "Kippah"]),
        Q(2, "At a mehndi party, the bride's hands are decorated with what?", "Henna", ["Gold leaf", "Glitter", "Pearls"]),
        Q(2, "The Irish Claddagh ring shows two hands holding what?", "A crowned heart", ["A shamrock", "A Celtic knot", "A harp"]),
        Q(2, "The cake's top tier is traditionally saved for when?", "The first anniversary", ["The honeymoon", "The rehearsal dinner", "The day after"]),
        Q(2, "A 'black tie' dress code calls for men to wear what?", "A tuxedo", ["A tailcoat", "A dark suit", "A morning coat"]),
        Q(2, "A mermaid wedding gown flares out at about where?", "The knee", ["The waist", "The hips", "Mid-thigh"]),
        Q(2, "A short veil worn over the bride's face is called a what?", "Blusher", ["Cathedral", "Chapel", "Fingertip"]),
        Q(2, "A Kir Royale is Champagne with a liqueur of which fruit?", "Blackcurrant", ["Raspberry", "Peach", "Cherry"]),
        Q(2, "A French 75 mixes Champagne with which spirit?", "Gin", ["Vodka", "Rum", "Tequila"]),
        Q(2, "Which Champagne label is the driest?", "Brut Nature", ["Extra Dry", "Brut", "Demi-Sec"], "Despite the name, Extra Dry is sweeter than Brut."),
        Q(2, "Eggs Benedict with spinach instead of ham is called what?", "Eggs Florentine", ["Eggs Royale", "Eggs Chesapeake", "Eggs Parisienne"]),

        Q(3, "Tiffany's classic 1886 solitaire setting uses how many prongs?", "Six", ["Four", "Eight", "Three"], "It lifts the diamond above the band to let in more light."),
        Q(3, "Who wrote De Beers' 1947 line 'A Diamond Is Forever'?", "Frances Gerety", ["Mary Wells Lawrence", "Shirley Polykoff", "Helen Lansdowne"], "Ad Age named it the best slogan of the 20th century."),
        Q(3, "Who designed Jacqueline Bouvier's 1953 wedding gown?", "Ann Lowe", ["Oleg Cassini", "Hubert de Givenchy", "Christian Dior"], "The Black designer went uncredited in the coverage at the time."),
        Q(3, "Which store started the first bridal registry, in 1924?", "Marshall Field's", ["Macy's", "Tiffany & Co.", "Sears"], "Clerks tracked each couple's china, silver, and crystal picks in Chicago."),
        Q(3, "Charles and Camilla's 2005 civil wedding was held where?", "Windsor Guildhall", ["Westminster Abbey", "St Paul's Cathedral", "Kensington Palace"], "A blessing at St George's Chapel followed."),
        Q(3, "Which soap's 1981 Luke and Laura wedding drew 30 million viewers?", "General Hospital", ["Days of Our Lives", "All My Children", "Guiding Light"], "Elizabeth Taylor had a guest role in the episodes."),
        Q(3, "The first 'Bachelorette,' Trista Rehn, married whom in 2003?", "Ryan Sutter", ["Charlie Maher", "Bob Guiney", "Aaron Buerge"], "Their wedding aired as a TV special on ABC."),
        Q(3, "Elvis and Priscilla married in 1967 at which Las Vegas hotel?", "The Aladdin", ["The Sands", "The Flamingo", "Caesars Palace"], "The ceremony took about eight minutes."),
        Q(3, "Eloping English couples famously fled to which Scottish village?", "Gretna Green", ["Portree", "Pitlochry", "Braemar"], "Scotland let couples marry without parental consent; England did not."),
        Q(3, "The British cousin of the mimosa, born in 1921, is called what?", "Buck's Fizz", ["Pimm's Cup", "Kir Royale", "Black Velvet"], "It was created at Buck's Club, a gentlemen's club in London."),
        Q(3, "Opening Champagne with a sword is called what?", "Sabrage", ["Remuage", "Dégorgement", "Assemblage"], "The blade slides along the seam and snaps off the collar and cork."),
        Q(3, "In modern astrology, which planet rules Scorpio?", "Pluto", ["Saturn", "Neptune", "Uranus"], "Before Pluto's 1930 discovery, Mars had the job."),
        Q(3, "Astrology groups signs as cardinal, fixed, and what?", "Mutable", ["Lunar", "Angular", "Solar"], "Gemini, Virgo, Sagittarius, and Pisces are the mutable signs."),
        Q(3, "Which constellation gets called the '13th zodiac sign'?", "Ophiuchus", ["Orion", "Cassiopeia", "Andromeda"], "The Sun crosses it from about November 29 to December 17."),
        Q(3, "Britain's first newspaper horoscope, in 1930, was for whose birth?", "Princess Margaret", ["Princess Elizabeth", "Prince Charles", "Princess Anne"], "R.H. Naylor wrote it for the Sunday Express."),
        Q(3, "Which zodiac sign sits directly opposite Aries?", "Libra", ["Cancer", "Capricorn", "Scorpio"], "Opposite signs sit six apart on the wheel."),
        Q(3, "The Hindu wedding rite Saptapadi means how many steps?", "Seven", ["Three", "Five", "Nine"], "'Sapta' is Sanskrit for seven, one vow per step."),
        Q(3, "Greek Orthodox couples wear linked crowns called what?", "Stefana", ["Koufeta", "Koumbaroi", "Kouloures"], "A ribbon joins the two crowns."),
        Q(3, "In Hispanic weddings, las arras are how many coins?", "Thirteen", ["Seven", "Twelve", "Twenty-one"], "The groom pours them into the bride's hands as a pledge to provide."),
        Q(3, "The two-handled Scottish cup couples share is called a what?", "Quaich", ["Luckenbooth", "Sgian-dubh", "Ceilidh"], "A luckenbooth is a Scottish love-token brooch."),
        Q(3, "At a German Polterabend, guests smash what for luck?", "Porcelain", ["Glassware", "Mirrors", "Walnuts"], "Glass is avoided, and the couple sweeps up the shards together."),
        Q(3, "The Jewish marriage contract is called what?", "Ketubah", ["Chuppah", "Mezuzah", "Tallit"], "Many couples frame it as art for their home."),
        Q(3, "A china anniversary traditionally marks how many years?", "20", ["15", "12", "35"], "Crystal marks the 15th and coral or jade the 35th."),
        Q(3, "The traditional 10th anniversary gift is made of what?", "Tin", ["Wood", "Crystal", "Leather"], "Aluminum is the usual modern stand-in."),
        Q(3, "Bridal house Pronovias was founded in which country?", "Spain", ["Italy", "France", "Portugal"], "Its roots go back to a Barcelona shop opened in 1922."),
        Q(3, "Meghan Markle's 2018 wedding dress came from which house?", "Givenchy", ["Dior", "Chanel", "Valentino"], "Clare Waight Keller designed it, Givenchy's first female artistic director."),
        Q(3, "Pachelbel, of the wedding favorite 'Canon in D,' was born where?", "Germany", ["Austria", "Italy", "France"], "Johann Pachelbel was born in Nuremberg in 1653."),
        Q(3, "Since Victorian times, British royal bridal bouquets include a sprig of what?", "Myrtle", ["Heather", "Rosemary", "Ivy"], "It's cut from a bush at Osborne House, Queen Victoria's Isle of Wight home."),
    ]
}
