import Foundation

extension HerWorld {
    /// Appended after the original 36, so existing question ids never shift.
    static let wellnessExtra: [QSpec] = [
        Q(1, "In yoga, Savasana is better known as which pose?", "Corpse Pose", ["Child's Pose", "Mountain Pose", "Tree Pose"]),
        Q(1, "SoulCycle classes are ridden on what?", "Stationary bikes", ["Rowing machines", "Treadmills", "Pilates reformers"]),
        Q(1, "Which hormone does the body release in darkness to help you fall asleep?", "Melatonin", ["Insulin", "Adrenaline", "Estrogen"]),
        Q(1, "Headspace is an app built mainly for what?", "Meditation", ["Running", "Calorie counting", "Journaling"]),
        Q(1, "Strava is a social app mostly for which athletes?", "Runners and cyclists", ["Swimmers and divers", "Golfers", "Weightlifters"]),
        Q(1, "Jane Fonda's best-selling 1982 home video taught what?", "An aerobics workout", ["Yoga", "Ballroom dancing", "Self-defense"]),
        Q(1, "Richard Simmons' classic workout videos were 'Sweatin' to the...' what?", "Oldies", ["Classics", "Hits", "Beat"]),
        Q(1, "What does REM stand for in REM sleep?", "Rapid Eye Movement", ["Restful Energy Mode", "Relaxed Early Motion", "Repeated Evening Movement"]),
        Q(1, "The yoga greeting 'namaste' comes from which ancient language?", "Sanskrit", ["Latin", "Tibetan", "Japanese"]),
        Q(1, "Acai, the berry in an acai bowl, is famously from which country?", "Brazil", ["Mexico", "Thailand", "Costa Rica"]),
        Q(1, "Matcha is a powdered form of what?", "Green tea", ["Black tea", "Coffee beans", "Cacao"]),
        Q(1, "The cozy lifestyle trend 'hygge' is most associated with which country?", "Denmark", ["Sweden", "Finland", "Iceland"]),
        Q(1, "Your skin makes which vitamin when exposed to sunlight?", "Vitamin D", ["Vitamin C", "Vitamin B12", "Vitamin K"]),
        Q(1, "Blue Zones are places known for people who do what?", "Live unusually long lives", ["Sleep unusually long", "Run marathons barefoot", "Eat only raw food"]),
        Q(1, "Shiatsu massage comes from which country?", "Japan", ["Thailand", "Korea", "India"]),
        Q(1, "Reflexology focuses mainly on pressure points in which body part?", "The feet", ["The scalp", "The back", "The neck"]),
        Q(1, "Aromatherapy relies on what?", "Essential oils", ["Sound bowls", "Hot stones", "Bath salts"]),
        Q(1, "The keto diet aims to put your body into which state?", "Ketosis", ["Glycolysis", "Thermogenesis", "Osmosis"]),
        Q(1, "The paleo diet is modeled on eating like whom?", "Stone Age hunter-gatherers", ["Ancient Romans", "Medieval monks", "Samurai warriors"]),
        Q(1, "Golden milk gets its color from which spice?", "Turmeric", ["Saffron", "Paprika", "Cinnamon"]),
        Q(1, "Lion's mane, reishi, and chaga are all types of what?", "Mushrooms", ["Seaweeds", "Root vegetables", "Flowers"]),
        Q(1, "Your body's internal 24-hour clock is called what?", "Circadian rhythm", ["Metabolic cycle", "Lunar rhythm", "REM cycle"]),
        Q(1, "A 5K race is about how many miles?", "3.1", ["2.5", "4", "5"]),
        Q(1, "Marie Kondo says to keep only the things that spark what?", "Joy", ["Memories", "Comfort", "Pride"]),
        Q(1, "Which sitcom gave the world the self-care motto 'Treat yo self'?", "Parks and Recreation", ["The Office", "Brooklyn Nine-Nine", "Community"]),
        Q(1, "In Japan, an onsen is what?", "A hot spring bath", ["A tea ceremony", "A meditation garden", "A massage table"]),
        Q(1, "The Blue Lagoon geothermal spa is in which country?", "Iceland", ["Norway", "New Zealand", "Canada"]),
        Q(1, "A couple's 'sleep divorce' means what?", "Sleeping apart", ["Going to bed angry", "Banning phones in bed", "Splitting the alarm"]),

        Q(2, "The name 'endorphin' blends 'endogenous' with which drug's name?", "Morphine", ["Codeine", "Aspirin", "Ephedrine"]),
        Q(2, "The Apple Watch's three Activity rings are Move, Exercise, and what?", "Stand", ["Sleep", "Breathe", "Steps"]),
        Q(2, "In kombucha brewing, what does SCOBY stand for?", "Symbiotic culture of bacteria and yeast", ["Sweet cultured organic brewing yeast", "Slow-cultured organic black tea yeast", "Starter culture of barley yeast"]),
        Q(2, "Oat milk brand Oatly comes from which country?", "Sweden", ["Denmark", "Ireland", "Canada"]),
        Q(2, "A hammam is also known as what kind of bath?", "A Turkish bath", ["A Roman bath", "A Finnish bath", "A Japanese bath"]),
        Q(2, "In yoga, Tadasana is which pose?", "Mountain Pose", ["Warrior Pose", "Tree Pose", "Cobra Pose"]),
        Q(2, "The Japanese practice 'shinrin-yoku' translates to what?", "Forest bathing", ["Moon gazing", "Silent walking", "Hot spring soaking"]),
        Q(2, "The word 'spa' comes from a town in which country?", "Belgium", ["Italy", "Switzerland", "Germany"], "Spa, in the Ardennes, has been famous for its mineral springs for centuries."),
        Q(2, "In Sweden, 'fika' is a break for what?", "Coffee and something sweet", ["A midday nap", "A cold plunge", "A walk outdoors"]),
        Q(2, "Who founded Lululemon in 1998?", "Chip Wilson", ["Phil Knight", "Kevin Plank", "Yvon Chouinard"]),
        Q(2, "Gwyneth Paltrow's Goop started in 2008 as what?", "A weekly email newsletter", ["A line of scented candles", "A cold-pressed juice bar", "A Los Angeles yoga studio"]),
        Q(2, "In 2018, Weight Watchers rebranded itself as what?", "WW", ["WellWatchers", "Watchers", "WeightWell"]),
        Q(2, "Spirulina, the green smoothie powder, is a type of what?", "Blue-green algae", ["Kelp", "Wheatgrass", "Moss"]),
        Q(2, "A traditional matcha whisk, or chasen, is carved from what?", "Bamboo", ["Birch", "Cherry wood", "Bone"]),
        Q(2, "Melatonin is made mainly in which gland?", "The pineal gland", ["The thyroid", "The pituitary gland", "The adrenal glands"]),
        Q(2, "The UN's International Day of Yoga falls on which date?", "June 21", ["March 20", "May 1", "September 22"], "It was first observed in 2015, on the longest day of the year in the Northern Hemisphere."),
        Q(2, "Which Pilates mat classic is named for its count of arm pumps?", "The Hundred", ["The Fifty", "The Thousand", "The Dozen"]),
        Q(2, "Tae Bo, the '90s workout craze, was created by whom?", "Billy Blanks", ["Richard Simmons", "Tony Little", "Chuck Norris"]),
        Q(2, "Which actress famously sold the ThighMaster on TV?", "Suzanne Somers", ["Jane Fonda", "Cindy Crawford", "Farrah Fawcett"]),
        Q(2, "Epsom salt is named after a spring town in which country?", "England", ["Germany", "France", "Austria"]),
        Q(2, "Which Japanese island is one of the original Blue Zones?", "Okinawa", ["Hokkaido", "Kyushu", "Shikoku"]),
        Q(2, "In the viral 12-3-30 treadmill workout, what is the 12?", "The incline percentage", ["Speed in mph", "Minutes of rest", "Laps to finish"]),
        Q(2, "Dry January began as a 2013 campaign in which country?", "The United Kingdom", ["Australia", "Canada", "Ireland"]),
        Q(2, "Whey protein is a byproduct of making what?", "Cheese", ["Butter", "Bread", "Beer"]),
        Q(2, "Pink Himalayan salt is mined mostly in which country?", "Pakistan", ["Nepal", "India", "Bhutan"]),
        Q(2, "The 'Scandinavian sleep method' gives a couple what?", "Two separate duvets", ["Two separate rooms", "A shared bedtime", "A cold bedroom"]),
        Q(2, "A morning person is often called which bird?", "A lark", ["An owl", "A robin", "A sparrow"]),
        Q(2, "Orangetheory Fitness is named after what?", "A heart-rate zone", ["A citrus diet", "Its founder's hometown", "A sunrise workout"]),

        Q(3, "The burpee is named after Royal H. Burpee, who was what?", "A physiologist", ["A Marine drill sergeant", "A football coach", "An Olympic gymnast"], "He devised it in 1939 as a quick fitness test for his Columbia PhD."),
        Q(3, "Jazzercise was founded in 1969 by whom?", "Judi Sheppard Missett", ["Jane Fonda", "Denise Austin", "Kathy Smith"], "She started it in Evanston, Illinois, as 'Jazz Dance for Fun and Fitness.'"),
        Q(3, "CrossFit's founder Greg Glassman started it in which California city?", "Santa Cruz", ["San Diego", "Venice Beach", "Sacramento"], "He and Lauren Jenai incorporated CrossFit in 2000 and opened a Santa Cruz gym in 2001."),
        Q(3, "Alo Yoga's name is an acronym for what?", "Air, Land, Ocean", ["Always Live Open", "Asana, Life, Om", "All Love Only"], "Childhood friends Danny Harris and Marco DeGeorge founded it in LA in 2007."),
        Q(3, "The Whole30 eating program launched in which year?", "2009", ["2003", "2012", "2015"], "Melissa and Dallas Hartwig created it; the book 'The Whole30' followed in 2015."),
        Q(3, "Chia seeds come from a plant in which family?", "Mint", ["Daisy", "Grass", "Legume"], "The chia plant, Salvia hispanica, is native to Mexico."),
        Q(3, "Yerba mate is sipped through a metal filter straw called what?", "A bombilla", ["A calabaza", "A chasen", "A mazagran"], "The hollow gourd it's served in is itself called a mate."),
        Q(3, "'Circadian' comes from Latin words meaning what?", "About a day", ["Around the sun", "Circle of sleep", "Night and day"], "Circa means 'about' and dies means 'day.'"),
        Q(3, "Brown noise, a popular sleep sound, is named after what?", "A botanist named Robert Brown", ["The color of dark soil", "Brown University", "A sound engineer named Brown"], "His 1827 study of particles jiggling in water gave us Brownian motion."),
        Q(3, "'Morning pages' come from which Julia Cameron book?", "The Artist's Way", ["Big Magic", "The Miracle Morning", "Bird by Bird"], "The practice is three pages of longhand writing first thing each morning."),
        Q(3, "K. Pattabhi Jois taught Ashtanga yoga from which Indian city?", "Mysore", ["Rishikesh", "Pune", "Chennai"], "He founded his Ashtanga Yoga Research Institute there in 1948."),
        Q(3, "A classic Bikram yoga room is heated to what temperature?", "105°F", ["85°F", "95°F", "115°F"], "The humidity is kept at 40 percent to mimic India's climate."),
        Q(3, "Joseph Pilates ran his New York studio with his partner, named what?", "Clara", ["Greta", "Helga", "Romana"], "Their studio sat at 939 Eighth Avenue in Manhattan."),
        Q(3, "The Megaformer is the machine behind which workout method?", "Lagree", ["Pure Barre", "Physique 57", "Gyrotonic"], "French-born trainer Sebastien Lagree built it as a tougher take on the Pilates reformer."),
        Q(3, "The Spinning indoor-cycling program was created by which cyclist?", "Johnny G", ["Greg LeMond", "Eddy Merckx", "Miguel Indurain"], "He moved his training indoors after a near-fatal close call on a night ride."),
        Q(3, "Jack LaLanne opened his first health club in 1936 in which city?", "Oakland", ["Los Angeles", "San Diego", "Chicago"], "He was 21 and paid $45 a month in rent."),
        Q(3, "Parkrun began in 2004 with 13 runners in which London park?", "Bushy Park", ["Hyde Park", "Richmond Park", "Regent's Park"], "Finish tokens were washers from a local hardware store."),
        Q(3, "The Romans called the English spa city of Bath what?", "Aquae Sulis", ["Aquae Calidae", "Aquae Romanae", "Deva Victrix"], "Sulis was a local goddess the Romans linked with Minerva."),
        Q(3, "Arianna Huffington founded which wellness company in 2016?", "Thrive Global", ["Goop", "Headspace", "Equinox"], "She left The Huffington Post that year to run it full time."),
        Q(3, "'Why We Sleep' (2017) was written by which neuroscientist?", "Matthew Walker", ["Andrew Huberman", "Peter Attia", "David Sinclair"], "Walker founded the Center for Human Sleep Science at UC Berkeley."),
        Q(3, "Uji, famed for top-grade matcha, is in which Japanese prefecture?", "Kyoto", ["Shizuoka", "Kagoshima", "Nara"], "Growers there pioneered shading tea bushes before harvest."),
        Q(3, "'Siesta' comes from Latin for what?", "The sixth hour", ["The quiet time", "The midday sun", "The short sleep"], "Romans counted hours from sunrise, so the sixth fell around noon."),
        Q(3, "Who invented the floating isolation tank in 1954?", "John C. Lilly", ["B.F. Skinner", "Carl Jung", "Ivan Pavlov"], "He built it at the National Institute of Mental Health."),
        Q(3, "Which Cornell psychologist is credited with coining 'power nap'?", "James Maas", ["William Dement", "Nathaniel Kleitman", "Charles Czeisler"], "He taught Cornell's intro psychology course for decades."),
        Q(3, "Which trainer created the P90X home workout series?", "Tony Horton", ["Shaun T", "Billy Blanks", "Jillian Michaels"], "P90X, short for Power 90 Extreme, followed his earlier Power 90 program."),
        Q(3, "Who co-founded Peloton and served as its first CEO?", "John Foley", ["Jack Dorsey", "Tony Hsieh", "Kevin Systrom"], "The company was founded in New York City in 2012."),
        Q(3, "The Swedish idea of 'lagom' means what?", "Just the right amount", ["Cozy togetherness", "Outdoor living", "Quiet solitude"], "The proverb 'lagom är bäst' means 'the right amount is best.'"),
        Q(3, "Oura, maker of the smart ring, was founded in which country?", "Finland", ["Sweden", "Israel", "Switzerland"], "It started in the city of Oulu in 2013."),
    ]
}
