import Foundation

/// Her World: the decks a partner who "knows his world" gets quizzed on.
enum HerWorld {
    static let decks: [Deck] = [skincare, fashion, romcoms, reality, divas, weddings, bookclub, wellness, gossip]

    static let skincare = Deck(id: "skincare", world: .hers, title: "Skincare & Beauty", tagline: "Serums, SPF, and why the order matters.", colorHex: "FF6FA5", specs: [
        Q(1, "Retinol is a form of which vitamin?", "Vitamin A", ["Vitamin C", "Vitamin E", "Vitamin K"]),
        Q(1, "Hyaluronic acid is loved for what?", "Holding moisture in the skin", ["Exfoliating dead skin", "Lightening skin", "Blocking the sun"]),
        Q(1, "What does a makeup primer do?", "Preps skin so makeup goes on smoothly and lasts", ["Cleans brushes", "Removes makeup", "Treats acne overnight"]),
        Q(1, "Contouring uses darker shades to do what?", "Create shadows that sculpt the face", ["Cover blemishes", "Add glitter", "Set powder"]),
        Q(1, "Which acid is the classic chemical exfoliant for acne-prone skin?", "Salicylic acid", ["Folic acid", "Citric acid", "Amino acid"]),
        Q(1, "What is a spoolie?", "A little brush for brows and lashes", ["A nail file", "A hair tie", "A face roller"]),
        Q(1, "A gel manicure is cured with what?", "UV or LED light", ["Hot water", "Steam", "A blow dryer"]),
        Q(1, "Hair color with lighter pieces painted on freehand is called what?", "Balayage", ["A perm", "Keratin", "A relaxer"]),
        Q(1, "What is double cleansing?", "An oil cleanser followed by a water-based one", ["Washing twice with the same soap", "Cleansing morning and night", "Using two washcloths"]),
        Q(1, "Vitamin C serum is mainly used for what?", "Brightening and evening out skin tone", ["Removing hair", "Curling lashes", "Setting makeup"]),
        Q(1, "'Non-comedogenic' on a label means what?", "Formulated not to clog pores", ["Fragrance-free", "Vegan", "Waterproof"]),
        Q(1, "Which is a famous makeup sponge brand?", "Beautyblender", ["Beautyblaster", "Glambubble", "Facefoam"]),
        Q(2, "Fenty Beauty launched in 2017 with how many foundation shades, a number that became the industry benchmark?", "40", ["12", "20", "100"]),
        Q(2, "'Glass skin' comes from which country's beauty culture?", "South Korea", ["France", "Brazil", "Italy"]),
        Q(2, "Niacinamide is a form of which vitamin?", "Vitamin B3", ["Vitamin A", "Vitamin D", "Vitamin K"]),
        Q(2, "Whose Great Lash mascara comes in the famous pink-and-green tube?", "Maybelline", ["CoverGirl", "L'Oréal", "Revlon"]),
        Q(2, "The '10-step routine' refers to which skincare tradition?", "Korean skincare", ["French pharmacy", "Ayurveda", "Hollywood glam"]),
        Q(2, "'Slugging' means sealing your skin overnight with what?", "Petroleum jelly", ["Honey", "Ice", "Rice water"]),
        Q(2, "The 'lipstick index' is the idea that in a downturn, what happens?", "Lipstick sales go up", ["Lipstick prices track oil", "Red lipstick predicts elections", "Lipstick sales collapse"], "Leonard Lauder of Estée Lauder coined it after 9/11."),
        Q(2, "A 'cat eye' is what?", "A winged eyeliner look", ["A lash-extension style", "A brow shape", "A contact lens"]),
        Q(2, "Which oil, from a tree native to Morocco, is a haircare favorite?", "Argan oil", ["Jojoba oil", "Tea tree oil", "Marula oil"]),
        Q(2, "In skincare, AHA stands for what?", "Alpha hydroxy acid", ["Advanced hydrating agent", "Anti-hyaluronic acid", "Active hair acid"]),
        Q(2, "Charlotte Tilbury's famous 'Pillow Talk' is a shade of what?", "Lip color", ["Foundation", "Perfume", "Bronzer"]),
        Q(2, "With lash extensions, a 'volume set' means what compared to 'classic'?", "Several fine lashes on each natural lash instead of one", ["Longer lashes only", "Colored lashes", "Bottom lashes only"]),
        Q(3, "Which AHA exfoliant was first made from bitter almonds?", "Mandelic acid", ["Glycolic acid", "Lactic acid", "Malic acid"], "Its name comes from 'Mandel,' German for almond."),
        Q(3, "On Asian sunscreens, the PA rating (PA++++) measures protection from what?", "UVA rays", ["UVB rays", "Blue light", "Infrared heat"], "SPF grades UVB; the Japanese PA scale grades UVA, from PA+ up to PA++++."),
        Q(3, "Squalane is named after which animal, its original source?", "Shark", ["Squid", "Snail", "Whale"], "Squalus is a genus of sharks; the compound was first found in shark liver oil."),
        Q(3, "The chemist who introduced SPF in 1974 founded which sun-care brand?", "Piz Buin", ["Coppertone", "Nivea", "Hawaiian Tropic"], "He named it for the Alpine peak where he got badly sunburned in 1938."),
        Q(3, "Whose Mascara-Matic popularized mascara in a tube with a built-in wand?", "Helena Rubinstein", ["Elizabeth Arden", "Estée Lauder", "Max Factor"], "Before it, most mascara was a hard cake you wet and brushed on."),
        Q(3, "Which Hollywood cosmetics pioneer popularized the word 'make-up'?", "Max Factor", ["Elizabeth Arden", "Estée Lauder", "Charles Revson"], "Until 1920 polite society said 'cosmetics'; 'make-up' was for the stage."),
        Q(3, "Differin went over the counter in the U.S. in 2016. Which retinoid is it?", "Adapalene", ["Tretinoin", "Tazarotene", "Isotretinoin"], "It was the first retinoid the FDA approved for over-the-counter acne use."),
        Q(3, "SK-II's signature ingredient, Pitera, was inspired by whose hands?", "Elderly sake brewers", ["Pearl divers", "Tea pickers", "Silk weavers"], "Researchers screened some 350 yeast strains to find the one behind it."),
        Q(3, "L'Oréal was founded in 1909 on which product?", "A hair dye", ["A face cream", "A lipstick", "A perfume"], "Chemist Eugène Schueller's first formula was a dye he called Auréale."),
        Q(3, "On ingredient labels, 'Butyrospermum parkii' is which ingredient?", "Shea butter", ["Cocoa butter", "Mango butter", "Beeswax"], "It comes from the nuts of the African shea tree."),
        Q(3, "Cold cream is credited to which ancient physician?", "Galen", ["Hippocrates", "Avicenna", "Dioscorides"], "His recipe blended rose water, beeswax, and almond or olive oil."),
        Q(3, "Hawaii's 2018 reef law banned sunscreens with oxybenzone and what?", "Octinoxate", ["Homosalate", "Octisalate", "Zinc oxide"], "Hawaii was the first U.S. state with such a ban; it took effect in 2021."),
    ])

    static let fashion = Deck(id: "fashion", world: .hers, title: "Fashion & Style", tagline: "Houses, hemlines, and the bag everyone knows.", colorHex: "9B5CFF", specs: [
        Q(1, "Which house uses the interlocking 'GG' logo?", "Gucci", ["Guess", "Givenchy", "Gap"]),
        Q(1, "What is a capsule wardrobe?", "A small set of pieces that all mix and match", ["Clothes stored in vacuum bags", "A rental subscription", "A wardrobe of only bags"]),
        Q(1, "What is haute couture?", "Custom high fashion made by hand for one client", ["Off-the-rack clothing", "Vintage clothing", "Sportswear"]),
        Q(1, "The Birkin bag is made by which house?", "Hermès", ["Prada", "Louis Vuitton", "Dior"]),
        Q(1, "What does ready-to-wear mean?", "Clothing sold in standard sizes rather than custom made", ["Clothes that need no ironing", "Second-hand clothes", "Clothes still with tags"]),
        Q(1, "What is a peplum?", "A short flared ruffle at the waist", ["A neckline", "A sleeve", "A heel"]),
        Q(1, "Who makes the Air Force 1 sneaker?", "Nike", ["Adidas", "Puma", "Reebok"]),
        Q(1, "Cashmere comes from which animal?", "Goats", ["Sheep", "Alpacas", "Rabbits"]),
        Q(1, "A classic trench coat is made of what?", "Cotton gabardine", ["Leather", "Wool felt", "Velvet"], "Burberry invented gabardine in 1879."),
        Q(1, "Anna Wintour is famous as the editor of which magazine?", "Vogue", ["Elle", "Harper's Bazaar", "Cosmopolitan"]),
        Q(1, "What is tulle?", "A fine stiff netting used in tutus and veils", ["A heavy wool", "A leather finish", "A type of button"]),
        Q(1, "'Wide-leg,' 'bootcut,' and 'skinny' describe what?", "Jean cuts", ["Hat brims", "Collar shapes", "Heel heights"]),
        Q(2, "The 1947 'New Look,' with a cinched waist and full skirt, came from whom?", "Christian Dior", ["Coco Chanel", "Yves Saint Laurent", "Cristóbal Balenciaga"]),
        Q(2, "Which house created 'Le Smoking,' the 1966 tuxedo for women?", "Yves Saint Laurent", ["Chanel", "Armani", "Versace"]),
        Q(2, "'Quiet luxury' means what?", "Understated, logo-free expensive clothing", ["Silent auctions", "Loud prints", "Fast fashion"]),
        Q(2, "The Met Gala raises money for what?", "The Met's Costume Institute", ["A film festival", "Milan Fashion Week", "A perfume launch"]),
        Q(2, "Who is known for the 1974 wrap dress?", "Diane von Furstenberg", ["Donna Karan", "Vera Wang", "Stella McCartney"]),
        Q(2, "Bottega Veneta's signature technique is what?", "Intrecciato woven leather", ["Quilted leather", "Monogram canvas", "Studded leather"]),
        Q(2, "What are kitten heels?", "Short slender heels, roughly one to two inches", ["Platform heels", "Wedges", "Block heels"]),
        Q(2, "Which fashion week opens the 'big four' each September?", "New York", ["London", "Milan", "Paris"]),
        Q(2, "What is a cold-shoulder top?", "A top with cutouts that bare the shoulders", ["A sleeveless turtleneck", "A cropped hoodie", "An unlined jacket"]),
        Q(2, "The classic Hermès silk scarf is what size?", "90 by 90 centimeters", ["50 by 50", "120 by 120", "70 by 70"]),
        Q(2, "Which house's Speedy bag was made famous by Audrey Hepburn?", "Louis Vuitton", ["Chanel", "Fendi", "Coach"]),
        Q(2, "Miu Miu is the sister brand of which house?", "Prada", ["Gucci", "Fendi", "Versace"], "It's Miuccia Prada's childhood nickname."),
        Q(3, "Who is considered the father of haute couture?", "Charles Frederick Worth", ["Paul Poiret", "Christian Dior", "Cristóbal Balenciaga"], "An Englishman, he opened his Paris house on the Rue de la Paix in 1858."),
        Q(3, "Hermès was founded in 1837 to make what?", "Harnesses for horses", ["Silk scarves", "Travel trunks", "Leather gloves"], "Its logo, a horse-drawn carriage, still nods to that harness-making start."),
        Q(3, "Before founding Gucci, Guccio Gucci worked at which London hotel?", "The Savoy", ["The Ritz", "Claridge's", "The Dorchester"], "He worked there as a teenager in 1899, then founded Gucci in Florence in 1921."),
        Q(3, "Grace Kelly famously used her Hermès bag to hide what?", "Her pregnancy", ["Her engagement ring", "A camera", "Her passport"], "A 1956 Life magazine photo made the bag famous, and it became the Kelly."),
        Q(3, "Chanel's historic Paris couture house is at which address?", "31 Rue Cambon", ["30 Avenue Montaigne", "24 Faubourg Saint-Honoré", "7 Rue de la Paix"], "It sits near the Hôtel Ritz, where Coco lived for decades."),
        Q(3, "Mary Quant said she named the miniskirt after what?", "Her favorite car, the Mini", ["A London nightclub", "A Beatles song", "Her pet poodle"], "Quant sold her designs at Bazaar, her boutique on King's Road."),
        Q(3, "Who was Jacqueline Kennedy's official couturier as First Lady?", "Oleg Cassini", ["Halston", "Hubert de Givenchy", "Oscar de la Renta"], "Dubbed her 'Secretary of Style,' he designed about 300 outfits for her."),
        Q(3, "Fendi's double-F logo was created by which designer?", "Karl Lagerfeld", ["Tom Ford", "Gianni Versace", "Valentino Garavani"], "He drew it in 1966 and designed for Fendi for more than 50 years."),
        Q(3, "What makes a pair of jeans 'selvedge' denim?", "Woven on a shuttle loom", ["Never washed after dyeing", "Blended with stretch fibers", "Dyed with natural indigo"], "The self-finished edge often shows a colored stripe inside the cuff."),
        Q(3, "Madeleine Vionnet is famous for pioneering what?", "The bias-cut dress", ["The wrap dress", "The shoulder pad", "The shirtwaist dress"], "She was the first to cut whole garments on the bias, not just trims."),
        Q(3, "Which is the oldest women's fashion magazine still publishing?", "Harper's Bazaar", ["Vogue", "Elle", "Marie Claire"], "It launched in New York in 1867, 25 years before Vogue."),
        Q(3, "Who founded the Met Gala in 1948?", "Eleanor Lambert", ["Diana Vreeland", "Anna Wintour", "Carmel Snow"], "The publicist also founded the International Best Dressed List."),
    ])

    static let romcoms = Deck(id: "romcoms", world: .hers, title: "Rom-Coms & Love Stories", tagline: "The lines, the leads, and the letters she never sent.", colorHex: "FF4D6D", specs: [
        Q(1, "In 'Notting Hill,' Julia Roberts plays a what?", "Famous actress", ["Bookshop owner", "Chef", "Lawyer"]),
        Q(1, "'Sleepless in Seattle' ends on top of which landmark?", "The Empire State Building", ["The Golden Gate Bridge", "The Space Needle", "The Statue of Liberty"]),
        Q(1, "Which Sandra Bullock rom-com is built on a fake engagement for a green card?", "The Proposal", ["Miss Congeniality", "Two Weeks Notice", "While You Were Sleeping"]),
        Q(1, "In 'Love Actually,' the cue-card scene plays out while carolers sing what?", "Silent Night", ["Jingle Bells", "O Holy Night", "Deck the Halls"]),
        Q(1, "Cher in 'Clueless' is based on which Jane Austen heroine?", "Emma", ["Elizabeth Bennet", "Anne Elliot", "Fanny Price"]),
        Q(1, "Who wrote 'The Fault in Our Stars'?", "John Green", ["Nicholas Sparks", "Colleen Hoover", "Emily Henry"]),
        Q(1, "In 'Mamma Mia!', how many possible dads does Sophie invite?", "Three", ["Two", "Four", "Five"]),
        Q(1, "'You've Got Mail' centers on rival what?", "Bookstores", ["Bakeries", "Flower shops", "Radio stations"]),
        Q(1, "Colleen Hoover's 'It Ends with Us' heroine is named what?", "Lily", ["Rose", "Daisy", "Violet"]),
        Q(1, "In 'How to Lose a Guy in 10 Days,' Kate Hudson writes for a what?", "Women's magazine", ["Newspaper", "Ad agency", "TV station"]),
        Q(1, "'Outlander' involves time travel to which country?", "Scotland", ["Ireland", "Wales", "France"]),
        Q(1, "Who wrote 'The Notebook'?", "Nicholas Sparks", ["John Green", "Danielle Steel", "Nora Roberts"]),
        Q(2, "In Emily Henry's 'Beach Read,' the romance writer is paired with a writer of what?", "Literary fiction", ["Horror", "Science fiction", "Poetry"]),
        Q(2, "Mr. Darcy's estate in 'Pride and Prejudice' is called what?", "Pemberley", ["Netherfield", "Longbourn", "Rosings"]),
        Q(2, "The famous deli scene in 'When Harry Met Sally' was filmed where?", "Katz's Delicatessen", ["Carnegie Deli", "Zabar's", "Russ & Daughters"]),
        Q(2, "Which publisher is synonymous with mass-market romance novels?", "Harlequin", ["Penguin", "Bantam", "Scholastic"]),
        Q(2, "In 'Bridgerton' season one, the Duke of Hastings is named what?", "Simon", ["Anthony", "Colin", "Benedict"]),
        Q(2, "'Red, White & Royal Blue' pairs a British prince with whom?", "The son of the U.S. president", ["A Broadway actor", "A footballer", "A journalist"]),
        Q(2, "In 'The Holiday,' the two women swap what?", "Homes", ["Jobs", "Cars", "Names"]),
        Q(2, "Captain Wentworth is the love interest in which Austen novel?", "Persuasion", ["Emma", "Mansfield Park", "Northanger Abbey"]),
        Q(2, "Who won the screenplay Oscar for 1995's 'Sense and Sensibility'?", "Emma Thompson", ["Kate Winslet", "Ang Lee", "Hugh Grant"]),
        Q(2, "In 'Crazy, Stupid, Love,' who plays the smooth ladies' man Jacob?", "Ryan Gosling", ["Steve Carell", "Bradley Cooper", "Ryan Reynolds"]),
        Q(2, "Sally Rooney's 'Normal People' is set mostly where?", "Ireland", ["Scotland", "England", "Wales"]),
        Q(2, "In 'The Princess Bride,' 'As you wish' really means what?", "I love you", ["Goodbye", "Thank you", "I'm sorry"]),
        Q(3, "Who directed 'When Harry Met Sally...'?", "Rob Reiner", ["Nora Ephron", "Penny Marshall", "Nancy Meyers"], "Rob Reiner's own mother, Estelle, delivers the line 'I'll have what she's having.'"),
        Q(3, "In 'Notting Hill,' William's bookshop specializes in what?", "Travel books", ["Rare first editions", "Cookbooks", "Children's books"], "The film's shop front is at 142 Portobello Road."),
        Q(3, "In 'Sleepless in Seattle,' Annie lives in which city?", "Baltimore", ["Boston", "Chicago", "Philadelphia"], "Annie is a reporter for The Baltimore Sun."),
        Q(3, "In 'You've Got Mail,' Kathleen Kelly's bookstore is called what?", "The Shop Around the Corner", ["Fox Books", "The Little Book Nook", "Storybook Lane"], "The name nods to the 1940 film 'The Shop Around the Corner,' an earlier take on the same story."),
        Q(3, "'Four Weddings and a Funeral' features a funeral poem by whom?", "W. H. Auden", ["T. S. Eliot", "Dylan Thomas", "Philip Larkin"], "Matthew, played by John Hannah, reads 'Funeral Blues' at Gareth's funeral."),
        Q(3, "In 'Love Actually,' the prime minister dances to which song?", "Jump (For My Love)", ["I'm So Excited", "Wake Me Up Before You Go-Go", "Dancing Queen"], "Hugh Grant has said filming the dance was 'absolute hell.'"),
        Q(3, "Audrey Hepburn won her Best Actress Oscar for which film?", "Roman Holiday", ["Breakfast at Tiffany's", "Sabrina", "My Fair Lady"], "She played Princess Ann, and it remained her only competitive Oscar win."),
        Q(3, "Which rom-com was the first film to win all five top Oscars?", "It Happened One Night", ["The Philadelphia Story", "Casablanca", "The Apartment"], "It swept Picture, Director, Actor, Actress, and Screenplay for 1934."),
        Q(3, "In 'Dirty Dancing,' Baby's real name is what?", "Frances", ["Penelope", "Lisa", "Margaret"], "She was named for Frances Perkins, the first woman in a U.S. Cabinet."),
        Q(3, "In 'Outlander,' Jamie Fraser's Scottish family estate is called what?", "Lallybroch", ["Castle Leoch", "Craigh na Dun", "Fraser's Ridge"], "Midhope Castle near Edinburgh stands in for Lallybroch on the show."),
        Q(3, "'She's the Man' updates which Shakespeare play?", "Twelfth Night", ["As You Like It", "Much Ado About Nothing", "A Midsummer Night's Dream"], "Viola's new school is Illyria, named for the play's setting."),
        Q(3, "'Before Sunrise' follows two strangers wandering which city overnight?", "Vienna", ["Paris", "Budapest", "Prague"], "Jesse and Céline reunite nine years later in Paris in 'Before Sunset.'"),
    ])

    static let reality = Deck(id: "reality", world: .hers, title: "Reality TV", tagline: "Roses, pods, villas, and the tribe that has spoken.", colorHex: "FF7A3D", specs: [
        Q(1, "On 'Survivor,' what is said when someone is voted out?", "The tribe has spoken", ["You're fired", "Please pack your knives", "Sashay away"]),
        Q(1, "'Sashay away' is the send-off on which show?", "RuPaul's Drag Race", ["Project Runway", "Top Chef", "Survivor"]),
        Q(1, "Heidi Klum's 'Project Runway' catchphrase was what?", "One day you're in, and the next day you're out", ["The tribe has spoken", "Pack your knives and go", "You're fired"]),
        Q(1, "'Please pack your knives and go' is from which show?", "Top Chef", ["Hell's Kitchen", "MasterChef", "Chopped"]),
        Q(1, "'Vanderpump Rules' spun off from which Real Housewives city?", "Beverly Hills", ["Orange County", "New York", "Atlanta"]),
        Q(1, "The Bachelor spin-off set at a beach resort with past contestants is called what?", "Bachelor in Paradise", ["Bachelor Island", "Bachelor Beach", "Love After Roses"]),
        Q(1, "Who said 'Kim, there's people that are dying'?", "Kourtney Kardashian", ["Kim Kardashian", "Khloé Kardashian", "Kris Jenner"]),
        Q(1, "Maddie Ziegler of 'Dance Moms' starred in music videos for which singer?", "Sia", ["Adele", "Lorde", "Halsey"]),
        Q(1, "On 'The Circle,' players communicate only through what?", "A social media app", ["Phone calls", "Letters", "Video chat"]),
        Q(1, "On 'Married at First Sight,' couples meet for the first time where?", "At the altar", ["At dinner", "On a plane", "In pods"]),
        Q(1, "'Below Deck' follows the crew of a what?", "Superyacht", ["Cruise ship", "Fishing boat", "Submarine"]),
        Q(1, "In 2022 'The Kardashians' moved from E! to which streamer?", "Hulu", ["Netflix", "HBO Max", "Peacock"]),
        Q(2, "'Scandoval' (2023) was a cheating scandal on which show?", "Vanderpump Rules", ["Love Island", "The Bachelor", "Selling Sunset"]),
        Q(2, "The famous table flip happened on which Real Housewives franchise?", "New Jersey", ["Atlanta", "New York", "Orange County"], "Teresa Giudice, season one finale."),
        Q(2, "Who hosts the U.S. version of 'The Traitors'?", "Alan Cumming", ["Andy Cohen", "Nick Cannon", "Jeff Probst"]),
        Q(2, "On 'Survivor,' the fire-making challenge decides what?", "The last spot in the final three", ["The overall winner", "Immunity at the merge", "Who goes to Exile Island"]),
        Q(2, "On 'Love Island,' a buzzing phone means someone shouts what?", "I've got a text!", ["You've got mail!", "Ring ring!", "Incoming!"]),
        Q(2, "On The Bachelor, 'Can I steal you for a second?' is used to do what?", "Pull the lead aside for one-on-one time", ["Ask for a rose", "Leave the show", "Ask for a date card"]),
        Q(2, "Before the Netflix reboot, 'Queer Eye' originally aired on which network?", "Bravo", ["MTV", "E!", "VH1"]),
        Q(2, "'The Hills' was a spin-off of which show?", "Laguna Beach", ["The O.C.", "Newport Harbor", "The Real World"]),
        Q(2, "On 'Too Hot to Handle,' the rules are enforced by a virtual assistant named what?", "Lana", ["Alexa", "Siri", "Cortana"]),
        Q(2, "The winner of 'RuPaul's Drag Race' is crowned what?", "America's Next Drag Superstar", ["Queen of the Runway", "Drag Idol", "Miss Congeniality"]),
        Q(2, "'The Real World' premiered on MTV in which year?", "1992", ["1985", "1999", "2003"]),
        Q(2, "Andy Cohen hosts which late-night Bravo show?", "Watch What Happens Live", ["Late Night Bravo", "The Andy Show", "After Hours"]),
        Q(3, "'Survivor' first aired as 'Expedition Robinson' in which country?", "Sweden", ["Norway", "Denmark", "The United Kingdom"], "It premiered on Swedish TV in 1997, three years before the U.S. version."),
        Q(3, "The 'Big Brother' format first aired in which country?", "The Netherlands", ["The United Kingdom", "Germany", "Sweden"], "Its name comes from George Orwell's novel '1984.'"),
        Q(3, "Who was the first person to win 'Survivor' twice?", "Sandra Diaz-Twine", ["Tony Vlachos", "Parvati Shallow", "Rob Mariano"], "She won Pearl Islands in 2003 and Heroes vs. Villains in 2010."),
        Q(3, "Who was the very first lead of 'The Bachelor' in 2002?", "Alex Michel", ["Andrew Firestone", "Aaron Buerge", "Bob Guiney"], "The Harvard-educated consultant met 25 women that first season."),
        Q(3, "Who won the first season of 'RuPaul's Drag Race'?", "BeBe Zahara Benet", ["Nina Flowers", "Tyra Sanchez", "Raja"], "Runner-up Nina Flowers was named Miss Congeniality."),
        Q(3, "Season one of Netflix's 'Love Is Blind' was filmed in which city?", "Atlanta", ["Chicago", "Dallas", "Seattle"], "The pods were built at Pinewood Atlanta Studios."),
        Q(3, "'Jersey Shore' season four was filmed in which Italian city?", "Florence", ["Rome", "Milan", "Venice"], "The roommates worked at a pizzeria near the Uffizi Gallery."),
        Q(3, "On 'The Amazing Race,' a task only one teammate can do is a what?", "Roadblock", ["Detour", "Fast Forward", "U-Turn"], "Teams choose who does it from a cryptic clue, before seeing the full task."),
        Q(3, "SUR, the restaurant on 'Vanderpump Rules,' is billed as short for what?", "Sexy Unique Restaurant", ["Simply Upscale Restaurant", "Sunset Urban Restaurant", "Stylish Upscale Rendezvous"], "'Sur' is Spanish for 'south'; the acronym came after Vanderpump bought in."),
        Q(3, "Who finished runner-up to Kelly Clarkson on 'American Idol' season one?", "Justin Guarini", ["Clay Aiken", "Ruben Studdard", "Tamyra Gray"], "The two co-starred in the 2003 movie 'From Justin to Kelly.'"),
        Q(3, "Which 'The Hills' star got her own spin-off, 'The City'?", "Whitney Port", ["Lauren Conrad", "Audrina Patridge", "Heidi Montag"], "It followed her move to New York to work for Diane von Furstenberg."),
        Q(3, "Before Peacock, 'Love Island USA' aired on which network?", "CBS", ["NBC", "Fox", "ABC"], "CBS aired its first three seasons, starting in 2019."),
    ])

    static let divas = Deck(id: "divas", world: .hers, title: "Pop Divas & Their Eras", tagline: "Swifties, the Beyhive, and who wrote what.", colorHex: "D63AE8", specs: [
        Q(1, "Taylor Swift's re-recorded albums carry which label?", "(Taylor's Version)", ["(Remastered)", "(Deluxe)", "(Redux)"]),
        Q(1, "'All Too Well (10 Minute Version)' is on which album?", "Red (Taylor's Version)", ["1989", "folklore", "Lover"]),
        Q(1, "Beyoncé's 2016 visual album was called what?", "Lemonade", ["Renaissance", "Cowboy Carter", "4"]),
        Q(1, "Dua Lipa's disco-flavored 2020 album was what?", "Future Nostalgia", ["Radical Optimism", "Dua Lipa", "Levitating"]),
        Q(1, "Billie Eilish's brother and producer is named what?", "Finneas", ["Phineas", "Fernando", "Felix"]),
        Q(1, "Which Spice Girl was Posh?", "Victoria Beckham", ["Mel B", "Emma Bunton", "Geri Halliwell"]),
        Q(1, "'vampire' and 'good 4 u' are by whom?", "Olivia Rodrigo", ["Sabrina Carpenter", "Gracie Abrams", "Tate McRae"]),
        Q(1, "Chappell Roan's 2024 breakout hit was what?", "Good Luck, Babe!", ["Espresso", "Birds of a Feather", "Greedy"]),
        Q(1, "Rihanna is from which country?", "Barbados", ["Jamaica", "Trinidad and Tobago", "The Bahamas"]),
        Q(1, "Miley Cyrus's Disney character was who?", "Hannah Montana", ["Lizzie McGuire", "Raven", "Alex Russo"]),
        Q(1, "Adele's albums are named after what?", "Her age when she made them", ["Cities", "Colors", "Seasons"]),
        Q(1, "Mariah Carey's holiday classic is what?", "All I Want for Christmas Is You", ["Last Christmas", "Santa Tell Me", "Mistletoe"]),
        Q(2, "Taylor Swift released 'folklore' and 'evermore' in which year?", "2020", ["2019", "2021", "2022"]),
        Q(2, "Beyoncé's 'Cowboy Carter' (2024) is her take on which genre?", "Country", ["Jazz", "Disco", "Gospel"]),
        Q(2, "Lady Gaga won her Oscar for which song?", "Shallow", ["Bad Romance", "Hold My Hand", "Always Remember Us This Way"]),
        Q(2, "Who wrote 'I Will Always Love You,' the song Whitney Houston made huge?", "Dolly Parton", ["Whitney Houston", "Diane Warren", "Carole King"]),
        Q(2, "'Anti-Hero' and 'Karma' are on which Taylor Swift album?", "Midnights", ["Lover", "evermore", "The Tortured Poets Department"]),
        Q(2, "How many exes does Ariana Grande name in 'thank u, next'?", "Four", ["Two", "Three", "Five"]),
        Q(2, "Dolly Parton's theme park is called what?", "Dollywood", ["Dollyland", "Parton Park", "Jolene World"]),
        Q(2, "Whose 2022 album 'Renaissance' celebrated house music and ballroom culture?", "Beyoncé", ["Madonna", "Rihanna", "Dua Lipa"]),
        Q(2, "Britney Spears's 2023 memoir is titled what?", "The Woman in Me", ["Oops... I Did It Again", "Toxic", "Britney Jean"]),
        Q(2, "Sabrina Carpenter's 2024 album is called what?", "Short n' Sweet", ["Emails I Can't Send", "Singular", "Guts"]),
        Q(2, "Madonna's nickname is what?", "Queen of Pop", ["Queen of Soul", "Queen of Country", "Queen of Rock"]),
        Q(2, "Whose 'Eras Tour' concert film hit theaters in October 2023?", "Taylor Swift", ["Beyoncé", "Olivia Rodrigo", "Adele"]),
        Q(3, "What was Taylor Swift's debut single?", "Tim McGraw", ["Teardrops on My Guitar", "Our Song", "Love Story"], "It came out in June 2006 and was named after the country star."),
        Q(3, "What was Madonna's first No. 1 on the Billboard Hot 100?", "Like a Virgin", ["Holiday", "Borderline", "Material Girl"], "It hit No. 1 in December 1984, just six weeks after entering the chart."),
        Q(3, "What was Mariah Carey's debut single?", "Vision of Love", ["Hero", "Emotions", "Someday"], "It went to No. 1 on the Hot 100 in the summer of 1990."),
        Q(3, "Céline Dion won Eurovision 1988 representing which country?", "Switzerland", ["Canada", "France", "Belgium"], "She won by a single point over the United Kingdom."),
        Q(3, "Who was the first woman inducted into the Rock & Roll Hall of Fame?", "Aretha Franklin", ["Tina Turner", "Diana Ross", "Janis Joplin"], "She was inducted in 1987."),
        Q(3, "Beyoncé played which legend in 'Cadillac Records' (2008)?", "Etta James", ["Billie Holiday", "Aretha Franklin", "Nina Simone"], "The director said the role was written with Beyoncé in mind."),
        Q(3, "Beyoncé's first Album of the Year Grammy came for which album?", "Cowboy Carter", ["Lemonade", "Renaissance", "Beyoncé"], "At the 2025 Grammys she became the first Black woman to win it since Lauryn Hill in 1999."),
        Q(3, "Katy Perry's 2001 Christian debut album came out under what name?", "Katy Hudson", ["Katheryn Elizabeth", "Kate Perry", "Katy Beth"], "She later took Perry, her mother's maiden name, partly to avoid confusion with actress Kate Hudson."),
        Q(3, "What was Rihanna's debut single?", "Pon de Replay", ["Umbrella", "SOS", "Unfaithful"], "It came from her 2005 debut album, 'Music of the Sun.'"),
        Q(3, "Sabrina Carpenter played Maya Hart on which Disney Channel show?", "Girl Meets World", ["Liv and Maddie", "Jessie", "Andi Mack"], "The 'Boy Meets World' spin-off ran on Disney Channel from 2014 to 2017."),
        Q(3, "The '1814' in Janet Jackson's 'Rhythm Nation 1814' is the year of what?", "The Star-Spangled Banner", ["The Louisiana Purchase", "The Bill of Rights", "The Emancipation Proclamation"], "Francis Scott Key wrote the anthem in 1814; the album came out in 1989."),
        Q(3, "Which future pop star was a Mouseketeer alongside Britney Spears?", "Christina Aguilera", ["Jessica Simpson", "Mandy Moore", "Hilary Duff"], "Justin Timberlake and Ryan Gosling were in the same 1993-94 cast."),
    ])

    static let weddings = Deck(id: "weddings", world: .hers, title: "Wedding Season", tagline: "Registries, mimosas, and what your rising sign means.", colorHex: "19B8B5", specs: [
        Q(1, "What is a rehearsal dinner?", "Dinner the night before the wedding, after practicing the ceremony", ["The first dinner after the honeymoon", "The engagement dinner", "The reception"]),
        Q(1, "A sweetheart table seats whom?", "Just the couple", ["The parents", "The wedding party", "The kids"]),
        Q(1, "What is a boutonnière?", "A small flower worn on a lapel", ["A bridal veil", "A cake topper", "A garter"]),
        Q(1, "Which zodiac sign is the scales?", "Libra", ["Gemini", "Virgo", "Aquarius"]),
        Q(1, "Mercury retrograde gets blamed for what?", "Communication and tech mishaps", ["Bad weather", "Sports losses", "Frizzy hair"]),
        Q(1, "Which of these is a fire sign?", "Aries", ["Cancer", "Pisces", "Taurus"]),
        Q(1, "What is a first look?", "The couple seeing each other before the ceremony, usually with a photographer", ["The first dance", "The engagement photo", "The proposal"]),
        Q(1, "What is a trousseau?", "A bride's collection of clothes and linens for married life", ["The wedding cake", "The bridal bouquet", "The wedding car"]),
        Q(1, "A Bellini is Prosecco and what?", "Peach purée", ["Orange juice", "Cranberry juice", "Lime juice"]),
        Q(1, "In astrology, the 'big three' are what?", "Sun, Moon, and Rising signs", ["Fire, Earth, and Water", "Past, Present, and Future", "Leo, Scorpio, and Aries"]),
        Q(1, "What does the best man traditionally hold before the vows?", "The rings", ["The bouquet", "The license", "The veil"]),
        Q(1, "In the U.S., the wedding ring is worn where?", "Fourth finger of the left hand", ["Index finger", "Thumb", "Right pinky"]),
        Q(2, "Traditionally, the groom's family paid for what?", "The rehearsal dinner", ["The cake", "The dress", "The flowers"]),
        Q(2, "A cathedral veil is what?", "The longest style, extending past the train", ["A short shoulder veil", "A birdcage veil", "A veil with a crown"]),
        Q(2, "The 'something blue' rhyme comes from where?", "Victorian England", ["France", "Italy", "Greece"]),
        Q(2, "'Eloping' originally meant what?", "Running away to marry in secret", ["A big destination wedding", "A courthouse wedding", "A second wedding"]),
        Q(2, "Scorpio is which kind of sign?", "A water sign", ["A fire sign", "An earth sign", "An air sign"]),
        Q(2, "A charcuterie board is what?", "A spread of cured meats, cheeses, and accompaniments", ["A dessert platter", "A brunch cocktail", "A cheese fondue"]),
        Q(2, "In Britain, a 'hen do' is what?", "A bachelorette party", ["A bridal shower", "A rehearsal dinner", "A baby shower"]),
        Q(2, "Your 'Saturn return' hits around what age?", "29 to 30", ["18", "40", "50"]),
        Q(2, "In the U.S., the average engagement lasts about how long?", "About a year", ["About a month", "About three years", "About five years"]),
        Q(2, "The Southern tradition of 'cake pulling' involves what?", "Bridesmaids pulling charms from the cake", ["Cutting the cake with a sword", "Eating cake for luck", "Hiding the groom's cake"]),
        Q(2, "The groom's cake tradition is tied to which U.S. region?", "The South", ["New England", "The Pacific Northwest", "The Midwest"]),
        Q(2, "'Brunch' blends which two words?", "Breakfast and lunch", ["Bread and crunch", "Bar and lunch", "Breakfast and munch"]),
        Q(3, "The first recorded diamond engagement ring was given by whom?", "Archduke Maximilian of Austria", ["Napoleon Bonaparte", "King Henry VIII", "King Louis XIV"], "He gave it to Mary of Burgundy in 1477."),
        Q(3, "The traditional 40th wedding anniversary gift is what?", "Ruby", ["Pearl", "Sapphire", "Emerald"], "Pearl marks the 30th, sapphire the 45th, and emerald the 55th."),
        Q(3, "In a Shinto wedding, the couple sips from three cups of what?", "Sake", ["Green tea", "Plum wine", "Barley tea"], "The ritual, san-san-kudo, means 'three-three-nine times.'"),
        Q(3, "At Italian weddings, 'confetti' are what?", "Sugared almonds", ["Paper streamers", "Grains of rice", "Rose petals"], "They're often given in fives, for health, wealth, happiness, fertility, and long life."),
        Q(3, "The French wedding cake built as a tower of cream puffs is called what?", "Croquembouche", ["Mille-feuille", "Paris-Brest", "Gâteau Saint-Honoré"], "Its name comes from French for 'crunches in the mouth.'"),
        Q(3, "Charles and Diana married in 1981 at which London church?", "St Paul's Cathedral", ["Westminster Abbey", "Southwark Cathedral", "St Martin-in-the-Fields"], "Diana's gown had a 25-foot train."),
        Q(3, "Who designed Kate Middleton's 2011 wedding dress?", "Sarah Burton for Alexander McQueen", ["Vera Wang", "Elizabeth Emanuel", "Clare Waight Keller"], "Its lace was hand-applied by the Royal School of Needlework."),
        Q(3, "Grace Kelly's 1956 wedding gown was a gift from which film studio?", "MGM", ["Paramount", "Warner Bros.", "20th Century Fox"], "MGM costume designer Helen Rose made it."),
        Q(3, "'Here Comes the Bride' comes from which Wagner opera?", "Lohengrin", ["Tannhäuser", "Tristan und Isolde", "Parsifal"], "Its real title is the 'Bridal Chorus,' from 1850."),
        Q(3, "Aquarius, the 'water bearer,' belongs to which element?", "Air", ["Water", "Earth", "Fire"], "It shares the air element with Gemini and Libra."),
        Q(3, "The Bellini was invented at which Venice bar?", "Harry's Bar", ["Caffè Florian", "Caffè Quadri", "Bar Danieli"], "Giuseppe Cipriani named it for the painter Giovanni Bellini."),
        Q(3, "Before designing wedding gowns, Vera Wang competed in which sport?", "Figure skating", ["Gymnastics", "Tennis", "Diving"], "She skated at the 1968 U.S. Championships, then spent 17 years at Vogue."),
    ])
}
