import Foundation

extension HerWorld {
    static let bookclub = Deck(id: "bookclub", world: .hers, title: "Book Club", tagline: "BookTok, bestsellers, and the TBR pile that never shrinks.", colorHex: "5B5BD6", specs: [
        Q(1, "BookTok is a community of readers on which app?", "TikTok", ["Instagram", "Facebook", "Snapchat"]),
        Q(1, "What does a TBR pile mean?", "To Be Read", ["Totally Boring Reads", "Top Bestseller Ranking", "The Best Reviews"]),
        Q(1, "Who wrote the Harry Potter books?", "J.K. Rowling", ["Stephenie Meyer", "Suzanne Collins", "Rick Riordan"]),
        Q(1, "Goodreads is a site for doing what?", "Tracking and rating the books you read", ["Buying used textbooks", "Renting audiobooks", "Finding a book club near you"]),
        Q(1, "Kindle e-readers are made by which company?", "Amazon", ["Apple", "Google", "Barnes & Noble"]),
        Q(1, "A memoir is a book about what?", "The author's own life", ["A made-up detective", "A famous king", "Cooking"]),
        Q(1, "Who wrote 'The Hunger Games'?", "Suzanne Collins", ["Veronica Roth", "J.K. Rowling", "Cassandra Clare"]),
        Q(1, "The paper cover wrapped around a hardcover is called a what?", "Dust jacket", ["Book belt", "Sleeve", "Wrapper"]),
        Q(1, "Reese Witherspoon's book club is called what?", "Reese's Book Club", ["Reese Reads", "Sunday Reads", "The Sunshine Shelf"]),
        Q(1, "'Enemies to lovers' is a type of what?", "Romance trope", ["Cookbook", "Poetry form", "Mystery clue"]),
        Q(1, "Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", ["Ernest Hemingway", "John Steinbeck", "Mark Twain"]),
        Q(1, "Amazon's audiobook service is called what?", "Audible", ["Spotify Books", "Libby", "Scribd"]),
        Q(2, "Who wrote 'Where the Crawdads Sing'?", "Delia Owens", ["Kristin Hannah", "Liane Moriarty", "Celeste Ng"]),
        Q(2, "Who wrote 'Gone Girl'?", "Gillian Flynn", ["Paula Hawkins", "Tana French", "Ruth Ware"]),
        Q(2, "'Fourth Wing' is set at a war college that trains riders of what?", "Dragons", ["Horses", "Griffins", "Wolves"]),
        Q(2, "In BookTok slang, ACOTAR stands for what?", "A Court of Thorns and Roses", ["A Castle of Time and Rain", "All Cats on the Roof", "A Crown of Thieves and Ruin"]),
        Q(2, "Who wrote 'The Seven Husbands of Evelyn Hugo'?", "Taylor Jenkins Reid", ["Emily Henry", "Colleen Hoover", "Sally Rooney"]),
        Q(2, "'Daisy Jones & The Six' is about what?", "A 1970s rock band", ["A girls' boarding school", "A Nashville songwriter", "Six sisters in Texas"]),
        Q(2, "Who wrote 'The Handmaid's Tale'?", "Margaret Atwood", ["Toni Morrison", "Alice Walker", "Ursula K. Le Guin"]),
        Q(2, "Who wrote 'Eat Pray Love'?", "Elizabeth Gilbert", ["Cheryl Strayed", "Glennon Doyle", "Brené Brown"]),
        Q(2, "'Verity' is a thriller by which usually-romance author?", "Colleen Hoover", ["Emily Henry", "Ali Hazelwood", "Tessa Bailey"]),
        Q(2, "'It Starts with Us' is the sequel to what?", "It Ends with Us", ["Ugly Love", "Verity", "November 9"]),
        Q(2, "Which app lets you borrow library ebooks for free?", "Libby", ["Kindle Unlimited", "Audible", "Scribd"]),
        Q(2, "Who wrote 'Little Women'?", "Louisa May Alcott", ["Jane Austen", "Charlotte Brontë", "Edith Wharton"]),
        Q(3, "Who wrote 'Fourth Wing'?", "Rebecca Yarros", ["Sarah J. Maas", "Leigh Bardugo", "Holly Black"]),
        Q(3, "Who wrote the ACOTAR series?", "Sarah J. Maas", ["Rebecca Yarros", "Jennifer L. Armentrout", "Cassandra Clare"]),
        Q(3, "In 'Lessons in Chemistry,' Elizabeth Zott ends up hosting what?", "A TV cooking show", ["A radio call-in show", "A science podcast", "A talk show for kids"]),
        Q(3, "Who wrote 'Little Fires Everywhere'?", "Celeste Ng", ["Liane Moriarty", "Ann Patchett", "Jodi Picoult"]),
        Q(3, "Who wrote 'The Midnight Library'?", "Matt Haig", ["Fredrik Backman", "Neil Gaiman", "David Nicholls"]),
        Q(3, "The Booker Prize is a major literary award based in which country?", "The United Kingdom", ["The United States", "Canada", "Australia"]),
        Q(3, "Oprah's Book Club started in which year?", "1996", ["1988", "2001", "2005"]),
        Q(3, "Kristin Hannah's 'The Nightingale' is set during what?", "World War II", ["The Civil War", "The Great Depression", "The Vietnam War"]),
        Q(3, "'Tomorrow, and Tomorrow, and Tomorrow' follows two friends who make what?", "Video games", ["Movies", "Podcasts", "Perfume"]),
        Q(3, "'Iron Flame' is the sequel to what?", "Fourth Wing", ["A Court of Mist and Fury", "Powerless", "Shadow and Bone"]),
        Q(3, "Who wrote 'A Little Life'?", "Hanya Yanagihara", ["Donna Tartt", "Ottessa Moshfegh", "Sally Rooney"]),
        Q(3, "Who wrote 'Wuthering Heights'?", "Emily Brontë", ["Charlotte Brontë", "Anne Brontë", "Mary Shelley"]),
    ])

    static let wellness = Deck(id: "wellness", world: .hers, title: "Wellness & Self-Care", tagline: "Pilates, matcha, cold plunges, and eight hours of sleep.", colorHex: "3DBF8A", specs: [
        Q(1, "Pilates is best known for building what?", "Core strength and control", ["Sprinting speed", "Vertical jump", "Grip strength"]),
        Q(1, "Matcha is what?", "Powdered green tea", ["Ground coffee", "A mushroom powder", "Cocoa"]),
        Q(1, "What is a cold plunge?", "Dipping into ice-cold water", ["A face mask", "A chilled smoothie", "A frozen dessert"]),
        Q(1, "Melatonin is a hormone that regulates what?", "Sleep", ["Appetite", "Hair growth", "Blood sugar"]),
        Q(1, "Vitamin D is nicknamed what?", "The sunshine vitamin", ["The beauty vitamin", "The energy vitamin", "The immune vitamin"]),
        Q(1, "Dry January means what?", "No alcohol for the month of January", ["No sugar in January", "A January skin routine", "No spending in January"]),
        Q(1, "Peloton is best known for what?", "Connected exercise bikes", ["Protein bars", "Running shoes", "Yoga mats"]),
        Q(1, "A gratitude journal is for writing down what?", "Things you're thankful for", ["Your grocery list", "Your workouts", "Your dreams"]),
        Q(1, "Oat milk is made from what?", "Oats", ["Almonds", "Rice", "Soybeans"]),
        Q(1, "The Stanley cup that went viral in 2023 was a what?", "A big insulated tumbler", ["A hockey trophy", "A face roller", "A yoga mat"]),
        Q(1, "How many hours of sleep are most adults advised to get?", "7 to 9", ["4 to 5", "5 to 6", "10 to 12"]),
        Q(1, "A digital detox means what?", "Time away from screens", ["Cleaning your phone", "Deleting old photos", "A new phone case"]),
        Q(2, "What kind of exercise class is barre inspired by?", "Ballet", ["Boxing", "Rowing", "Gymnastics"]),
        Q(2, "HIIT stands for what?", "High-Intensity Interval Training", ["Heavy Iron Indoor Training", "Hot Isometric Interval Time", "High-Impact Indoor Toning"]),
        Q(2, "A reformer is equipment used in what?", "Pilates", ["CrossFit", "Spin class", "Barre"]),
        Q(2, "Cortisol is often called what?", "The stress hormone", ["The sleep hormone", "The love hormone", "The hunger hormone"]),
        Q(2, "Kombucha is what?", "Fermented tea", ["Sparkling coffee", "A yogurt drink", "Coconut water"]),
        Q(2, "Goop was founded by which actress?", "Gwyneth Paltrow", ["Jessica Alba", "Reese Witherspoon", "Kate Hudson"]),
        Q(2, "Oura is a fitness tracker worn as a what?", "A ring", ["A watch", "A headband", "An ankle strap"]),
        Q(2, "In the 16:8 style of intermittent fasting, what is the 8?", "Hours you can eat", ["Hours you fast", "Glasses of water", "Days per week"]),
        Q(2, "A 'hot girl walk' is what?", "A long walk for a mood and confidence boost", ["A treadmill sprint", "A hike with weights", "A walk to the gym"]),
        Q(2, "Collagen, popular in supplements, is a type of what?", "Protein", ["Vitamin", "Carbohydrate", "Mineral"]),
        Q(2, "The Calm app is famous for what?", "Sleep stories and meditation", ["Step counting", "Recipe plans", "Run tracking"]),
        Q(2, "'Macros' is short for what?", "Macronutrients: protein, carbs, and fat", ["Macro workouts", "Major calories", "Meal accounts"]),
        Q(3, "Pilates was invented by Joseph Pilates, who was born where?", "Germany", ["The United States", "Italy", "Sweden"]),
        Q(3, "A traditional Bikram yoga class has how many postures?", "26", ["12", "40", "108"]),
        Q(3, "Erewhon, famous for pricey smoothies, is what kind of business?", "A Los Angeles grocery store", ["A yoga chain", "A supplement brand", "A spa"]),
        Q(3, "The '10,000 steps a day' target began as marketing for what?", "A 1960s Japanese pedometer", ["A 1980s Nike shoe", "A Fitbit launch", "A 1990s diet book"]),
        Q(3, "Lululemon was founded in which city?", "Vancouver", ["Los Angeles", "Sydney", "Portland"]),
        Q(3, "Wim Hof is famous for what?", "Cold exposure and breathing techniques", ["Marathon running", "Vegan cooking", "Sleep coaching"]),
        Q(3, "The 'sleepy girl mocktail' mixes magnesium with which juice?", "Tart cherry", ["Orange", "Cranberry", "Pineapple"]),
        Q(3, "Ozempic was originally approved to treat what?", "Type 2 diabetes", ["High blood pressure", "Migraines", "Insomnia"]),
        Q(3, "Roughly how much protein is in one large egg?", "About 6 grams", ["About 1 gram", "About 15 grams", "About 25 grams"]),
        Q(3, "Which form of magnesium is the popular pick for sleep?", "Magnesium glycinate", ["Magnesium sulfate", "Magnesium oxide", "Magnesium chloride"]),
        Q(3, "How does a sauna differ from a steam room?", "A sauna uses dry heat", ["A sauna is colder", "A sauna uses water jets", "A sauna is only outdoors"]),
        Q(3, "Alo Yoga is headquartered in which city?", "Los Angeles", ["New York", "Vancouver", "Miami"]),
    ])

    static let gossip = Deck(id: "gossip", world: .hers, title: "Celebrity Couples & Gossip", tagline: "Who's dating, who's engaged, and who conscious-uncoupled.", colorHex: "FFB020", specs: [
        Q(1, "Beyoncé is married to which rapper?", "Jay-Z", ["Drake", "Kanye West", "Diddy"]),
        Q(1, "'Bennifer' is the nickname for Jennifer Lopez and whom?", "Ben Affleck", ["Ben Stiller", "Benedict Cumberbatch", "Ben Platt"]),
        Q(1, "Prince Harry is married to whom?", "Meghan Markle", ["Kate Middleton", "Pippa Middleton", "Zara Tindall"]),
        Q(1, "Blake Lively is married to which actor?", "Ryan Reynolds", ["Ryan Gosling", "Chris Evans", "Bradley Cooper"]),
        Q(1, "'Brangelina' referred to Angelina Jolie and whom?", "Brad Pitt", ["Brad Paisley", "Bradley Cooper", "Brendan Fraser"]),
        Q(1, "Zendaya's longtime partner plays which superhero?", "Spider-Man", ["Batman", "Thor", "Aquaman"]),
        Q(1, "Victoria Beckham is married to which soccer legend?", "David Beckham", ["Wayne Rooney", "Gary Neville", "Steven Gerrard"]),
        Q(1, "Justin Bieber's wife is named what?", "Hailey", ["Selena", "Gigi", "Kendall"]),
        Q(1, "Kim Kardashian's ex-husband is which rapper?", "Kanye West", ["Jay-Z", "Travis Scott", "Drake"]),
        Q(1, "Kris Jenner is known as the family's what?", "Momager", ["Chef", "Stylist", "Publicist"]),
        Q(1, "TMZ is what?", "A celebrity news site", ["A record label", "A talent agency", "A fashion house"]),
        Q(1, "Taylor Swift got engaged in 2025 to which football star?", "Travis Kelce", ["Patrick Mahomes", "Jason Kelce", "Joe Burrow"]),
        Q(2, "Tom Brady's ex-wife is which supermodel?", "Gisele Bündchen", ["Adriana Lima", "Heidi Klum", "Karlie Kloss"]),
        Q(2, "Kourtney Kardashian married which drummer?", "Travis Barker", ["Tommy Lee", "Dave Grohl", "Travis Scott"]),
        Q(2, "Kylie Jenner dated which 'Dune' actor?", "Timothée Chalamet", ["Austin Butler", "Jacob Elordi", "Paul Mescal"]),
        Q(2, "Priyanka Chopra is married to which Jonas brother?", "Nick", ["Joe", "Kevin", "Frankie"]),
        Q(2, "Rihanna's partner and the father of her sons is which rapper?", "A$AP Rocky", ["Drake", "Travis Scott", "Chris Brown"]),
        Q(2, "Chrissy Teigen is married to which singer?", "John Legend", ["John Mayer", "Usher", "Bruno Mars"]),
        Q(2, "At the 2022 Oscars, Will Smith slapped whom?", "Chris Rock", ["Kevin Hart", "Jimmy Kimmel", "Dave Chappelle"]),
        Q(2, "Jennifer Aniston was married to Brad Pitt and which other actor?", "Justin Theroux", ["Vince Vaughn", "John Mayer", "Paul Rudd"]),
        Q(2, "Kate Middleton's official title is what?", "Princess of Wales", ["Duchess of Sussex", "Queen Consort", "Princess Royal"]),
        Q(2, "Selena Gomez got engaged in 2024 to which producer?", "Benny Blanco", ["Justin Bieber", "The Weeknd", "Zedd"]),
        Q(2, "Pete Davidson dated Kim Kardashian and which pop star?", "Ariana Grande", ["Miley Cyrus", "Dua Lipa", "Olivia Rodrigo"]),
        Q(2, "Beyoncé and Jay-Z's first daughter is named what?", "Blue Ivy", ["North", "Stormi", "Rumi"]),
        Q(3, "Gwyneth Paltrow and Chris Martin famously called their split what?", "Conscious uncoupling", ["A soft launch", "A brand pivot", "A gentle exit"]),
        Q(3, "Britney Spears's ex-husband Kevin Federline was a what?", "Backup dancer", ["Record producer", "Actor", "DJ"]),
        Q(3, "Paris Hilton and Nicole Richie starred in which early-2000s reality show?", "The Simple Life", ["The Hills", "Laguna Beach", "Rich Girls"]),
        Q(3, "Tom Cruise's ex-wife Katie Holmes starred in which teen drama?", "Dawson's Creek", ["The O.C.", "One Tree Hill", "Gilmore Girls"]),
        Q(3, "Which Marvel actor married Portuguese actress Alba Baptista in 2023?", "Chris Evans", ["Chris Hemsworth", "Chris Pratt", "Sebastian Stan"]),
        Q(3, "Sabrina Carpenter dated which 'Saltburn' actor?", "Barry Keoghan", ["Jacob Elordi", "Paul Mescal", "Archie Madekwe"]),
        Q(3, "Olivia Wilde dated which former boy-band member?", "Harry Styles", ["Zayn Malik", "Niall Horan", "Nick Jonas"]),
        Q(3, "Kim Kardashian and Kanye West's kids are North, Saint, Chicago, and who?", "Psalm", ["Reign", "Stormi", "True"]),
        Q(3, "Megan Fox has a daughter with which musician?", "Machine Gun Kelly", ["Post Malone", "Travis Barker", "Blake Shelton"]),
        Q(3, "Oprah's bombshell interview with Harry and Meghan aired in which year?", "2021", ["2019", "2020", "2022"]),
        Q(3, "Ryan Reynolds and Blake Lively have how many children?", "Four", ["Two", "Three", "Five"]),
        Q(3, "Sofía Vergara's ex-husband Joe Manganiello starred in which movie series?", "Magic Mike", ["Fast & Furious", "Twilight", "John Wick"]),
    ])
}
