import Foundation

/// Her World: the decks a partner who "knows his world" gets quizzed on.
enum HerWorld {
    static let decks: [Deck] = [skincare, fashion, romcoms, reality, divas, weddings]

    static let skincare = Deck(id: "skincare", world: .hers, title: "Skincare & Beauty", tagline: "Serums, SPF, and why the order matters.", symbol: "drop.fill", colorHex: "D96C8A", specs: [
        Q(1, "What does SPF stand for?", "Sun Protection Factor", ["Skin Protection Formula", "Solar Prevention Filter", "Sun Proof Finish"]),
        Q(1, "Which product goes on first in a typical skincare routine?", "Cleanser", ["Moisturizer", "Sunscreen", "Serum"]),
        Q(1, "Mascara is applied to what?", "Eyelashes", ["Eyebrows", "Lips", "Cheeks"]),
        Q(1, "Where does blush go?", "Cheeks", ["Eyelids", "Lips", "Nose"]),
        Q(1, "Which of these is a lip product?", "Gloss", ["Toner", "Serum", "Primer"]),
        Q(1, "What is a toner for?", "Prepping skin right after cleansing", ["Removing hair", "Adding shimmer", "Curling lashes"]),
        Q(1, "A French manicure is known for what on the tips?", "White tips", ["Red tips", "Glitter tips", "Black tips"]),
        Q(1, "Which tool curls eyelashes?", "An eyelash curler", ["Tweezers", "A spoolie", "A beauty sponge"]),
        Q(1, "A blackhead is basically what?", "A clogged pore", ["A mole", "A freckle", "A scar"]),
        Q(1, "Which product is for taking makeup off at night?", "Micellar water", ["Setting spray", "Dry shampoo", "Hairspray"]),
        Q(1, "Dry shampoo is used to do what?", "Soak up oil between washes", ["Whiten teeth", "Curl hair", "Fix split ends"]),
        Q(1, "A 'matte' lipstick finish has what quality?", "No shine", ["Extra gloss", "Glitter", "See-through color"]),
        Q(2, "Retinol is a form of which vitamin?", "Vitamin A", ["Vitamin C", "Vitamin E", "Vitamin K"]),
        Q(2, "Hyaluronic acid is loved for what?", "Holding moisture in the skin", ["Exfoliating dead skin", "Lightening skin", "Blocking the sun"]),
        Q(2, "What does a makeup primer do?", "Preps skin so makeup goes on smoothly and lasts", ["Cleans brushes", "Removes makeup", "Treats acne overnight"]),
        Q(2, "Contouring uses darker shades to do what?", "Create shadows that sculpt the face", ["Cover blemishes", "Add glitter", "Set powder"]),
        Q(2, "Which acid is the classic chemical exfoliant for acne-prone skin?", "Salicylic acid", ["Folic acid", "Citric acid", "Amino acid"]),
        Q(2, "What is a spoolie?", "A little brush for brows and lashes", ["A nail file", "A hair tie", "A face roller"]),
        Q(2, "A gel manicure is cured with what?", "UV or LED light", ["Hot water", "Steam", "A blow dryer"]),
        Q(2, "Hair color with lighter pieces painted on freehand is called what?", "Balayage", ["A perm", "Keratin", "A relaxer"]),
        Q(2, "What is double cleansing?", "An oil cleanser followed by a water-based one", ["Washing twice with the same soap", "Cleansing morning and night", "Using two washcloths"]),
        Q(2, "Vitamin C serum is mainly used for what?", "Brightening and evening out skin tone", ["Removing hair", "Curling lashes", "Setting makeup"]),
        Q(2, "'Non-comedogenic' on a label means what?", "Formulated not to clog pores", ["Fragrance-free", "Vegan", "Waterproof"]),
        Q(2, "Which is a famous makeup sponge brand?", "Beautyblender", ["Beautyblaster", "Glambubble", "Facefoam"]),
        Q(3, "Fenty Beauty launched in 2017 with how many foundation shades, a number that became the industry benchmark?", "40", ["12", "20", "100"]),
        Q(3, "'Glass skin' comes from which country's beauty culture?", "South Korea", ["France", "Brazil", "Italy"]),
        Q(3, "Niacinamide is a form of which vitamin?", "Vitamin B3", ["Vitamin A", "Vitamin D", "Vitamin K"]),
        Q(3, "Whose Great Lash mascara comes in the famous pink-and-green tube?", "Maybelline", ["CoverGirl", "L'Oréal", "Revlon"]),
        Q(3, "The '10-step routine' refers to which skincare tradition?", "Korean skincare", ["French pharmacy", "Ayurveda", "Hollywood glam"]),
        Q(3, "'Slugging' means sealing your skin overnight with what?", "Petroleum jelly", ["Honey", "Ice", "Rice water"]),
        Q(3, "The 'lipstick index' is the idea that in a downturn, what happens?", "Lipstick sales go up", ["Lipstick prices track oil", "Red lipstick predicts elections", "Lipstick sales collapse"], "Leonard Lauder of Estée Lauder coined it after 9/11."),
        Q(3, "A 'cat eye' is what?", "A winged eyeliner look", ["A lash-extension style", "A brow shape", "A contact lens"]),
        Q(3, "Which oil, from a tree native to Morocco, is a haircare favorite?", "Argan oil", ["Jojoba oil", "Tea tree oil", "Marula oil"]),
        Q(3, "In skincare, AHA stands for what?", "Alpha hydroxy acid", ["Advanced hydrating agent", "Anti-hyaluronic acid", "Active hair acid"]),
        Q(3, "Charlotte Tilbury's famous 'Pillow Talk' is a shade of what?", "Lip color", ["Foundation", "Perfume", "Bronzer"]),
        Q(3, "With lash extensions, a 'volume set' means what compared to 'classic'?", "Several fine lashes on each natural lash instead of one", ["Longer lashes only", "Colored lashes", "Bottom lashes only"]),
    ])

    static let fashion = Deck(id: "fashion", world: .hers, title: "Fashion & Style", tagline: "Houses, hemlines, and the bag everyone knows.", symbol: "handbag.fill", colorHex: "8B5CF6", specs: [
        Q(1, "What is a clutch?", "A small handbag with no strap", ["A type of shoe", "A jacket", "A hat"]),
        Q(1, "Stilettos are what?", "High heels with a thin heel", ["Flat sandals", "Rain boots", "Sneakers"]),
        Q(1, "What does LBD stand for?", "Little black dress", ["Long blue denim", "Light beige blazer", "Lace bridal dress"]),
        Q(1, "Which brand is famous for red-soled shoes?", "Christian Louboutin", ["Gucci", "Nike", "Zara"]),
        Q(1, "A cardigan is what?", "A sweater that opens at the front", ["A pair of pants", "A scarf", "A skirt"]),
        Q(1, "What is denim?", "The fabric jeans are made of", ["A type of silk", "A shoe style", "A necklace"]),
        Q(1, "Athleisure blends athletic wear with what?", "Everyday casual clothes", ["Evening gowns", "Business suits", "Swimwear"]),
        Q(1, "What is a tote?", "A large open-top bag", ["A small wallet", "A belt", "A hair clip"]),
        Q(1, "Which of these is a shoe brand?", "Steve Madden", ["Steve Jobs", "Steve Harvey", "Steve Austin"]),
        Q(1, "A maxi dress is how long?", "Floor-length", ["Above the knee", "Sleeveless", "Backless"]),
        Q(1, "A hoop is what kind of jewelry?", "A circular earring", ["A ring", "A bracelet", "A brooch"]),
        Q(1, "Chanel is a fashion house from which country?", "France", ["Italy", "United States", "Spain"]),
        Q(2, "Which house uses the interlocking 'GG' logo?", "Gucci", ["Guess", "Givenchy", "Gap"]),
        Q(2, "What is a capsule wardrobe?", "A small set of pieces that all mix and match", ["Clothes stored in vacuum bags", "A rental subscription", "A wardrobe of only bags"]),
        Q(2, "What is haute couture?", "Custom high fashion made by hand for one client", ["Off-the-rack clothing", "Vintage clothing", "Sportswear"]),
        Q(2, "The Birkin bag is made by which house?", "Hermès", ["Prada", "Louis Vuitton", "Dior"]),
        Q(2, "What does ready-to-wear mean?", "Clothing sold in standard sizes rather than custom made", ["Clothes that need no ironing", "Second-hand clothes", "Clothes still with tags"]),
        Q(2, "What is a peplum?", "A short flared ruffle at the waist", ["A neckline", "A sleeve", "A heel"]),
        Q(2, "Who makes the Air Force 1 sneaker?", "Nike", ["Adidas", "Puma", "Reebok"]),
        Q(2, "Cashmere comes from which animal?", "Goats", ["Sheep", "Alpacas", "Rabbits"]),
        Q(2, "A classic trench coat is made of what?", "Cotton gabardine", ["Leather", "Wool felt", "Velvet"], "Burberry invented gabardine in 1879."),
        Q(2, "Anna Wintour is famous as the editor of which magazine?", "Vogue", ["Elle", "Harper's Bazaar", "Cosmopolitan"]),
        Q(2, "What is tulle?", "A fine stiff netting used in tutus and veils", ["A heavy wool", "A leather finish", "A type of button"]),
        Q(2, "'Wide-leg,' 'bootcut,' and 'skinny' describe what?", "Jean cuts", ["Hat brims", "Collar shapes", "Heel heights"]),
        Q(3, "The 1947 'New Look,' with a cinched waist and full skirt, came from whom?", "Christian Dior", ["Coco Chanel", "Yves Saint Laurent", "Cristóbal Balenciaga"]),
        Q(3, "Which house created 'Le Smoking,' the 1966 tuxedo for women?", "Yves Saint Laurent", ["Chanel", "Armani", "Versace"]),
        Q(3, "'Quiet luxury' means what?", "Understated, logo-free expensive clothing", ["Silent auctions", "Loud prints", "Fast fashion"]),
        Q(3, "The Met Gala raises money for what?", "The Met's Costume Institute", ["A film festival", "Milan Fashion Week", "A perfume launch"]),
        Q(3, "Who is known for the 1974 wrap dress?", "Diane von Furstenberg", ["Donna Karan", "Vera Wang", "Stella McCartney"]),
        Q(3, "Bottega Veneta's signature technique is what?", "Intrecciato woven leather", ["Quilted leather", "Monogram canvas", "Studded leather"]),
        Q(3, "What are kitten heels?", "Short slender heels, roughly one to two inches", ["Platform heels", "Wedges", "Block heels"]),
        Q(3, "Which fashion week opens the 'big four' each September?", "New York", ["London", "Milan", "Paris"]),
        Q(3, "What is a cold-shoulder top?", "A top with cutouts that bare the shoulders", ["A sleeveless turtleneck", "A cropped hoodie", "An unlined jacket"]),
        Q(3, "The classic Hermès silk scarf is what size?", "90 by 90 centimeters", ["50 by 50", "120 by 120", "70 by 70"]),
        Q(3, "Which house's Speedy bag was made famous by Audrey Hepburn?", "Louis Vuitton", ["Chanel", "Fendi", "Coach"]),
        Q(3, "Miu Miu is the sister brand of which house?", "Prada", ["Gucci", "Fendi", "Versace"], "It's Miuccia Prada's childhood nickname."),
    ])

    static let romcoms = Deck(id: "romcoms", world: .hers, title: "Rom-Coms & Love Stories", tagline: "The lines, the leads, and the letters she never sent.", symbol: "heart.fill", colorHex: "E0435E", specs: [
        Q(1, "In 'The Notebook,' the couple is named what?", "Noah and Allie", ["Jack and Rose", "Ross and Rachel", "Edward and Bella"]),
        Q(1, "Who wrote 'Pride and Prejudice'?", "Jane Austen", ["Charlotte Brontë", "Emily Brontë", "Mary Shelley"]),
        Q(1, "In 'Titanic,' the two leads are who?", "Jack and Rose", ["Noah and Allie", "Danny and Sandy", "Harry and Sally"]),
        Q(1, "'You had me at hello' is from which movie?", "Jerry Maguire", ["Notting Hill", "Clueless", "Love Actually"]),
        Q(1, "In 'Twilight,' Bella falls for a what?", "Vampire", ["Werewolf", "Ghost", "Wizard"]),
        Q(1, "'Dirty Dancing': 'Nobody puts Baby in a ...'", "Corner", ["Cage", "Closet", "Car"]),
        Q(1, "Who plays the lead in 'Legally Blonde'?", "Reese Witherspoon", ["Julia Roberts", "Sandra Bullock", "Meg Ryan"]),
        Q(1, "In 'Grease,' the couple is who?", "Danny and Sandy", ["Jack and Rose", "Noah and Allie", "Ross and Rachel"]),
        Q(1, "Which of these is a Nora Ephron rom-com?", "When Harry Met Sally", ["Die Hard", "Jaws", "Gladiator"]),
        Q(1, "'Crazy Rich Asians' is mostly set where?", "Singapore", ["Tokyo", "Hong Kong", "Seoul"]),
        Q(1, "'Bridgerton' is set in which era?", "Regency England", ["Ancient Rome", "1980s New York", "Medieval France"]),
        Q(1, "In '10 Things I Hate About You,' Heath Ledger serenades her with which song?", "Can't Take My Eyes Off You", ["My Girl", "Uptown Girl", "Wonderwall"]),
        Q(2, "In 'Notting Hill,' Julia Roberts plays a what?", "Famous actress", ["Bookshop owner", "Chef", "Lawyer"]),
        Q(2, "'Sleepless in Seattle' ends on top of which landmark?", "The Empire State Building", ["The Golden Gate Bridge", "The Space Needle", "The Statue of Liberty"]),
        Q(2, "Which Sandra Bullock rom-com is built on a fake engagement for a green card?", "The Proposal", ["Miss Congeniality", "Two Weeks Notice", "While You Were Sleeping"]),
        Q(2, "In 'Love Actually,' the cue-card scene plays out while carolers sing what?", "Silent Night", ["Jingle Bells", "O Holy Night", "Deck the Halls"]),
        Q(2, "Cher in 'Clueless' is based on which Jane Austen heroine?", "Emma", ["Elizabeth Bennet", "Anne Elliot", "Fanny Price"]),
        Q(2, "Who wrote 'The Fault in Our Stars'?", "John Green", ["Nicholas Sparks", "Colleen Hoover", "Emily Henry"]),
        Q(2, "In 'Mamma Mia!', how many possible dads does Sophie invite?", "Three", ["Two", "Four", "Five"]),
        Q(2, "'You've Got Mail' centers on rival what?", "Bookstores", ["Bakeries", "Flower shops", "Radio stations"]),
        Q(2, "Colleen Hoover's 'It Ends with Us' heroine is named what?", "Lily", ["Rose", "Daisy", "Violet"]),
        Q(2, "In 'How to Lose a Guy in 10 Days,' Kate Hudson writes for a what?", "Women's magazine", ["Newspaper", "Ad agency", "TV station"]),
        Q(2, "'Outlander' involves time travel to which country?", "Scotland", ["Ireland", "Wales", "France"]),
        Q(2, "Who wrote 'The Notebook'?", "Nicholas Sparks", ["John Green", "Danielle Steel", "Nora Roberts"]),
        Q(3, "In Emily Henry's 'Beach Read,' the romance writer is paired with a writer of what?", "Literary fiction", ["Horror", "Science fiction", "Poetry"]),
        Q(3, "Mr. Darcy's estate in 'Pride and Prejudice' is called what?", "Pemberley", ["Netherfield", "Longbourn", "Rosings"]),
        Q(3, "The famous deli scene in 'When Harry Met Sally' was filmed where?", "Katz's Delicatessen", ["Carnegie Deli", "Zabar's", "Russ & Daughters"]),
        Q(3, "Which publisher is synonymous with mass-market romance novels?", "Harlequin", ["Penguin", "Bantam", "Scholastic"]),
        Q(3, "In 'Bridgerton' season one, the Duke of Hastings is named what?", "Simon", ["Anthony", "Colin", "Benedict"]),
        Q(3, "'Red, White & Royal Blue' pairs a British prince with whom?", "The son of the U.S. president", ["A Broadway actor", "A footballer", "A journalist"]),
        Q(3, "In 'The Holiday,' the two women swap what?", "Homes", ["Jobs", "Cars", "Names"]),
        Q(3, "Captain Wentworth is the love interest in which Austen novel?", "Persuasion", ["Emma", "Mansfield Park", "Northanger Abbey"]),
        Q(3, "Who won the screenplay Oscar for 1995's 'Sense and Sensibility'?", "Emma Thompson", ["Kate Winslet", "Ang Lee", "Hugh Grant"]),
        Q(3, "In 'Crazy, Stupid, Love,' who plays the smooth ladies' man Jacob?", "Ryan Gosling", ["Steve Carell", "Bradley Cooper", "Ryan Reynolds"]),
        Q(3, "Sally Rooney's 'Normal People' is set mostly where?", "Ireland", ["Scotland", "England", "Wales"]),
        Q(3, "In 'The Princess Bride,' 'As you wish' really means what?", "I love you", ["Goodbye", "Thank you", "I'm sorry"]),
    ])

    static let reality = Deck(id: "reality", world: .hers, title: "Reality TV", tagline: "Roses, pods, villas, and the tribe that has spoken.", symbol: "tv.fill", colorHex: "F26D3D", specs: [
        Q(1, "On 'The Bachelor,' what does the lead hand out to keep people around?", "Roses", ["Rings", "Keys", "Tickets"]),
        Q(1, "'Keeping Up with the Kardashians' followed which family?", "The Kardashian-Jenners", ["The Osbournes", "The Hiltons", "The Hadids"]),
        Q(1, "Which show has singles 'coupling up' in a villa?", "Love Island", ["Big Brother", "Survivor", "The Voice"]),
        Q(1, "'RuPaul's Drag Race' ends each episode with a what?", "Lip sync", ["Dance-off", "Cooking test", "Spelling bee"]),
        Q(1, "Which show locks housemates in a house full of cameras?", "Big Brother", ["Big Bang", "Big Little Lies", "Big Mouth"]),
        Q(1, "On 'The Great British Bake Off,' the best baker of the week is named what?", "Star Baker", ["Head Chef", "Top Cook", "Golden Whisk"]),
        Q(1, "The 'Real Housewives' franchise started in which city?", "Orange County", ["Atlanta", "New York", "Beverly Hills"]),
        Q(1, "Tan, Antoni, Jonathan, Karamo, and Bobby are the cast of what?", "Queer Eye", ["Love Is Blind", "Selling Sunset", "The Circle"]),
        Q(1, "On 'Love Is Blind,' contestants first talk in what?", "Pods", ["Cars", "Boats", "Elevators"]),
        Q(1, "'Selling Sunset' is about selling what?", "Luxury real estate", ["Cars", "Sunglasses", "Wine"]),
        Q(1, "A rose ceremony decides what?", "Who stays on The Bachelor", ["Who wins Drag Race", "Who bakes next", "Who cooks dinner"]),
        Q(1, "'Vanderpump Rules' is set in which city?", "Los Angeles", ["Miami", "New York", "Las Vegas"]),
        Q(2, "On 'Survivor,' what is said when someone is voted out?", "The tribe has spoken", ["You're fired", "Please pack your knives", "Sashay away"]),
        Q(2, "'Sashay away' is the send-off on which show?", "RuPaul's Drag Race", ["Project Runway", "Top Chef", "Survivor"]),
        Q(2, "Heidi Klum's 'Project Runway' catchphrase was what?", "One day you're in, and the next day you're out", ["The tribe has spoken", "Pack your knives and go", "You're fired"]),
        Q(2, "'Please pack your knives and go' is from which show?", "Top Chef", ["Hell's Kitchen", "MasterChef", "Chopped"]),
        Q(2, "'Vanderpump Rules' spun off from which Real Housewives city?", "Beverly Hills", ["Orange County", "New York", "Atlanta"]),
        Q(2, "The Bachelor spin-off set at a beach resort with past contestants is called what?", "Bachelor in Paradise", ["Bachelor Island", "Bachelor Beach", "Love After Roses"]),
        Q(2, "Who said 'Kim, there's people that are dying'?", "Kourtney Kardashian", ["Kim Kardashian", "Khloé Kardashian", "Kris Jenner"]),
        Q(2, "Maddie Ziegler of 'Dance Moms' starred in music videos for which singer?", "Sia", ["Adele", "Lorde", "Halsey"]),
        Q(2, "On 'The Circle,' players communicate only through what?", "A social media app", ["Phone calls", "Letters", "Video chat"]),
        Q(2, "On 'Married at First Sight,' couples meet for the first time where?", "At the altar", ["At dinner", "On a plane", "In pods"]),
        Q(2, "'Below Deck' follows the crew of a what?", "Superyacht", ["Cruise ship", "Fishing boat", "Submarine"]),
        Q(2, "In 2022 'The Kardashians' moved from E! to which streamer?", "Hulu", ["Netflix", "HBO Max", "Peacock"]),
        Q(3, "'Scandoval' (2023) was a cheating scandal on which show?", "Vanderpump Rules", ["Love Island", "The Bachelor", "Selling Sunset"]),
        Q(3, "The famous table flip happened on which Real Housewives franchise?", "New Jersey", ["Atlanta", "New York", "Orange County"], "Teresa Giudice, season one finale."),
        Q(3, "Who hosts the U.S. version of 'The Traitors'?", "Alan Cumming", ["Andy Cohen", "Nick Cannon", "Jeff Probst"]),
        Q(3, "On 'Survivor,' the fire-making challenge decides what?", "The last spot in the final three", ["The overall winner", "Immunity at the merge", "Who goes to Exile Island"]),
        Q(3, "On 'Love Island,' a buzzing phone means someone shouts what?", "I've got a text!", ["You've got mail!", "Ring ring!", "Incoming!"]),
        Q(3, "On The Bachelor, 'Can I steal you for a second?' is used to do what?", "Pull the lead aside for one-on-one time", ["Ask for a rose", "Leave the show", "Ask for a date card"]),
        Q(3, "Before the Netflix reboot, 'Queer Eye' originally aired on which network?", "Bravo", ["MTV", "E!", "VH1"]),
        Q(3, "'The Hills' was a spin-off of which show?", "Laguna Beach", ["The O.C.", "Newport Harbor", "The Real World"]),
        Q(3, "On 'Too Hot to Handle,' the rules are enforced by a virtual assistant named what?", "Lana", ["Alexa", "Siri", "Cortana"]),
        Q(3, "The winner of 'RuPaul's Drag Race' is crowned what?", "America's Next Drag Superstar", ["Queen of the Runway", "Drag Idol", "Miss Congeniality"]),
        Q(3, "'The Real World' premiered on MTV in which year?", "1992", ["1985", "1999", "2003"]),
        Q(3, "Andy Cohen hosts which late-night Bravo show?", "Watch What Happens Live", ["Late Night Bravo", "The Andy Show", "After Hours"]),
    ])

    static let divas = Deck(id: "divas", world: .hers, title: "Pop Divas & Their Eras", tagline: "Swifties, the Beyhive, and who wrote what.", symbol: "music.mic", colorHex: "C026D3", specs: [
        Q(1, "Taylor Swift's fans call themselves what?", "Swifties", ["Little Monsters", "The Beyhive", "Arianators"]),
        Q(1, "Whose fans are the Beyhive?", "Beyoncé", ["Rihanna", "Adele", "Lady Gaga"]),
        Q(1, "Fenty Beauty was founded by whom?", "Rihanna", ["Beyoncé", "Selena Gomez", "Kylie Jenner"]),
        Q(1, "Lady Gaga's fans are called what?", "Little Monsters", ["Swifties", "Beliebers", "Barbz"]),
        Q(1, "Who released the album '30'?", "Adele", ["Taylor Swift", "Ariana Grande", "Dua Lipa"]),
        Q(1, "Rare Beauty is the makeup brand of whom?", "Selena Gomez", ["Ariana Grande", "Miley Cyrus", "Demi Lovato"]),
        Q(1, "Beyoncé got her start in which group?", "Destiny's Child", ["Spice Girls", "TLC", "Fifth Harmony"]),
        Q(1, "Which Taylor Swift tour became a record-breaking phenomenon in 2023 and 2024?", "The Eras Tour", ["The Red Tour", "Reputation Stadium Tour", "1989 World Tour"]),
        Q(1, "Ariana Grande starred in which 2024 movie?", "Wicked", ["Barbie", "Mean Girls", "Wonka"]),
        Q(1, "'Espresso' (2024) is a hit by whom?", "Sabrina Carpenter", ["Olivia Rodrigo", "Chappell Roan", "Billie Eilish"]),
        Q(1, "Olivia Rodrigo's breakout single was what?", "drivers license", ["Espresso", "Levitating", "bad guy"]),
        Q(1, "Which singer is nicknamed Queen B?", "Beyoncé", ["Britney Spears", "Billie Eilish", "Bebe Rexha"]),
        Q(2, "Taylor Swift's re-recorded albums carry which label?", "(Taylor's Version)", ["(Remastered)", "(Deluxe)", "(Redux)"]),
        Q(2, "'All Too Well (10 Minute Version)' is on which album?", "Red (Taylor's Version)", ["1989", "folklore", "Lover"]),
        Q(2, "Beyoncé's 2016 visual album was called what?", "Lemonade", ["Renaissance", "Cowboy Carter", "4"]),
        Q(2, "Dua Lipa's disco-flavored 2020 album was what?", "Future Nostalgia", ["Radical Optimism", "Dua Lipa", "Levitating"]),
        Q(2, "Billie Eilish's brother and producer is named what?", "Finneas", ["Phineas", "Fernando", "Felix"]),
        Q(2, "Which Spice Girl was Posh?", "Victoria Beckham", ["Mel B", "Emma Bunton", "Geri Halliwell"]),
        Q(2, "'vampire' and 'good 4 u' are by whom?", "Olivia Rodrigo", ["Sabrina Carpenter", "Gracie Abrams", "Tate McRae"]),
        Q(2, "Chappell Roan's 2024 breakout hit was what?", "Good Luck, Babe!", ["Espresso", "Birds of a Feather", "Greedy"]),
        Q(2, "Rihanna is from which country?", "Barbados", ["Jamaica", "Trinidad and Tobago", "The Bahamas"]),
        Q(2, "Miley Cyrus's Disney character was who?", "Hannah Montana", ["Lizzie McGuire", "Raven", "Alex Russo"]),
        Q(2, "Adele's albums are named after what?", "Her age when she made them", ["Cities", "Colors", "Seasons"]),
        Q(2, "Mariah Carey's holiday classic is what?", "All I Want for Christmas Is You", ["Last Christmas", "Santa Tell Me", "Mistletoe"]),
        Q(3, "Taylor Swift released 'folklore' and 'evermore' in which year?", "2020", ["2019", "2021", "2022"]),
        Q(3, "Beyoncé's 'Cowboy Carter' (2024) is her take on which genre?", "Country", ["Jazz", "Disco", "Gospel"]),
        Q(3, "Lady Gaga won her Oscar for which song?", "Shallow", ["Bad Romance", "Hold My Hand", "Always Remember Us This Way"]),
        Q(3, "Who wrote 'I Will Always Love You,' the song Whitney Houston made huge?", "Dolly Parton", ["Whitney Houston", "Diane Warren", "Carole King"]),
        Q(3, "'Anti-Hero' and 'Karma' are on which Taylor Swift album?", "Midnights", ["Lover", "evermore", "The Tortured Poets Department"]),
        Q(3, "How many exes does Ariana Grande name in 'thank u, next'?", "Four", ["Two", "Three", "Five"]),
        Q(3, "Dolly Parton's theme park is called what?", "Dollywood", ["Dollyland", "Parton Park", "Jolene World"]),
        Q(3, "Whose 2022 album 'Renaissance' celebrated house music and ballroom culture?", "Beyoncé", ["Madonna", "Rihanna", "Dua Lipa"]),
        Q(3, "Britney Spears's 2023 memoir is titled what?", "The Woman in Me", ["Oops... I Did It Again", "Toxic", "Britney Jean"]),
        Q(3, "Sabrina Carpenter's 2024 album is called what?", "Short n' Sweet", ["Emails I Can't Send", "Singular", "Guts"]),
        Q(3, "Madonna's nickname is what?", "Queen of Pop", ["Queen of Soul", "Queen of Country", "Queen of Rock"]),
        Q(3, "Whose 'Eras Tour' concert film hit theaters in October 2023?", "Taylor Swift", ["Beyoncé", "Olivia Rodrigo", "Adele"]),
    ])

    static let weddings = Deck(id: "weddings", world: .hers, title: "Wedding Season", tagline: "Registries, mimosas, and what your rising sign means.", symbol: "sparkles", colorHex: "0EA5A4", specs: [
        Q(1, "What does RSVP on an invitation mean?", "Please reply", ["Bring a gift", "Dress formally", "Arrive early"], "From the French 'répondez s'il vous plaît.'"),
        Q(1, "Who traditionally stands beside the bride at the ceremony?", "The maid of honor", ["The best man", "The officiant", "The ring bearer"]),
        Q(1, "What is a bridal shower?", "A pre-wedding party where the bride gets gifts", ["The bride's morning routine", "The rehearsal", "A spa day on the honeymoon"]),
        Q(1, "Something old, something new, something borrowed, something ...", "Blue", ["Gold", "Pink", "Green"]),
        Q(1, "What does the bride toss to the single guests?", "The bouquet", ["The cake", "The veil", "The rings"]),
        Q(1, "A mimosa is orange juice and what?", "Champagne", ["Vodka", "Gin", "Beer"]),
        Q(1, "Avocado toast is a staple of which meal?", "Brunch", ["Midnight snack", "Tea time", "Dessert"]),
        Q(1, "Which zodiac sign is the lion?", "Leo", ["Aries", "Taurus", "Scorpio"]),
        Q(1, "What is a save-the-date?", "An early heads-up sent before the invitation", ["The gift registry", "A honeymoon booking", "The seating chart"]),
        Q(1, "What is a wedding registry?", "A list of gifts the couple would like", ["The guest list", "The marriage license", "The DJ playlist"]),
        Q(1, "What do the newlyweds traditionally do first at the reception?", "A first dance", ["Cut the cake", "Toss the bouquet", "Leave early"]),
        Q(1, "What is a bachelorette party?", "A pre-wedding celebration for the bride", ["A post-wedding brunch", "The rehearsal dinner", "The engagement party"]),
        Q(2, "What is a rehearsal dinner?", "Dinner the night before the wedding, after practicing the ceremony", ["The first dinner after the honeymoon", "The engagement dinner", "The reception"]),
        Q(2, "A sweetheart table seats whom?", "Just the couple", ["The parents", "The wedding party", "The kids"]),
        Q(2, "What is a boutonnière?", "A small flower worn on a lapel", ["A bridal veil", "A cake topper", "A garter"]),
        Q(2, "Which zodiac sign is the scales?", "Libra", ["Gemini", "Virgo", "Aquarius"]),
        Q(2, "Mercury retrograde gets blamed for what?", "Communication and tech mishaps", ["Bad weather", "Sports losses", "Frizzy hair"]),
        Q(2, "Which of these is a fire sign?", "Aries", ["Cancer", "Pisces", "Taurus"]),
        Q(2, "What is a first look?", "The couple seeing each other before the ceremony, usually with a photographer", ["The first dance", "The engagement photo", "The proposal"]),
        Q(2, "What is a trousseau?", "A bride's collection of clothes and linens for married life", ["The wedding cake", "The bridal bouquet", "The wedding car"]),
        Q(2, "A Bellini is Prosecco and what?", "Peach purée", ["Orange juice", "Cranberry juice", "Lime juice"]),
        Q(2, "In astrology, the 'big three' are what?", "Sun, Moon, and Rising signs", ["Fire, Earth, and Water", "Past, Present, and Future", "Leo, Scorpio, and Aries"]),
        Q(2, "What does the best man traditionally hold before the vows?", "The rings", ["The bouquet", "The license", "The veil"]),
        Q(2, "In the U.S., the wedding ring is worn where?", "Fourth finger of the left hand", ["Index finger", "Thumb", "Right pinky"]),
        Q(3, "Traditionally, the groom's family paid for what?", "The rehearsal dinner", ["The cake", "The dress", "The flowers"]),
        Q(3, "A cathedral veil is what?", "The longest style, extending past the train", ["A short shoulder veil", "A birdcage veil", "A veil with a crown"]),
        Q(3, "The 'something blue' rhyme comes from where?", "Victorian England", ["France", "Italy", "Greece"]),
        Q(3, "'Eloping' originally meant what?", "Running away to marry in secret", ["A big destination wedding", "A courthouse wedding", "A second wedding"]),
        Q(3, "Scorpio is which kind of sign?", "A water sign", ["A fire sign", "An earth sign", "An air sign"]),
        Q(3, "A charcuterie board is what?", "A spread of cured meats, cheeses, and accompaniments", ["A dessert platter", "A brunch cocktail", "A cheese fondue"]),
        Q(3, "In Britain, a 'hen do' is what?", "A bachelorette party", ["A bridal shower", "A rehearsal dinner", "A baby shower"]),
        Q(3, "Your 'Saturn return' hits around what age?", "29 to 30", ["18", "40", "50"]),
        Q(3, "In the U.S., the average engagement lasts about how long?", "About a year", ["About a month", "About three years", "About five years"]),
        Q(3, "The Southern tradition of 'cake pulling' involves what?", "Bridesmaids pulling charms from the cake", ["Cutting the cake with a sword", "Eating cake for luck", "Hiding the groom's cake"]),
        Q(3, "The groom's cake tradition is tied to which U.S. region?", "The South", ["New England", "The Pacific Northwest", "The Midwest"]),
        Q(3, "'Brunch' blends which two words?", "Breakfast and lunch", ["Bread and crunch", "Bar and lunch", "Breakfast and munch"]),
    ])
}
