import Foundation

extension HerWorld {
    static let bookclub = Deck(id: "bookclub", world: .hers, title: "Book Club", tagline: "BookTok, bestsellers, and the TBR pile that never shrinks.", colorHex: "5B5BD6", specs: [
        Q(1, "Who wrote 'Where the Crawdads Sing'?", "Delia Owens", ["Kristin Hannah", "Liane Moriarty", "Celeste Ng"]),
        Q(1, "Who wrote 'Gone Girl'?", "Gillian Flynn", ["Paula Hawkins", "Tana French", "Ruth Ware"]),
        Q(1, "'Fourth Wing' is set at a war college that trains riders of what?", "Dragons", ["Horses", "Griffins", "Wolves"]),
        Q(1, "In BookTok slang, ACOTAR stands for what?", "A Court of Thorns and Roses", ["A Castle of Time and Rain", "All Cats on the Roof", "A Crown of Thieves and Ruin"]),
        Q(1, "Who wrote 'The Seven Husbands of Evelyn Hugo'?", "Taylor Jenkins Reid", ["Emily Henry", "Colleen Hoover", "Sally Rooney"]),
        Q(1, "'Daisy Jones & The Six' is about what?", "A 1970s rock band", ["A girls' boarding school", "A Nashville songwriter", "Six sisters in Texas"]),
        Q(1, "Who wrote 'The Handmaid's Tale'?", "Margaret Atwood", ["Toni Morrison", "Alice Walker", "Ursula K. Le Guin"]),
        Q(1, "Who wrote 'Eat Pray Love'?", "Elizabeth Gilbert", ["Cheryl Strayed", "Glennon Doyle", "Brené Brown"]),
        Q(1, "'Verity' is a thriller by which usually-romance author?", "Colleen Hoover", ["Emily Henry", "Ali Hazelwood", "Tessa Bailey"]),
        Q(1, "'It Starts with Us' is the sequel to what?", "It Ends with Us", ["Ugly Love", "Verity", "November 9"]),
        Q(1, "Which app lets you borrow library ebooks for free?", "Libby", ["Kindle Unlimited", "Audible", "Scribd"]),
        Q(1, "Who wrote 'Little Women'?", "Louisa May Alcott", ["Jane Austen", "Charlotte Brontë", "Edith Wharton"]),
        Q(2, "Who wrote 'Fourth Wing'?", "Rebecca Yarros", ["Sarah J. Maas", "Leigh Bardugo", "Holly Black"]),
        Q(2, "Who wrote the ACOTAR series?", "Sarah J. Maas", ["Rebecca Yarros", "Jennifer L. Armentrout", "Cassandra Clare"]),
        Q(2, "In 'Lessons in Chemistry,' Elizabeth Zott ends up hosting what?", "A TV cooking show", ["A radio call-in show", "A science podcast", "A talk show for kids"]),
        Q(2, "Who wrote 'Little Fires Everywhere'?", "Celeste Ng", ["Liane Moriarty", "Ann Patchett", "Jodi Picoult"]),
        Q(2, "Who wrote 'The Midnight Library'?", "Matt Haig", ["Fredrik Backman", "Neil Gaiman", "David Nicholls"]),
        Q(2, "The Booker Prize is a major literary award based in which country?", "The United Kingdom", ["The United States", "Canada", "Australia"]),
        Q(2, "Oprah's Book Club started in which year?", "1996", ["1988", "2001", "2005"]),
        Q(2, "Kristin Hannah's 'The Nightingale' is set during what?", "World War II", ["The Civil War", "The Great Depression", "The Vietnam War"]),
        Q(2, "'Tomorrow, and Tomorrow, and Tomorrow' follows two friends who make what?", "Video games", ["Movies", "Podcasts", "Perfume"]),
        Q(2, "'Iron Flame' is the sequel to what?", "Fourth Wing", ["A Court of Mist and Fury", "Powerless", "Shadow and Bone"]),
        Q(2, "Who wrote 'A Little Life'?", "Hanya Yanagihara", ["Donna Tartt", "Ottessa Moshfegh", "Sally Rooney"]),
        Q(2, "Who wrote 'Wuthering Heights'?", "Emily Brontë", ["Charlotte Brontë", "Anne Brontë", "Mary Shelley"]),
        Q(3, "Charlotte Brontë first published 'Jane Eyre' under what name?", "Currer Bell", ["Ellis Bell", "Acton Bell", "George Eliot"], "Emily and Anne published as Ellis and Acton Bell."),
        Q(3, "Novelist George Eliot's real name was what?", "Mary Ann Evans", ["Elizabeth Gaskell", "Mary Wollstonecraft", "Charlotte Brontë"], "She wrote 'Middlemarch' and 'Silas Marner' under the pen name."),
        Q(3, "Liane Moriarty's novel 'Big Little Lies' is set in which country?", "Australia", ["The United States", "New Zealand", "England"], "HBO moved the story to Monterey, California."),
        Q(3, "In 'Evelyn Hugo,' which reporter does Evelyn choose to tell her story?", "Monique Grant", ["Celia St. James", "Daisy Jones", "Nina Riva"], "Why Evelyn chose Monique is the book's final reveal."),
        Q(3, "In 'Fourth Wing,' Violet bonds with which black dragon?", "Tairn", ["Sgaeyl", "Cath", "Deigh"], "Tairn's mate, Sgaeyl, is bonded to Xaden Riorson."),
        Q(3, "Who narrates Madeline Miller's 'The Song of Achilles'?", "Patroclus", ["Achilles", "Odysseus", "Briseis"], "It won the 2012 Orange Prize for Fiction."),
        Q(3, "What was the very first pick of Oprah's Book Club?", "The Deep End of the Ocean", ["Song of Solomon", "She's Come Undone", "The Book of Ruth"], "Toni Morrison's 'Song of Solomon' was the second pick, a month later."),
        Q(3, "What was Colleen Hoover's debut novel?", "Slammed", ["Ugly Love", "Hopeless", "It Ends with Us"], "She self-published it in 2012 so her mother could read it on her new Kindle."),
        Q(3, "What was Sally Rooney's debut novel?", "Conversations with Friends", ["Normal People", "Beautiful World, Where Are You", "Intermezzo"], "'Normal People' followed a year later, in 2018."),
        Q(3, "'Frankenstein' is subtitled 'The Modern' what?", "Prometheus", ["Lazarus", "Icarus", "Pygmalion"], "Mary Shelley started writing it when she was 18."),
        Q(3, "In Kristin Hannah's 'The Nightingale,' the sisters are Vianne and who?", "Isabelle", ["Rachel", "Sophie", "Madeleine"], "Isabelle's Resistance code name, the Nightingale, gives the book its title."),
        Q(3, "Which Austen novel was first published after her death, alongside 'Persuasion'?", "Northanger Abbey", ["Emma", "Mansfield Park", "Sense and Sensibility"], "The two came out together in December 1817, months after Austen died that July."),
    ])

    static let wellness = Deck(id: "wellness", world: .hers, title: "Wellness & Self-Care", tagline: "Pilates, matcha, cold plunges, and eight hours of sleep.", colorHex: "3DBF8A", specs: [
        Q(1, "What kind of exercise class is barre inspired by?", "Ballet", ["Boxing", "Rowing", "Gymnastics"]),
        Q(1, "HIIT stands for what?", "High-Intensity Interval Training", ["Heavy Iron Indoor Training", "Hot Isometric Interval Time", "High-Impact Indoor Toning"]),
        Q(1, "A reformer is equipment used in what?", "Pilates", ["CrossFit", "Spin class", "Barre"]),
        Q(1, "Cortisol is often called what?", "The stress hormone", ["The sleep hormone", "The love hormone", "The hunger hormone"]),
        Q(1, "Kombucha is what?", "Fermented tea", ["Sparkling coffee", "A yogurt drink", "Coconut water"]),
        Q(1, "Goop was founded by which actress?", "Gwyneth Paltrow", ["Jessica Alba", "Reese Witherspoon", "Kate Hudson"]),
        Q(1, "Oura is a fitness tracker worn as a what?", "A ring", ["A watch", "A headband", "An ankle strap"]),
        Q(1, "In the 16:8 style of intermittent fasting, what is the 8?", "Hours you can eat", ["Hours you fast", "Glasses of water", "Days per week"]),
        Q(1, "A 'hot girl walk' is what?", "A long walk for a mood and confidence boost", ["A treadmill sprint", "A hike with weights", "A walk to the gym"]),
        Q(1, "Collagen, popular in supplements, is a type of what?", "Protein", ["Vitamin", "Carbohydrate", "Mineral"]),
        Q(1, "The Calm app is famous for what?", "Sleep stories and meditation", ["Step counting", "Recipe plans", "Run tracking"]),
        Q(1, "'Macros' is short for what?", "Macronutrients: protein, carbs, and fat", ["Macro workouts", "Major calories", "Meal accounts"]),
        Q(2, "Pilates was invented by Joseph Pilates, who was born where?", "Germany", ["The United States", "Italy", "Sweden"]),
        Q(2, "A traditional Bikram yoga class has how many postures?", "26", ["12", "40", "108"]),
        Q(2, "Erewhon, famous for pricey smoothies, is what kind of business?", "A Los Angeles grocery store", ["A yoga chain", "A supplement brand", "A spa"]),
        Q(2, "The '10,000 steps a day' target began as marketing for what?", "A 1960s Japanese pedometer", ["A 1980s Nike shoe", "A Fitbit launch", "A 1990s diet book"]),
        Q(2, "Lululemon was founded in which city?", "Vancouver", ["Los Angeles", "Sydney", "Portland"]),
        Q(2, "Wim Hof is famous for what?", "Cold exposure and breathing techniques", ["Marathon running", "Vegan cooking", "Sleep coaching"]),
        Q(2, "The 'sleepy girl mocktail' mixes magnesium with which juice?", "Tart cherry", ["Orange", "Cranberry", "Pineapple"]),
        Q(2, "Ozempic was originally approved to treat what?", "Type 2 diabetes", ["High blood pressure", "Migraines", "Insomnia"]),
        Q(2, "Roughly how much protein is in one large egg?", "About 6 grams", ["About 1 gram", "About 15 grams", "About 25 grams"]),
        Q(2, "Which form of magnesium is the popular pick for sleep?", "Magnesium glycinate", ["Magnesium sulfate", "Magnesium oxide", "Magnesium chloride"]),
        Q(2, "How does a sauna differ from a steam room?", "A sauna uses dry heat", ["A sauna is colder", "A sauna uses water jets", "A sauna is only outdoors"]),
        Q(2, "Alo Yoga is headquartered in which city?", "Los Angeles", ["New York", "Vancouver", "Miami"]),
        Q(3, "What did Joseph Pilates originally call his method?", "Contrology", ["Coreology", "Kinetics", "Body Balance"], "He refined it while interned on the Isle of Man during World War I."),
        Q(3, "Matcha is stone-ground from shade-grown leaves called what?", "Tencha", ["Sencha", "Hojicha", "Genmaicha"], "The tea bushes are covered to block sunlight for weeks before harvest."),
        Q(3, "The Yoga Sutras are traditionally credited to whom?", "Patanjali", ["Valmiki", "Kalidasa", "Chanakya"], "The text is a set of 195 or 196 short Sanskrit aphorisms."),
        Q(3, "In 1968, the Beatles studied meditation in which Indian town?", "Rishikesh", ["Goa", "Mysore", "Dharamshala"], "They trained in Transcendental Meditation at Maharishi Mahesh Yogi's ashram."),
        Q(3, "Who developed Mindfulness-Based Stress Reduction (MBSR)?", "Jon Kabat-Zinn", ["Deepak Chopra", "Thich Nhat Hanh", "Eckhart Tolle"], "He started it in 1979 at the University of Massachusetts Medical School."),
        Q(3, "The barre workout traces back to Lotte Berk's 1959 studio in which city?", "London", ["New York", "Paris", "Los Angeles"], "Berk, a German-born dancer, taught in a basement studio on Manchester Street."),
        Q(3, "Kefir, the fermented milk drink, is traditionally from which mountain region?", "The Caucasus", ["The Alps", "The Himalayas", "The Andes"], "It was traditionally fermented in goatskin bags hung near the door."),
        Q(3, "The Ayurvedic herb ashwagandha's name means what in Sanskrit?", "Smell of a horse", ["Strength of a lion", "Root of calm", "Gift of the sun"], "The root has a strong, horse-like odor."),
        Q(3, "In a Finnish sauna, what is 'löyly'?", "Steam from water on hot stones", ["The birch-twig whisk", "The cold plunge after", "The top bench"], "The word originally meant 'spirit' or 'life.'"),
        Q(3, "Zumba was created by a fitness instructor from which country?", "Colombia", ["Brazil", "Cuba", "Puerto Rico"], "Beto Pérez forgot his usual music and taught with salsa and merengue tapes."),
        Q(3, "In Ayurveda, the three doshas are vata, pitta, and what?", "Kapha", ["Ojas", "Prana", "Agni"], "The three are traditionally linked to wind, bile, and phlegm."),
        Q(3, "A Tabata round is 20 seconds of all-out work, then how much rest?", "10 seconds", ["5 seconds", "20 seconds", "40 seconds"], "It's named for Japanese scientist Izumi Tabata; eight rounds take four minutes."),
    ])

    static let gossip = Deck(id: "gossip", world: .hers, title: "Celebrity Couples & Gossip", tagline: "Who's dating, who's engaged, and who conscious-uncoupled.", colorHex: "FFB020", specs: [
        Q(1, "Tom Brady's ex-wife is which supermodel?", "Gisele Bündchen", ["Adriana Lima", "Heidi Klum", "Karlie Kloss"]),
        Q(1, "Kourtney Kardashian married which drummer?", "Travis Barker", ["Tommy Lee", "Dave Grohl", "Travis Scott"]),
        Q(1, "Kylie Jenner dated which 'Dune' actor?", "Timothée Chalamet", ["Austin Butler", "Jacob Elordi", "Paul Mescal"]),
        Q(1, "Priyanka Chopra is married to which Jonas brother?", "Nick", ["Joe", "Kevin", "Frankie"]),
        Q(1, "Rihanna's partner and the father of her sons is which rapper?", "A$AP Rocky", ["Drake", "Travis Scott", "Chris Brown"]),
        Q(1, "Chrissy Teigen is married to which singer?", "John Legend", ["John Mayer", "Usher", "Bruno Mars"]),
        Q(1, "At the 2022 Oscars, Will Smith slapped whom?", "Chris Rock", ["Kevin Hart", "Jimmy Kimmel", "Dave Chappelle"]),
        Q(1, "Jennifer Aniston was married to Brad Pitt and which other actor?", "Justin Theroux", ["Vince Vaughn", "John Mayer", "Paul Rudd"]),
        Q(1, "Kate Middleton's official title is what?", "Princess of Wales", ["Duchess of Sussex", "Queen Consort", "Princess Royal"]),
        Q(1, "Selena Gomez got engaged in 2024 to which producer?", "Benny Blanco", ["Justin Bieber", "The Weeknd", "Zedd"]),
        Q(1, "Pete Davidson dated Kim Kardashian and which pop star?", "Ariana Grande", ["Miley Cyrus", "Dua Lipa", "Olivia Rodrigo"]),
        Q(1, "Beyoncé and Jay-Z's first daughter is named what?", "Blue Ivy", ["North", "Stormi", "Rumi"]),
        Q(2, "Gwyneth Paltrow and Chris Martin famously called their split what?", "Conscious uncoupling", ["A soft launch", "A brand pivot", "A gentle exit"]),
        Q(2, "Britney Spears's ex-husband Kevin Federline was a what?", "Backup dancer", ["Record producer", "Actor", "DJ"]),
        Q(2, "Paris Hilton and Nicole Richie starred in which early-2000s reality show?", "The Simple Life", ["The Hills", "Laguna Beach", "Rich Girls"]),
        Q(2, "Tom Cruise's ex-wife Katie Holmes starred in which teen drama?", "Dawson's Creek", ["The O.C.", "One Tree Hill", "Gilmore Girls"]),
        Q(2, "Which Marvel actor married Portuguese actress Alba Baptista in 2023?", "Chris Evans", ["Chris Hemsworth", "Chris Pratt", "Sebastian Stan"]),
        Q(2, "Sabrina Carpenter dated which 'Saltburn' actor?", "Barry Keoghan", ["Jacob Elordi", "Paul Mescal", "Archie Madekwe"]),
        Q(2, "Olivia Wilde dated which former boy-band member?", "Harry Styles", ["Zayn Malik", "Niall Horan", "Nick Jonas"]),
        Q(2, "Kim Kardashian and Kanye West's kids are North, Saint, Chicago, and who?", "Psalm", ["Reign", "Stormi", "True"]),
        Q(2, "Megan Fox has a daughter with which musician?", "Machine Gun Kelly", ["Post Malone", "Travis Barker", "Blake Shelton"]),
        Q(2, "Oprah's bombshell interview with Harry and Meghan aired in which year?", "2021", ["2019", "2020", "2022"]),
        Q(2, "Ryan Reynolds and Blake Lively have how many children?", "Four", ["Two", "Three", "Five"]),
        Q(2, "Sofía Vergara's ex-husband Joe Manganiello starred in which movie series?", "Magic Mike", ["Fast & Furious", "Twilight", "John Wick"]),
        Q(3, "George and Amal Clooney married in 2014 in which Italian city?", "Venice", ["Florence", "Rome", "Milan"], "Former Rome mayor Walter Veltroni officiated at Ca' Farsetti."),
        Q(3, "Kourtney Kardashian and Travis Barker's 2022 Italian wedding was in which town?", "Portofino", ["Positano", "Capri", "Bellagio"], "They had married legally in Santa Barbara a week earlier."),
        Q(3, "Priyanka Chopra and Nick Jonas married in 2018 in which Indian city?", "Jodhpur", ["Udaipur", "Jaipur", "Mumbai"], "They held Hindu and Christian ceremonies at Umaid Bhawan Palace."),
        Q(3, "Gwen Stefani and Blake Shelton married in 2021 on his ranch in which state?", "Oklahoma", ["Tennessee", "Texas", "Montana"], "They met as coaches on 'The Voice.'"),
        Q(3, "Kristen Bell and Dax Shepard's 2013 wedding took place where?", "A Beverly Hills courthouse", ["A Malibu beach", "A Las Vegas chapel", "A Napa vineyard"], "They waited to marry until same-sex marriage was legal in California."),
        Q(3, "Humphrey Bogart and Lauren Bacall first starred together in which film?", "To Have and Have Not", ["Casablanca", "The Big Sleep", "Key Largo"], "It was Bacall's film debut; they married in 1945."),
        Q(3, "Beyoncé and Jay-Z released their 2018 joint album under what name?", "The Carters", ["The Knowles", "The Throne", "Bey & Hov"], "'Everything Is Love' won the Grammy for Best Urban Contemporary Album."),
        Q(3, "What was Beyoncé and Jay-Z's first song together?", "'03 Bonnie & Clyde", ["Crazy in Love", "Drunk in Love", "Déjà Vu"], "It samples Tupac's 1996 song 'Me and My Girlfriend.'"),
        Q(3, "Jennifer Lopez wore her famous green Versace dress to which event?", "The 2000 Grammys", ["The 2000 Oscars", "The 2000 Golden Globes", "The 2000 MTV VMAs"], "Google's Eric Schmidt said searches for it led to Google Images."),
        Q(3, "Serena Williams married the co-founder of which website?", "Reddit", ["Twitter", "Pinterest", "Tumblr"], "They married in New Orleans in 2017."),
        Q(3, "Paul Newman was married for 50 years to which actress?", "Joanne Woodward", ["Elizabeth Taylor", "Natalie Wood", "Lee Remick"], "They met in the 1953 Broadway production of 'Picnic.'"),
        Q(3, "Kelly Ripa met Mark Consuelos on the set of which soap opera?", "All My Children", ["General Hospital", "Days of Our Lives", "One Life to Live"], "They played love interests on the show and eloped in Las Vegas in 1996."),
    ])
}
