import Foundation

extension HisWorld {
    static let actionmovies = Deck(id: "actionmovies", world: .his, title: "Action Movies & Dad TV", tagline: "Yippee-ki-yay, Nakatomi Plaza, and every Dutton.", symbol: "film.fill", colorHex: "0D9488", specs: [
        Q(1, "Who plays John McClane in 'Die Hard'?", "Bruce Willis", ["Mel Gibson", "Arnold Schwarzenegger", "Harrison Ford"]),
        Q(1, "James Bond's code number is what?", "007", ["001", "009", "077"]),
        Q(1, "'Rocky' is about a what?", "Boxer", ["Race car driver", "Wrestler", "Football coach"]),
        Q(1, "'Top Gun' is about what?", "Fighter pilots", ["Race car drivers", "Navy SEALs", "Astronauts"]),
        Q(1, "The 'Fast & Furious' movies started out being about what?", "Street racing", ["Bank robbers", "Spies", "Boxing"]),
        Q(1, "'I'll be back' is the catchphrase from which movie?", "The Terminator", ["Predator", "RoboCop", "Rambo"]),
        Q(1, "'Jurassic Park' is about a theme park full of what?", "Dinosaurs", ["Robots", "Sharks", "Aliens"]),
        Q(1, "In 'Breaking Bad,' Walter White is a chemistry teacher who starts making what?", "Meth", ["Moonshine", "Counterfeit money", "Fireworks"]),
        Q(1, "'The Sopranos' is about a mob boss in which state?", "New Jersey", ["New York", "Nevada", "Illinois"]),
        Q(1, "Indiana Jones's day job is what?", "Archaeology professor", ["Pilot", "Detective", "Army officer"]),
        Q(1, "Who stars in the 'Mission: Impossible' movies?", "Tom Cruise", ["Matt Damon", "Keanu Reeves", "Brad Pitt"]),
        Q(1, "In 'John Wick,' what sends John on his revenge spree?", "Someone killed his dog", ["Someone stole his boat", "Someone burned his house", "Someone kidnapped his brother"]),
        Q(2, "'Are you not entertained?' is shouted in which movie?", "Gladiator", ["Braveheart", "300", "Troy"]),
        Q(2, "Who directed 'The Godfather'?", "Francis Ford Coppola", ["Martin Scorsese", "Steven Spielberg", "Brian De Palma"]),
        Q(2, "Who starred in and directed 'Braveheart'?", "Mel Gibson", ["Kevin Costner", "Russell Crowe", "Clint Eastwood"]),
        Q(2, "Kevin Costner played rancher John Dutton in which show?", "Yellowstone", ["Longmire", "Justified", "Bosch"]),
        Q(2, "'Predator' (1987) starred which action legend?", "Arnold Schwarzenegger", ["Sylvester Stallone", "Bruce Willis", "Jean-Claude Van Damme"]),
        Q(2, "'Die Hard' takes place at Christmas inside which building?", "Nakatomi Plaza", ["The Sears Tower", "The Empire State Building", "Trump Tower"]),
        Q(2, "'Top Gun: Maverick' came out in which year?", "2022", ["2019", "2020", "2024"]),
        Q(2, "'Casino Royale' (2006) introduced which actor as Bond?", "Daniel Craig", ["Pierce Brosnan", "Timothy Dalton", "Henry Cavill"]),
        Q(2, "'Band of Brothers' follows Easy Company through which war?", "World War II", ["Vietnam", "Korea", "World War I"]),
        Q(2, "'Bad Boys' stars Will Smith and whom?", "Martin Lawrence", ["Chris Tucker", "Eddie Murphy", "Jamie Foxx"]),
        Q(2, "Matt Damon plays which amnesiac spy?", "Jason Bourne", ["Ethan Hunt", "Jack Ryan", "John Wick"]),
        Q(2, "'Saving Private Ryan' opens with which battle?", "D-Day at Omaha Beach", ["The Battle of the Bulge", "Iwo Jima", "Pearl Harbor"]),
        Q(3, "The first 'Rambo' movie is titled what?", "First Blood", ["Rambo", "Last Blood", "Cold Blood"]),
        Q(3, "'Heat' (1995) paired Al Pacino with which actor?", "Robert De Niro", ["Joe Pesci", "Jack Nicholson", "Gene Hackman"]),
        Q(3, "In 'Point Break,' Keanu Reeves chases surfing bank robbers led by whom?", "Patrick Swayze", ["Val Kilmer", "Kurt Russell", "Charlie Sheen"]),
        Q(3, "'The Rock' (1996) is set on which island?", "Alcatraz", ["Ellis Island", "Catalina", "Angel Island"]),
        Q(3, "Who produced 'Band of Brothers' with Steven Spielberg?", "Tom Hanks", ["George Clooney", "Ron Howard", "Clint Eastwood"]),
        Q(3, "'I'm your huckleberry' is a line from which Western?", "Tombstone", ["Unforgiven", "Wyatt Earp", "3:10 to Yuma"]),
        Q(3, "Riggs and Murtaugh are the cop duo in which series?", "Lethal Weapon", ["Rush Hour", "Bad Boys", "48 Hrs."]),
        Q(3, "Who directed 'Goodfellas'?", "Martin Scorsese", ["Francis Ford Coppola", "Brian De Palma", "Quentin Tarantino"]),
        Q(3, "Rocky's Soviet opponent in 'Rocky IV' is named what?", "Ivan Drago", ["Clubber Lang", "Apollo Creed", "Tommy Gunn"]),
        Q(3, "'1883' and '1923' are prequels to which show?", "Yellowstone", ["Longmire", "Deadwood", "Hell on Wheels"]),
        Q(3, "Who plays Jack Reacher in the Prime Video series?", "Alan Ritchson", ["Tom Cruise", "Chris Hemsworth", "Henry Cavill"]),
        Q(3, "Who plays Furiosa in 'Mad Max: Fury Road'?", "Charlize Theron", ["Anya Taylor-Joy", "Scarlett Johansson", "Emily Blunt"]),
    ])

    static let tech = Deck(id: "tech", world: .his, title: "Tech & Gadgets", tagline: "Routers, chips, and why he needs a third monitor.", symbol: "cpu.fill", colorHex: "0EA5E9", specs: [
        Q(1, "Which company makes the iPhone?", "Apple", ["Samsung", "Google", "Microsoft"]),
        Q(1, "What does Wi-Fi let a device do?", "Connect to a network wirelessly", ["Charge faster", "Take better photos", "Block ads"]),
        Q(1, "Bluetooth is mostly used for what?", "Short-range wireless connections, like headphones", ["Long-distance calls", "Satellite TV", "Charging"]),
        Q(1, "Android apps come from which store?", "Google Play", ["The App Store", "Steam", "Xbox Live"]),
        Q(1, "Alexa is whose voice assistant?", "Amazon's", ["Apple's", "Google's", "Microsoft's"]),
        Q(1, "What does Ctrl+Z (or Cmd+Z) do?", "Undo", ["Zoom", "Save", "Close"]),
        Q(1, "ChatGPT was created by which company?", "OpenAI", ["Google", "Meta", "Apple"]),
        Q(1, "Which company makes Windows?", "Microsoft", ["Apple", "IBM", "Intel"]),
        Q(1, "AirDrop shares files between what?", "Nearby Apple devices", ["Any phone and a printer", "Email accounts", "Android and iPhone"]),
        Q(1, "What does a VPN do?", "Hides and encrypts your internet traffic", ["Speeds up Wi-Fi", "Blocks spam calls", "Stores your photos"]),
        Q(1, "'The cloud' refers to what?", "Storing data on remote servers", ["Weather apps", "Wireless charging", "Airplane mode"]),
        Q(1, "USB-C is a type of what?", "Charging and data connector", ["Battery", "Speaker", "Screen"]),
        Q(2, "What does 4K refer to on a TV?", "Screen resolution, about 4,000 pixels wide", ["Screen size", "Refresh rate", "Brightness"]),
        Q(2, "An HDMI cable carries what?", "Video and audio", ["Only power", "Only internet", "Only audio"]),
        Q(2, "RAM is a computer's what?", "Short-term working memory", ["Long-term storage", "Processor", "Graphics chip"]),
        Q(2, "How does an SSD differ from a hard drive?", "It has no moving parts", ["It's slower", "It holds less", "It needs a fan"]),
        Q(2, "Nvidia is best known for making what?", "Graphics chips", ["Phones", "Routers", "Cameras"]),
        Q(2, "5G is the fifth generation of what?", "Cellular networks", ["Wi-Fi", "Bluetooth", "GPS"]),
        Q(2, "Two-factor authentication adds what to a password?", "A second step, like a code sent to your phone", ["A longer password", "A security question", "A fingerprint reader"]),
        Q(2, "'Phishing' is what?", "Fake messages designed to steal your info", ["A type of virus", "Slow internet", "A search engine"]),
        Q(2, "Starlink provides internet from where?", "Satellites", ["Cell towers", "Undersea cables", "Balloons"]),
        Q(2, "Steam is a store for what?", "PC games", ["Music", "Movies", "Phone apps"]),
        Q(2, "Most phones use which kind of rechargeable battery?", "Lithium-ion", ["Alkaline", "Lead-acid", "Nickel-cadmium"]),
        Q(2, "Ring video doorbells are owned by which company?", "Amazon", ["Google", "Apple", "Samsung"]),
        Q(3, "A Raspberry Pi is what?", "A tiny, cheap computer", ["A dessert app", "A Wi-Fi router", "A smart speaker"]),
        Q(3, "The Linux operating system was created by whom?", "Linus Torvalds", ["Bill Gates", "Steve Wozniak", "Tim Berners-Lee"]),
        Q(3, "The first iPhone went on sale in which year?", "2007", ["2005", "2009", "2010"]),
        Q(3, "Moore's law predicts the transistors on a chip double about every how long?", "Two years", ["Six months", "Five years", "Ten years"]),
        Q(3, "HTTP stands for what?", "HyperText Transfer Protocol", ["High-Tech Transfer Program", "Home Terminal Text Port", "HyperText Typing Process"]),
        Q(3, "Apple Vision Pro launched in which year?", "2024", ["2022", "2023", "2025"]),
        Q(3, "Bitcoin's creator is known by which pseudonym?", "Satoshi Nakamoto", ["Vitalik Buterin", "Hal Finney", "Nick Szabo"]),
        Q(3, "A mesh Wi-Fi system uses what to cover a house?", "Multiple linked nodes", ["One stronger antenna", "A wired extender", "A satellite dish"]),
        Q(3, "A screen's refresh rate is measured in what?", "Hertz", ["Watts", "Pixels", "Bits"]),
        Q(3, "Cherry MX is a famous brand of what?", "Mechanical keyboard switches", ["Gaming mice", "Monitors", "Headsets"]),
        Q(3, "Nest thermostats are made by which company?", "Google", ["Amazon", "Honeywell", "Apple"]),
        Q(3, "GitHub is a site for hosting what?", "Code", ["Photos", "Music", "Recipes"]),
    ])

    static let fightnight = Deck(id: "fightnight", world: .his, title: "Fight Night", tagline: "The Octagon, the sweet science, and WrestleMania.", symbol: "figure.boxing", colorHex: "DC2626", specs: [
        Q(1, "UFC stands for what?", "Ultimate Fighting Championship", ["United Fight Club", "Universal Fighting Circuit", "Ultimate Fight Company"]),
        Q(1, "MMA stands for what?", "Mixed martial arts", ["Modern martial arts", "Major muscle athletics", "Mixed match association"]),
        Q(1, "UFC fights take place in an eight-sided cage called what?", "The Octagon", ["The Cage", "The Ring", "The Hexagon"]),
        Q(1, "Which boxer was known as 'The Greatest'?", "Muhammad Ali", ["Mike Tyson", "Joe Frazier", "George Foreman"]),
        Q(1, "WWE is what?", "Scripted professional wrestling", ["Olympic wrestling", "A boxing league", "A jiu-jitsu federation"]),
        Q(1, "WWE's biggest annual event is called what?", "WrestleMania", ["SummerSlam", "Royal Rumble", "Survivor Series"]),
        Q(1, "Conor McGregor is from which country?", "Ireland", ["Scotland", "England", "Australia"]),
        Q(1, "Dwayne Johnson's wrestling name was what?", "The Rock", ["The Hulk", "The Undertaker", "Stone Cold"]),
        Q(1, "A submission ends a fight when the opponent does what?", "Taps out", ["Falls down", "Leaves the cage", "Drops his gloves"]),
        Q(1, "A knockout is abbreviated as what?", "KO", ["TKO", "SUB", "DEC"]),
        Q(1, "Despite the name, a boxing ring is what shape?", "Square", ["Round", "Oval", "Octagonal"]),
        Q(1, "Muay Thai comes from which country?", "Thailand", ["Japan", "Brazil", "Korea"]),
        Q(2, "Mike Tyson famously bit the ear of which opponent?", "Evander Holyfield", ["Lennox Lewis", "Riddick Bowe", "Buster Douglas"]),
        Q(2, "TKO means the fight ended how?", "The referee stopped it", ["By knockout", "By decision", "By coin flip"]),
        Q(2, "Floyd Mayweather retired with what pro record?", "50-0", ["45-1", "40-0", "55-2"]),
        Q(2, "Jake Paul fought Mike Tyson in which year?", "2024", ["2022", "2023", "2025"]),
        Q(2, "Who is the UFC's long-time president?", "Dana White", ["Vince McMahon", "Bob Arum", "Joe Rogan"]),
        Q(2, "Ronda Rousey's background before MMA was in which sport?", "Judo", ["Boxing", "Wrestling", "Karate"]),
        Q(2, "Which catchphrase belongs to John Cena?", "You can't see me", ["Rest in peace", "If you smell what I'm cooking", "Give me a hell yeah"]),
        Q(2, "How long is a standard professional boxing round?", "3 minutes", ["2 minutes", "5 minutes", "10 minutes"]),
        Q(2, "How many rounds is a championship boxing bout?", "12", ["10", "15", "20"]),
        Q(2, "A 'southpaw' boxer fights in which stance?", "Left-handed", ["Right-handed", "Crouched", "Backward"]),
        Q(2, "Manny Pacquiao is from which country?", "The Philippines", ["Mexico", "Thailand", "Puerto Rico"]),
        Q(2, "'Ground and pound' means what?", "Striking an opponent from on top after a takedown", ["Kicking the legs", "Punching the body in a clinch", "Slamming from a headlock"]),
        Q(3, "The 'Rumble in the Jungle' was Muhammad Ali vs whom?", "George Foreman", ["Joe Frazier", "Sonny Liston", "Ken Norton"]),
        Q(3, "The 'Thrilla in Manila' was Ali vs whom?", "Joe Frazier", ["George Foreman", "Larry Holmes", "Leon Spinks"]),
        Q(3, "'Stone Cold' Steve Austin's finishing move is called what?", "The Stunner", ["The Tombstone", "The People's Elbow", "The Sharpshooter"]),
        Q(3, "Khabib Nurmagomedov retired undefeated with what record?", "29-0", ["25-0", "30-1", "27-0"]),
        Q(3, "Jon Jones won which UFC title in 2023?", "Heavyweight", ["Light heavyweight", "Middleweight", "Welterweight"]),
        Q(3, "The Undertaker's WrestleMania streak ended at how many wins?", "21", ["16", "25", "30"]),
        Q(3, "Tyson Fury's nickname is what?", "The Gypsy King", ["The Body Snatcher", "Iron Mike", "The Beast"]),
        Q(3, "Canelo Álvarez is from which country?", "Mexico", ["Spain", "Argentina", "Puerto Rico"]),
        Q(3, "Georges St-Pierre is from which country?", "Canada", ["France", "Belgium", "The United States"]),
        Q(3, "The Gracie family made which martial art famous?", "Brazilian jiu-jitsu", ["Muay Thai", "Judo", "Sambo"]),
        Q(3, "AEW is a rival to which wrestling company?", "WWE", ["UFC", "Bellator", "PFL"]),
        Q(3, "A UFC title fight is scheduled for how many rounds?", "Five", ["Three", "Seven", "Twelve"]),
    ])
}
