import Foundation

extension HisWorld {
    static let actionmovies = Deck(id: "actionmovies", world: .his, title: "Action Movies & Dad TV", tagline: "Yippee-ki-yay, Nakatomi Plaza, and every Dutton.", colorHex: "0D9488", specs: [
        Q(1, "'Are you not entertained?' is shouted in which movie?", "Gladiator", ["Braveheart", "300", "Troy"]),
        Q(1, "Who directed 'The Godfather'?", "Francis Ford Coppola", ["Martin Scorsese", "Steven Spielberg", "Brian De Palma"]),
        Q(1, "Who starred in and directed 'Braveheart'?", "Mel Gibson", ["Kevin Costner", "Russell Crowe", "Clint Eastwood"]),
        Q(1, "Kevin Costner played rancher John Dutton in which show?", "Yellowstone", ["Longmire", "Justified", "Bosch"]),
        Q(1, "'Predator' (1987) starred which action legend?", "Arnold Schwarzenegger", ["Sylvester Stallone", "Bruce Willis", "Jean-Claude Van Damme"]),
        Q(1, "'Die Hard' takes place at Christmas inside which building?", "Nakatomi Plaza", ["The Sears Tower", "The Empire State Building", "Trump Tower"]),
        Q(1, "'Top Gun: Maverick' came out in which year?", "2022", ["2019", "2020", "2024"]),
        Q(1, "'Casino Royale' (2006) introduced which actor as Bond?", "Daniel Craig", ["Pierce Brosnan", "Timothy Dalton", "Henry Cavill"]),
        Q(1, "'Band of Brothers' follows Easy Company through which war?", "World War II", ["Vietnam", "Korea", "World War I"]),
        Q(1, "'Bad Boys' stars Will Smith and whom?", "Martin Lawrence", ["Chris Tucker", "Eddie Murphy", "Jamie Foxx"]),
        Q(1, "Matt Damon plays which amnesiac spy?", "Jason Bourne", ["Ethan Hunt", "Jack Ryan", "John Wick"]),
        Q(1, "'Saving Private Ryan' opens with which battle?", "D-Day at Omaha Beach", ["The Battle of the Bulge", "Iwo Jima", "Pearl Harbor"]),
        Q(2, "The first 'Rambo' movie is titled what?", "First Blood", ["Rambo", "Last Blood", "Cold Blood"]),
        Q(2, "'Heat' (1995) paired Al Pacino with which actor?", "Robert De Niro", ["Joe Pesci", "Jack Nicholson", "Gene Hackman"]),
        Q(2, "In 'Point Break,' Keanu Reeves chases surfing bank robbers led by whom?", "Patrick Swayze", ["Val Kilmer", "Kurt Russell", "Charlie Sheen"]),
        Q(2, "'The Rock' (1996) is set on which island?", "Alcatraz", ["Ellis Island", "Catalina", "Angel Island"]),
        Q(2, "Who produced 'Band of Brothers' with Steven Spielberg?", "Tom Hanks", ["George Clooney", "Ron Howard", "Clint Eastwood"]),
        Q(2, "'I'm your huckleberry' is a line from which Western?", "Tombstone", ["Unforgiven", "Wyatt Earp", "3:10 to Yuma"]),
        Q(2, "Riggs and Murtaugh are the cop duo in which series?", "Lethal Weapon", ["Rush Hour", "Bad Boys", "48 Hrs."]),
        Q(2, "Who directed 'Goodfellas'?", "Martin Scorsese", ["Francis Ford Coppola", "Brian De Palma", "Quentin Tarantino"]),
        Q(2, "Rocky's Soviet opponent in 'Rocky IV' is named what?", "Ivan Drago", ["Clubber Lang", "Apollo Creed", "Tommy Gunn"]),
        Q(2, "'1883' and '1923' are prequels to which show?", "Yellowstone", ["Longmire", "Deadwood", "Hell on Wheels"]),
        Q(2, "Who plays Jack Reacher in the Prime Video series?", "Alan Ritchson", ["Tom Cruise", "Chris Hemsworth", "Henry Cavill"]),
        Q(2, "Who plays Furiosa in 'Mad Max: Fury Road'?", "Charlize Theron", ["Anya Taylor-Joy", "Scarlett Johansson", "Emily Blunt"]),
        Q(3, "'Die Hard' was adapted from which novel?", "Nothing Lasts Forever", ["The Detective", "First Blood", "Rogue Male"], "Roderick Thorp wrote it in 1979 as a sequel to his novel 'The Detective.'"),
        Q(3, "Arnold's character in 'Commando' is named what?", "John Matrix", ["Dutch Schaefer", "Ben Richards", "Douglas Quaid"], "Mark L. Lester directed the 1985 film."),
        Q(3, "In 'Top Gun,' Goose's real name is what?", "Nick Bradshaw", ["Tom Kazansky", "Pete Mitchell", "Bradley Bradshaw"], "His son Bradley, call sign Rooster, flies in 'Top Gun: Maverick.'"),
        Q(3, "Who played Bond in 1969's 'On Her Majesty's Secret Service'?", "George Lazenby", ["Roger Moore", "Timothy Dalton", "Sean Connery"], "He was a model with no film experience, and he played Bond only once."),
        Q(3, "Saul Goodman's real name is what?", "Jimmy McGill", ["Chuck McGill", "Howard Hamlin", "Mike Ehrmantraut"], "Bob Odenkirk played him in both 'Breaking Bad' and 'Better Call Saul.'"),
        Q(3, "'Deserve's got nothing to do with it' is from which Western?", "Unforgiven", ["Tombstone", "The Outlaw Josey Wales", "Pale Rider"], "Clint Eastwood's Will Munny says it to Gene Hackman's Little Bill."),
        Q(3, "'A Fistful of Dollars' was an unofficial remake of which Kurosawa film?", "Yojimbo", ["Seven Samurai", "Rashomon", "Sanjuro"], "Toho sued, and Kurosawa reportedly earned more from the settlement than from 'Yojimbo.'"),
        Q(3, "Who says 'Clever girl' in 'Jurassic Park'?", "Robert Muldoon", ["Ray Arnold", "Dennis Nedry", "Henry Wu"], "Muldoon, the park's game warden, says it seconds before a raptor gets him."),
        Q(3, "In the original 'Magnum, P.I.,' Magnum drives which Ferrari?", "Ferrari 308", ["Ferrari Testarossa", "Ferrari F40", "Ferrari 250 GTO"], "The car belonged to Robin Masters, the estate's rarely seen owner."),
        Q(3, "In 'Gladiator,' arena crowds know Maximus by what name?", "The Spaniard", ["The Gaul", "The Thracian", "The Celt"], "Joaquin Phoenix played Commodus, the emperor Maximus is out to kill."),
        Q(3, "Who played Jack Ryan in 'The Hunt for Red October' (1990)?", "Alec Baldwin", ["Harrison Ford", "Ben Affleck", "Chris Pine"], "Harrison Ford took over the role two years later in 'Patriot Games.'"),
        Q(3, "In 'Lonesome Dove' (1989), Robert Duvall plays which ex-Ranger?", "Gus McCrae", ["Woodrow Call", "Jake Spoon", "Pea Eye Parker"], "Tommy Lee Jones played his partner Call; the novel won the 1986 Pulitzer."),
    ])

    static let tech = Deck(id: "tech", world: .his, title: "Tech & Gadgets", tagline: "Routers, chips, and why he needs a third monitor.", colorHex: "0EA5E9", specs: [
        Q(1, "What does 4K refer to on a TV?", "Screen resolution, about 4,000 pixels wide", ["Screen size", "Refresh rate", "Brightness"]),
        Q(1, "An HDMI cable carries what?", "Video and audio", ["Only power", "Only internet", "Only audio"]),
        Q(1, "RAM is a computer's what?", "Short-term working memory", ["Long-term storage", "Processor", "Graphics chip"]),
        Q(1, "How does an SSD differ from a hard drive?", "It has no moving parts", ["It's slower", "It holds less", "It needs a fan"]),
        Q(1, "Nvidia is best known for making what?", "Graphics chips", ["Phones", "Routers", "Cameras"]),
        Q(1, "5G is the fifth generation of what?", "Cellular networks", ["Wi-Fi", "Bluetooth", "GPS"]),
        Q(1, "Two-factor authentication adds what to a password?", "A second step, like a code sent to your phone", ["A longer password", "A security question", "A fingerprint reader"]),
        Q(1, "'Phishing' is what?", "Fake messages designed to steal your info", ["A type of virus", "Slow internet", "A search engine"]),
        Q(1, "Starlink provides internet from where?", "Satellites", ["Cell towers", "Undersea cables", "Balloons"]),
        Q(1, "Steam is a store for what?", "PC games", ["Music", "Movies", "Phone apps"]),
        Q(1, "Most phones use which kind of rechargeable battery?", "Lithium-ion", ["Alkaline", "Lead-acid", "Nickel-cadmium"]),
        Q(1, "Ring video doorbells are owned by which company?", "Amazon", ["Google", "Apple", "Samsung"]),
        Q(2, "A Raspberry Pi is what?", "A tiny, cheap computer", ["A dessert app", "A Wi-Fi router", "A smart speaker"]),
        Q(2, "The Linux operating system was created by whom?", "Linus Torvalds", ["Bill Gates", "Steve Wozniak", "Tim Berners-Lee"]),
        Q(2, "The first iPhone went on sale in which year?", "2007", ["2005", "2009", "2010"]),
        Q(2, "Moore's law predicts the transistors on a chip double about every how long?", "Two years", ["Six months", "Five years", "Ten years"]),
        Q(2, "HTTP stands for what?", "HyperText Transfer Protocol", ["High-Tech Transfer Program", "Home Terminal Text Port", "HyperText Typing Process"]),
        Q(2, "Apple Vision Pro launched in which year?", "2024", ["2022", "2023", "2025"]),
        Q(2, "Bitcoin's creator is known by which pseudonym?", "Satoshi Nakamoto", ["Vitalik Buterin", "Hal Finney", "Nick Szabo"]),
        Q(2, "A mesh Wi-Fi system uses what to cover a house?", "Multiple linked nodes", ["One stronger antenna", "A wired extender", "A satellite dish"]),
        Q(2, "A screen's refresh rate is measured in what?", "Hertz", ["Watts", "Pixels", "Bits"]),
        Q(2, "Cherry MX is a famous brand of what?", "Mechanical keyboard switches", ["Gaming mice", "Monitors", "Headsets"]),
        Q(2, "Nest thermostats are made by which company?", "Google", ["Amazon", "Honeywell", "Apple"]),
        Q(2, "GitHub is a site for hosting what?", "Code", ["Photos", "Music", "Recipes"]),
        Q(3, "Bluetooth is named after whom?", "A Viking-era Danish king", ["Its Swedish inventor", "A Norse god", "An Ericsson executive"], "Harald Bluetooth was famed for uniting the Danes, as Bluetooth unites devices."),
        Q(3, "In 1947, what 'bug' was found jammed in Harvard's Mark II computer?", "A moth", ["A cockroach", "A beetle", "A spider"], "The logbook page, moth still taped on, is at the Smithsonian."),
        Q(3, "Who designed the QWERTY layout for his 1870s typewriter?", "Christopher Latham Sholes", ["August Dvorak", "Thomas Edison", "Alexander Graham Bell"], "Remington bought his design, and its success made QWERTY the standard."),
        Q(3, "What was the first item ever sold on eBay?", "A broken laser pointer", ["A Pez dispenser", "A Beanie Baby", "A used textbook"], "The buyer paid $14.83 and said he collected broken laser pointers."),
        Q(3, "The QR code was invented in Japan to do what?", "Track car parts in factories", ["Print airline boarding passes", "Speed up grocery checkout", "Label museum exhibits"], "Its three corner squares let a scanner read it from any angle."),
        Q(3, "What was the first commercially available microprocessor?", "The Intel 4004", ["The Intel 8086", "The Zilog Z80", "The Motorola 68000"], "Intel built it in 1971 for a Japanese calculator maker, Busicom."),
        Q(3, "ARPANET's first message in 1969 was meant to be 'LOGIN.' What got through?", "LO", ["L", "LOG", "LOGI"], "The system crashed after two letters; about an hour later the full login worked."),
        Q(3, "The first public handheld cellphone call, in 1973, came from which company?", "Motorola", ["Bell Labs", "Nokia", "Ericsson"], "Engineer Martin Cooper called his rival at Bell Labs from a Manhattan sidewalk."),
        Q(3, "Junk email is called 'spam' thanks to what?", "A Monty Python sketch", ["A Hormel ad jingle", "A military acronym", "A Usenet user's nickname"], "In the 1970 sketch, Vikings drown out a café by singing 'Spam.'"),
        Q(3, "In cybersecurity, a 'zero-day' is what?", "A flaw unknown to its maker", ["A virus set to go off at midnight", "A bug fixed the day it's found", "Malware that deletes itself"], "The name means the vendor has had zero days to fix it."),
        Q(3, "Sony co-developed the compact disc with which company?", "Philips", ["Panasonic", "Toshiba", "Pioneer"], "Philips also introduced the cassette tape, in 1963."),
        Q(3, "Besides Jobs and Wozniak, who was Apple's third co-founder?", "Ronald Wayne", ["Jef Raskin", "John Sculley", "Paul Allen"], "He drew Apple's first logo and withdrew from the company after just 12 days."),
    ])

    static let fightnight = Deck(id: "fightnight", world: .his, title: "Fight Night", tagline: "The Octagon, the sweet science, and WrestleMania.", colorHex: "DC2626", specs: [
        Q(1, "Mike Tyson famously bit the ear of which opponent?", "Evander Holyfield", ["Lennox Lewis", "Riddick Bowe", "Buster Douglas"]),
        Q(1, "TKO means the fight ended how?", "The referee stopped it", ["By knockout", "By decision", "By coin flip"]),
        Q(1, "Floyd Mayweather retired with what pro record?", "50-0", ["45-1", "40-0", "55-2"]),
        Q(1, "Jake Paul fought Mike Tyson in which year?", "2024", ["2022", "2023", "2025"]),
        Q(1, "Who is the UFC's long-time president?", "Dana White", ["Vince McMahon", "Bob Arum", "Joe Rogan"]),
        Q(1, "Ronda Rousey's background before MMA was in which sport?", "Judo", ["Boxing", "Wrestling", "Karate"]),
        Q(1, "Which catchphrase belongs to John Cena?", "You can't see me", ["Rest in peace", "If you smell what I'm cooking", "Give me a hell yeah"]),
        Q(1, "How long is a standard professional boxing round?", "3 minutes", ["2 minutes", "5 minutes", "10 minutes"]),
        Q(1, "How many rounds is a championship boxing bout?", "12", ["10", "15", "20"]),
        Q(1, "A 'southpaw' boxer fights in which stance?", "Left-handed", ["Right-handed", "Crouched", "Backward"]),
        Q(1, "Manny Pacquiao is from which country?", "The Philippines", ["Mexico", "Thailand", "Puerto Rico"]),
        Q(1, "'Ground and pound' means what?", "Striking an opponent from on top after a takedown", ["Kicking the legs", "Punching the body in a clinch", "Slamming from a headlock"]),
        Q(2, "The 'Rumble in the Jungle' was Muhammad Ali vs whom?", "George Foreman", ["Joe Frazier", "Sonny Liston", "Ken Norton"]),
        Q(2, "The 'Thrilla in Manila' was Ali vs whom?", "Joe Frazier", ["George Foreman", "Larry Holmes", "Leon Spinks"]),
        Q(2, "'Stone Cold' Steve Austin's finishing move is called what?", "The Stunner", ["The Tombstone", "The People's Elbow", "The Sharpshooter"]),
        Q(2, "Khabib Nurmagomedov retired undefeated with what record?", "29-0", ["25-0", "30-1", "27-0"]),
        Q(2, "Jon Jones won which UFC title in 2023?", "Heavyweight", ["Light heavyweight", "Middleweight", "Welterweight"]),
        Q(2, "The Undertaker's WrestleMania streak ended at how many wins?", "21", ["16", "25", "30"]),
        Q(2, "Tyson Fury's nickname is what?", "The Gypsy King", ["The Body Snatcher", "Iron Mike", "The Beast"]),
        Q(2, "Canelo Álvarez is from which country?", "Mexico", ["Spain", "Argentina", "Puerto Rico"]),
        Q(2, "Georges St-Pierre is from which country?", "Canada", ["France", "Belgium", "The United States"]),
        Q(2, "The Gracie family made which martial art famous?", "Brazilian jiu-jitsu", ["Muay Thai", "Judo", "Sambo"]),
        Q(2, "AEW is a rival to which wrestling company?", "WWE", ["UFC", "Bellator", "PFL"]),
        Q(2, "A UFC title fight is scheduled for how many rounds?", "Five", ["Three", "Seven", "Twelve"]),
        Q(3, "Cassius Clay won Olympic boxing gold at which Games?", "Rome 1960", ["Melbourne 1956", "Tokyo 1964", "Mexico City 1968"], "He won as an 18-year-old light heavyweight."),
        Q(3, "Modern boxing rules are named after which nobleman?", "The Marquess of Queensberry", ["The Duke of Wellington", "The Earl of Derby", "The Marquess of Salisbury"], "Written by John Graham Chambers, they brought in gloves and three-minute rounds."),
        Q(3, "The very first UFC event, in 1993, was held in which city?", "Denver", ["Las Vegas", "Atlantic City", "Miami"], "Royce Gracie won the one-night, eight-man tournament."),
        Q(3, "In jiu-jitsu and MMA, a 'kimura' attacks which joint?", "The shoulder", ["The knee", "The ankle", "The neck"], "It is named for judoka Masahiko Kimura, who beat Hélio Gracie with it in 1951."),
        Q(3, "Who was the first UFC fighter to hold two titles at once?", "Conor McGregor", ["Georges St-Pierre", "Randy Couture", "Daniel Cormier"], "He added the lightweight belt at UFC 205 in 2016 while still featherweight champ."),
        Q(3, "Who was the first heavyweight to hold all four major belts at once?", "Oleksandr Usyk", ["Lennox Lewis", "Tyson Fury", "Anthony Joshua"], "He beat Tyson Fury in 2024 to add the WBC belt to his WBA, IBF and WBO titles."),
        Q(3, "The 1980 'No Más' fight was Roberto Durán vs. whom?", "Sugar Ray Leonard", ["Marvin Hagler", "Thomas Hearns", "Wilfred Benítez"], "Durán quit in the eighth round of their rematch in New Orleans."),
        Q(3, "Who was double-crossed out of the title in the 1997 'Montreal Screwjob'?", "Bret Hart", ["Shawn Michaels", "The Undertaker", "Stone Cold Steve Austin"], "Vince McMahon had the bell rung while Hart was locked in his own Sharpshooter."),
        Q(3, "In pro wrestling, what is 'kayfabe'?", "Presenting scripted action as real", ["A wrestler's finishing move", "A no-disqualification match", "A backstage contract dispute"], "Breaking kayfabe is like an actor breaking character on camera."),
        Q(3, "Who was boxing's first Black world heavyweight champion?", "Jack Johnson", ["Joe Louis", "Floyd Patterson", "Sonny Liston"], "He took the title from Tommy Burns in Sydney, Australia, in 1908."),
        Q(3, "Griffin vs. Bonnar, 'the fight that saved the UFC,' was the finale of what?", "The Ultimate Fighter", ["UFC 100", "Pride Grand Prix", "Strikeforce on CBS"], "Dana White gave both fighters UFC contracts after the 2005 brawl."),
        Q(3, "Which WWE star went on to win the UFC heavyweight title?", "Brock Lesnar", ["Bobby Lashley", "Dave Bautista", "CM Punk"], "He stopped Randy Couture at UFC 91 in 2008, in just his fourth pro MMA fight."),
    ])
}
