import Foundation

/// His World: the decks a partner who "knows her world" gets quizzed on.
enum HisWorld {
    static let decks: [Deck] = [football, ballsports, cars, grill, nerd, gear, actionmovies, tech, fightnight]

    static let football = Deck(id: "football", world: .his, title: "Football 101", tagline: "Downs, the red zone, and why everyone's yelling.", colorHex: "2FA562", specs: [
        Q(1, "What is an interception?", "A defender catches a pass meant for the offense", ["Recovering a fumble", "Blocking a kick", "A late-hit penalty"]),
        Q(1, "What is a sack?", "Tackling the quarterback behind the line before he throws", ["Dropping a pass", "Returning a kickoff", "A hit out of bounds"]),
        Q(1, "'2nd and 7' means what?", "Second down, 7 yards to go for a first down", ["2 minutes, 7 seconds left", "Second quarter, 7 points", "Two players, seven yards"]),
        Q(1, "A safety scores how many points for the defense?", "2", ["1", "3", "6"]),
        Q(1, "How many yards does an offensive holding penalty cost?", "10", ["5", "15", "20"]),
        Q(1, "What is the red zone?", "Inside the opponent's 20-yard line", ["The end zone", "Midfield", "The bench area"]),
        Q(1, "A two-point conversion replaces what?", "The extra-point kick", ["A field goal", "The kickoff", "A punt"]),
        Q(1, "What is a fumble?", "The ball carrier loses the ball", ["A dropped pass", "A missed kick", "A false start"]),
        Q(1, "Which position lines up wide and catches passes?", "Wide receiver", ["Center", "Guard", "Nose tackle"]),
        Q(1, "The line of scrimmage is what?", "Where the ball sits when a play starts", ["The goal line", "The 50-yard line", "The sideline"]),
        Q(1, "'Icing the kicker' means what?", "Calling a timeout right before a field goal", ["Kicking in cold weather", "Blocking a kick", "Faking a kick"]),
        Q(1, "A coach throws a red flag to do what?", "Ask for a replay review", ["Call a timeout", "End the game", "Eject a player"]),
        Q(2, "Which two teams are tied for the most Super Bowl wins with six each?", "Patriots and Steelers", ["Cowboys and 49ers", "Packers and Giants", "Broncos and Raiders"]),
        Q(2, "What is a pick six?", "An interception returned for a touchdown", ["Six interceptions in a game", "A sixth-round draft pick", "A six-point safety"]),
        Q(2, "A Hail Mary is what?", "A long, desperate pass as time runs out", ["A short screen pass", "A 60-yard field goal", "A quarterback sneak"]),
        Q(2, "The West Coast offense is known for what?", "Short, quick passes", ["Deep bombs", "Running only", "No-huddle tempo"]),
        Q(2, "How many Super Bowls did Tom Brady win?", "7", ["5", "6", "8"]),
        Q(2, "In football, 'the box' is what?", "The area near the line where the linemen and linebackers stand", ["The end zone", "The replay booth", "The penalty area"]),
        Q(2, "How many teams make the NFL playoffs?", "14", ["12", "16", "10"]),
        Q(2, "The Vince Lombardi Trophy goes to whom?", "The Super Bowl winner", ["The league MVP", "The best coach", "The rookie of the year"]),
        Q(2, "A nickel defense has how many defensive backs?", "5", ["4", "6", "3"]),
        Q(2, "Which position snaps the ball?", "The center", ["The guard", "The tackle", "The tight end"]),
        Q(2, "'Cover 2' means what?", "Two safeties deep", ["Two cornerbacks blitzing", "Two tight ends", "Two quarterbacks"]),
        Q(2, "What is the Lambeau Leap?", "Packers players jumping into the stands after a touchdown", ["A quarterback sneak", "A goal-line dive", "A kickoff-return move"]),
        Q(3, "'The Catch' in January 1982 was Joe Montana's pass to whom?", "Dwight Clark", ["Jerry Rice", "Freddie Solomon", "Roger Craig"], "The play was designed for Freddie Solomon, who was covered."),
        Q(3, "Whose 1975 playoff pass popularized the term 'Hail Mary'?", "Roger Staubach", ["Terry Bradshaw", "Fran Tarkenton", "Joe Namath"], "He told reporters he threw it up and prayed Drew Pearson would catch it."),
        Q(3, "Which Cowboy was Super Bowl V MVP despite losing the game?", "Chuck Howley", ["Bob Lilly", "Roger Staubach", "Lee Roy Jordan"], "He is the only Super Bowl MVP from a losing team, and the first non-quarterback to win it."),
        Q(3, "The 1967 'Ice Bowl' was the Packers vs. which team?", "Dallas Cowboys", ["Chicago Bears", "Oakland Raiders", "Minnesota Vikings"], "Kickoff was 13 below zero, and Bart Starr won it on a quarterback sneak in the final seconds."),
        Q(3, "Which team drafted John Elway No. 1 overall in 1983?", "Baltimore Colts", ["Denver Broncos", "New York Jets", "San Diego Chargers"], "Elway threatened to play baseball for the Yankees until the Colts traded him to Denver."),
        Q(3, "The NFL was founded in 1920 in a car showroom in which city?", "Canton, Ohio", ["Chicago, Illinois", "Green Bay, Wisconsin", "Akron, Ohio"], "It was called the American Professional Football Association until 1922."),
        Q(3, "Which NFL franchise is the oldest continuously run pro football team?", "Arizona Cardinals", ["Green Bay Packers", "Chicago Bears", "New York Giants"], "They and the Bears are the only 1920 NFL charter members still playing."),
        Q(3, "On defense, who is the 'Mike'?", "The middle linebacker", ["The weak-side linebacker", "The strong safety", "The nose tackle"], "Sam and Will are the strong-side and weak-side linebackers."),
        Q(3, "A quarterback's 'hard count' tries to do what?", "Draw the defense offside", ["Change the play at the line", "Stop the game clock", "Signal a trick play"], "On fourth-and-short, a 5-yard offside flag hands the offense a first down."),
        Q(3, "The 1968 'Heidi Game' is famous because NBC did what?", "Cut to a movie before the finish", ["Aired the first instant replay", "Lost its signal at halftime", "Showed the first TV timeout"], "East Coast viewers missed Oakland scoring two touchdowns in nine seconds to win."),
        Q(3, "Lamar Hunt said the name 'Super Bowl' came from what?", "His kids' Super Ball toy", ["A newspaper naming contest", "The shape of the trophy", "A radio host's catchphrase"], "Hunt founded the AFL and owned the Kansas City Chiefs."),
        Q(3, "After a fair catch, an NFL team may try what rare play?", "A field goal with no snap", ["A two-point try", "An onside punt", "A free timeout"], "The defense must line up 10 yards away, so it is nearly impossible to block."),
    ] + footballExtra)

    static let ballsports = Deck(id: "ballsports", world: .his, title: "Ball Sports Grab Bag", tagline: "Hoops, baseball, hockey, soccer, golf. One deck, no mercy.", colorHex: "F59E0B", specs: [
        Q(1, "How long is the NBA shot clock?", "24 seconds", ["30 seconds", "45 seconds", "12 seconds"]),
        Q(1, "A double play in baseball is what?", "Two outs on one play", ["Two home runs", "A double", "Two walks"]),
        Q(1, "In soccer, a yellow card means what?", "A caution", ["Ejection", "A goal", "A penalty kick"]),
        Q(1, "A birdie in golf is what?", "One stroke under par", ["One over par", "Two under par", "A hole in one"]),
        Q(1, "How many hockey players per side are on the ice, goalie included?", "6", ["5", "7", "4"]),
        Q(1, "What is March Madness?", "The NCAA basketball tournament", ["The NBA Finals", "Spring training", "The Masters"]),
        Q(1, "The Stanley Cup is awarded in which league?", "NHL", ["NBA", "MLB", "NFL"]),
        Q(1, "In baseball, RBI stands for what?", "Runs batted in", ["Runs by inning", "Rounds before intermission", "Right base infield"]),
        Q(1, "A free throw is worth how much?", "1 point", ["2 points", "3 points", "Half a point"]),
        Q(1, "In soccer, a clean sheet means what?", "The team allowed no goals", ["A clean uniform", "A new field", "A draw"]),
        Q(1, "The Masters is played at which course?", "Augusta National", ["Pebble Beach", "St Andrews", "Pinehurst"]),
        Q(1, "Extra innings are what?", "Baseball's overtime when tied after nine", ["A rain delay", "The seventh-inning stretch", "The playoffs"]),
        Q(2, "An eagle in golf is what?", "Two strokes under par", ["One under par", "Three under par", "One over par"]),
        Q(2, "A triple-double in basketball is what?", "Double digits in three stat categories", ["Three three-pointers", "30 points", "Three dunks"]),
        Q(2, "A perfect game in baseball means what?", "No batter reaches base", ["No runs allowed", "No hits, but walks are fine", "27 strikeouts"]),
        Q(2, "Who became the NBA's all-time leading scorer in 2023?", "LeBron James", ["Kareem Abdul-Jabbar", "Michael Jordan", "Kobe Bryant"]),
        Q(2, "In hockey, icing is what?", "Shooting the puck from your side of center all the way past the far goal line untouched", ["Cooling the rink", "A goalie freezing the puck", "A penalty for fighting"]),
        Q(2, "In soccer, offside is called when what happens?", "An attacker is beyond the last defender when the ball is played", ["A player leaves the field", "The ball goes out", "A foul in the box"]),
        Q(2, "Which soccer tournament is held every four years for national teams?", "The FIFA World Cup", ["The Champions League", "The Premier League", "The Copa del Rey"]),
        Q(2, "In tennis, deuce means what?", "40-40", ["30-30", "Match point", "A tiebreak"]),
        Q(2, "A designated hitter does what?", "Bats in place of the pitcher", ["Runs for a slow batter", "Bats cleanup", "Pitches in relief"]),
        Q(2, "A pick-and-roll is what?", "A screen, then the screener rolls to the basket", ["A rebound", "A steal", "A jump ball"]),
        Q(2, "In golf, 'the rough' is what?", "Longer grass beside the fairway", ["The green", "A bunker", "The tee box"]),
        Q(2, "Which NBA star is nicknamed the Greek Freak?", "Giannis Antetokounmpo", ["Nikola Jokić", "Luka Dončić", "Joel Embiid"]),
        Q(3, "Which golf major's champion is handed the Claret Jug?", "The Open Championship", ["The Masters", "The U.S. Open", "The PGA Championship"], "First played in 1860, the Open is golf's oldest major."),
        Q(3, "What is baseball's 'Mendoza Line'?", "A .200 batting average", ["A .250 batting average", "A .300 batting average", "A 3.00 ERA"], "Mario Mendoza's own career average was .215, a bit above his line."),
        Q(3, "In baseball, a 'golden sombrero' means what?", "Striking out four times in a game", ["Three homers in a game", "Hitting for the cycle", "Four hits in a game"], "Five strikeouts is a 'platinum sombrero.'"),
        Q(3, "The NBA logo's designer based its silhouette on which player?", "Jerry West", ["Michael Jordan", "Bob Cousy", "Elgin Baylor"], "Designer Alan Siegel worked from a magazine photo of West in 1969."),
        Q(3, "In hockey, what is a 'Gordie Howe hat trick'?", "A goal, an assist and a fight", ["Three goals in one period", "Three goals on three shots", "A goal in three straight games"], "Howe himself pulled it off only twice."),
        Q(3, "Which trophy goes to the MVP of the NHL playoffs?", "The Conn Smythe Trophy", ["The Hart Trophy", "The Vezina Trophy", "The Art Ross Trophy"], "Unlike the Super Bowl or NBA Finals MVP awards, it covers the entire postseason."),
        Q(3, "After the 'Miracle on Ice,' whom did the U.S. beat to clinch 1980 gold?", "Finland", ["The Soviet Union", "Sweden", "Czechoslovakia"], "The famous win over the Soviets was not the final game; the U.S. rallied past Finland two days later."),
        Q(3, "In soccer, what is a 'Panenka'?", "A chipped penalty down the middle", ["A bicycle kick", "A curled free kick", "A no-look back-heel pass"], "Antonín Panenka used it to win Euro 1976 for Czechoslovakia."),
        Q(3, "Which country won the first FIFA World Cup in 1930?", "Uruguay", ["Brazil", "Argentina", "Italy"], "Uruguay hosted and beat Argentina 4-2 in the final."),
        Q(3, "Roland Garros, home of the French Open, is named after a what?", "A World War I fighter pilot", ["A French tennis champion", "A former French president", "The stadium's architect"], "Garros was the first person to fly across the Mediterranean, in 1913."),
        Q(3, "In 1988, who won all four tennis majors plus Olympic gold?", "Steffi Graf", ["Martina Navratilova", "Chris Evert", "Monica Seles"], "She beat Gabriela Sabatini for the gold in Seoul."),
        Q(3, "Arnold Palmer's legion of fans was nicknamed what?", "Arnie's Army", ["Palmer's Posse", "The King's Court", "Arnie's Angels"], "The name began with soldiers from nearby Camp Gordon who worked the Masters scoreboards."),
    ] + ballsportsExtra)

    static let cars = Deck(id: "cars", world: .his, title: "Cars & Engines", tagline: "Horsepower, torque, and what that light means.", colorHex: "5B6B8C", specs: [
        Q(1, "RPM stands for what?", "Revolutions per minute", ["Rotations per mile", "Rapid power mode", "Rate per mile"]),
        Q(1, "Which company makes the Corvette?", "Chevrolet", ["Ford", "Dodge", "Pontiac"]),
        Q(1, "A hybrid car has what?", "Both a gas engine and an electric motor", ["A diesel engine", "Two gas engines", "A truck bed"]),
        Q(1, "ABS stands for what?", "Anti-lock braking system", ["Automatic brake sensor", "Advanced body structure", "Air bag system"]),
        Q(1, "Which brand's logo is a prancing horse?", "Ferrari", ["Lamborghini", "Maserati", "Bugatti"]),
        Q(1, "A turbocharger does what?", "Forces more air into the engine for more power", ["Charges the battery", "Adds fuel capacity", "Stiffens the suspension"]),
        Q(1, "Which brand makes the Wrangler?", "Jeep", ["Ford", "GMC", "Subaru"]),
        Q(1, "Torque describes what?", "Twisting force, felt as pulling power", ["Top speed", "Fuel economy", "Brake strength"]),
        Q(1, "A stick shift is what?", "A manual transmission", ["An automatic transmission", "A parking brake", "A gear indicator"]),
        Q(1, "The octane number on a gas pump measures what?", "A fuel's resistance to engine knock", ["Price per gallon", "Fuel weight", "Fuel color"]),
        Q(1, "Which brand makes the 3 Series and the M3?", "BMW", ["Audi", "Mercedes-Benz", "Lexus"]),
        Q(1, "Lug nuts hold what on?", "A wheel", ["The engine", "The seat belts", "The doors"]),
        Q(2, "'0-60' measures what?", "How long it takes to accelerate from 0 to 60 mph", ["Top speed", "Braking distance", "Fuel range"]),
        Q(2, "A V8 engine has how many cylinders?", "8", ["4", "6", "12"]),
        Q(2, "Which race is billed as the Greatest Spectacle in Racing?", "The Indianapolis 500", ["The Daytona 500", "Le Mans", "The Monaco Grand Prix"]),
        Q(2, "Drifting is what?", "Deliberately sliding the rear of the car through turns", ["Coasting in neutral", "Hydroplaning", "Cruise control on the highway"]),
        Q(2, "Which brand makes the 911?", "Porsche", ["Ferrari", "Audi", "Aston Martin"]),
        Q(2, "A catalytic converter does what?", "Cuts toxic exhaust emissions", ["Converts AC to DC", "Adds horsepower", "Filters oil"]),
        Q(2, "How does AWD usually differ from 4WD?", "AWD works all the time automatically; 4WD is typically switched on", ["AWD is only for trucks", "4WD is electric", "They're identical"]),
        Q(2, "The first mass-produced car built on a moving assembly line was what?", "The Ford Model T", ["The Chevy Bel Air", "The VW Beetle", "The Cadillac Series 62"]),
        Q(2, "A dyno test measures what?", "An engine's power output", ["Tire pressure", "Paint thickness", "Oil viscosity"]),
        Q(2, "Lewis Hamilton has how many Formula 1 world titles?", "7", ["5", "6", "8"]),
        Q(2, "The Hellcat is a high-performance trim from which brand?", "Dodge", ["Ford", "Chevrolet", "Jeep"]),
        Q(2, "In Formula 1, DRS stands for what?", "Drag reduction system", ["Direct racing signal", "Driver response system", "Dual rear suspension"]),
        Q(3, "Unlike a turbo, a supercharger is usually driven by what?", "A belt off the crankshaft", ["Exhaust gas pressure", "Ram air from the grille", "Heat from the radiator"], "A turbo spins on exhaust instead, which is why it can lag."),
        Q(3, "Heel-toe downshifting lets a driver do what?", "Brake while blipping the throttle", ["Shift without using the clutch", "Hold the car still on a hill", "Launch without wheelspin"], "The blip matches engine revs to the lower gear so the car doesn't lurch."),
        Q(3, "A Hemi engine is named for the shape of what?", "Its combustion chambers", ["Its valve covers", "Its intake manifold", "Its oil pan"], "Chrysler made the name famous, but hemi heads date back to at least 1901."),
        Q(3, "The '40' in the Ford GT40 refers to what?", "Its height in inches", ["Its wheelbase in inches", "Its weight in hundreds of pounds", "Henry Ford II's age at launch"], "It stood just 40 inches tall, measured at the windshield."),
        Q(3, "Before sports cars, Ferruccio Lamborghini got rich building what?", "Tractors", ["Motorcycles", "Aircraft engines", "Sewing machines"], "His first car, the 350 GT, arrived in 1964."),
        Q(3, "The 'GTO' in Ferrari 250 GTO and Pontiac GTO stands for what?", "Gran Turismo Omologato", ["Grand Touring Option", "Gran Turismo Originale", "Grand Touring Overdrive"], "Omologato means homologated: approved for racing in the GT class."),
        Q(3, "Subaru's six-star logo depicts what?", "The Pleiades star cluster", ["Orion's Belt", "The Big Dipper", "The Southern Cross"], "Subaru is the Japanese name for the Pleiades."),
        Q(3, "Ayrton Senna won all three of his F1 titles with which team?", "McLaren", ["Williams", "Lotus", "Ferrari"], "He took them in 1988, 1990, and 1991, all with Honda engines."),
        Q(3, "Who won the very first Daytona 500, in 1959?", "Lee Petty", ["Richard Petty", "Junior Johnson", "Fireball Roberts"], "It took three days of studying photos to overturn a call for Johnny Beauchamp."),
        Q(3, "Carroll Shelby built the Cobra on a roadster from which British maker?", "AC Cars", ["Triumph", "MG", "Lotus"], "Shelby dropped a Ford V8 into the AC Ace, built for a small six."),
        Q(3, "Gearheads doing an 'LS swap' are installing what?", "A GM small-block V8", ["A Ford Coyote V8", "A limited-slip differential", "A lowered suspension"], "The LS family debuted as the LS1 in the 1997 Corvette."),
        Q(3, "The Nürburgring's Nordschleife is nicknamed what?", "The Green Hell", ["The Brickyard", "The Lady in Black", "The Temple of Speed"], "Jackie Stewart coined it after winning there in rain and fog in 1968."),
    ] + carsExtra)

    static let grill = Deck(id: "grill", world: .his, title: "Grilling, Beer & Whiskey", tagline: "Low and slow, neat or on the rocks.", colorHex: "E0632A", specs: [
        Q(1, "Scotch must be made where?", "Scotland", ["Ireland", "England", "Wales"]),
        Q(1, "Medium-rare beef is pulled at about what internal temperature?", "130 to 135°F", ["160°F", "180°F", "100°F"]),
        Q(1, "Smoking meat means what?", "Cooking it low and slow with wood smoke", ["Grilling on high heat", "Boiling then grilling", "Deep frying"]),
        Q(1, "Whiskey served 'neat' is what?", "Nothing added, no ice", ["Over ice", "With soda", "Shaken with ice"]),
        Q(1, "A stout is what kind of beer?", "Dark and roasty", ["Light lager", "Wheat beer", "Sour beer"]),
        Q(1, "A dry rub is what?", "Spices rubbed on meat before cooking", ["A marinade", "A sauce", "A cleaning method"]),
        Q(1, "Single-malt Scotch is made from what?", "Malted barley at one distillery", ["Corn", "Wheat", "Rye"]),
        Q(1, "ABV on a beer can means what?", "Alcohol by volume", ["Aged beer variety", "American brew version", "Alcohol bottle value"]),
        Q(1, "A reverse sear means what?", "Cook low first, then sear hot at the end", ["Sear, then boil", "Sear both sides twice", "Chill, then sear"]),
        Q(1, "Bourbon must be aged in what?", "New charred oak barrels", ["Used wine barrels", "Steel tanks", "Plastic vats"]),
        Q(1, "Which beer style is cloudy with orange and coriander notes?", "Belgian witbier", ["Pilsner", "Stout", "Amber ale"]),
        Q(1, "'The stall' when smoking a brisket is what?", "When the internal temperature stops rising for hours", ["When the fire goes out", "When the bark burns", "When the guests leave"]),
        Q(2, "Pilsner originated in which country?", "The Czech Republic", ["Germany", "Belgium", "The Netherlands"], "Named for the city of Plzeň."),
        Q(2, "The Texas Crutch is what?", "Wrapping meat in foil or butcher paper mid-smoke", ["A brisket knife", "A grill brush", "A spice rub"]),
        Q(2, "American rye whiskey must be at least what percent rye?", "51%", ["25%", "75%", "100%"]),
        Q(2, "A boilermaker is what?", "A shot of whiskey with a beer", ["A beer with lime", "Whiskey and soda", "A boiled beer"]),
        Q(2, "Yamazaki and Hakushu whiskies are made by which company?", "Suntory", ["Nikka", "Kirin", "Asahi"]),
        Q(2, "Which wood gives a strong, bacon-like smoke flavor?", "Hickory", ["Apple", "Cherry", "Alder"]),
        Q(2, "Guinness is brewed in which city?", "Dublin", ["Belfast", "Cork", "Galway"]),
        Q(2, "The Maillard reaction is what?", "The browning that creates flavor when proteins and sugars are heated", ["Meat resting", "Fat rendering", "Smoke soaking in"]),
        Q(2, "A Manhattan cocktail is whiskey and what?", "Sweet vermouth", ["Cola", "Tonic", "Cream"]),
        Q(2, "A tomahawk is what?", "A bone-in ribeye with a long rib bone", ["A brisket cut", "A pork loin", "A grilling axe"]),
        Q(2, "In brewing, 'wort' is what?", "The sweet liquid before fermentation", ["The foam on top", "The spent grain", "The bottle cap"]),
        Q(2, "Which BBQ style is known for thick, sweet tomato-and-molasses sauce?", "Kansas City", ["Carolina vinegar", "Central Texas", "Memphis dry rub"]),
        Q(3, "The 1516 Reinheitsgebot allowed only water, hops, and what?", "Barley", ["Yeast", "Wheat", "Rye"], "Brewers used yeast, but saw it as part of the process, not an ingredient."),
        Q(3, "Which of these is an authentic Trappist beer?", "Westmalle", ["Leffe", "Duvel", "Hoegaarden"], "Leffe is an abbey-style beer brewed by AB InBev, not inside a monastery."),
        Q(3, "A hefeweizen's banana and clove flavors come from what?", "The yeast", ["The wheat", "The hops", "Added spices"], "The yeast makes an ester that tastes like banana and a phenol that tastes like clove."),
        Q(3, "A beer's SRM number measures what?", "Its color", ["Its bitterness", "Its alcohol", "Its sweetness"], "SRM runs from about 2 for pale lagers to 40-plus for imperial stouts."),
        Q(3, "Tennessee whiskey is filtered through charcoal made from which wood?", "Sugar maple", ["Hickory", "White oak", "Black walnut"], "It's called the Lincoln County Process, and Tennessee wrote it into law in 2013."),
        Q(3, "Maker's Mark and Pappy Van Winkle use which grain in place of rye?", "Wheat", ["Oats", "Extra corn", "Millet"], "Bill Samuels Sr. picked Maker's recipe by baking a loaf of bread from each candidate."),
        Q(3, "Bottled-in-bond whiskey must be bottled at what proof?", "100 proof", ["80 proof", "90 proof", "110 proof"], "The 1897 law also requires four years in a bonded warehouse from one distillery and one season."),
        Q(3, "Alabama white barbecue sauce is built on what?", "Mayonnaise", ["Buttermilk", "Sour cream", "Greek yogurt"], "It's credited to Big Bob Gibson of Decatur, Alabama, who made it for smoked chicken in 1925."),
        Q(3, "California's Santa Maria-style barbecue is built around which cut?", "Tri-tip", ["Brisket", "Pork shoulder", "Beef short ribs"], "It's grilled over native coast live oak, which locals call red oak."),
        Q(3, "What makes a porterhouse a porterhouse instead of a T-bone?", "A bigger piece of tenderloin", ["A longer bone", "More marbling", "It's cut from the rib"], "USDA specs require the porterhouse tenderloin to be at least 1.25 inches wide."),
        Q(3, "A brisket's pink smoke ring forms when smoke gases bind with what?", "Myoglobin in the meat", ["Collagen", "Rendered fat", "Sugar in the rub"], "Nitric oxide from the fire binds myoglobin into a pink form that heat can't turn gray."),
        Q(3, "In whiskey making, 'sour mash' means what?", "Adding old mash to a new batch", ["Aging it in used wine casks", "Mashing unripe grain", "Adding citrus to the mash"], "Jim Beam and Jack Daniel's are both made with the sour mash process."),
    ] + grillExtra)

    static let nerd = Deck(id: "nerd", world: .his, title: "Games & Superheroes", tagline: "Respawns, Wakanda, and what GG means.", colorHex: "7C4DFF", specs: [
        Q(1, "Which villain snapped his fingers in 'Avengers: Infinity War'?", "Thanos", ["Loki", "Ultron", "Red Skull"]),
        Q(1, "The hero of 'The Legend of Zelda' is named what?", "Link", ["Zelda", "Ganon", "Epona"]),
        Q(1, "In Mario Kart, which item hunts down whoever is in first place?", "The blue shell", ["The banana", "The red shell", "The star"]),
        Q(1, "Which hero only says 'I am Groot'?", "Groot", ["Rocket", "Drax", "Star-Lord"]),
        Q(1, "In games, a respawn is what?", "Coming back after dying", ["Saving the game", "A new level", "A boss fight"]),
        Q(1, "Wolverine belongs to which team?", "The X-Men", ["The Avengers", "The Justice League", "The Fantastic Four"]),
        Q(1, "Which game series is set in Hyrule?", "The Legend of Zelda", ["Final Fantasy", "Elden Ring", "Skyrim"]),
        Q(1, "Batman's city is called what?", "Gotham", ["Metropolis", "Star City", "Central City"]),
        Q(1, "Twitch is what?", "A livestreaming platform for gamers", ["A game console", "A controller", "An esport"]),
        Q(1, "Which hero carries a vibranium shield?", "Captain America", ["Black Panther", "Thor", "Hawkeye"]),
        Q(1, "The green creeper that explodes is from which game?", "Minecraft", ["Fortnite", "Roblox", "Terraria"]),
        Q(1, "GTA stands for what?", "Grand Theft Auto", ["Great Tactical Army", "Global Team Arena", "Giant Turbo Attack"]),
        Q(2, "Which game won Game of the Year at The Game Awards 2022?", "Elden Ring", ["God of War Ragnarök", "Horizon Forbidden West", "Stray"]),
        Q(2, "Which company makes Zelda and Mario?", "Nintendo", ["Sony", "Sega", "Capcom"]),
        Q(2, "Black Panther's home country is what?", "Wakanda", ["Latveria", "Genosha", "Atlantis"]),
        Q(2, "'Souls-like' games are known for what?", "High difficulty and stamina-based combat", ["Farming", "Puzzle solving", "Sports"]),
        Q(2, "Who played Iron Man in the Marvel movies?", "Robert Downey Jr.", ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"]),
        Q(2, "Fortnite Battle Royale launched in which year?", "2017", ["2015", "2019", "2013"]),
        Q(2, "Deadpool is famous for doing what?", "Breaking the fourth wall", ["Flying", "Shrinking", "Reading minds"]),
        Q(2, "In game chat, GG means what?", "Good game", ["Get going", "Great gun", "Go get 'em"]),
        Q(2, "Which Marvel hero comes from Asgard?", "Thor", ["Vision", "Hulk", "Ant-Man"]),
        Q(2, "Elden Ring was made by which studio?", "FromSoftware", ["Bethesda", "Ubisoft", "Rockstar"]),
        Q(2, "Who won the 2020 Best Actor Oscar for playing the Joker?", "Joaquin Phoenix", ["Heath Ledger", "Jared Leto", "Jack Nicholson"]),
        Q(2, "Speedrunning is what?", "Finishing a game as fast as possible", ["Playing on the hardest mode", "Racing games only", "Playing while running"]),
        Q(3, "In 1981's 'Donkey Kong,' Mario's job was what?", "Carpenter", ["Plumber", "Electrician", "Bricklayer"], "He became a plumber in 'Mario Bros.' because much of that game is set underground."),
        Q(3, "The Konami Code (up, up, down, down...) first appeared in which game?", "Gradius", ["Contra", "Castlevania", "Metal Gear"], "Programmer Kazuhisa Hashimoto added it because he found the game too hard to test."),
        Q(3, "Spider-Man made his debut in which comic?", "Amazing Fantasy #15", ["Amazing Spider-Man #1", "Tales of Suspense #39", "Strange Tales #110"], "Its strong sales earned Spider-Man his own series seven months later."),
        Q(3, "Wolverine debuted in 1974 in which hero's comic?", "The Incredible Hulk", ["Captain America", "Daredevil", "Spider-Man"], "He appeared in the last panel of Hulk #180 before his full debut in #181."),
        Q(3, "Captain America's very first shield in 1941 was what shape?", "Triangular", ["Round", "Square", "Star-shaped"], "A rival publisher said it looked too much like their hero the Shield's, so issue #2 went round."),
        Q(3, "In 'The Killing Joke,' the Joker's origin is as a failed what?", "Stand-up comedian", ["Magician", "Circus clown", "Rock singer"], "Alan Moore wrote it and Brian Bolland drew it in 1988."),
        Q(3, "Which Infinity Stone waits on Vormir, for the price of a loved one?", "The Soul Stone", ["The Mind Stone", "The Time Stone", "The Reality Stone"], "Thanos traded Gamora for it; Black Widow gave herself up in 'Endgame.'"),
        Q(3, "'Would you kindly' is the twist phrase in which game?", "BioShock", ["Portal", "Half-Life 2", "Fallout 3"], "Atlas, really Frank Fontaine, uses the phrase to control your character."),
        Q(3, "Sony's PlayStation began as a CD add-on for which console?", "The Super Nintendo", ["The Sega Genesis", "The Nintendo 64", "The TurboGrafx-16"], "Nintendo ditched Sony for Philips at CES 1991, so Sony built its own console."),
        Q(3, "Who voiced Batman in 'Batman: The Animated Series'?", "Kevin Conroy", ["Mark Hamill", "Adam West", "Michael Keaton"], "Mark Hamill voiced the Joker opposite him."),
        Q(3, "Halo's Master Chief goes by what name and number?", "John-117", ["Kelly-087", "Linda-058", "Jorge-052"], "Steve Downes, a former radio DJ, voiced him in the first 'Halo' in 2001."),
        Q(3, "Nintendo was founded in 1889 to make what?", "Playing cards", ["Paper lanterns", "Sewing machines", "Bicycles"], "Fusajiro Yamauchi started it in Kyoto to make hanafuda, or flower cards."),
    ] + nerdExtra)

    static let gear = Deck(id: "gear", world: .his, title: "Tools, Gear & Outdoors", tagline: "Torque wrenches, bowlines, and why the cooler is a Yeti.", colorHex: "5FA31B", specs: [
        Q(1, "A torque wrench is for what?", "Tightening bolts to an exact tightness", ["Cutting pipe", "Measuring angles", "Removing paint"]),
        Q(1, "WD-40 is mostly used to do what?", "Loosen rusted parts and displace moisture", ["Glue wood", "Clean windows", "Sharpen blades"]),
        Q(1, "A socket set is used with a what?", "Ratchet", ["Hammer", "Saw", "Drill bit"]),
        Q(1, "Catch and release means what?", "Letting fish go after you catch them", ["A fishing net", "A lure", "A type of reel"]),
        Q(1, "Which knot makes a fixed loop that won't slip?", "A bowline", ["A square knot", "A slip knot", "A granny knot"]),
        Q(1, "'Leave no trace' is what?", "An outdoor ethic of leaving nature as you found it", ["A hunting method", "A camping brand", "A trail name"]),
        Q(1, "A miter saw makes what kind of cuts?", "Precise angled cuts", ["Curved cuts", "Holes", "Sanding passes"]),
        Q(1, "A bear canister is what?", "A locked food container for bear country", ["Bear repellent", "A tent shape", "A cooler brand"]),
        Q(1, "R-value on a sleeping pad measures what?", "Insulation from the cold ground", ["Weight", "Size", "Waterproofing"]),
        Q(1, "A spinner in fishing is what?", "A lure with a spinning blade", ["A reel type", "A rod", "A knot"]),
        Q(1, "A chalk line is used to do what?", "Snap a long straight line on a surface", ["Measure angles", "Clean tools", "Mark tires"]),
        Q(1, "Waders are what?", "Waterproof overalls for standing in water", ["Hiking boots", "Rain jackets", "Fishing hats"]),
        Q(2, "Gore-Tex is what?", "A waterproof, breathable fabric membrane", ["A tent brand", "A type of rope", "A boot sole"]),
        Q(2, "A come-along is what?", "A hand-operated winch", ["A rope", "A ladder", "A saw"]),
        Q(2, "The 'Ten Essentials' list is for what?", "Hiking safety gear", ["Toolbox basics", "Fishing tackle", "Truck maintenance"]),
        Q(2, "A ferro rod is used to do what?", "Start fires by striking sparks", ["Sharpen knives", "Measure water depth", "Tie flies"]),
        Q(2, "A trolling motor is what?", "A quiet electric motor for slowly positioning a boat", ["A large outboard", "A jet engine", "A winch"]),
        Q(2, "Which saw cuts curves in wood?", "A jigsaw", ["A circular saw", "A table saw", "A hand plane"]),
        Q(2, "Fly fishing casts what?", "A weighted line with a nearly weightless fly", ["A heavy lure", "A net", "A bobber"]),
        Q(2, "Bushcraft means what?", "Wilderness skills using natural materials", ["Trimming bushes", "Landscaping", "Bird hunting"]),
        Q(2, "Leatherman is known for what?", "Multi-tools", ["Boots", "Belts", "Saddles"]),
        Q(2, "A GFCI outlet protects against what?", "Shock from ground faults", ["Power surges", "Overheating", "Fire only"]),
        Q(2, "In camping, a bivy is what?", "A minimal one-person shelter", ["A large family tent", "A camp stove", "A hammock"]),
        Q(2, "Yeti is famous as a brand of what?", "Coolers", ["Tents", "Trucks", "Boots"]),
        Q(3, "A Robertson screwdriver, a Canadian favorite, has what tip shape?", "Square", ["Cross", "Six-point star", "Hexagon"], "Robertson refused Henry Ford an exclusive license, so the drive stayed mostly Canadian."),
        Q(3, "The 'd' in nail sizes like 16d stands for what?", "Penny", ["Diameter", "Dozen", "Depth"], "It traces to the Roman denarius; sizes once reflected price per hundred nails."),
        Q(3, "Which knot is best for joining two ropes of different thickness?", "The sheet bend", ["The square knot", "The clove hitch", "The taut-line hitch"], "A square knot tends to slip when the two ropes don't match."),
        Q(3, "To campers and loggers, a 'widowmaker' is what?", "A dead limb that could fall", ["A dull, glancing axe", "A flash-flood gully", "A lightning-prone ridge"], "Look up for them before you pitch a tent under trees."),
        Q(3, "In woodworking, a saw's 'kerf' is what?", "The width of the cut it makes", ["The angle of its teeth", "Its teeth per inch", "Its blade guard"], "Teeth bent side to side make the kerf wider than the blade, so it won't bind."),
        Q(3, "Down 'fill power' measures what?", "How much space an ounce fills", ["The feather-to-down ratio", "Total ounces of down", "Its temperature rating"], "One ounce of 800-fill down lofts to about 800 cubic inches."),
        Q(3, "The Pulaski, a wildfire tool, combines an axe with what?", "An adze", ["A shovel", "A hammer", "A saw"], "It honors ranger Ed Pulaski, a hero of the 1910 Big Burn."),
        Q(3, "On a compass, 'declination' is what?", "Angle from true to magnetic north", ["The needle's downward tilt", "Error from nearby metal", "The sun's angle at noon"], "It changes by place and over time, so maps list it with a year."),
        Q(3, "The Appalachian Trail's northern end is atop which mountain?", "Mount Katahdin", ["Mount Washington", "Mount Mansfield", "Springer Mountain"], "The southern end is Springer Mountain in Georgia, nearly 2,200 miles away."),
        Q(3, "In fly fishing, a 'nymph' imitates what?", "A young underwater insect", ["A floating adult insect", "A small baitfish", "A fish egg"], "Nymphs are fished below the surface, often weighted with a bead head."),
        Q(3, "Which of these screws on with a left-hand (reverse) thread?", "A bike's left pedal", ["A garden hose", "A light bulb", "A jar lid"], "Reverse threads keep pedaling from slowly unscrewing it."),
        Q(3, "Which company introduced the first cordless electric drill, in 1961?", "Black & Decker", ["Makita", "Milwaukee", "Craftsman"], "Black & Decker later built the power head for the Apollo 15 moon drill."),
    ] + gearExtra)
}

enum Decks {
    static let all: [Deck] = HerWorld.decks + HisWorld.decks
    static func byID(_ id: String) -> Deck? { all.first { $0.id == id } }
    static func decks(in world: World) -> [Deck] { all.filter { $0.world == world } }
}
