import Foundation

/// His World: the decks a partner who "knows her world" gets quizzed on.
enum HisWorld {
    static let decks: [Deck] = [football, ballsports, cars, grill, nerd, gear, actionmovies, tech, fightnight]

    static let football = Deck(id: "football", world: .his, title: "Football 101", tagline: "Downs, the red zone, and why everyone's yelling.", symbol: "football.fill", colorHex: "2FA562", specs: [
        Q(1, "How many points is a touchdown worth (before the extra point)?", "6", ["7", "3", "1"]),
        Q(1, "How many downs does a team get to gain 10 yards?", "4", ["3", "2", "5"]),
        Q(1, "Who throws the ball on most plays?", "The quarterback", ["The kicker", "The running back", "The center"]),
        Q(1, "How many players does each team have on the field at once?", "11", ["9", "10", "12"]),
        Q(1, "A field goal is worth how many points?", "3", ["6", "1", "2"]),
        Q(1, "The NFL championship game is called what?", "The Super Bowl", ["The World Series", "The Stanley Cup", "The Finals"]),
        Q(1, "Where does the ball have to go for a touchdown?", "The end zone", ["Through the uprights", "Midfield", "The sideline"]),
        Q(1, "A yellow flag on the field means what?", "A penalty", ["A touchdown", "A timeout", "Halftime"]),
        Q(1, "How long is a football field between the goal lines?", "100 yards", ["50 yards", "120 yards", "100 feet"]),
        Q(1, "What is a punt?", "Kicking the ball away on fourth down", ["A long throw", "A running play", "A trick play"]),
        Q(1, "Halftime comes after which quarter?", "The 2nd", ["The 1st", "The 3rd", "The 4th"]),
        Q(1, "A kickoff starts what?", "The game and each half", ["Only overtime", "Only the fourth quarter", "Only the Super Bowl"]),
        Q(2, "What is an interception?", "A defender catches a pass meant for the offense", ["Recovering a fumble", "Blocking a kick", "A late-hit penalty"]),
        Q(2, "What is a sack?", "Tackling the quarterback behind the line before he throws", ["Dropping a pass", "Returning a kickoff", "A hit out of bounds"]),
        Q(2, "'2nd and 7' means what?", "Second down, 7 yards to go for a first down", ["2 minutes, 7 seconds left", "Second quarter, 7 points", "Two players, seven yards"]),
        Q(2, "A safety scores how many points for the defense?", "2", ["1", "3", "6"]),
        Q(2, "How many yards does an offensive holding penalty cost?", "10", ["5", "15", "20"]),
        Q(2, "What is the red zone?", "Inside the opponent's 20-yard line", ["The end zone", "Midfield", "The bench area"]),
        Q(2, "A two-point conversion replaces what?", "The extra-point kick", ["A field goal", "The kickoff", "A punt"]),
        Q(2, "What is a fumble?", "The ball carrier loses the ball", ["A dropped pass", "A missed kick", "A false start"]),
        Q(2, "Which position lines up wide and catches passes?", "Wide receiver", ["Center", "Guard", "Nose tackle"]),
        Q(2, "The line of scrimmage is what?", "Where the ball sits when a play starts", ["The goal line", "The 50-yard line", "The sideline"]),
        Q(2, "'Icing the kicker' means what?", "Calling a timeout right before a field goal", ["Kicking in cold weather", "Blocking a kick", "Faking a kick"]),
        Q(2, "A coach throws a red flag to do what?", "Ask for a replay review", ["Call a timeout", "End the game", "Eject a player"]),
        Q(3, "Which two teams are tied for the most Super Bowl wins with six each?", "Patriots and Steelers", ["Cowboys and 49ers", "Packers and Giants", "Broncos and Raiders"]),
        Q(3, "What is a pick six?", "An interception returned for a touchdown", ["Six interceptions in a game", "A sixth-round draft pick", "A six-point safety"]),
        Q(3, "A Hail Mary is what?", "A long, desperate pass as time runs out", ["A short screen pass", "A 60-yard field goal", "A quarterback sneak"]),
        Q(3, "The West Coast offense is known for what?", "Short, quick passes", ["Deep bombs", "Running only", "No-huddle tempo"]),
        Q(3, "How many Super Bowls did Tom Brady win?", "7", ["5", "6", "8"]),
        Q(3, "In football, 'the box' is what?", "The area near the line where the linemen and linebackers stand", ["The end zone", "The replay booth", "The penalty area"]),
        Q(3, "How many teams make the NFL playoffs?", "14", ["12", "16", "10"]),
        Q(3, "The Vince Lombardi Trophy goes to whom?", "The Super Bowl winner", ["The league MVP", "The best coach", "The rookie of the year"]),
        Q(3, "A nickel defense has how many defensive backs?", "5", ["4", "6", "3"]),
        Q(3, "Which position snaps the ball?", "The center", ["The guard", "The tackle", "The tight end"]),
        Q(3, "'Cover 2' means what?", "Two safeties deep", ["Two cornerbacks blitzing", "Two tight ends", "Two quarterbacks"]),
        Q(3, "What is the Lambeau Leap?", "Packers players jumping into the stands after a touchdown", ["A quarterback sneak", "A goal-line dive", "A kickoff-return move"]),
    ])

    static let ballsports = Deck(id: "ballsports", world: .his, title: "Ball Sports Grab Bag", tagline: "Hoops, baseball, hockey, soccer, golf. One deck, no mercy.", symbol: "basketball.fill", colorHex: "F59E0B", specs: [
        Q(1, "A basketball shot from beyond the arc is worth how much?", "3 points", ["2 points", "1 point", "4 points"]),
        Q(1, "A standard baseball game has how many innings?", "9", ["7", "10", "12"]),
        Q(1, "A home run happens in which sport?", "Baseball", ["Basketball", "Hockey", "Golf"]),
        Q(1, "In soccer, who can use their hands inside the box?", "The goalkeeper", ["The striker", "The midfielder", "The defender"]),
        Q(1, "Hockey is played on what?", "Ice", ["Grass", "Clay", "Hardwood"]),
        Q(1, "How many strikes make an out?", "3", ["2", "4", "1"]),
        Q(1, "In golf, 'par' is what?", "The expected number of strokes for a hole", ["A hole in one", "A sand trap", "The clubhouse"]),
        Q(1, "Which sport uses a puck?", "Hockey", ["Soccer", "Golf", "Basketball"]),
        Q(1, "How many basketball players per team are on the court?", "5", ["6", "7", "11"]),
        Q(1, "A hat trick is what?", "Three goals by one player in a game", ["A magic trick", "A penalty", "A free throw"]),
        Q(1, "In tennis, a score of zero is called what?", "Love", ["Nil", "Zip", "Duck"]),
        Q(1, "The World Series is the championship of which league?", "MLB", ["NBA", "NHL", "MLS"]),
        Q(2, "How long is the NBA shot clock?", "24 seconds", ["30 seconds", "45 seconds", "12 seconds"]),
        Q(2, "A double play in baseball is what?", "Two outs on one play", ["Two home runs", "A double", "Two walks"]),
        Q(2, "In soccer, a yellow card means what?", "A caution", ["Ejection", "A goal", "A penalty kick"]),
        Q(2, "A birdie in golf is what?", "One stroke under par", ["One over par", "Two under par", "A hole in one"]),
        Q(2, "How many hockey players per side are on the ice, goalie included?", "6", ["5", "7", "4"]),
        Q(2, "What is March Madness?", "The NCAA basketball tournament", ["The NBA Finals", "Spring training", "The Masters"]),
        Q(2, "The Stanley Cup is awarded in which league?", "NHL", ["NBA", "MLB", "NFL"]),
        Q(2, "In baseball, RBI stands for what?", "Runs batted in", ["Runs by inning", "Rounds before intermission", "Right base infield"]),
        Q(2, "A free throw is worth how much?", "1 point", ["2 points", "3 points", "Half a point"]),
        Q(2, "In soccer, a clean sheet means what?", "The team allowed no goals", ["A clean uniform", "A new field", "A draw"]),
        Q(2, "The Masters is played at which course?", "Augusta National", ["Pebble Beach", "St Andrews", "Pinehurst"]),
        Q(2, "Extra innings are what?", "Baseball's overtime when tied after nine", ["A rain delay", "The seventh-inning stretch", "The playoffs"]),
        Q(3, "An eagle in golf is what?", "Two strokes under par", ["One under par", "Three under par", "One over par"]),
        Q(3, "A triple-double in basketball is what?", "Double digits in three stat categories", ["Three three-pointers", "30 points", "Three dunks"]),
        Q(3, "A perfect game in baseball means what?", "No batter reaches base", ["No runs allowed", "No hits, but walks are fine", "27 strikeouts"]),
        Q(3, "Who became the NBA's all-time leading scorer in 2023?", "LeBron James", ["Kareem Abdul-Jabbar", "Michael Jordan", "Kobe Bryant"]),
        Q(3, "In hockey, icing is what?", "Shooting the puck from your side of center all the way past the far goal line untouched", ["Cooling the rink", "A goalie freezing the puck", "A penalty for fighting"]),
        Q(3, "In soccer, offside is called when what happens?", "An attacker is beyond the last defender when the ball is played", ["A player leaves the field", "The ball goes out", "A foul in the box"]),
        Q(3, "Which soccer tournament is held every four years for national teams?", "The FIFA World Cup", ["The Champions League", "The Premier League", "The Copa del Rey"]),
        Q(3, "In tennis, deuce means what?", "40-40", ["30-30", "Match point", "A tiebreak"]),
        Q(3, "A designated hitter does what?", "Bats in place of the pitcher", ["Runs for a slow batter", "Bats cleanup", "Pitches in relief"]),
        Q(3, "A pick-and-roll is what?", "A screen, then the screener rolls to the basket", ["A rebound", "A steal", "A jump ball"]),
        Q(3, "In golf, 'the rough' is what?", "Longer grass beside the fairway", ["The green", "A bunker", "The tee box"]),
        Q(3, "Which NBA star is nicknamed the Greek Freak?", "Giannis Antetokounmpo", ["Nikola Jokić", "Luka Dončić", "Joel Embiid"]),
    ])

    static let cars = Deck(id: "cars", world: .his, title: "Cars & Engines", tagline: "Horsepower, torque, and what that light means.", symbol: "car.fill", colorHex: "5B6B8C", specs: [
        Q(1, "MPG stands for what?", "Miles per gallon", ["Motor power gauge", "Maximum pressure gauge", "Miles per gear"]),
        Q(1, "In an automatic car, which pedal is on the right?", "The gas pedal", ["The brake", "The clutch", "The parking brake"]),
        Q(1, "A check-engine light usually means what?", "The car's computer found a problem", ["Oil is low", "The tank is full", "The tires need air"]),
        Q(1, "Tesla is known for making what?", "Electric cars", ["Diesel trucks", "Motorcycles", "Tractors"]),
        Q(1, "The trunk is where on a car?", "The back", ["The front", "The roof", "Under the seats"]),
        Q(1, "A convertible is what?", "A car whose roof folds away", ["A four-door car", "A hybrid", "A truck"]),
        Q(1, "4WD means what?", "Four-wheel drive", ["Four-window design", "Forty-wide diesel", "Four-wheel disc"]),
        Q(1, "Which company makes the Mustang?", "Ford", ["Chevrolet", "Dodge", "Toyota"]),
        Q(1, "The 'E' on a fuel gauge means what?", "Empty", ["Engine", "Electric", "Extra"]),
        Q(1, "SUV stands for what?", "Sport utility vehicle", ["Super urban van", "Standard used vehicle", "Small utility van"]),
        Q(1, "Windshield wipers clear what?", "Rain and debris from the windshield", ["Snow from the roof", "Dirt from tires", "Fog from mirrors"]),
        Q(1, "Horsepower measures what?", "Engine power", ["Fuel capacity", "Tire size", "Top speed"]),
        Q(2, "RPM stands for what?", "Revolutions per minute", ["Rotations per mile", "Rapid power mode", "Rate per mile"]),
        Q(2, "Which company makes the Corvette?", "Chevrolet", ["Ford", "Dodge", "Pontiac"]),
        Q(2, "A hybrid car has what?", "Both a gas engine and an electric motor", ["A diesel engine", "Two gas engines", "A truck bed"]),
        Q(2, "ABS stands for what?", "Anti-lock braking system", ["Automatic brake sensor", "Advanced body structure", "Air bag system"]),
        Q(2, "Which brand's logo is a prancing horse?", "Ferrari", ["Lamborghini", "Maserati", "Bugatti"]),
        Q(2, "A turbocharger does what?", "Forces more air into the engine for more power", ["Charges the battery", "Adds fuel capacity", "Stiffens the suspension"]),
        Q(2, "Which brand makes the Wrangler?", "Jeep", ["Ford", "GMC", "Subaru"]),
        Q(2, "Torque describes what?", "Twisting force, felt as pulling power", ["Top speed", "Fuel economy", "Brake strength"]),
        Q(2, "A stick shift is what?", "A manual transmission", ["An automatic transmission", "A parking brake", "A gear indicator"]),
        Q(2, "The octane number on a gas pump measures what?", "A fuel's resistance to engine knock", ["Price per gallon", "Fuel weight", "Fuel color"]),
        Q(2, "Which brand makes the 3 Series and the M3?", "BMW", ["Audi", "Mercedes-Benz", "Lexus"]),
        Q(2, "Lug nuts hold what on?", "A wheel", ["The engine", "The seat belts", "The doors"]),
        Q(3, "'0-60' measures what?", "How long it takes to accelerate from 0 to 60 mph", ["Top speed", "Braking distance", "Fuel range"]),
        Q(3, "A V8 engine has how many cylinders?", "8", ["4", "6", "12"]),
        Q(3, "Which race is billed as the Greatest Spectacle in Racing?", "The Indianapolis 500", ["The Daytona 500", "Le Mans", "The Monaco Grand Prix"]),
        Q(3, "Drifting is what?", "Deliberately sliding the rear of the car through turns", ["Coasting in neutral", "Hydroplaning", "Cruise control on the highway"]),
        Q(3, "Which brand makes the 911?", "Porsche", ["Ferrari", "Audi", "Aston Martin"]),
        Q(3, "A catalytic converter does what?", "Cuts toxic exhaust emissions", ["Converts AC to DC", "Adds horsepower", "Filters oil"]),
        Q(3, "How does AWD usually differ from 4WD?", "AWD works all the time automatically; 4WD is typically switched on", ["AWD is only for trucks", "4WD is electric", "They're identical"]),
        Q(3, "The first mass-produced car built on a moving assembly line was what?", "The Ford Model T", ["The Chevy Bel Air", "The VW Beetle", "The Cadillac Series 62"]),
        Q(3, "A dyno test measures what?", "An engine's power output", ["Tire pressure", "Paint thickness", "Oil viscosity"]),
        Q(3, "Lewis Hamilton has how many Formula 1 world titles?", "7", ["5", "6", "8"]),
        Q(3, "The Hellcat is a high-performance trim from which brand?", "Dodge", ["Ford", "Chevrolet", "Jeep"]),
        Q(3, "In Formula 1, DRS stands for what?", "Drag reduction system", ["Direct racing signal", "Driver response system", "Dual rear suspension"]),
    ])

    static let grill = Deck(id: "grill", world: .his, title: "Grilling, Beer & Whiskey", tagline: "Low and slow, neat or on the rocks.", symbol: "flame.fill", colorHex: "E0632A", specs: [
        Q(1, "BBQ is short for what?", "Barbecue", ["Big beef quantity", "Bar brew queue", "Beef brisket quarter"]),
        Q(1, "A lager is a kind of what?", "Beer", ["Whiskey", "Wine", "Cider"]),
        Q(1, "The classic burger is made from what?", "Ground beef", ["Brisket", "Ribeye", "Flank steak"]),
        Q(1, "Bourbon is a whiskey from where?", "The United States", ["Scotland", "Ireland", "Japan"]),
        Q(1, "Brisket is a cut from where on the cow?", "The chest", ["The leg", "The back", "The tail"]),
        Q(1, "Which lights faster, a gas grill or charcoal?", "Gas", ["Charcoal", "They're the same", "Neither will light"]),
        Q(1, "IPA stands for what?", "India Pale Ale", ["Imperial Porter Ale", "International Pilsner Association", "Irish Pub Ale"]),
        Q(1, "A ribeye is what?", "A steak", ["A rack of pork ribs", "A fish fillet", "A sausage"]),
        Q(1, "Medium-rare beef looks like what inside?", "Warm and red in the center", ["No pink at all", "Gray all the way through", "Cold and raw"]),
        Q(1, "Hops give beer what?", "Bitterness and aroma", ["Alcohol", "Color", "Foam only"]),
        Q(1, "'Wings' at a sports bar are what?", "Chicken wings", ["Turkey wings", "Duck wings", "Fish fins"]),
        Q(1, "Which of these is a beer glass?", "A pint glass", ["A flute", "A coupe", "A martini glass"]),
        Q(2, "Scotch must be made where?", "Scotland", ["Ireland", "England", "Wales"]),
        Q(2, "Medium-rare beef is pulled at about what internal temperature?", "130 to 135°F", ["160°F", "180°F", "100°F"]),
        Q(2, "Smoking meat means what?", "Cooking it low and slow with wood smoke", ["Grilling on high heat", "Boiling then grilling", "Deep frying"]),
        Q(2, "Whiskey served 'neat' is what?", "Nothing added, no ice", ["Over ice", "With soda", "Shaken with ice"]),
        Q(2, "A stout is what kind of beer?", "Dark and roasty", ["Light lager", "Wheat beer", "Sour beer"]),
        Q(2, "A dry rub is what?", "Spices rubbed on meat before cooking", ["A marinade", "A sauce", "A cleaning method"]),
        Q(2, "Single-malt Scotch is made from what?", "Malted barley at one distillery", ["Corn", "Wheat", "Rye"]),
        Q(2, "ABV on a beer can means what?", "Alcohol by volume", ["Aged beer variety", "American brew version", "Alcohol bottle value"]),
        Q(2, "A reverse sear means what?", "Cook low first, then sear hot at the end", ["Sear, then boil", "Sear both sides twice", "Chill, then sear"]),
        Q(2, "Bourbon must be aged in what?", "New charred oak barrels", ["Used wine barrels", "Steel tanks", "Plastic vats"]),
        Q(2, "Which beer style is cloudy with orange and coriander notes?", "Belgian witbier", ["Pilsner", "Stout", "Amber ale"]),
        Q(2, "'The stall' when smoking a brisket is what?", "When the internal temperature stops rising for hours", ["When the fire goes out", "When the bark burns", "When the guests leave"]),
        Q(3, "Pilsner originated in which country?", "The Czech Republic", ["Germany", "Belgium", "The Netherlands"], "Named for the city of Plzeň."),
        Q(3, "The Texas Crutch is what?", "Wrapping meat in foil or butcher paper mid-smoke", ["A brisket knife", "A grill brush", "A spice rub"]),
        Q(3, "American rye whiskey must be at least what percent rye?", "51%", ["25%", "75%", "100%"]),
        Q(3, "A boilermaker is what?", "A shot of whiskey with a beer", ["A beer with lime", "Whiskey and soda", "A boiled beer"]),
        Q(3, "Yamazaki and Hakushu whiskies are made by which company?", "Suntory", ["Nikka", "Kirin", "Asahi"]),
        Q(3, "Which wood gives a strong, bacon-like smoke flavor?", "Hickory", ["Apple", "Cherry", "Alder"]),
        Q(3, "Guinness is brewed in which city?", "Dublin", ["Belfast", "Cork", "Galway"]),
        Q(3, "The Maillard reaction is what?", "The browning that creates flavor when proteins and sugars are heated", ["Meat resting", "Fat rendering", "Smoke soaking in"]),
        Q(3, "A Manhattan cocktail is whiskey and what?", "Sweet vermouth", ["Cola", "Tonic", "Cream"]),
        Q(3, "A tomahawk is what?", "A bone-in ribeye with a long rib bone", ["A brisket cut", "A pork loin", "A grilling axe"]),
        Q(3, "In brewing, 'wort' is what?", "The sweet liquid before fermentation", ["The foam on top", "The spent grain", "The bottle cap"]),
        Q(3, "Which BBQ style is known for thick, sweet tomato-and-molasses sauce?", "Kansas City", ["Carolina vinegar", "Central Texas", "Memphis dry rub"]),
    ])

    static let nerd = Deck(id: "nerd", world: .his, title: "Games & Superheroes", tagline: "Respawns, Wakanda, and what GG means.", symbol: "gamecontroller.fill", colorHex: "7C4DFF", specs: [
        Q(1, "Bruce Wayne is which hero?", "Batman", ["Superman", "Spider-Man", "Iron Man"]),
        Q(1, "Mario's brother is who?", "Luigi", ["Wario", "Toad", "Yoshi"]),
        Q(1, "Which company makes the PlayStation?", "Sony", ["Microsoft", "Nintendo", "Sega"]),
        Q(1, "Superman's weakness is what?", "Kryptonite", ["Water", "Fire", "Gold"]),
        Q(1, "Fortnite is what kind of game?", "A battle royale", ["A racing game", "A sports game", "A puzzle game"]),
        Q(1, "Iron Man's real name is what?", "Tony Stark", ["Bruce Banner", "Steve Rogers", "Peter Parker"]),
        Q(1, "Pokémon's most famous mascot is who?", "Pikachu", ["Charizard", "Eevee", "Snorlax"]),
        Q(1, "Which console does Microsoft make?", "Xbox", ["PlayStation", "Switch", "Wii"]),
        Q(1, "Spider-Man got his powers from what?", "A radioactive spider bite", ["A lab explosion", "An alien suit", "Magic"]),
        Q(1, "Minecraft is famous for what?", "Building with blocks", ["Racing cars", "Fighting tournaments", "Cooking"]),
        Q(1, "Thor's hammer is called what?", "Mjolnir", ["Excalibur", "Stormbreaker", "Gungnir"]),
        Q(1, "Master Chief is the hero of which game series?", "Halo", ["Call of Duty", "Gears of War", "Doom"]),
        Q(2, "Which villain snapped his fingers in 'Avengers: Infinity War'?", "Thanos", ["Loki", "Ultron", "Red Skull"]),
        Q(2, "The hero of 'The Legend of Zelda' is named what?", "Link", ["Zelda", "Ganon", "Epona"]),
        Q(2, "In Mario Kart, which item hunts down whoever is in first place?", "The blue shell", ["The banana", "The red shell", "The star"]),
        Q(2, "Which hero only says 'I am Groot'?", "Groot", ["Rocket", "Drax", "Star-Lord"]),
        Q(2, "In games, a respawn is what?", "Coming back after dying", ["Saving the game", "A new level", "A boss fight"]),
        Q(2, "Wolverine belongs to which team?", "The X-Men", ["The Avengers", "The Justice League", "The Fantastic Four"]),
        Q(2, "Which game series is set in Hyrule?", "The Legend of Zelda", ["Final Fantasy", "Elden Ring", "Skyrim"]),
        Q(2, "Batman's city is called what?", "Gotham", ["Metropolis", "Star City", "Central City"]),
        Q(2, "Twitch is what?", "A livestreaming platform for gamers", ["A game console", "A controller", "An esport"]),
        Q(2, "Which hero carries a vibranium shield?", "Captain America", ["Black Panther", "Thor", "Hawkeye"]),
        Q(2, "The green creeper that explodes is from which game?", "Minecraft", ["Fortnite", "Roblox", "Terraria"]),
        Q(2, "GTA stands for what?", "Grand Theft Auto", ["Great Tactical Army", "Global Team Arena", "Giant Turbo Attack"]),
        Q(3, "Which game won Game of the Year at The Game Awards 2022?", "Elden Ring", ["God of War Ragnarök", "Horizon Forbidden West", "Stray"]),
        Q(3, "Which company makes Zelda and Mario?", "Nintendo", ["Sony", "Sega", "Capcom"]),
        Q(3, "Black Panther's home country is what?", "Wakanda", ["Latveria", "Genosha", "Atlantis"]),
        Q(3, "'Souls-like' games are known for what?", "High difficulty and stamina-based combat", ["Farming", "Puzzle solving", "Sports"]),
        Q(3, "Who played Iron Man in the Marvel movies?", "Robert Downey Jr.", ["Chris Evans", "Chris Hemsworth", "Mark Ruffalo"]),
        Q(3, "Fortnite Battle Royale launched in which year?", "2017", ["2015", "2019", "2013"]),
        Q(3, "Deadpool is famous for doing what?", "Breaking the fourth wall", ["Flying", "Shrinking", "Reading minds"]),
        Q(3, "In game chat, GG means what?", "Good game", ["Get going", "Great gun", "Go get 'em"]),
        Q(3, "Which Marvel hero comes from Asgard?", "Thor", ["Vision", "Hulk", "Ant-Man"]),
        Q(3, "Elden Ring was made by which studio?", "FromSoftware", ["Bethesda", "Ubisoft", "Rockstar"]),
        Q(3, "Who won the 2020 Best Actor Oscar for playing the Joker?", "Joaquin Phoenix", ["Heath Ledger", "Jared Leto", "Jack Nicholson"]),
        Q(3, "Speedrunning is what?", "Finishing a game as fast as possible", ["Playing on the hardest mode", "Racing games only", "Playing while running"]),
    ])

    static let gear = Deck(id: "gear", world: .his, title: "Tools, Gear & Outdoors", tagline: "Torque wrenches, bowlines, and why the cooler is a Yeti.", symbol: "wrench.and.screwdriver.fill", colorHex: "5FA31B", specs: [
        Q(1, "Which tool drives screws?", "A screwdriver", ["A hammer", "A wrench", "Pliers"]),
        Q(1, "A Phillips screwdriver has what shape of tip?", "A cross", ["A flat blade", "A star", "A hexagon"]),
        Q(1, "You measure length with what?", "A tape measure", ["A level", "A wrench", "A chisel"]),
        Q(1, "A level checks what?", "Whether something is straight or flat", ["Weight", "Cutting angle", "Sanding grit"]),
        Q(1, "Fishing line is wound onto what?", "The reel", ["The hook", "The lure", "The bobber"]),
        Q(1, "Kindling is what?", "Small sticks for starting a fire", ["A type of tent", "A camp stove", "A sleeping bag"]),
        Q(1, "Duct tape is what?", "A strong all-purpose tape", ["A kind of rope", "A glue", "A paint"]),
        Q(1, "A cordless drill runs on what?", "A battery", ["Gas", "Steam", "A wall cord"]),
        Q(1, "A tent stake does what?", "Pins a tent to the ground", ["Holds the tent up from inside", "Keeps rain off", "Cushions the floor"]),
        Q(1, "A cooler is for what?", "Keeping food and drinks cold", ["Cooling the tent", "Filtering water", "Storing tools"]),
        Q(1, "PSI on a tire measures what?", "Air pressure", ["Tread depth", "Tire width", "Speed rating"]),
        Q(1, "A stud finder locates what?", "Wood framing behind a wall", ["Nails in tires", "Lost keys", "Underground pipes"]),
        Q(2, "A torque wrench is for what?", "Tightening bolts to an exact tightness", ["Cutting pipe", "Measuring angles", "Removing paint"]),
        Q(2, "WD-40 is mostly used to do what?", "Loosen rusted parts and displace moisture", ["Glue wood", "Clean windows", "Sharpen blades"]),
        Q(2, "A socket set is used with a what?", "Ratchet", ["Hammer", "Saw", "Drill bit"]),
        Q(2, "Catch and release means what?", "Letting fish go after you catch them", ["A fishing net", "A lure", "A type of reel"]),
        Q(2, "Which knot makes a fixed loop that won't slip?", "A bowline", ["A square knot", "A slip knot", "A granny knot"]),
        Q(2, "'Leave no trace' is what?", "An outdoor ethic of leaving nature as you found it", ["A hunting method", "A camping brand", "A trail name"]),
        Q(2, "A miter saw makes what kind of cuts?", "Precise angled cuts", ["Curved cuts", "Holes", "Sanding passes"]),
        Q(2, "A bear canister is what?", "A locked food container for bear country", ["Bear repellent", "A tent shape", "A cooler brand"]),
        Q(2, "R-value on a sleeping pad measures what?", "Insulation from the cold ground", ["Weight", "Size", "Waterproofing"]),
        Q(2, "A spinner in fishing is what?", "A lure with a spinning blade", ["A reel type", "A rod", "A knot"]),
        Q(2, "A chalk line is used to do what?", "Snap a long straight line on a surface", ["Measure angles", "Clean tools", "Mark tires"]),
        Q(2, "Waders are what?", "Waterproof overalls for standing in water", ["Hiking boots", "Rain jackets", "Fishing hats"]),
        Q(3, "Gore-Tex is what?", "A waterproof, breathable fabric membrane", ["A tent brand", "A type of rope", "A boot sole"]),
        Q(3, "A come-along is what?", "A hand-operated winch", ["A rope", "A ladder", "A saw"]),
        Q(3, "The 'Ten Essentials' list is for what?", "Hiking safety gear", ["Toolbox basics", "Fishing tackle", "Truck maintenance"]),
        Q(3, "A ferro rod is used to do what?", "Start fires by striking sparks", ["Sharpen knives", "Measure water depth", "Tie flies"]),
        Q(3, "A trolling motor is what?", "A quiet electric motor for slowly positioning a boat", ["A large outboard", "A jet engine", "A winch"]),
        Q(3, "Which saw cuts curves in wood?", "A jigsaw", ["A circular saw", "A table saw", "A hand plane"]),
        Q(3, "Fly fishing casts what?", "A weighted line with a nearly weightless fly", ["A heavy lure", "A net", "A bobber"]),
        Q(3, "Bushcraft means what?", "Wilderness skills using natural materials", ["Trimming bushes", "Landscaping", "Bird hunting"]),
        Q(3, "Leatherman is known for what?", "Multi-tools", ["Boots", "Belts", "Saddles"]),
        Q(3, "A GFCI outlet protects against what?", "Shock from ground faults", ["Power surges", "Overheating", "Fire only"]),
        Q(3, "In camping, a bivy is what?", "A minimal one-person shelter", ["A large family tent", "A camp stove", "A hammock"]),
        Q(3, "Yeti is famous as a brand of what?", "Coolers", ["Tents", "Trucks", "Boots"]),
    ])
}

enum Decks {
    static let all: [Deck] = HerWorld.decks + HisWorld.decks
    static func byID(_ id: String) -> Deck? { all.first { $0.id == id } }
    static func decks(in world: World) -> [Deck] { all.filter { $0.world == world } }
}
